### ISSUE TITLE
SwiftKey keyboard is auto correcting entered seedphrase

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-react#10018]
# Bug Report

As a Portuguese speaker, my Android keyboard is configured for auto-correct in Portuguese. 

## Problem

When entering the seedphrase, it auto corrects to portuguese words.
An overview of the background required to understand the problem.
A problem description.

#### Expected behavior

Autocorrects to the known BIP-32 dictionary.

#### Actual behavior

Auto-corrects using keyboard.

**Comment by hesterbruikman** [comment]
@3esmit What Android phone are you on? 

I ask because I used to have this problem, but on Samsung Galaxy S10, Android Keyboard no longer auto-corrects when I enter a seed phrase. In other apps my keyboard auto-corrects, but no longer the case in Status; emojis, mic, etc are also disabled. I assumed we were deliberately suppressing these keyboard functions.

![Screenshot_20200211-182056_Status](https://user-images.githubusercontent.com/35233054/74261388-787a3a80-4cfb-11ea-990f-153019ff842f.jpg)

**Comment by 3esmit** [comment]
Hi, I verified with the user and he have

Device: Xiaomi note 6

![image](https://user-images.githubusercontent.com/224810/74285499-c0ea2600-4d04-11ea-9e64-3e056b4e9adc.png)


The user said he had **SwiftKey** installed as default keyboard.

**Comment by 3esmit** [comment]
I was not able to reproduce this bug in my device. I tried installing swiftkey but it detects the config for no wordsuggest.

**Comment by churik** [comment]
Couldn't reproduce it on Xiaomi Note 9, OS: Android 10QKQ1 with Swift keyboard.
@3esmit thank you for logging it!
Please reopen if see it again.
