### ISSUE TITLE
Resolve inaccessible Keycard multiaccount in Status

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10026]
# Problem
The user is not informed of the moment the keys have successfully been generated and moved to the Keycard. This could lead to an undesirable situation when the user:

- Cancels the process when asked to write down the PUK code and Pairing code
- Generates new keys
- Tries to store these Keys on Keycard

The user will currently receive the following message and will no longer be able to use the card. However the user will not be able to login or recover the existing account (they will not have written down their seed phrase at this stage)

![photo_2020-02-10_16 34 19_1](https://user-images.githubusercontent.com/35233054/74230779-5cf43d00-4cc5-11ea-8af1-0d0d163a4bdc.jpeg)

## Implementation
Show a state that the keys have been generated and placed on the Keycard to better inform the user that at this point they can longer return.

In addition, solutions depend on:

- Can the card hold multiple multiaccounts? (Why not?)
- Can the back up seed phrase step precede the PUK and Pairing code? (At least that way, the keys can be accessed)
- Can the multiaccount be added to `Your keys`, without the PUK and Pairing code been written down, for a limited time. With the passcode providing access. Blocking all functionality, only showing the PUK code and Pairing code

## Notes
Needs specification of options

## Future Steps
- Design screens for decided upon option
- Implementation

**Comment by guylouis** [comment]
@hesterbruikman 

If we take again the steps you described:
1/ Cancels the process when asked to write down the PUK code and Pairing code
2/ Generates new keys
3/ Tries to store these Keys on Keycard

After 1/ currently the message the user gets is:
 "Dangerous operation. 
This will cancel keycard setup. It's highly recommended to finish the setup in order to use keycard. Do you really want to cancel ?"

And the state of his card is that it's initalized with a pairing code + pin + puk, but it has no multiaccount on it. 

When the user goes through 2 and 3/ then when he will tap a card, he will not get  the screen you showed, but a request to enter his pairing code. Which he did not write...

So for me the issue is really about, not being clear to the user when he cancels the setup in 1/ that if he doesn't write his pairing code, he's actually f***ed and can throw his card away. 

I completed the miro diagram of the onboarding logic (what happens with the card)
https://miro.com/app/board/o9J_kvIXxoU=/

Possible solutions I see: 
i/ change the warning to something much more explicit
ii/ change where the actual pairing of the card is done with the phone + allow a user to change his pairing code when he knows his PIN. So if the user cancels here, then he can resume (only with the same phone), and then he can set up a new pairing code in the settings

I prefer i/ since ii/ needs to build this new 'change pairing code' feature which will be longer

**Comment by hesterbruikman** [comment]
Maybe first i, and then ii. At least have a mitigation in place initially. Then refine by making sure the scenario of being locked out without PUK and Pairing code can't occur. 

Initially the scenario can lead to Keycard being unusable, but at least it doesn't have funds on it. I don't know how this would work out when you have a KeycardCash purchased with funds and you want to pair this card to Status to move the funds.

**Comment by guylouis** [comment]
Ok so for now and for launch let's do i, which is a simple copy update. I propose: 
"
Pick up your pen ! 
Your keycard has now a pairing code set-up. If you cancel here and do not write it down, you won't be able to use your keycard anymore
"

**Comment by guylouis** [comment]
Also the copy below needs to be changed because there is no reset feature for now
![image](https://user-images.githubusercontent.com/11461437/74653418-60396e00-5188-11ea-85bc-7cbb57d256ed.png)

Copy should simply be 
"This card has already an account setup, if you want to access it use the 'Recover with Keycard' option"

**Comment by guylouis** [comment]
We have factory reset now (see link below) and this can be closed 
https://github.com/status-im/status-react/pull/12115
