### ISSUE TITLE
Too hard to find and share chat key

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#10052]
# Feature Issue

Currently the only way to find your chat key is the tiny icon in the top right corner of `Profile` view.
Several users have complained that they were unable to find their own chat key and share it.

### User Story

As a user, I want to to be able to actually find my chat key.

### Description

The icon is too hidden, too small, and - as one user in `#support` suggested - looks like a logout button. What we need is a more obvious way - or ways - to get and share your chat key/ENS name.

**Comment by errorists** [comment]
[9 designs later](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4323%3A19953), here's what I propose to do

<img width="1526" alt="Screenshot 2020-02-26 at 09 38 09" src="https://user-images.githubusercontent.com/4932774/75327174-39f88a00-587c-11ea-83de-e76901451642.png">

1. Add the chat key below your currently used username.
2. Embed the avatar, name and key into touchable so tapping any one of them will bring up the share popover
3. Use platform specific share icons, since for Android users, the upward arrow is mostly unfamiliar.

Design can be found [here](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4336%3A1208)

**Comment by StatusSceptre** [comment]
Will include in 1.3. Release 1.2 is built.
