### ISSUE TITLE
Add support for adding new accounts in wallet with keycard

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10101]
# Feature Issue

Add support for adding new accounts in a wallet with keycard

After we implemented private key and seed support, and reworked adding accounts feature https://github.com/status-im/status-react/pull/10100  we need to add keycard support

**Comment by rasom** [comment]
@flexsurfer does it meant adding keycard account to on-device multiacc or what exactly?

**Comment by flexsurfer** [comment]
it means adding new account in keycard multiaccount wallet
so you have multiaccount created with keycard, and you want to generate a new account in the wallet, or import account from seed or private key, we had an implementation for account generation but screens have been reworked, and we need to reintroduce generating new account for keycard multiaccounts and implement seed and private key support

**Comment by rasom** [comment]
@flexsurfer ok, got it, thanks

do we have a design for keycard version?

**Comment by flexsurfer** [comment]
no @errorists

**Comment by guylouis** [comment]
@rasom @hesterbruikman @rachelhamlin 

Based on our discussion on 10/03

For a keycard Multiaccount we have 3 options when user adds a new account based on seed or private key:
1/ ask him to tap the card + PIN 
2/ define a new password 
3/ (temporary) remove this importing options for keycard mutliaccounts

For a non keycard multiaccount
1'/ use the same password as used to protect the multiaccount
2'/ ask him to define one new password 

of course choices should be consistent : 1/1' or 2/2'

**PROS and CONS for 1/ 2/ 3/:**
1/
Pros: 
No need for more design work to implement
Keycard multiaccount get same features as non keycard ones 
Cons: 
can be confusing for users, since it makes him think that the new account is stored on the card (it's not, only a key in the card is used to encrypt it)
2/
Pros:  less confusion
Cons: need the user to define and memorize a new password. Needs some design work
3/
temporary solution

**Comment by guylouis** [comment]
update : this issue is simply about being able to 'add a new account' when the multi account is a keycard one. This new account is created on the BIP44 path. There is no need for specific designs here. 

The design of how to import private keys (from private key or seed+paths) will be handled in separate issues.
