### ISSUE TITLE
Feature request - Payment request deeplink

### ISSUE THREAD

**Issue by bogdyak** [status-im/status-react#10167]
## EIP links over status-im:// universal/deep link

Is there already support of something like
```
ethereum:pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16
```

but through
```
status-im:pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16
```

Thanks

**Comment by flexsurfer** [comment]
@churik or @Serhy could you confirm that `status-im://pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16` already works ? thanks

**Comment by Serhy** [comment]
It doesn't work yet. 
We parse `ethereum:pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16` when scanning it from QR code (but there is an issue with picking up amount https://github.com/status-im/status-react/issues/10093)

But neither: 
`status-im://pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16`
nor
`status-im://ethereum:pay-snt.thetoken.eth/transfer?address=unicorn.stateofus.eth&uint256=1e16`
open the `Send transaction` bottom sheet in Status when opening link 

I guess this is a feature we have to add additionally.

**Comment by bogdyak** [comment]
@Serhy Thank you for picking this up. Will be looking forward to updates. 
I will integrate status with our system once mentioned features will be implemented

**Comment by hesterbruikman** [comment]
fyi @guylouis as this regards QR code payment requests and we have something in place for Keycard payment requests

**Comment by guylouis** [comment]
TBH, I am not sure how keycard or request screen is linked with this. cc @gravityblast  and @bitgamma for insight

**Comment by gravityblast** [comment]
in our current use case we open the request screen from a point of sale dapp, and we need a complex message to be signed so the standard uri wouldn't work, but we can think about it for other use cases.

**Comment by guylouis** [comment]
Some thoughts after reading this in detail
- when status gets a EIP681 link, this link does not have information about which account to use (and it makes sense!) it's up to status UI to allow the user to chose from which account this will be paid
- The account could thus be any of the accounts from the user excepting read-only accounts 
- regarding the ability to open status from a link on the keycard request screen I see different options 
i. we use a eip681 link to specify the amount and asset to transfer, and we either specify with an extra parameter (we're thus extending eip681 in the link) that any keycard should be able to sign this, or let the user chose which account to use to sign in the status UI (makes sense anyway since we are now multiaccount)
ii. we don't use eip681 links for this but rather a link to a dApp, this dApp being super simple and a call to web3.signtypedData(details of the transaction to sign) which pops up the request screen. The dApp is then the one to decide what to do with the meta-tx (send it with gas abstraction to a user wallet etc.)

I actually think that only option ii. makes sense because 
- in i. until we have defined a payment network to be used within status, we don't know what to do with the information provided to status (we have the amount to transfer, and a keycard EOA to sign a meta tx BUT no user wallet to use)
- ii. doesn't need any extra development and is quite generic wrgds to which payment network is used. 

cc @bitgamma cc @gravityblast @hesterbruikman

**Comment by gravityblast** [comment]
> regarding the ability to open status from a link on the keycard request screen I see different options

@guylouis what's the use case though? Normally a URI opens the wallet with a payment pre-filled.
With the cash applet the user doesn't even use a device, it's the "merchant" that has the device. what could be a use case for the merchant to use a link/qrcode?

**Comment by guylouis** [comment]
<del> I think when it makes sense to include the detail of the payment (amount, asset) in the QR code/link itself. For instance to streamline the user experience at a booth that sells only one item (scan this QR code to get your one hot dog, or entrance ticket), thus the 'price' of the item is already encoded. 

hmm yes good point, I think Hester had in mind a case where one given point of sales application (not using our framework) could call status app through a link that would trigger the request screen ...

**Comment by hesterbruikman** [comment]
👆 Exactly, a dedicated payment app (other than the Status merchant dapp) uses a link to create a payment request that the buyer then signs on their own device. Considering the numerous merchant apps already out there, integrating with inventory, accounting, etc.. From a merchant's perspective it would be way more convenient to send a payment request from their existing UI than to have to 'get into web3'.

- Buyer provides digital or physical shopping card
- Merchant app generates payment url (+QR code)
- Merchant sends url or shows QR code
- Buyer taps on url or scans code
- Client shows Keycard sign request screen
- Buyer signs and shares confirmation

For reference, this is the standard in The Netherlands for creating interbank payment requests: https://www.ideal.nl/en/consumers/ideal-payment-request/. It's more or less the flow I have in mind

Tangential, another scenario would be more relevant when the user can merge Keycard MA and regular MA (#10128)
- User A sends request
- User B selects Keycard account (in case of multiple accounts)
- Client prompts Keycard signing

**Comment by guylouis** [comment]
the point to clarify (btw is 'the client' above a typo, do you mean the merchant or the buyer ?) is if the request screen is prompted on the merchant phone (in this case this is some kind of inter-app communications between the pos app and status) or the buyer phone (in this case, I personnaly need to think about how this would work, this doesn't seem obvious to me for now)

**Comment by hesterbruikman** [comment]
> the point to clarify (btw is 'the client' above a typo, do you mean the merchant or the buyer ?) 
I mean client of the buyer. 
- Merchant shows QR 
- Buyer scans QR
- Buyer selects wanting to pay with Keycard
- Device of buyer prompts Keycard sign tx request

alterntatively:
- Merchant asks payment method
- Buyer chooses Keycard
- Merchant shows QR (keycard_signtypeddata)
- Buyer scans QR
- Device of buyer prompts Keycard sign tx request

**Comment by guylouis** [comment]
Ok so this is a way for the payment terminal to prompt the tap of the keycard on the buyer's phone and not the payment terminal itself

note: a 'status pay' account user might be able to make payments with his status phone without keycard too. That's something we can decide fro a UX standpoint and design the multisig of smart contract accordingly 

@hesterbruikman @gravityblast @bitgamma

**Comment by hesterbruikman** [comment]
> note: a 'status pay' account user might be able to make payments with his status phone without keycard too. That's something we can decide fro a UX standpoint and design the multisig of smart contract accordingly

Good point! What I like about this payment flow is that it moves technical requirements from the merchant to the buyer, which is a lot more suited to certain locales and merchant types

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
