### ISSUE TITLE
Allow delete multiaccount

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10195]
# Problem
Allow removing a multiaccount. This feature will be required to introduce moving an existing regular multiaccount to Keycard. Maintaining the multiaccount on local storage (keys on phone) would nullify the security Keycard brings. 

We have also received this feature request multiple times. Although it is not entirely clear why people ask for this feature, opposed to uninstalling the app, it makes sense to want to have a sense of security by being able to remove data.

## Implementation
1. Add list item in `Settings` > `Privacy and security`
- Add popover dialog for confirmation
- Remove keys and any additional data from database
- If user does not have other multiaccounts: 
Open first screen of onboarding
- If user does have other multiaccounts
Open `Your keys`

2. Add remove action on `Your keys`
- Longpress action on list item
- Show bottom sheet `Delete profile` - similarly to `Delete chat`

## Acceptance Criteria
Implementation follows design (to be added)

**Comment by hesterbruikman** [comment]
cc @rachelhamlin @guylouis

**Comment by guylouis** [comment]
This is needed also to be able to[ reset a keycard ](https://github.com/status-im/status-react/issues/9229)(clean it from from his secrets), since once it is cleared we need to remove the multiaccount from Status UX 

See roman comment here https://github.com/status-im/status-react/issues/9229#issuecomment-552314034
