### ISSUE TITLE
Screen is jumping when switching between tabs with open tabbar with and without text

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10211]
# Bug Report

## Problem
Video: https://drive.google.com/file/d/1sKznc9AMSDEAouq_-PLEI4DLFy8paXoy/view?usp=sharing
Added to release, because issue is extremely visible. 

#### Expected behavior
navigation is smooth

#### Actual behavior
screen is jumping

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join to any chat (leave in chat screen)
- Switch tab

### Additional Information

- Status version: nightly 24/03/2020
- Operating System: Android

**Comment by churik** [comment]
cc @rachelhamlin @Ferossgp

**Comment by errorists** [comment]
I can't access the video, help a guy out with a dropbox link? ;)

**Comment by Ferossgp** [comment]
@errorists Here 2 videos which show the problem
V1.1 https://drive.google.com/file/d/1NnD14faNo6sC9YrU8U9q8SFrrslOu3Ck/view?usp=sharing
Now: https://drive.google.com/file/d/1NqmoJv0z6gZPrn-1gf3GrY5PJ-0hlHmu/view?usp=drivesdk

**Comment by flexsurfer** [comment]
for some reason on video, it doesn't show the full picture, dunno why in real life it's even worse https://drive.google.com/file/d/15aTqv_ApePyA8hUaUXOpnzIvXV_Ntb0n/view?usp=sharing

**Comment by Ferossgp** [comment]
I found the reason for the problem in docs:
https://reactnavigation.org/docs/bottom-tab-navigator#lazy
`Note: tabs are not re-rendered upon subsequent visits.`

The jump happens because when we navigate to a tab it moves fast between 2 states that were skipped, small and big again. We need to find a hack to not re render element in that case.
