### ISSUE TITLE
Blocking user takes ~5-10s, and chats are emtpy during that time

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#10312]
# Bug Report

## Problem

When blocking user, all chats are empty for ~5-10s

#### Expected behavior

There are messages in the chat then blocking user

https://drive.google.com/file/d/16AK_y1vAKWHArxCnQ87rjsC-wYckNEjV/view

**Comment by flexsurfer** [comment]
blocking is very heavy
we need to go through all the messages, remove them, update all the chats
is probably not optimized as well, so we need to make sure
there's probably some index missing or some weird stuff happening

**Comment by hesterbruikman** [comment]
User report in #support
> whenever i block someone on Status, app crashes after i click 'block user'
> I have to log out
> sometimes if i tap their avatar & use block user it doesn't block them until i click send a message then tap their profile and block them
> I have to log out
> restart app**

**Comment by flexsurfer** [comment]
@hesterbruikman @cammellos  this issue pretty critical, because we have more and more spam, so user have to block that, and more users use status longer so they will be facing this issue more and more

**Comment by cammellos** [comment]
Probably the best thing to do here is to actually show a loading screen to the user. This is a fairly rare action, and it's expensive as deletion from the database take a long time (we want to delete rather than soft delete), and then we need to re-calculate all messages count, last messages etc.
Would that be ok?

**Comment by flexsurfer** [comment]
but based on users feedback app crashes `whenever i block someone on Status, app crashes after i click 'block user'`, so loading screen won't help

**Comment by hesterbruikman** [comment]
Added to 1.4.1 which is planned to be the fixes release following release of Keycard integration.

I actually haven't been able to reproduce the issue myself and would like to better understand under what circumstance this occurs and how common this is. Does it have to do with the number of messages the user you want to block has left in a chat?

Also, and I'm sure this has been discussed, why are we removing the full history? If that's the issue we might consider blocking only to block (i.e.' hide') future messages from this user

**Comment by cammellos** [comment]
>  Does it have to do with the number of messages the user you want to block has left in a chat?
Yes, removal from database can be very expensive, and this is one of those cases.

> Also, and I'm sure this has been discussed, why are we removing the full history?

Not sure what the discussion was initially, it makes sense to remove everything, so that you don't have your chat overwhelmed by spam, though whether this is necessary I don''t know, blocking from the moment forward can also be ok. 

There's the issue of say the user has a message that makes the app barely usable, in which case not removing messages would not address it.

**Comment by churik** [comment]
Tried to reproduce it:
- open Status , join #status channel and load history for 30 days
- join #status-chines channel, load history
- blocked most active users one-by-one

In my case (tested on IPhone7) - no problems with blocking or rendering chat messages after user block.

**Comment by flexsurfer** [comment]
yeah it won't be visible on new account
