### ISSUE TITLE
Can't load any messages after rejoining a public group

### ISSUE THREAD

**Issue by KyleNie** [status-im/status-react#10362]
# Bug Report

## Problem

If I delete a public group and join it again, no messages will load as if it's an empty group. "Fetch more messages" doesn't work. 

#### Expected behavior

Previous messages are loaded.

#### Actual behavior

Nothing appears and "fetch more messages" button won't get it work. 
### Reproduction

- Join a public group 
- delete chat 
- join the same group again
### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.2.0
[comment]: # (Android or iOS.)
- Operating System: Android Q

**Comment by flexsurfer** [comment]
@cammellos probably for public chats we need to clear all data, and consider it as brand new chat when joining again, wdyt ?

**Comment by cammellos** [comment]
@flexsurfer it's actually an explicit behavior, we did this I believe because we were required by the previous security audit.

The idea is that if you join a chat, delete it because you don't want some of those messages, if you re-join the chat you don't want to see them again.

I am not sure that's really needed for public chats (while 1-to-1 I would be more cautios, also there are some technical constraints with that), so we could change the behavior. 

I think it's a question for UX team this one, @errorists @hesterbruikman

**Comment by errorists** [comment]
to be honest, I think it goes against common sense expectation. a public chat is an immutable record of conversations; if you left it and rejoined, you would fully expect to fetch its latest state including everything you seen before

> delete it because you don't want some of those messages,

I think the expectation is more like, you don't want to participate in it, it's about choosing to subscribe to a conversation

_edit_: maybe to leave a more definite design consideration : the optimal UX here is what the issue author described as expected behaviour
