### ISSUE TITLE
After 1 launch of application buttons ob android native dialogs are unaccessible

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10428]
# Bug Report

## Problem

<img width="254" alt="Monosnap 2020-04-24 12-35-20" src="https://user-images.githubusercontent.com/4557972/80203853-1d809000-8628-11ea-842c-3b1c18c20554.png">

Not sure that this issue is only about keycard errors but tried with the error-report dialog for creating account flow and I couldn't.

#### Expected behavior
Can tap OK button

#### Actual behavior
OK button is not accessible; only way to continue use app is to relaunch the app.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status (reproducible only  on 1 launch of app, is not reproducible if that build already was installed, removed and reinstalled) 
- Go to get Started > Generate Keys > Next > select keycard > Begin setup
- Tap any card (not keycard) or keycard without applet

### Additional Information

- Status version: nightly 24/04/2020
- Operating System: Android 10 (phone Xiaomi Mi Note 9)

**Comment by churik** [comment]
cc @guylouis

**Comment by guylouis** [comment]
cc @bitgamma 
do you know which is the test we apply to the card when displaying this message ? meaning are we discrimintaing between the case where the card is a keycard (e.g with the global platform key of the card ?) and the card is another card than keycard (e.g. your VISA card in your wallet) ?
If not, how could we discriminate (which criteria is best) so that wer can have two different error messages?

**Comment by bitgamma** [comment]
I don't know exactly what test we make, but I guess we only try to SELECT the applet's AID. We could check the keys by issuing an INITIALIZE UPDATE, but we risk to block the card's ISD if it happens about 5 times (depends on card) so that'd be a bad idea. We could use the ATR + the output of the GET DATA command to see if it is a card with the same configuration as the JCOP4 platform we use.

Since this would be a bit hit-and-miss and since it should be easy for the user to realize what they have in their hands, I wouldn't put too much logic to discriminate between a Keycard with deleted applet and a non-Keycard.

**Comment by guylouis** [comment]
Ok so the message is ok
We just need an OK button to close the issue

**Comment by churik** [comment]
It's not only on this error. After error all system-dialogs with OK, Cancel, Continue etc buttons are shown without these buttons.
They are cut until restrt of the application.

**Comment by rasom** [comment]
I can't reproduce this in dev env

**Comment by rasom** [comment]
@churik tried on latest nightly, the issue is not reproducible on redmi note 8 pro, android 9

**Comment by hesterbruikman** [comment]
Same issue occurred when attempting to `longpress` > `delete chat` #10872 

Issue remains until app is closed or reinstalled. Issue disappeared when closing and reopening the app, while notifications kept running.

**Comment by cammellos** [comment]
@churik is this still an issue? Otherwise feel free to close. Thanks!

**Comment by churik** [comment]
Haven't seen it for a long time.
closing for now
