### ISSUE TITLE
Change copy of seed backup warning message in Keycard onboarding

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#10719]
in Keycard onboarding, the following message is shown to the user after he is been shown is seed phrase. 
![image](https://user-images.githubusercontent.com/11461437/83050102-527b6a80-a04c-11ea-9d1f-31e970148126.png)

The copy is actually incorrect, since if the user has lost his device, if he still has his pairing code then he will be able to access his funds from an other phone. 

The copy should be changed to 
"
Written the seed phrase down! 
You won't have a second chance
If you lose access, for example by losing your keycard, you can only access your keys with your seed phrase. No one, but you has your seed phrase. Write it down. Keep it safe
"

cc @hesterbruikman

**Comment by hesterbruikman** [comment]
For clarity, these are the current dialogs for regular multiaccount and keycard multiaccount. The issue is to change the keycard multiaccount message only as the keys can be accessed on another device with the pairingcode (not requiring the seed phrase)

![Frame 2](https://user-images.githubusercontent.com/35233054/83503064-d311ef00-a4c2-11ea-9ea9-cf3c288ee9ec.png)
