### ISSUE TITLE
'Release username' flow for stateofus.eth ENS name is broken

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#10794]
# Problem
When the stateofus ENS username expires after 1 year, the user needs to 'Release' the name and re-register it. In order to do so, the user is directed to a blogpost with instructions https://our.status.im/managing-your-ens-name-in-v1/

Following the instructions is virtually impossible using Status alone:
- 'Release username' opens Browser selection, which does not include Status browser
- https://etherscan.io/enslookup does not work in Status browser
- Contract link to release does not work in Status browser. `Connect to web3` gives an error message 'Unable to locate a compatible web3 browser'

Current flow that worked was to import seed phrase into MetaMask wallet, connect with with contract dapp through MetaMask.

## Implementation
Don't know where to start 🙃

## Acceptance Criteria
Name can be released and registered without leaving Status

## Notes
Not sure what the reason is that the label hash needs to be looked up manually. Is this something Status can do? Or does that require undesirable interfacing with Etherscan? 

## Future Steps

**Comment by acolytec3** [comment]
Someone just asked me about this in the Status discord so thought I'd mention it here.  That reference to "look up the name on Etherscan" isn't helpful since Etherscan (at least per the instructions) doesn't show you the label hash.  I did some digging on the ENS site and [here](https://docs.ens.domains/contract-api-reference/name-processing#how-do-i-find-the-labelhash-namehash-of-a-name) they provide a query for their subgraph that will pull it out.  Can the blog article be updated to reflect this so people at least have a direction on how to release their names?

**Comment by churik** [comment]
Now it is ready to develop on react side according to https://github.com/status-im/status-go/pull/2792

**Comment by yqrashawn** [comment]
> - [etherscan.io/enslookup](https://etherscan.io/enslookup) does not work in Status browser
> - Contract link to release does not work in Status browser. Connect to web3 gives an error message 'Unable to locate a compatible web3 browser'

Just checked with the latest production version, these two works fine now.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
