### ISSUE TITLE
Update framework for keycard to support reset passcode flow

### ISSUE THREAD

**Issue by churik** [status-im/status-react#10827]
# Problem

Currently there is no option to add automation tests for:
- wrong PIN error
- frozen card flow
- blocked card flow

## Acceptance Criteria
- see "Wrong passcode" error
- can finish "Reset passcode" when card is frozen
- can get "Blocked card"  screen

**Comment by churik** [comment]
cc @rasom @guylouis

**Comment by guylouis** [comment]
@churik  do you think it is still needed ?

**Comment by churik** [comment]
It is. each release we recheck it manually, in case it will be available it can be automated.

**Comment by bitgamma** [comment]
@churik do you mean that the simulated keycard should support those methods? basically implement "real" PIN/PUK handling etc?

**Comment by churik** [comment]
if that's possible and not too complicated, yes
(and also if that can identify real issues with keycard from your POV)

**Comment by churik** [comment]
if not -I'll close this

**Comment by bitgamma** [comment]
for sure it can help to find regressions especially since the PIN/PUK components are reused in several places and thus testing if a change affected other flow becomes tedious. When the native modules are updated as well though (react-native-status-keycard), we will need to test on real devices at least some basic flows since the simulated device completely skips the native interaction. 

I don't think this will be too complicated, I will work on it when I have some time.
