### ISSUE TITLE
Timer isn't refreshed after the entire audio message has been played in 1-1/group chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11100]
# Bug Report

## Problem

After the entire audio message has been played timer isn't refreshed and the last second of the audio message is shown.
Also, timestamp looks like the length of the audio message.

#### Expected behavior

After playing the audio message, the timer shows 0:00.

#### Actual behavior

![ezgif com-resize (21)](https://user-images.githubusercontent.com/67952253/90643886-5c200300-e234-11ea-9430-b81eb0e9581e.gif)

### Reproduction

- Open 1-1/group chat
- Send audio message
- Play audio message 

### Additional Information

- Status version: Nightly 19/08
- Operating System: Android, iOS

@errorists Could you recommend how to place the timestamp so it doesn't look like the length of the audio message?

**Comment by churik** [comment]
Let's have @errorists eyes on it.
@errorists if you think that looks fine, please close the issue.
Thanks!

**Comment by errorists** [comment]
It's temporary, the idea is to remove timestamps from messages entirely and [have them show up on tap or gesture only.](https://github.com/status-im/status-react/issues/10734) So while I agree it's imperfect, I think it's something we can live with. For a quick fix, I'd hide the duration of the audio message since it's really not that important: the audio is already downloaded, if you feel like it's too long then you can pause it, I doubt anyone cares if it's 10 seconds or 30.

**Comment by churik** [comment]
so can be closed then for now, thank you!
