### ISSUE TITLE
Push notification for commands in 1-1 chat, request transaction/address-request/decline

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11175]
As a user
I want to receive push notifications when a (requests for) transaction is sent to me
So that I know immediately that someone has sent me some funds

### Acceptance

User receives a push notification when is sent: 
- a request transaction 
- address request
- decline 

Out of scope:
- accept it in 1-1 chat.

**Comment by cammellos** [comment]
I'll change this up to a feature as out of scope, only messages were in the initial feature.

**Comment by cammellos** [comment]
There's an issue with the `Accept` feature.

Once a user "accepts" sending funds, the transaction is not displayed immediately and is validated first.
So if a user sends a push notification as soon as accept is clicked, the receiving user will not see the transaction.

We need UX input on this one, a couple of options are:
1) Immediately show the transaction post as the user clicks on accept, showing the user that is still being validated
2) Send a push notification only when the transaction is validated (this is bad, as the user might have gone offline before that).

So 1 is preferred. 
I kind of remember @errorists already had some ideas on this, would you mind giving your thoughts (link to issue if you already created one).
For now I'll keep it out of scope as it's ready to be picked up otherwise, and we can leave "accept" on a separate issue.
thanks

**Comment by churik** [comment]
after https://github.com/status-im/status-react/pull/11653 PNs for commands in chat are not working anymore, so feature is the same for IOS and for Android.

**Comment by pavloburykh** [comment]
### UPDATE
Bug is also relevant for Android since implementation of remote notifications https://github.com/status-im/status-react/pull/13028

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app. 
Added `recheck` label for easy finding that one in case of need.
