### ISSUE TITLE
Showing channel list when typing # in chat

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#11377]
# Problem
If channels are not accurately 'mentioned' others can end up in an empty chat because of a typo, misspelling, etc.. Currently, users need to put in effort to manually enter the correct chat name

### User story
As a user
I want to see a list of public chats to select from when 'mentioning' a chat 
Because I want to make sure I include the exact chat name to prevent others from ending up in an empty chat

### Content requirements
Chat list should include
- channels already in your list
- channels in our hard coded list (see https://github.com/status-im/status-react/pull/10934)

## Acceptance Criteria
- Channel list is populated and visible upon entering `#`
- Channel list includes required content alphabetically
- Continuing to enter manually allows to confirm by tapping on channel from list (replacing the manual input following `#`)
- cc @errorists for any further input requirements as discussed for mentions

## Future Steps
This can in the future be expanded with
- channels in your community (future)
- channels where contacts have posted (future)

**Comment by shivekkhurana** [comment]
This issue not straightforward to implement and will need some changes to how the @ "at" mentions work.

## Current process
- An on-change handler is triggered each time a character is entered
  - This handler is triggered at different places depending on the platform but has the same effect
- A matching function computes the positions of `@` signs
  - For the text: `Yo you @fds Dodd’s fest @fds dad  fed`
  - The at-index representation is `[{:from 7, :to 23, :checked? true, :mention false, :channel-mention? false, :next-at-idx 24} {:from 24, :to 37, :checked? false, :mention false]` 
  - The `:from` signifies and `:to` signify the start and end of search term. Everything after the `@` sign is considered to be a search term until the next `@` sign is encountered.
  - If the user didn't choose an autocomplete-suggestion for the first `@` sign, and proceed to type another `@` sign, the first search term is marked as checked:true and mention:false
  - Had the user selected a suggestion, the search term will be marked as checked:true and mention:true

- If there was indeed a mention
  - The input value is updated with the correct text (for example: `Yo you @fds Dodd’s fest @fds dad  fed  @moxarra jYo you @fds Dodd’s fest @fds dad  fed  @moxarra j`, here moxarra was added when the suggestion was pressed, this could also be a three letter username)
  - Then the same `@` indexing criteria is used to generate the new representation of the text
     - In this case, it would be ` [{:from 7, :to 23, :checked? true, :mention false, :channel-mention? false, :next-at-idx 24} {:from 24, :to 38, :checked? true, :mention false, :next-at-idx 39} {:from 39, :to 46, :checked? true, :mention? true}]`
  - This intermediate state is then used to calculate the new value of the text-input: `[[:text Yo you ] [:text @fds Dodd’s fest ] [:text @fds dad  fed  ] [:mention @moxarra] [:text  j]][[:text Yo you ] [:text @fds Dodd’s fest ] [:text @fds dad  fed  ] [:mention @moxarra] [:text  j]]`
  - The input then renders the blocks marked as `:mention` with a blue color

## Problem
The system is built around `@` indexes. `@` signs are anchor points, and everything in between is a search term. Using these `@` indices, the intermediate state is calculated and the new value of text-input is computed.

If we were to replicate the same proccess with`#` as an index, instead of `@`, the new value of text-input will be incompatible with the one produced by `@` version. There is no easy way of reconciliation, so the mentions matching needs to happen in the same function, ie. we need to stop considering `@` as the defacto anchor and allow for more anchors like `#`. 

Maybe in future, we can have a `!` anchor for commands, like `!send 1.5 eth`, the commands would have a suggestion list.

The current system is brittle, needs more thought and refactoring.

**Comment by shivekkhurana** [comment]
🦆 Thinking out loud here, but one possible solution can be to rebuilt the auto-complete in a simpler way:
```
{:autocompletes 
                           [{:anchor "@"
                             :search-boundary 3  ;; consider upto 3 words after anchor text as the search term
                             :suggestions (fn [search-term]) ;; return list of suggestions for matched search term
                             :suggestions-render (fn [])}
                             
                            {:anchor "#"
                             :search-boundary 1  ;; consider upto 1 words after anchor text as the search term
                             :suggestions (fn [search-term]) ;; return list of suggestions for matched search term
                             :suggestions-render (fn [])}

                            ;; more anchors if need be
]}
```

Then this config will be passed to an on-change handler, with the current input value. This function will look for the last match (ie. if there are multiple anchors in a text, like "Hi @ my name is @shivek and I'm talking in channel #sta", then only #sta will be processed. Everything else will be considered processed already), and show suggestions. 

I might be missing something here, but this will simplify the current system because we don't need to maintain indices anymore. This will also make it easy to add/remove anchors in future. Say we want to use a `!` sign for commands, just add config and it will start working.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
