### ISSUE TITLE
No permission requested for files and media storage on Android when saving an image from the chat view

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#11402]
# Bug Report

## Problem

The issue is reopened and updated as the behavior has changed.

If try to save an image from the chat view without previously granting access to "Files and media" storage (i.e. on the fresh build) the access request will not be shown **_but the image will be saved_**. 

#### Expected behavior

File and media access is requested when saving an image, if it has not been previously granted

#### Actual behavior

Image is saved although no permission was granted

### Reproduction

User A:
- Install Status

User B:
- Start 1-1 chat with User A
- Send an image

User A:
- Open the image
- Three dots -> Save
- Check the device gallery

### Additional Information

- Status version: Nightly 22/09
- Operating System: Android

**Comment by qoqobolo** [comment]
The issue is reopened and the description is updated as the behavior has changed.

cc @bitgamma

**Comment by bitgamma** [comment]
@qoqobolo this is the expected behaviour on Android 10 and newer when using the scoped storage model (which among other things deprecates the WRITE_EXTERNAL_STORAGE permission). This has been introduced in https://github.com/status-im/status-react/pull/12542. The permission is still requested on Android 9 and lower (although I couldn't test because I don't have an Android 9 device).

**Comment by qoqobolo** [comment]
@bitgamma checked on Android 8 and yes, the permission is requested, you are right.
Sorry to bother you! Thanks a lot for the explanation!

**Comment by bitgamma** [comment]
No problem, thanks for checking with older Android version!
