### ISSUE TITLE
Add custom clj-kondo hooks for custom macroses

### ISSUE THREAD

**Issue by Ferossgp** [status-im/status-react#11528]
Add custom [clj-kondo hooks](https://github.com/borkdude/clj-kondo/blob/master/doc/hooks.md) for macroses to ensure that lint rules are followed inside them.

Macros to be handled:
- `fx/defn` - similarly to defn with check on metadata for `::events`
- `fx/merge` - seems like it could be lint'ed as thread macro, plus warn on limitations 
- `defview` 
- `letsubs` - lint as let + check on types for the values, warn on chained subscription

**Comment by Ferossgp** [comment]
`fx/defn` are not tracked by [carve](https://github.com/borkdude/carve) thus we have a lot of dead code in the fx/defn. I assume that fixing clj-kondo lint will open the ability to carve them too, but would require to `carve` only definitions without `{:events []}`

**Comment by mostafarahimifard** [comment]
سلام. خسته نباشید. من زیاد ازاین برنامه سردر نمیارم.
لطفا بگوئیدچطور  میتوانم ازاین برنامه کسب درآمد کنم؟؟؟
خواهشا راهنمائی کنید که خیلی لازم دارم
ممنون وتشکر

**Comment by churik** [comment]
@flexsurfer does it still make sense from your POV?
Close if not, thank you!

**Comment by ilmotta** [comment]
FYI: @Ferossgp, @flexsurfer, @ulisesmac, we don't need to put energy into fixing the lint problems related to the macro because I'm pretty sure the macro will be removed/deprecated in the not so distant future.

A long time ago I experimented with migrating away from the `rf/defn` and `rf/merge` combo and use the functional and conventional approach offered by re-frame, i.e. `reg-event-fx` and the `:fx` effect. Here's the branch if you want to take a look https://github.com/status-im/status-mobile/tree/experiment/stop-using-rf-defn-and-rf-merge.

I just need to find the time to come back to this topic and open a smaller PR to showcase the differences and benefits. It's more interesting than it looks, but I can't explain now :)
