### ISSUE TITLE
app.tornado.cash crashes app on Android with 'java.lang.illegalArgumentException'

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11565]
# Bug Report

## Problem
Initially reported by a user.
At attempt to deposit ETH via dapp `app.tornado.cash` status crashes with error:
![Screenshot_20201220-105743_Status](https://user-images.githubusercontent.com/4557972/102760835-6256f500-4376-11eb-8c3b-3ca1cd6fdbdb.jpg)
Works with MetaMask in Chrome and with Status on IOS.

#### Expected behavior
can deposit ETH or gracefully handled error

#### Actual behavior
crash

### Reproduction

- Open Status
- Restore multiaccount with seed phrase (with at least 0.1 ETH to check the case)
- Open `app.tornado.cash`
- Connect wallet
- Try to deposit 0.1 ETH

### Additional Information

- Status version: nightly 21/12/20, release 1.9.0
- Operating System: Android only

#### Logs

[Status-debug-logs.zip](https://github.com/status-im/status-react/files/5723473/Status-debug-logs.zip)

**Comment by flexsurfer** [comment]
https://stackoverflow.com/a/32638439

**Comment by churik** [comment]
still relevant on 1.13

**Comment by churik** [comment]
on 1.15 the crash is happening on "Setup account" stage
![IMAGE 2021-07-27 13:08:03](https://user-images.githubusercontent.com/4557972/127144092-c45c5d82-7830-4035-8b1e-c37ac0e7b497.jpg)

**Comment by churik** [comment]
Reproducible on https://github.com/status-im/status-react/pull/12409

**Comment by bitgamma** [comment]
This is a known problem with Android webview not supporting blob URL's for download. On react-native-webview's side this is being fixed by https://github.com/react-native-webview/react-native-webview/pull/2091

**Comment by bitgamma** [comment]
the bug in react-native-webview should be fixed upstream. Since we are using a fork and made some changes integrating the fix will probably not be trivial. <strike>Ideally, I want to try to avoid using our fork altogether since in the meantime upstream has received many improvements and seems  to also implement the functionality we implemented in our fork (although probably is not 1-to-1 compatible, let's see).</strike> I updated our fork and applied our changes
