### ISSUE TITLE
Implement new Connectivity dialogues and remove 'Offline' snackbars

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#11716]
# Problem
Currently we display prominent 'Offline' snackbars whenever mail server connection is lost. This is misleading in setting the expectation that all messaging is offline when that's not the case. In addition the interface used to capture communication around network state is too prominent prominent compared to the kind of reliability that's experienced.

## Implementation
![](https://user-images.githubusercontent.com/4932774/106914436-4a101f00-6705-11eb-8032-95a7575153fe.png)

[Design here](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=18667%3A61903)

* [ ] Remove 'offline' and 'waiting for wi-fi' snackbars, and replace them with appropriate icons situated in Chat top bars
* [ ] Tapping those icons should display a bottom sheet with appropriate content
* [ ] nodes offline: crossed out cloud icon
* [ ] completely offline: crossed out wireless icon, red colour
* [ ] on mobile connection and syncing: mobile device with signal
* [ ] on mobile connection and not syncing: crossed out mobile device with signal
* [ ] from the dialogue, tapping on `Settings` takes you to `Sync settings`

## Acceptance Criteria
The interface is implemented and tested. Please be extra mindful around triggering those states and only display the icons once we can reasonably predict that something is wrong, let's not be overzealous.

## Notes
I'm not 100% happy with the `on mobile connection and not syncing icon`, please let me know if you have a better idea that works at that size

## Future Steps
Work towards improving reliability and bandwidth consumption so this dialogue will be less and less necessary :crossed_fingers:

**Comment by guylouis** [comment]
the screen I get is different from the designs, with a bottom part showing 

![image](https://user-images.githubusercontent.com/11461437/109983384-0fe56d80-7d03-11eb-901e-a87fe39c7bc3.png)

I find the bottom part confusing because I read 'Use mobile data' and I don't immediately understand that it refers to the download of history message, but take it as a use 'mobile data with status' which is more general. I know that it still shows that I am connected with peers, but I think that it's mostly a matter of copy and size of sections in this screen to make things much clearer
