### ISSUE TITLE
Can't send images > 1 MB from IOS 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#11733]
# Bug Report

## Problem
The standard size for photos / selfies, made from IPhone 12 is > 2 MB.
At attempt to send any standard photo from gallery or directly from camera image message including description is not sent.
Note: the same photos are sent fine from Android device (Xiaomi Mi Note 9, Android 10)
Currently, the same behavior is in Release 1.10.

#### Expected behavior
Message is sent

#### Actual behavior
![IMAGE 2021-02-10 13:30:00](https://user-images.githubusercontent.com/4557972/107510352-140ae900-6ba4-11eb-8aaf-1258953de8c0.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Start 1-1 chat 
- Try to send selfie with description

### Additional Information

- Status version: RC 1.11 build 5

- Operating System: iOS14, IPhone 12

#### Logs

[status_logs.zip](https://github.com/status-im/status-react/files/5958134/status_logs.zip)

**Comment by churik** [comment]
The compressed  image is 628 kb and it still couldn't be sent
[status_logs.zip](https://github.com/status-im/status-react/files/5958263/status_logs.zip)

**Comment by flexsurfer** [comment]
```
=2021-02-10T12:51:36+0000 lvl=eror msg="failed to send a datasync message" error="huge messages are not allowed [7b0bfd0821e59863f5f40180dc678d0b2989fcd52af43962244409c3e0d85ed3][1377157][1048576]"
t=2021-02-10T12:51:36+0000 lvl=eror msg="failed to send message" error="huge messages are not allowed [7b0bfd0821e59863f5f40180dc678d0b2989fcd52af43962244409c3e0d85ed3][1377157][1048576]"
```

**Comment by flexsurfer** [comment]
@churik you say that its 628Kb how did you check that? im not sure what whese numbers are [1377157][1048576] but it seems like its a size of message and its more than 628

**Comment by cammellos** [comment]
Some more infos from @Samyoul :

```
I don't think status.go is used for chat image resize
https://github.com/status-im/status-go/blob/664d68a2c84746b30e38f7b711cbc5e1ed098133/protocol/messenger.go#L2062-L2068
```
Basically images are not resized in status-go yet, as it predates the profile pictures functionalities, that might result in images too large.

One potential solution is to use status-go to resize images:
```
We need to prevent the resize from status-react because that will cause problems
But once we have the image payload we can use https://github.com/status-im/status-go/blob/a77a40fdf43888c328919f378f6e287fa9976c61/images/encode.go#L28
 ```
Similarly to what we do with profile images

**Comment by qfrank** [comment]
I'll look into it :)

**Comment by qfrank** [comment]
Currently i have moved resizing to status-go, it works good except when uri is something like `ph://AC40459B-5AF7-4BFB-8B3E-53D10A6D21C4/L0/001`, before this i assume uri should be like `/Users/mac/Library/Developer/CoreSimulator/Devices/2B199AB3-1C70-41F7-A970-687332269E5F/data/Containers/Data/Application/881EDB22-0886-44FE-8032-33316C4DB5DA/tmp/react-native-image-crop-picker/E3D3E2E0-6CB6-444A-8913-E41125D0C5BE.jpg` so that status-go could access the image content.

Looks like we need a native implementation method called e.g. convertPhAssetToUri  similar to this: https://github.com/itinance/react-native-fs/blob/f2f8f4a058cd9acfbcac3b8cf1e08fa1e9b09786/RNFSManager.m#L752-L753 , but i'm not familiar with object-c. If there is someone could implement it, that would be great, otherwise i'll try to use [expo-media-library](https://github.com/expo/expo/tree/main/packages/expo-media-library) (not my prefer, it's a little heavy) @cammellos

**Comment by churik** [comment]
Couldn't reproduce on nightly 05/04/22 - tried to send several dozens of images of different size and resolution: all sent successfully and fetched from offline
