### ISSUE TITLE
Can't connect Hermez wallet dApp to Status wallet

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#11925]
**Issue** 
As a user I can't connect Hermez wallet dApp (https://wallet.hermez.io/login) to my status wallet

**Reproduction** 
- in Status browser browse https://wallet.hermez.io/login
- click on 'connect with metamask'
- the user then gets the following error  "input is invalid type"
![IMG_03F4D93CC4E8-1](https://user-images.githubusercontent.com/11461437/112443014-bc3bd200-8d4c-11eb-830e-822ad1619087.jpeg)

**Comment by flexsurfer** [comment]
for some reason page won't load on iphone

**Comment by flexsurfer** [comment]
ok on android i can see it uses both eth_sign and signTypedData_v4, both not supported by status, personal_sign is supported instead of eth_sign and signTypedData_v4 blocked by https://github.com/MetaMask/eth-sig-util/issues/106, so i guess its time to just implement both just to be compatible with MM? cc @cammellos

**Comment by flexsurfer** [comment]
eth_sign can be just supported by personal_sign in status, i guess latest dapps and libraries use eth_sign as personal_sign with same parameters
