### ISSUE TITLE
[Bug] show / hide password "eye" won't "hide' password

### ISSUE THREAD

**Issue by nahuhh** [status-im/status-react#11955]
# Bug Report

#### Expected behavior

[comment]: the 👀 in the password field should hided the password. 

#### Actual behavior

[comment]: unable to hide password after revealing password. 

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

#### Acceptance Criteria

Rules for the future PR to be accepted.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- log out or add an acct
- type password
- tap the show password eye
- nothing it shows the password 
- Tap again
- password still visible 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: 1.12.1 (20210324160131)
[comment]: # 
- Operating System: android 10

**Comment by churik** [comment]
@nahuhh 
thanks for reporting!
Reporducible on 1.13 release
UPD: Reporducible on 1.15 release

**Comment by bitgamma** [comment]
the underlying problem is in react-native itself https://github.com/facebook/react-native/issues/27946

we can workaround this, but when the password is shown the keyboard changes to activate autocorrect/autocomplete (reverts to disabling it when hidden again). Would this behaviour better than the current one? If yes I will open a PR. It surely looks less broken.

also, I have noticed that when entering the seed phrase, the autocomplete is active (which means the seed phrase becomes stored by the keyboard itself, depending on its settings). I have a fix for this one already.

@churik wdyt?
