### ISSUE TITLE
"Community information is not found" after opening community view from home

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12008]
# Bug Report

## Problem
Just after creating community "Not found" when accessing it via home view.
Blocker for testing/dogfooding communities.

## Expected behavior
Can see community page

#### Actual behavior
![IMAGE 2021-04-20 08:42:37](https://user-images.githubusercontent.com/4557972/115349619-5d834000-a1b4-11eb-85c7-5faae41a1ec0.jpg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create community
- Open community from home view

### Additional Information

- Status version: nightly 20/04/21
- Operating System: Android, iOS

**Comment by vkjr** [comment]
@flexsurfer, checked recent commits and found out that issue was introduced by [chat list optimization](https://github.com/status-im/status-react/commit/073371c4edf667488d4dea65fb9c6c7042930249). Unfortunately I wasn't able to quickly understand the reason, so reassigning issue to you.

Strange thing I noticed: when navigated to community page, `community-id` comes as an object and `community` retrieved as `nil`. I suspected `community-id` to be a string.
