### ISSUE TITLE
Wallet refresh after user has used buy crypto feature 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12000]
In order to reduce the number of requests to infura, we have reduced the frequency and situations where the wallet is refreshed. 
When a user uses buy crypto, he expects to know he received his crypto as soon as he received them. 

We should trigger refresh of the wallet after right after the user has used on buy crypto feature. 

note: exact behaviour to be decided and described before implementation

cc @cammellos

**Comment by hesterbruikman** [comment]
Good news on this one, @rasom already updated the behavior in #11924

**Comment by rasom** [comment]
@hesterbruikman @guylouis currently after opening "buy crypto" we check history 20 and then 40 minutes later. Do you want to have some additional intervals, like check in 5/10 mins and then return to 20 minutes period?

**Comment by hesterbruikman** [comment]
Ah I thought tx history checking was resumed _for_ 30 mins for an empty account in case 'buy crypto' is tapped. Do I understand correctly that we check _at_ 20 min and _at_ 40 min, after tapping 'buy crypto'?

If so, yes I think additional intervals would be good. 

Another discussion would be to include other methods for incoming pending transactions so that we know with more accuracy if it makes sense to check confirmed transactions.

cc @carlfairclough

**Comment by hesterbruikman** [comment]
Reopening after discussion on [Discord](https://discord.com/channels/624205794384281629/626738033701683200/832529786454409246) 

#11821 implemented watching for transactions, however the interval is low and can be configured
Agreed interval is 2/3/5/10/20

Pull to refresh as merged in #11937 should give the user sufficient options to fill the gaps in between intervals
