### ISSUE TITLE
Request user's approval of terms of services 

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#12081]
**Goal**
We want the user to approve the most recent terms of services as listed here https://status.im/terms-of-service/ before he uses status mobile and status desktop

**Notes** 
To avoid using a push notification service, we can consider we will update our terms of services only concurrently with new releases 

**Design**
@errorists could you suggest a design for this ? 

cc @cammellos

**Comment by errorists** [comment]
[added designs](https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=9417%3A32524). Since T&C remained in Hester's playground I would defer to her when she's back if these should be shown immediately after splash and before login with no option of declining (right) or after you sign in with the option to decline and be logged out of that account (left)

<img width="1116" alt="Screenshot 2021-05-05 at 11 09 11" src="https://user-images.githubusercontent.com/4932774/117119602-9a455e80-ad92-11eb-9f87-9729ff817cbc.png">

**Comment by guylouis** [comment]
as a note, I see that Carly wrote in Discord
> The language next to the button should read, “I have read and agree to your Terms of Service and Privacy Policy""

**Comment by errorists** [comment]
yea, that's not gonna fit haha 😅

**Comment by guylouis** [comment]
closed and replaced by #12206 and #12207 for more clarity (distinction between existing users and new users)
