### ISSUE TITLE
Sync of communities data

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12145]
As a user
I want the communities data to be synced across my devices
So that I can easily use multiple devices

### Description

When a user joins a community
- The community should be joined as well on a paired device

When a user leaves a community
- The changes should be reflected on the paired device

When a user creates a community
- The community should show up on a paired device

**Comment by guylouis** [comment]
for reference, part of the broader sync effort for status documented here https://docs.google.com/spreadsheets/d/12Oi6rVkxB2so2L493xGRe_0HbF4NRvdXMAbQ7x9f2ic/edit#gid=0

and added phase 2 label since it was prioritized as part of phase 2, reference document here 
https://docs.google.com/spreadsheets/d/1HIrp1xTO0obt9T-DgR0Kpv5U5pc9twloHGEcOo70lmw/edit#gid=1478131306

**Comment by churik** [comment]
Closed in #12248
