### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12286]
As a user
I want to be able to delete messages
So that I can correct any potential mistake I made

### Description

We should provide users a way to delete messages, that should delete messages on both devices.
We should keep the data on the device in order to show a record. 
The implementation can be done similarly to how we did with edit messages.

**Comment by cammellos** [comment]
@errorists do we have mobile designs for this? would you mind linking them? Thanks!

**Comment by errorists** [comment]
<img width="351" alt="Screenshot 2021-07-08 at 09 07 10" src="https://user-images.githubusercontent.com/4932774/124877959-e350a380-dfcb-11eb-9c47-e8ceec8452d7.png">

Sure. It would mostly amount to adding the `Delete` button to the list of actions. Since the list of actions is too large to fit the container horizontally like it does now, we would also need to change the layout to vertical. I spoke with Brian about it earlier and it shouldn't be a biggie.

Deleted messages leave no trace in chat, there is no confirmation warning.

[Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=20791%3A54)

**Comment by shivekkhurana** [comment]
### ℹ️ The backend is being worked on here: https://github.com/status-im/status-go/pull/2279

**Comment by churik** [comment]
Closed in https://github.com/status-im/status-react/pull/12390
