### ISSUE TITLE
Implement swap

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12523]
As a user
 I want to be able to swap different tokens
So I can more easily manage my assets

# Description

The goal of this feature is to integrate Paraswap for swapping assets in Status. 

## Design
- The UI flow is at https://www.figma.com/file/UQSs6JFVpYRhpgCimvVDPl/Swaps%2C-WalletConnect-%F0%9F%94%926-Dec-21?node-id=69%3A13840
- The design incorporates signing multiple transactions in the first attempt where the approval transaction has not been made. In this case we just need to sign two transactions, and broadcast them together. 
- Its understood that the status of the transactions (ie failed, pending, stuck) will not be visible for now. This status section will be added later.
- The currently merged UI is slightly different from the design shown above. This is because the above design reduces scope, and tries to not break existing layout. The merged UI (with round action buttons) was how the feature entry point was envisioned, and will be soon.
- Currently, the entry point is via the three dot menu on the wallet as per the design. This needs to be implemented in the UI.
- The design system guidelines for this feature (and in general) are at https://www.figma.com/file/Qj5jhvbxby4DkbggSsYZHS/Design-System-%E2%8E%9C-Mobile?node-id=986%3A9641

## Paraswap
- The Paraswap integration includes two steps: getting data like liquidity pairs, liquidity volumes, slippage etc and then making actual transactions
- There is a JS implementation here : https://github.com/paraswap/paraswap-widget that can act as a reference.
- The Status app can directly interact with Paraswap contracts. As long as Status doesn't charge any commission on the swaps, Paraswap fee will be 0. But if Status chooses to charge a commission, Paraswap will take a cut in that commission. 
- The Paraswap website doesn't charge any commission (except for liquidity provider fee and gas).
- Here's the Meta Mask implementation of the Swaps https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/swaps.js

## Next steps overview
- Get quotes https://github.com/paraswap/paraswap-sdk
- Get associated metadata - like gas price, liquidity fee
- Figure out if an approval txn is needed
- If not, generate and sign a swap txn
- If yes, generate an approve and swap txn, sign them both and broadcast at once

**Comment by cammellos** [comment]
There's still a question on which service we will be using underneath for the swap, I'll update the task as necessary, blocked for the time being.

**Comment by shivekkhurana** [comment]
The goal of this feature is to integrate Paraswap for swapping assets in Status. 

## Design
- The UI flow is at https://www.figma.com/file/UQSs6JFVpYRhpgCimvVDPl/Swaps%2C-WalletConnect-%F0%9F%94%926-Dec-21?node-id=69%3A13840
- The design incorporates signing multiple transactions in the first attempt where the approval transaction has not been made. In this case we just need to sign two transactions, and broadcast them together. 
- Its understood that the status of the transactions (ie failed, pending, stuck) will not be visible for now. This status section will be added later.
- The currently merged UI is slightly different from the design shown above. This is because the above design reduces scope, and tries to not break existing layout. The merged UI (with round action buttons) was how the feature entry point was envisioned, and will be soon.
- Currently, the entry point is via the three dot menu on the wallet as per the design. This needs to be implemented in the UI.
- The design system guidelines for this feature (and in general) are at https://www.figma.com/file/Qj5jhvbxby4DkbggSsYZHS/Design-System-%E2%8E%9C-Mobile?node-id=986%3A9641

## Paraswap
- The Paraswap integration includes two steps: getting data like liquidity pairs, liquidity volumes, slippage etc and then making actual transactions
- There is a JS implementation here : https://github.com/paraswap/paraswap-widget that can act as a reference.
- The Status app can directly interact with Paraswap contracts. As long as Status doesn't charge any commission on the swaps, Paraswap fee will be 0. But if Status chooses to charge a commission, Paraswap will take a cut in that commission. 
- The Paraswap website doesn't charge any commission (except for liquidity provider fee and gas).
- Here's the Meta Mask implementation of the Swaps https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/swaps.js

## Next steps overview
- Get quotes https://github.com/paraswap/paraswap-sdk
- Get associated metadata - like gas price, liquidity fee
- Figure out if an approval txn is needed
- If not, generate and sign a swap txn
- If yes, generate an approve and swap txn, sign them both and broadcast at once

**Comment by churik** [comment]
closing due to re-design, label `recheck` added for future re-consideration
