### ISSUE TITLE
Statuses of other users are not displayed in user profile and Timeline (if add user to contacts)

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#12596]
# Bug Report

## Problem 

If open a user profile of UserA who has statuses in his profile, they won't be displayed there. If UserB adds this user to contacts, the user's statuses will also not be shown in UserB's Timeline.

The issue is reproducible on Nightly 17/09 and 16/09, but is not reproducible on Nightly 15/09

#### Expected behavior

Can see statuses when opening user profile of any user and statuses of my contacts in my Timeline

#### Actual behavior

Statuses of other users are not displayed anywhere 

### Reproduction

UserA:
1. Open Timeline tab
2. Post smth

UserB:
1. Open user profile of UserA and check statuses
2. Add UserB to contacts and check Timeline tab

### Additional Information

- Status version: nightly 16/09, 17/09 (no issue in nightly 15/09)
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by rapidddenis** [comment]
Shall User also see statuses directly in chats?

**Comment by rapidddenis** [comment]
Settings like:
"Show my status to everyone"
"Show my status to contacts only"

Same ass icons pics

**Comment by flexsurfer** [comment]
this change probably a reason https://github.com/status-im/status-go/commit/bd1e6b0033c7abbd6dbfeef54d0e1e2918f8f343#diff-59d196f7f72de56c64ba2c559fcbb51762c418a22d2b83c59662b772a09b3c0aR1014

**Comment by qoqobolo** [comment]
@rapidddenis 
> Shall User also see statuses directly in chats?

No, currently User can only see statuses in the User Profile and in their own Timeline tab if the User is added to contacts.

> Settings like:
"Show my status to everyone"
"Show my status to contacts only"
Same ass icons pics

We don't have these settings now. Everyone can see statuses in the User Profile.

**Comment by rapidddenis** [comment]
Do we need such capability? Seems YES to me.

**Comment by qoqobolo** [comment]
Summon @hesterbruikman, your opinion is needed here.
WDYT, do we need privacy settings that make user statuses visible only to contacts?
If so, we will log a feature request for this.
Thanks

**Comment by hesterbruikman** [comment]
@qoqobolo https://tenor.com/view/im-glad-you-called-thanks-for-calling-i-appreciate-you-calling-im-happy-you-called-nancy-travis-gif-15608014

@rapidddenis If I understand correctly you're suggesting something like a public, read-only timeline. When you enable `Show my status to everyone`, anyone will be able to see your status updates when they view your profile, correct? 

First up: this seems doable. What's needed here is for another user viewing your profile to _subscribe to a topic_ where you post your updates; When you publish updates, others still need to decide if they want to receive them to prevent a literal inbox overload. Due to the nature of collecting messages through the Status Network, collecting everyone's updates can result in it taking a really long time to load messages. Not ideal. It needs a filter.

Currently this filter is updated when people add you as a contact. Viewing a profile can be used as trigger to update the filter. 

I'll check on some other opinions. I think it's a valuable feature, but as the team is working on community chat, I'm not sure what the future of status timeline looks like. i.e. it could be replaced by following a 'read-only' community which would be similar to status updates, but works quite differently.

**Comment by rapidddenis** [comment]
> @rapidddenis If I understand correctly you're suggesting something like a public, read-only timeline. When you enable `Show my status to everyone`, anyone will be able to see your status updates when they view your profile, correct?

Yes.

> I'll check on some other opinions. I think it's a valuable feature, but as the team is working on community chat, I'm not sure what the future of status timeline looks like. i.e. it could be replaced by following a 'read-only' community which would be similar to status updates, but works quite differently.

Please add this feature in new implementation.
Actually great idea, each user/chat key can be a read only community by default. For example with paid content, seen only to contacts or invited users.
