### ISSUE TITLE
Show warning when adding ENS name for wallet account

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#12750]
# Feature Issue

Indicate to the user that they cannot add an ENS name for a added wallet account, since that's now the account from which chat identity is derived.

### User Story

As a user I don't want to be confused by inability to configure an ENS name because it is owned by a wallet account I've added to the app rather than the main account. I want to see a warning explaining that wallet accounts can't make use of the ENS name.

### Description

Since we check ownership of ENS record against only the main account if the owner is an added wallet it just says we are not the owner, making the user confused. We should be able to easily detect that the owner isn't the main account but rather one of the added wallet accounts and explain to the user why that won't work.

### Acceptance Criteria

Want me to restate what I already wrote in like 3 different ways?

### Notes

Nope.

**Comment by hesterbruikman** [comment]
@flexsurfer see also #10142 for a UI by Maciej for this

**Comment by carlfairclough** [comment]
@jakubgs @flexsurfer @hesterbruikman 

Derived chat keys aren't connected to the default wallet address (aside from being derived from the same seed phrase), so really the user should be able to have an ENS name (`*.stateofus.eth, *.eth`) owned by any public key and have that point to a chat key. Otherwise I think we're accidentally creating a moat around ENS names, Status Chat & Status Wallet by forcing folks to migrate ENS to their first Status account.

The issue is, IMO, that **folks can't point ENS names from imported accounts to chat keys, but should be able to**. I want to cover this on the design side for wallet, unless my understanding is incorrect 🤡

**Comment by flexsurfer** [comment]
@carlfairclough its covered here  #10142
