### ISSUE TITLE
Add Binance Smart chain as main network

### ISSUE THREAD

**Issue by churik** [status-im/status-react#12760]
# Bug Report

## Problem 
Requested by users. Currently can be added as custom network, but have ETH as main currency and transaction history can't be loaded

#### Expected behavior
1) Can see correct balance of BNB 
2) Can see transaction history
3) Can easily switch to Binance smart chain as it will be in the list of Main networks

#### Actual behavior
<img width="411" alt="Monosnap 2021-10-28 12-24-11 png 2021-10-28 12-26-57" src="https://user-images.githubusercontent.com/4557972/139238424-da349f95-801b-436c-ba66-0a8400d08fce.png">

![IMAGE 2021-10-28 12:28:41](https://user-images.githubusercontent.com/4557972/139238585-0f5b777e-316b-4e94-bfed-bd1fbc620cd4.jpg)

### Reproduction

1) Open Status
2) Add custom network with params: 
URL: https://bsc-dataseed.binance.org/
ID: 56

### Additional Information

- Status version: release 1.17 
- Operating System: Android, iOS

**Comment by churik** [comment]
Basically, for any custom RPC chain we missing some optional params, which are using in MetaMask for instance (currency symbol, block explorer)
![Monosnap 2021-11-03 16-31-36](https://user-images.githubusercontent.com/4557972/140091730-1c6201aa-a9f5-429a-8cd2-11e5c58c11dd.png)
I believe it may be related to https://github.com/status-im/status-react/issues/12777 also, as we don't have blockcain explorer added on these chains (just an assumption)

Anyway, if custom RPC can work as it works in metamsk - that would be just awesome.

**Comment by qoqobolo** [comment]
Additional related issue that was reported from our user:

### Cannot connect to Dapps in binance smart chain

**Steps:**
1. Switch to Binance smart chain 
2. Open browser and navigate to some of the following DApps:

- Farm.rabbitfinance.io
- pancakebunny.finance
- pancakeswap.finance
- App.alpacafinance.org
- www.tranchess.com

3. Allow connection to the wallet

**Expected behavior:** can connect and use DApp normally
**Actual behavior:** DApp and Status browser tabs freeze

OS: Android, iOS
Status version: 1.17, Nightly 3/11

**Comment by flexsurfer** [comment]
@qoqobolo dapps are fixed here https://github.com/status-im/status-react/pull/12791

**Comment by flexsurfer** [comment]
@churik we don't use block explorers that's why history doesn't work, dunno might be @rasom could comment what we can do about that ,but most likely it depends on RPC if it supports methods we need for history or not
