### ISSUE TITLE
Add functionality for changing the order of channels in community categories

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#12808]
# Feature Issue

leftover from https://github.com/status-im/status-react/issues/12292

### User Story

As a community admin, I want to change the order of channels in community categories

**Related conversation**
https://github.com/status-im/status-react/pull/12758#issuecomment-955849770

**Comment by hesterbruikman** [comment]
@Parveshdhull, @blake-hunsicker is working on a design for this. 

Also, apologies if I missed this: Are there limitations that prevent us from using a drag and drop action here?

**Comment by Parveshdhull** [comment]
Hi @hesterbruikman,
These are the reasons(IMO) which make buttons a better choice than draggable for this feature
- Reorder screen is only used by admins and only on rare occasions, and using another external library just for some rare cases doesn't seem right.
- If used draggable then categories are ordered using drag, and nested channels are also ordered using drag and drop and especially in iOS, reorder screen is also itself draggable(drag to close).
It looks like too many nested drags and might conflict with each other.
- If the number of channels inside the categories increases, then it will be very difficult for the user to track the drag in mobile screens.
He/she might accidentally drop at the wrong positions/categories and get confused about the previous location of the channel (this might work better on desktop). Buttons are just simple and clear about what they will do.

What do you think?

**Comment by hesterbruikman** [comment]
I get the reservation about an external library. This is a pattern that will likely come up more though. So I do think it's worth seeing if there is a way to make a drag and drop usable, given the issues you describe in point 2 and 3. 

These are great points and definitely seems it will take more time and experimentation/prototyping to see if we can introduce a drag that shows a transition state to see where the drag will end up upon release.

**Comment by carlfairclough** [comment]
@Parveshdhull I remember the previous issue being chatted about and we needed a global pattern for reordering, and I hoped the up/down arrows were sufficient as an interim measure but it seems not 😅

I'm working on network & token list management at the moment, which includes global patterns for editing, reordering etc. I will send this over ASAP. We should leverage native (or almost native) patterns for these things, e.g. reordering:

Android (Material)
https://kstatic.googleusercontent.com/files/3b4f47c77955908daec564c62deebb0a1ea2e1dab3cd664580613d4e86675780f36b558adc40d13758e6fa0f8e505398e80ec51f922e1177d0447727077b63f6

iOS
https://developer.apple.com/design/human-interface-guidelines/ios/images/Gestures_Drag.mp4

If this reorder interaction interferes with an underlying gesture (e.g. drag to dismiss) then it should be disabled during the reorder

**Comment by Parveshdhull** [comment]
@hesterbruikman, @carlfairclough Sounds good 👍,
So, Does [this](https://github.com/computerjazz/react-native-draggable-flatlist) looks good for drag and drop implementation?
Also, how will UI work? Drag and drop sound fine for a simple list, but are channels and categories are ordered on the same screen?

**Comment by Parveshdhull** [comment]
I look forward to @blake-hunsicker's designs

**Comment by blake-hunsicker** [comment]
Here are the [WIP designs](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=22168%3A103261) (pending feedback from design, devs).

Notes so far:

- The user can move individual channels
- When the user presses on a category's drag handle, they will move the category and its child channels
- All colors I used for the focus state exist already [in this file](https://www.figma.com/file/aVp7AMrSuRBW58serJdaXOrk/Status-Colors?node-id=367%3A232), which appears to be the mobile design system color scheme
- Not sure what options we have for haptic feedback, but it'd be very nice to include
- The one new style I'd introduce is the shadow -- the only existing style I found was labelled legacy and [wasn't strong enough IMO](https://www.figma.com/file/ThsieWfnM0NHmd5qCWKMkBF5/Bars?node-id=318%3A304).
- ~~Just saw @carlf's idea to circumvent the edit mode with a long press... that sounds good to me:~~ (Can't do this because the user must be able to longpress on chats to open a menu)
    > ~~a regular tap-hold interaction should trigger the reordering, IMO. drag handles are maybe unnecessary~~

**Comment by blake-hunsicker** [comment]
One question while @Parveshdhull thinks things over, @hesterbruikman and @John-44:

Can users move a single non-category channel wherever they want, or do they have to group non-category channels together? Asking because users will probably want to move an important non-category channel around and away from others (like a "Welcome" channel, or a temporarily important one, like "Liscon Logistics"). I see no problem with it, but want to make sure. Below is an example:

<img width="713" alt="Screen Shot 2021-11-12 at 2 44 21 PM" src="https://user-images.githubusercontent.com/28980512/141525773-415a9663-bb6f-4d11-8f3b-546f8cda73d4.png">

**Comment by John-44** [comment]
@blake-hunsicker yes users can move single channels that are not in a category wherever they want, and when grabbed these channels that are not in a category should be moved individually (not grouped)

**Comment by flexsurfer** [comment]
hey, drag-drop is a complex feature, and in RN it will be challenging to implement effective and performant one, so it would be cool if we can go with buttons for the first implementation, I feel like it's not a major feature for communities and will be used not often right?

**Comment by John-44** [comment]
@flexsurfer I discussed this with @cammellos on Monday, we agreed that we would implement @blake-hunsicker 's designs in three steps, with the final implementation step fully implementing @blake-hunsicker 's design, and each of the implementation steps happening sequentially, one after another.  We are going to need drag and drop lists in other places so good to get this in.  Happy to hop on a call to discuss further if that would be useful, but my current understanding is that this '3 step' (landing each step in product after it's complete) is the current plan of record.  Happy to discuss more, feel free to ping me

**Comment by blake-hunsicker** [comment]
Changed the designs to add segmented control, as discussed in our last meeting.

In the new designs, the user can both move channels and categories, depending on which tab is active: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=22167%3A100053
