### ISSUE TITLE
Link to message

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#12842]
As a user
I want to be able to post links to messages 
So that I can share them with other users

### Description

We should add a way to link to messages by longpressing on them and have an option to copy the link message.

If a user would click on a message, it should be taken to that chat (if it exists) and load that message (if it's the database).

If either the chat nor the message is there no action should be taken for the time being, though we might revisit in the future.

**Comment by cammellos** [comment]
Initial implementation https://github.com/status-im/status-react/pull/12705

**Comment by du82** [comment]
How about links to posts in the timeline too?

**Comment by flexsurfer** [comment]
implementation for this issue related to implementation for [[THE ISSUE] Add an unread messages indicator inside chats ] https://github.com/status-im/status-react/issues/6375
we've been trying to implement THE ISSUE, but no success, here I'll write a summary on what has been done and why it hasn't succeed 

### 1. What we want to achieve

Let's say we have a chat with 1000 messages and we load chunks of 25 at a time
Let's say we want to show message 500 to the user

We need to initialize list with messages from 475 to 525 and scroll to message 500, then when user is scrolling up or down we need to load more messages 

also we need to maintain scroll position when adding new items to the list

### 2. What we need from the list component
 a. onStartRached event to load more messages on scroll in one direction
 b. onEndReached event to load more messages on scroll in another direction
 c. maintainScrollPosition setting

### 3. Why can't we use RN FlatList component

Firstly because its developed and optimized only for one direction, adding messages in another direction is not optimized and not performant, as a result, it does not have onStartRached event
Also there is no  maintainScrollPosition setting for Android, there is open PR https://github.com/facebook/react-native/pull/29466#pullrequestreview-845019219 but it has issues so it can't be used , but because FlatList in anyway doesn't support opposite direction there is no sense trying to implement maintainScrollPosition also there is issue from 2009 https://github.com/facebook/react-native/issues/25239# still not resolved

there is component https://github.com/GetStream/react-native-bidirectional-infinite-scroll#readme 
which tryes to implement onStartRached and maintainScrollPosition in js on top on FlatList, and it has lots of issues, we even outsourced a team of RN devs to make it work in status app but no luck, still lots of issues https://github.com/status-im/status-react/pull/12705

### 4. Other List implementations
a. https://github.com/Flipkart/recyclerlistview

this component optimized for items with the same constant height. Our second major problem is that our items in status has dynamic height, and its quite hard to calculate height before rendering, so its only way to calculate height is to render item but it doesn't make sense if we're speaking about performance , because all list implemented with RN Bridge

here is pretty interesting discussion and attempts to achieve same goal as ours https://github.com/Expensify/App/issues/2985 

the latest results of discussion is here  https://github.com/Flipkart/recyclerlistview/pull/647 

but still there are lots of questions: example shows items with the same height, its not clear how good component maintain position, and how good onEndReached and onStartReached events work when loading messages fast
and latest action on this PR is from Oct 8, 2021

this component has same major issues as FlatList https://github.com/Flipkart/recyclerlistview/issues/44

b. https://www.npmjs.com/package/react-native-vision-list
implementation of Native list on the new RN architecture, sounds promising , but sources are closed https://github.com/margelo/react-native-vision-list#readme , probably later will be published

**Comment by roryabraham** [comment]
Hi 👋 I've got a proof-of-concept with bidirectional pagination implemented in RecyclerListView – take a look at [this PR](https://github.com/Flipkart/recyclerlistview/pull/647). I'm currently working on implementing it in our application with non-deterministic item heights. If you want to try it out help test, feel free! If it works out for us at [Expensify](https://github.com/Expensify/App), we'll probably maintain it pretty actively.

https://www.npmjs.com/package/react-native-vision-list does sound cool though 😏

**Comment by cammellos** [comment]
Closing as this is currently blocked and will need design input
