### ISSUE TITLE
Can't connect to OpenSea dapp

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#13017]
# Bug Report
When visiting opensea.io and attempting to connect wallet, dapp does not trigger. Dapp redirects to download and install MetaMask.

## Problem 
[comment]: # (A problem description)
Can't connect to OpenSea. As we link to OpenSea from wallet, it is an issue that the dapp is not compatible

#### Expected behavior
- Connect with Status is an option
- Tap on MetaMask prompts connection request

#### Actual behavior
- Tap on MetaMask redirects to metamask.app.link

### Additional Information

- Status version: 1.18
- Operating System: Android
- also observed on iOS, unclear if it's the same issue

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
it works in MM mobile app, just wondering how opensea detects MM mobile

**Comment by flexsurfer** [comment]
```
if (ethereum && (!mustBeMetaMask || ethereum.isMetaMask)) {
        resolve(ethereum);
      } 
```

**Comment by hesterbruikman** [comment]
> 

Is that what they use or might be using? Could it be they're using https://github.com/MetaMask/providers?

**Comment by flexsurfer** [comment]
anyway i don't think we can fix it on our side, we need to contact them and ask to add status as an option

**Comment by qoqobolo** [comment]
Closing this since it is still possible to connect to Opensea with Status with the following steps:
1. Open Opensea
2. Tap three dots at the bottom right > `Connect wallet` > `Allow`

_Here is expected to open a modal window with the `Accept and sign` button, however, sometimes you need to refresh the page to see it_ 

3. Refresh the page
4. Tap `Accept and sign` and sign a message

https://user-images.githubusercontent.com/67952253/180220050-042a155c-5ef9-44f1-b94c-3f88bbfe0a11.MP4

---

Please, feel free to reopen this if you think that it's possible to fix it on our side or if we still want to be able to connect with MetaMask without installing the app (will need to edit the issue in that case).
