### ISSUE TITLE
Add changelog from status-go on upgrade

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13090]
If status-go is upgraded in status-react, we should add in the commit the changelog of the changes, this should be done automatically through hooks. Ideally that's reflected as well in the PR description so QA is aware of the changes brought in each PR.

**Comment by jakubgs** [comment]
After a chat with @churik I have some clarity on how this could work:

* The commit description for `status-go-version.json` changes needs to include indication of what changed in `status-go`
* Generating a full change log from from Git for `status-go` would require a mostly full clone and would be quite complex
* Usage of a GitHub diff link [like this](https://github.com/status-im/status-go/compare/62a04392...4b057b09) instead of a full changelog was approved by @churik, which is simple to generate
* The remaining issue is where to get the previous commit of `status-go` against which to compare:
  - Get it from the current branch-off point for the `status-react` PR branch. Will often be outdated compared to `develop`
  - Get it from the current version used in `develop` of `status-react`. But that will not reflect real changes in the PR.
  - Rebase the PR branch and __then__ get the previous `status-go` commit from `develop`, ensuring it's up-to-date
* The issue with the last option is that it forces developers to rebase when they might not want to.

Here are some possibilities regarding the update script:

* Change update script to commit the `status-go-version.json` change as compared to current branch-off point.
* Change update script to always force a rebase and commit the `status-go-version.json` change.
* Split the script into two separate scripts:
   - `update-status-go.sh` - Functionality as it is right now.
   - `commit-status-go.sh` - Utilizes `update-status-go.sh` but also commits the changes. It can either
     A. Not rebase at all, depend on developer to do so.
     B. Make rebase optional with a flag like `--rebase`.
     C. Attempt a rebase but skip it if not possible without conflicts.
     D. Force a rebase and block updating `status-go-version.json`

Now, this is a question more to developers. Which behavior makes the most sense to you?

I'm mostly thinking B and C make most sense.

**Comment by jakubgs** [comment]
According to @cammellos the other way to do this is using Git hooks. Most probably [`prepare-commit-msg`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) which could be used to either prepare a diff link when making a new commit, or updating the commit being amended with the correct diff link.

 This might be simpler than doing a separate script like `commit-status-go.sh`. The annoyance with hooks is that:

1. They have to be installed, which is separate process from cloning/fetching repo
2. They can break and mess with committing workflow for devs, so they have to be simple
3. They can slow down the workflow by trying to do too much

**Comment by jakubgs** [comment]
The workflow of a Git hook would look something like this:

1. Check if the files being commited include `status-go-version.json`
  - This can probably be done with `git diff --cached --name-only -r`
2. Find the branch off point for the feature branch
  - Most probably can be done with `git merge-base`
3. Extract the commit used in `status-go-version.json` at that time
  - Could be done with `git show REVISION:path/to/file`
4. Generate a GitHub diff link based on the new and current commits
5. Check if the default/current commit description contains a link
  - If it does not add the diff in a predictable format, probably at the end
  - If it is update the current link with the new one

In addition to that we'll need a way to install the hook. The simplest way would probably be to put the hook under `scripts/hooks` and then symlink it with `ln -s` in a `Makefile` target `_install-hooks`(kinda like `_tmpdir-mk`) that is called by default, with `-include` for example.

**Comment by jakubgs** [comment]
Part of the workflow could also be a warning telling user to rebase if `develop` has moved on.

But that could be a separate PR.

**Comment by flexsurfer** [comment]
reopen because part of the hook were reverted, because of error on macos cc @audriu

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-react/commit/c69b6408107cea7be9c4fce660e767205082eb19

**Comment by jakubgs** [comment]
The issue is trivial. BSD version of Sed simply makes a value for `-i` flag mandatory, unlike GNU Sed:
https://singhkays.com/blog/sed-error-i-expects-followed-by-text/
