### ISSUE TITLE
Implement token price charts in new wallet redesign

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13338]
As a user
I want to see the historical price of my tokens/coins in the wallet
So that I can track how well my investments are doing

### Description

We should show a chart for each token/coin/wallet to the user so that they can track their portfolio performance.
in the scope of this task we should also understand which service we can rely on for fetching such data (infura/cryptocompare/coingecko etc)

**Comment by flexsurfer** [comment]
to implement this we need to get prices for the period of time, balances of all tokens in all wallets , and show the graph
for graph we could use https://github.com/margelo/react-native-graph
for prices we use cryptocompare, it has a historical API for Daily ,Hourly and Minute Pair 
balances we should get from infura but there is no API for that, this might be really difficult to implement, because we need to analyze all transactions history for all wallets to get history of balances

**Comment by cammellos** [comment]
Closing this as will be re-evaluated as the wallet effort starts
