### ISSUE TITLE
IOS app crashes on sending logs/reporting a bug

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#13342]
## Problem 
IOS app crashes on sending logs/reporting a bug

### Reproduction

1) Open Status IOS build
2) Create/Login existing the account
3) Shake the device
4) Tap on "Report a bug" or "Share logs"
5) Observe the result

#### Actual behavior
App crashes

#### Expected behavior
User is able to send bug report or logs. 

https://user-images.githubusercontent.com/97245802/167597558-1bef8812-0436-4733-bdee-08421dddd8d2.mp4

### Additional Information

- Status version: nightly 
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by flexsurfer** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/11790366/167838436-bf468f2d-1322-478b-9e8d-a5a4833ca8bd.png">

**Comment by flexsurfer** [comment]
error happens in this obj-c method
```
RCT_EXPORT_METHOD(sendLogs:(NSString *)dbJson
                  jsLogs:(NSString *)jsLogs
                  callback:(RCTResponseSenderBlock)callback) {
                  ```

**Comment by flexsurfer** [comment]
@bitgamma any thoughts?

**Comment by bitgamma** [comment]
@flexsurfer I'd say first thing to check is if the paths passed at https://github.com/status-im/status-react/blob/b83fe64b0f1bbfc5c453ef3eb8c7d04ad42d0bed/modules/react-native-status/ios/RCTStatus/RCTStatus.m#L178 are not nil. 

If they are not nil or otherwise invalid, what about trying https://github.com/marmelroy/Zip instead? It is already imported because the Keycard.swift SDK is using it. Looking at the issue tracker of the SSZipArchive project I see many people are experiencing crashes.
