### ISSUE TITLE
Black square instead image instead of content

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13417]
It was reported that a black square is shown instead of the images in chat, that's likely due to the new server implementation.

**Comment by cammellos** [comment]
Some questions that might help us debug the issue:

1) Does it happen on any account, or only on a specific account? (helps us understand whether is a performance issue)
2) Does it happen with any image, or all the images?
3) Is it triggered by putting the app in the background/foreground (i.e Login -> Go to chat -> can you see the images? -> put app in the background -> put the app in the foreground -> send another image -> can you see the new image?)g

**Comment by churik** [comment]
1. Definitely not on any account, couldn't reproduce with IOS 15.5, IOS 14 (Status 1.19 )on a fresh account
2. Likely the issue is in data inside the account, not in the images themselves
3. Didn't manage to reproduce it on fresh accounts at all

What I noticed - is that sometimes images are shown as black squares when trying to be fetched to chat, but for me, it is pretty quick.

However, randomly can be reproduced issue where images are not shown:
![IMAGE 2022-05-27 14:03:51](https://user-images.githubusercontent.com/4557972/170695818-4fbef258-a3f3-43db-9112-74c6d1676852.jpg)
Image to reproduce: 
![JPEG](https://user-images.githubusercontent.com/4557972/170695854-79f1e333-0d12-448a-a204-565543d5fee6.jpeg)
Logs:
[geth.log](https://github.com/status-im/status-react/files/8786489/geth.log)
[Status.log](https://github.com/status-im/status-react/files/8786490/Status.log)
Issue is gone after reopening a chat.

Continue investigation, how it can be related to performance

**Comment by churik** [comment]
So based on: https://github.com/status-im/status-react/pull/13422 https://github.com/status-im/status-react/pull/13425
https://github.com/status-im/status-react/pull/13431 this behavior should be less noticeable or gone. 

So should be better in 1.20, please reopen if still an issue
