### ISSUE TITLE
Message timestamps will not align with real message order if history is fetched from offline

### ISSUE THREAD

**Issue by churik** [status-im/status-react#13462]
# Bug Report

## Problem 
Timestamps of messages do not correspond to their real order when messages are fetching from offline.

#### Expected behavior
Timestamps of messages are the same as for the sender

#### Actual behavior
The order of messages is right, but timestamps are mixing up
https://user-images.githubusercontent.com/4557972/172573241-50e12340-4c06-4c8f-ad94-a8ac48e85a44.mp4

### Reproduction

1) Device 1: start chat with Device2
2) Device 2: close the app
3) Device 1: send 50 messages in 10 mins
4) Device 2: open the app 
5) Device 2: check messages order and timestamps on each of them

### Additional Information

- Status Version: nightly 08/06/2022
- Operating System: Android, iOS

**Comment by cammellos** [comment]
This is due to re-transmission, we use the whisper timestamp, which is the time the message is sent, in case of re-transmission it would be more recent.
The other option is to use a user-defined timestamp, the issue is that is fully controlled by the other client, unfortunately there's no bullet proof solution.

**Comment by churik** [comment]
Closing because of redesign
