### ISSUE TITLE
Search for tags with dot ('#7.14Newsname'.)

### ISSUE THREAD

**Issue by ironurbane** [status-im/status-react#1350]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: In discover tab,  i want to search some tag, like '7.14Newsname'
#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Tag will be "#7.14Newsname"
#### Actual behavior
[comment]: # (Describe what actually happened.)
Tag are "#7" and "#14Newsname"
### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Click Discover Tab
- Click Search button 
- Input keyword '7.14Newsname'

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.9(1434)
* Operating System: IOS 10.3.2

**Comment by annadanchenko** [comment]
It's allowed to create tags with punctuation marks inside, for example #ab!cd #ab,cd #ab.cd # ab?cd #ab:cd #ab;cd They are shown as one word in the status field on Profile and on Recent section in Discover. However, it's not possible to search using same words because search splits it into 2 parts and finds nothing by searching for these 2 parts: ab.cd -> ab cd -> nothing found.
Issue occurs for tags with .,;;?!

Video: https://drive.google.com/open?id=0Bz3t9zSg1wb7enYwNWVMZnpucjQ

Tags are shown as one word if they contain punctuation mark inside it:
![img_0420](https://user-images.githubusercontent.com/6584810/27429936-7dbbc300-574f-11e7-8835-b4934b64f776.jpg)

Search splits search term "any.thing" to "any" and "thing" (issue):
![img_0423](https://user-images.githubusercontent.com/6584810/27429990-a846dee8-574f-11e7-825b-de3c8c741f01.jpg)

**Comment by jeluard** [comment]
Tags are expected to be alpha-numeric characters only. Creating invalid tags must be prevented.

Current split w/o warnings is misleading and will probably evolve.

**Comment by annadanchenko** [comment]
Discover feature is removed
