### ISSUE TITLE
Extend mutual contact requests to pairing

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#13590]
As a user
I want my mutual contact requests to be synced across devices
So that I can communicate with my mutual contacts on each device

### Description

We haven't tested mutual contact requests when two devices are paired, so there's a few cases that we need to check and fix if not working.

A is a pk, B is a pk, 
A1 is a device with pk A
A2 is a different device with pk A

### Syncing with sync all 

1) A1 creates an account, enables mutual contact requests
2) B1 creates an account, enables mutual contact requests
3) A1 sends a contact request to B1
4) B1 accepts the contact request
5) A2 creates an account
6) A1 & A2 enables pairing
7) A1 clicks on Sync All

Expected:
A2 is a mutual contact of B1

### Syncing after pairing

1) A1 creates an account, enables mutual contact requests
2) A2 creates an account
3)  A1 & A2 enables pairing
4) B1 creates an account, enables mutual contact requests
5) A1 sends a contact request to B1
6) B1 accepts the contact request

Expected:
A2 is a mutual contact of B1

**Comment by pavloburykh** [comment]
@cammellos  hi!

I've checked those flows, described in feature request. In fact they work, because we sync contacts of same account on different devices as we used to do it before implementation of contact request functionality. 

At the same time, there are a few questions in scope of mutual contact requests syncing/pairing:

1) Are we going to implement syncing of contact request setting value? Currently we don't. So if Device 1 has enabled contact requests - it will not be enabled on paired Device 2

**CR enabled on paired Device 1**
![photo_2022-07-05 13 28 17](https://user-images.githubusercontent.com/97245802/177309005-1ea7a79c-cd3b-4468-b751-67ed72ea1ba3.jpeg)

**CR disabled on paired Device 2**
![photo_2022-07-05 13 38 23](https://user-images.githubusercontent.com/97245802/177310017-4c6263eb-273e-4940-97be-3bdc2033b36a.jpeg)

2) When paired Device 1 accepts contact request from Device 3, contact request on paired Device 2 will still be in unresolved state in Activity Center, although Device 3 will be added to contacts on both paired Devices 1 and 2.

**AC of paired Device 1**
![photo_2022-07-05 13 36 07](https://user-images.githubusercontent.com/97245802/177309619-523c700c-a317-4bee-a11b-945897d52fb2.jpeg)

**AC of paired Device 2**
![photo_2022-07-05 13 36 10](https://user-images.githubusercontent.com/97245802/177309624-bf85ee3f-2ead-47de-bd57-f0ab9c6f2e13.jpeg)

**Comment by cammellos** [comment]
> Are we going to implement syncing of contact request setting value? Currently we don't. So if Device 1 has enabled contact requests - it will not be enabled on paired Device 2

I'd say no, this is a temporary toggle, so no need.

> When paired Device 1 accepts contact request from Device 3, contact request on paired Device 2 will still be in unresolved state in Activity Center, although Device 3 will be added to contacts on both paired Devices 1 and 2.

This needs implementing, thanks!

**Comment by cammellos** [comment]
Thanks @pavloburykh , I have created a separate issue tracking the case you mentioned https://github.com/status-im/status-react/issues/13672 , closing this one as it does not apply.
