### ISSUE TITLE
Opensea sign up flow doesn't work with Wallet Connect (keycard)

### ISSUE THREAD

**Issue by D4nte** [status-im/status-react#13615]
# Bug Report

## Problem 
As part of Opensea sign up flow, you need to sign a message.
When taping the 'accept and sign' button on opensea after going through the wallet connect sign flow, I signed the message using my keycard but then nothing happened 

#### Expected behavior

Opensea gets the signature and finishes the sign up flow 

#### Actual behavior

Once signed, nothing happens 

### Reproduction

Sign up on Opensea using wallet connect and keycard

### Additional Information

- Status version: 1.19.0
- Operating System: Android

Note: impossible to use Opensea with Status, even in dapp browser.

**Comment by churik** [comment]
After investigation, I found out that the issue is reproducible only with signing message from OpenSea using keycard.
The app connects fine using a password - could connect OpenSea and purchase NFT.

**Steps:**
- restore multiaccount from seed phrase and choose storage `Keycard`
- enable wallet connect in `Advanced`
- desktop (used chrome): open https://opensea.io/  -> Wallet connect
- device: + > Scan QR from wallet connect
- device: tap connect
- desktop: Accept and sign
- device: sign message 

**Expected result:**
wallet is connected, Accept and sign popup is closed
**Actual result:**

Device flow: 


nothing happens with  Accept and sign popup, if tap on cancel - the connection is dropped.

https://user-images.githubusercontent.com/4557972/177170754-2577d1cc-57b3-443a-828a-bdf2cc8ce5c5.mp4


![image](https://user-images.githubusercontent.com/4557972/177170395-895a56a2-3def-4b1d-aad8-9a93ab4409d7.png)

Log: 
[geth.log](https://github.com/status-im/status-react/files/9040010/geth.log)

**Comment by churik** [comment]
cc @briansztamfater  @flexsurfer

**Comment by D4nte** [comment]
Yep that's the one. Nice reproduction! 👍👍

**Comment by bitgamma** [comment]
analysis so far (notes to self, but thought I'd share):

* The reason the signup fail, is that the generated signature for the message is invalid. This only happens when signing with Keycard
* Using the same Keycard account and https://example.walletconnect.org/ instead generates valid signatures (verified also through https://etherscan.io/verifiedSignatures#)
* Signing the same exact text using etherscan.io generates a valid signature. Maybe there are some parameters which I have to check

UPDATE:

Apparently the reason why the wrong signature is generated, is because OpenSea passes the address all lowercase instead of mixed case and makes a comparison fail, which in turns selects the wrong derivation path on card

**Comment by D4nte** [comment]
Same issue with https://unstoppabledomains.com/auth where nothing happen after message being signed. Is it the same problem?

**Comment by bitgamma** [comment]
it is probably the same, the bug would appaear basically with any dapp using WalletConnect + Keycard when signing stuff.

**Comment by ECBSJ** [comment]
The question that I'm wondering is...why does OpenSea even require the step of signing a message before using it? Before when connecting it with WalletConnect, I was never prompted with this step of signing some message...
