### ISSUE TITLE
Sync all devices after initial pairing

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#14447]
As a user
I want my data to be transferred after I paired my devices
So that all my devices are synchronized

### Description

When restoring seed phrase from the paired process (@Samyoul is working on it)
after the pairing is successful, we should make sure the data is transferred to the new device, over the established TCP connection (in order to skip waku).

Basically, the effect should be identical as the user has clicked on `Sync all` from the old device to the new device.

Essentially replicating what SyncDevices in status-go does, but not over waku, over this TCP connection, which means creating some protobufs and processing them on the other end as we would as they were received from waku.

**Comment by Samyoul** [comment]
## Potential Approach

Replicate a similar process flow of:

```go
func (m *Messenger) SyncDevices(ctx context.Context, ensName, photoPath string) (err error)
```

https://github.com/status-im/status-go/blob/10362432769bb759307f911656294b113adf1fa7/protocol/messenger.go#L2220-L2375

BUT, adapt all the called unexported functions that internally call `_, err = m.dispatchMessage(ctx, common.RawMessage{ ... })` so that they return the `Payload: encodedMessage` and DO NOT dispatch the message.

Example, in the case of `func (m *Messenger) syncSettings() error`, create a new function called `makeSyncSettingProtobufs() ([][]byte, error)`, where `[][]byte` represents an array of marshalled `common.RawMessage.Payload`

Once all the encoded messages are returned bundle them into a single protobuf and send the data via 2 new `PairingServer` handlers registered to a new endpoint. You will need to create a new handler for both sending the data and receiving the data.

**Registering a new enpoint**
https://github.com/status-im/status-go/blob/02446b185dcd9f53351a686e10ad36af695497d6/server/server_pairing.go#L112-L115

```go
	s.SetHandlers(HandlerPatternMap{
		pairingReceive:   handlePairingReceive(s),
		pairingChallenge: handlePairingChallenge(s),
	})
```

**Create a new Pairing handler**
https://github.com/status-im/status-go/blob/f33c1cec383d8cd7e14af2832b8017d1e204d9cf/server/handlers.go#L402-L422

```go
func handlePairingReceive(ps *PairingServer) http.HandlerFunc {
	signal.SendLocalPairingEvent(Event{Type: EventConnectionSuccess})

	return func(w http.ResponseWriter, r *http.Request) {
		payload, err := ioutil.ReadAll(r.Body)
		if err != nil {
			signal.SendLocalPairingEvent(Event{Type: EventTransferError, Error: err.Error()})
			ps.logger.Error("ioutil.ReadAll(r.Body)", zap.Error(err))
			return
		}
		signal.SendLocalPairingEvent(Event{Type: EventTransferSuccess})

		err = ps.PayloadManager.Receive(payload)
		if err != nil {
			signal.SendLocalPairingEvent(Event{Type: EventProcessError, Error: err.Error()})
			ps.logger.Error("ps.PayloadManager.Receive(payload)", zap.Error(err))
			return
		}
		signal.SendLocalPairingEvent(Event{Type: EventProcessSuccess})
	}
}
```

Next you will need to replicate the same logic but in `PairingClient` side. A good starting point will be:

https://github.com/status-im/status-go/blob/02446b185dcd9f53351a686e10ad36af695497d6/server/client.go#L92-L105
```go
func (c *PairingClient) PairAccount() error {
	switch c.serverMode {
	case Receiving:
		return c.sendAccountData()
	case Sending:
		err := c.getChallenge()
		if err != nil {
			return err
		}
		return c.receiveAccountData()
	default:
		return fmt.Errorf("unrecognised server mode '%d'", c.serverMode)
	}
}
```

Both `(c *PairingClient) sendAccountData() error` and `(c *PairingClient) receiveAccountData() error` are effectively client side handlers. Also Pay particular attention to `serverMode; case Sending:` in the above code, this process makes multiple calls, `c.getChallenge()` and `c.receiveAccountData()`, for security the PairingClient MUST always provide a challenge response when requesting data from a `PairingServer`.
