### ISSUE TITLE
"Jump to" panel overlaps tabs (Xiaomi Mi 9T Pro)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#14633]
# Bug Report

## Problem 
Was not able to reproduce it on other devices (Tried on Xiaomi, Huawei, and Samsung)
Any help with reproduction is highly appreciated.

#### Expected behavior
no overlapping

#### Actual behavior

https://user-images.githubusercontent.com/4557972/209359542-59a7ba6a-4455-459f-a201-6ac1e1c7232f.mp4

### Reproduction

1) Open Status
2) Tap on "Jump to"

### Additional Information

- Status Version: nightly 23/12/22
- Operating System: Android 10 (MIUI 12.0.5) 
- Device: Mi 9T Pro

**Comment by Parveshdhull** [comment]
**Issue Cause:** https://github.com/facebook/react-native/issues/23693
**Current Workaround:** https://github.com/status-im/status-mobile/blob/a39e0f6fbdcf73779f4cd618b02f24691c1ea737/src/status_im2/contexts/shell/constants.cljs#L20

Will fix it, thank you for finding it.

**Comment by Parveshdhull** [comment]
Another react-native Issue, reporting same bug: https://github.com/facebook/react-native/issues/27231

**Comment by Parveshdhull** [comment]
So the issue is with devices with notch and dimensions/window

- With notch devices providing height only of the screen without a status bar included.
- While without notch devices providing height with status bar included.

So first we have to detect if the device has a notch, and if it has we need to manually add status-bar height.

But the problem is how to detect the notch.
1. [First way](https://github.com/facebook/react-native/issues/23693#issuecomment-662860819) - According to official android [guidelines](https://m2.material.io/design/platform-guidance/android-bars.html#status-bar), a simple status bar (without a notch) should have a height of 24, so we can detect the status bar height and compare it with this. But for some reason, several android devices don't follow this. For example `Real me 1`
2. [Another way](https://stackoverflow.com/a/56975058) is using the `react-native-device-info` library. But I am not sure, if even this library will be able to provide correct data because from some research of native java code on how to detect notch, they all are relying on 24 guidelines.
But I am currently not able to test this due to https://github.com/status-im/status-mobile/issues/14651

And even if this library will be able to detect notch correctly, we probably shouldn't use it. Because we had a problem with the library in the past while releasing fdroid releases (due to google dependency)
https://github.com/status-im/status-mobile/issues/11809 https://github.com/status-im/status-mobile/pull/13360

**Comment by Parveshdhull** [comment]
> Another way

Looks like `react-native-device-info` don't detect device notch. It just has a list of device names with notch and checks if devices belongs to that list.

https://github.com/react-native-device-info/react-native-device-info/blob/master/src/internal/devicesWithNotch.ts

https://github.com/react-native-device-info/react-native-device-info/blob/f0bf711ead00e50fe8b576ffa44c542012e06358/src/index.ts#L386

**Comment by Parveshdhull** [comment]
Stack-overflow question (https://stackoverflow.com/questions/52514075/how-to-detect-if-device-support-notch-display) is also not working

It also relies on status bar height to be 24. But even without notch, devices are having height much more than that.
Real me 1 - 28
Xiaomi Mi 97 Pro - 34.90 ([ref](https://github.com/status-im/status-mobile/pull/14639#issuecomment-1366549879))

**Comment by Parveshdhull** [comment]
Oh, it seems its not react-native bug, but actually its bug of android. I tried writing native code and got same result (device with notch didn't included status height in screen height)

```
Context context = getReactApplicationContext();
WindowManager windowManager = (WindowManager) getReactApplicationContext().getBaseContext().getSystemService(Context.WINDOW_SERVICE);

Display display = windowManager.getDefaultDisplay();
Point size = new Point();
display.getSize(size);
```
