### ISSUE TITLE
Low contrast in activity center colors

### ISSUE THREAD

**Issue by ibrkhalil** [status-im/status-react#14684]
Low contrast in activity center text, Text is really hard to read

![image](https://user-images.githubusercontent.com/33176106/210132951-025f744e-3c29-47b0-9c7c-1112f8df6c00.png)

**Comment by flexsurfer** [comment]
@ibrkhalil is it a bug or is it by design ?

**Comment by flexsurfer** [comment]
also status-bar color looks wrong

**Comment by ibrkhalil** [comment]
> @ibrkhalil is it a bug or is it by design ?

If it's the proposed design then we need to change it

**Comment by flexsurfer** [comment]
сс @pedro-et @xAlisher

**Comment by ilmotta** [comment]
This is a subtle bug, quite easy to fix @ibrkhalil. The text components inside the `empty-tab` component need to explicitly specify a color for dark mode, because the Activity Center is designed for dark mode only.

Here's where we should fix: https://github.com/status-im/status-mobile/blob/develop/src/status_im2/contexts/activity_center/view.cljs#L34

**Comment by smohamedjavid** [comment]
This issue is fixed in https://github.com/status-im/status-mobile/pull/14916
