### ISSUE TITLE
Missing blur effect and shadow in toast component

### ISSUE THREAD

**Issue by yqrashawn** [status-im/status-react#14702]
# Bug Report

There are missing blur effect and shadow in current implementation of toast component

Details and related discussion at https://github.com/status-im/status-mobile/pull/14618#issuecomment-1370614039

Figma: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=7337%3A236708&t=nmPQOHE4r0t3rI13-4

**Comment by VolodLytvynenko** [comment]
**Notes for QA:**
Currently, the toast is shown for the following events:
1. Message removing
2. Community joining and leaving

Tests that need to be provided:
1. Verify that the appropriate mark is shown for each toast
![image](https://user-images.githubusercontent.com/52490791/211816375-673f03f6-a0b6-4ba3-8e44-275c6905d2f0.png)
2. Verify opacity is fixed

**Comment by VolodLytvynenko** [comment]
hi @yqrashawn will this mark be implemented within the scope of this PR?
![image](https://user-images.githubusercontent.com/52490791/211816965-daff78aa-b02a-4407-97d5-aab52a6a8988.png)

**Comment by yqrashawn** [comment]
> will this mark be implemented within the scope of this PR?

ah, ok, this is already implemented in develop, but with incorrect color

**Comment by VolodLytvynenko** [comment]
> > will this mark be implemented within the scope of this PR?
> 
> ah, ok, this is already implemented in develop, but with incorrect color

I see. Thank you!
One more question. I noticed that some marks are incorrect for successful toasts. Could you also fix it in the scope of the current task?

**Actual behavior:**
Red mark is shown for the removed message
![image](https://user-images.githubusercontent.com/52490791/212040410-502bd82d-3718-46c6-a50a-0e64f534b0eb.png)


**Expected behavior:**
green mark is shown for the removed message and for 
![image](https://user-images.githubusercontent.com/52490791/212040070-6e64e04e-6e1a-43ff-ab99-48ced9c79df2.png)

**Additional info:**
The same green mark is not shown after succeeded joining the community
**Steps:**
1. Make USER_A and USER_B as mutual contacts 
2. Create a community as USER_A
3. Join the community as USER_B

**Actual result:**
![image](https://user-images.githubusercontent.com/52490791/212048556-70a42b29-c1a9-4d22-8f75-cb9ad89fc608.png)

**Expected result:**
the icon within toast should be in the form of green checkmark
![image](https://user-images.githubusercontent.com/52490791/212048669-a6fb5d60-ba72-48aa-bc56-41c0d560860c.png)

**Comment by yqrashawn** [comment]
Ah, thanks, will do @VladimrLitvinenko
