### ISSUE TITLE
useEffect should return `undefined`

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14714]
`useEffect` should return nothing or `undefined`. The current implementation of `use-effect` in `react-native` ns doesn't always do that. The following example causes it to return the value in the dependency array:

`(rn/use-effect #(reanimated/set-shared-value y @scroll-height) [@scroll-height])`

**Comment by ilmotta** [comment]
It seems the implementation in `quo.react/effect!` is much more mature and correct. https://github.com/status-im/status-mobile/blob/develop/src/quo/react.cljs#L86

The implementation of `react-native.core/use-effect` is simply wrong.

We can either:

1. Fix the existing function in `react-native.core/use-effect`.
2. Move (not copy) the `quo.react/effect!` to `react-native.core` and rename it to `use-effect`.

There are only two usages of `react-native.core/use-effect`, so it's quite easy to get it replaced. That's why I prefer option 2, and also because `quo.react/effect!` already works, no need to reinvent the wheel.

I prefer the second option, but before working on this change, @flexsurfer, could you share your opinion here?

**Comment by flexsurfer** [comment]
no strong opinion, option 2 is ok

**Comment by ilmotta** [comment]
Closing, since this issue was solved by commit bd3c724c66cc23d20aa13805176d910bdfe66a4c.
