### ISSUE TITLE
User does not appear in contact list after adding

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14770]
Issue is introduced by https://github.com/status-im/status-mobile/pull/14747
cc @cammellos 

**Steps:**

1. User A adds User B to contacts via 'Add contact'
2. See if User B will appear within the contact list of User A

**Actual result:** User B does not appear in contact list after adding. After some time, User B receives CR from User A. When User B accepts CR he appears within the contact list of User A. 

**Expected result:** user is added to contact list

https://user-images.githubusercontent.com/97245802/212117324-81eb0e8d-0256-431e-9df4-6a4123aab437.mp4

[geth.log](https://github.com/status-im/status-mobile/files/10403455/geth.log)
[Status.log](https://github.com/status-im/status-mobile/files/10403457/Status.log)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by cammellos** [comment]
@pavloburykh I believe that's expected, a contact is only a contact if it's a mutual contact, though the interface is very confusing, but it should be shown as pending, as we do in the `home` screen, let me check exactly how the designs handles this, but I believe this is the old UI (so maybe after `add contact` we should redirect the user to the home screen for now, if they are not ready)

**Comment by cammellos** [comment]
@pavloburykh 
If you see the new designs (under dev review) https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?node-id=1694%3A380170&t=tTHRAPv40EYyOPed-0 
the user will be sent to the user profile, where is clearer that `add contact` has an action, since once you input the public key, you will land on their profile, and from there you can click on "Add contact", it will after that be visibile in `home` under pending contact requests, we can keep the issue open until that gets merged if you'd like, but in general, it's the correct behavior, but the flows haven't been updated yet, what do you think?

**Comment by pavloburykh** [comment]
@cammellos thank you for explanation. I think there is no need to keep this issue to keep opened. Will be waiting for new flow to be implemented.
