### ISSUE TITLE
shadow-cljs shuts down suddently after running for some time

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#14846]
Shadow-cljs keeps on shutting down after running for some time with the error below. Trying to rerun `make run-clojure` gives the same error. Trying to run it after restarting the terminal also gives the same error. It only works again after restarting the laptop.

```
shadow-cljs - watching build :mobile
already started
{:build-id :mobile}
ExceptionInfo: already started
	shadow.cljs.devtools.server.supervisor/start-worker (supervisor.clj:27)
	...
	shadow.cljs.devtools.server.socket-repl/connection-loop (socket_repl.clj:102)
	shadow.cljs.devtools.server.socket-repl/connection-loop (socket_repl.clj:72)
	shadow.cljs.devtools.server.socket-repl/start/fn--16593/fn--16594/fn--16596 (socket_repl.clj:142)
error Command failed with exit code 1.
```

**Comment by flexsurfer** [comment]
probably process hangs, try to find it and kill/force quit

**Comment by OmarBasem** [comment]
I tried killing every process that has `nix` or `clojure` or `cljs` in its name, but still keep getting the same error. Happens every day. Only works again after restarting my machine.

@Parveshdhull @ilmotta has any of you faced this issue before or know a probable solution?

**Comment by ilmotta** [comment]
I'm sorry to hear that @OmarBasem, but unfortunately I've never faced this problem to help much. I hate when my DX is affected by anything.

But, you could try some things to pinpoint the issue.

- Since when has this problem started to happen? I'm assuming it's relatively new to happen every day for you (?). If that's the case, you can checkout older commits and see if you can identify when the problem first appeared (bisect) . But if the problem is sort of non-deterministic, this could take too long :/

- Have you recently upgraded anything on your machine that could be related?

- Another thing we can try is to upgrade shadow-cljs, which is quite old already. Assuming it could be related to shadow-cljs... There have been many fixes since our current version. Last week I upgraded shadow-cljs to a newer version in a local branch, but not new enough that I think would help fix your issue. Going on a tangent, I think shadow-cljs should be kept up-to-date, period, because Clojure is a very stable language, it's not like Webpack for instance.

- The other thing is that, even though I use NixOS for full reproducibility, I sometimes had to restart my machine even after killing all processes, but it was rare and never happened for months already. The only reason I can think of is that restarting the machine is likely cleaning up caches (in temp files, etc).

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, this error can be reproduced by running `make run-clojure` in two separate terminal sessions in the same folder. So looks like there is a separate instance of shadow-cljs running accidentally or disowned by some bug.

I don't know the working of tmux or if it will even solve your problem, but you can try this script I use `ts` for start development session and alias `tk` for killing it.

And hopefully once the tmux session is killed it will also kill all of the child processes.

https://gist.github.com/Parveshdhull/489221a01a4170c67691c7a4ed9bf54c

**Comment by flexsurfer** [comment]
yeah, definitely looks like it shutting down not by itself, but another instance is running for some reason

**Comment by ilmotta** [comment]
> Hi @OmarBasem, this error can be reproduced by running `make run-clojure` in two separate terminal sessions in the same folder. So looks like you have a separate instance of shadow-cljs running probably accidentally or disowned by some bug.
> 
> I don't know the working of tmux or if it will even solve your problem, but you can try this script I use `ts` and alias `tk` for start & kill your development session. And hopefully once the tmux session is killed it will also kill all of the child processes. https://gist.github.com/Parveshdhull/489221a01a4170c67691c7a4ed9bf54c

Nice to know! I got used to run `pkill watchman` as well if I terminate the project processes, because it's common for me to get some zombie watchman processes. This has helped me a lot so far to get a sane environment.

**Comment by OmarBasem** [comment]
Thank you @ilmotta for your input. This Problem has been happening for several months. I have upgraded my OS couple of months ago, but this problem was happening before that also. Would be great if we can upgrade `shadow-cljs`.

Thank you @Parveshdhull for sharing this script. I will try the script's commands and hopefully will fix the problem.

**Comment by OmarBasem** [comment]
So here is what worked for me in case someone comes across this in the future:

When I tried to kill all `nix` processes it seems I still missed the one specific process running `shadow-cljs`. The following command can get that specific process:

`ps aux | grep shadow-cljs `

Then kill it: `kill <PID>`

**Comment by flexsurfer** [comment]
do you know why that happened? i mean why did you have two nix processes with shadow-cljs ? do you use the same terminal for make run-clojure command ?

**Comment by OmarBasem** [comment]
Not sure why that is happening. Yes, I am using the same terminal. Worth noting that I always debug on 2 devices, not sure if that can interfere with shadow-cljs
