### ISSUE TITLE
Improve home screen chat avatar

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#14861]
# Problem

Home screen chat avatar needs to be improved

### Improvements 
1. Add identity ring for chat avatar
2. Avatar looks different from actual [designs](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System?node-id=115%3A6787&t=rh3OC99AuNYNVy6d-0). Fox ex, in design we are only using two characters as initials, but in implementation it is three

### Screenshot
<img src="https://user-images.githubusercontent.com/17097240/214050682-dd078eb5-d0ef-420f-9674-e040f9ef1dea.png" width=300/>

**Comment by ulisesmac** [comment]
Hey @Parveshdhull 

Just a question, in the screenshot you sent, the avatar component is showing three characters because the name has three words. if it has 4 words it looks as follows:

![image](https://user-images.githubusercontent.com/90291778/216161568-419ada94-4473-4b5c-8a90-4f5509392daf.png)

Then, should we only consider the first two words and ignore the rest?

Thanks!

**Comment by Parveshdhull** [comment]
> Then, should we only consider the first two words and ignore the rest?

Yes, probably we should ignore the rest. But lets confirm with the design team
cc: @pedro-et, @xAlisher

**Comment by Parveshdhull** [comment]
> But lets confirm with the design team

Yes, ignore the rest. (confirmed by design team)

**Comment by ulisesmac** [comment]
> > But lets confirm with the design team
> 
> Yes, ignore the rest. (confirmed by design team)

Ok, thanks!
