### ISSUE TITLE
Unread badge appears on AC (activity center) icon for user after he sends community access request

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14872]
**Preconditions:** User A and User B are mutual contacts. 

**Steps:** 

1. Create Require approval community by User A
2. Share community link to User B
3. Open community link by User B
4. Send access request to community by User B
5. Check if unread badge on AC icon appeared for User B after sending a request

**Actual result:** Unread badge appears on AC icon after sending community access request. There are no unread notifications in AC. Unread badge remains to be shown and does not disappear in future. 

**Expected result:**  unread indicator should not appear for user after sending community access request, as currently we don't send any notifications to sender. 

[sender_of_comm_request.zip](https://github.com/status-im/status-mobile/files/10490574/sender_of_comm_request.zip)

https://user-images.githubusercontent.com/97245802/214312291-4d485e39-9c67-48e7-b20f-f5538cce0e8e.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@pavloburykh, @qoqobolo. Thanks for reporting this, it's indeed a problem. It seems what's happening here is what @smohamedjavid explained to me:

The unread indicator comes from a count in the backend DB that doesn't care about the types of notifications. All the query cares about is that there are unread and accepted notifications. The issue as Javid pointed out, is that not all types of notifications are currently implemented on the frontend, so that's likely why you are seeing the unread indicator appear, but no notification is actually rendered in the AC.

For performance reasons and due to other complexities, the count of notifications will always be fetched separately from what's currently visible to the user. So unless we do something about the root cause of this issue, this can and will probably happen again in the future (e.g. if we implement new types of notifications).

#### Suggested solution

We can fix this by allowing the frontend to fetch only the count of notifications for specific types that are implemented to be visible in the AC. This will require a small change in `status-go`. cc @smohamedjavid We could change the status-go endpoint to accept a list of types.

**Comment by alwx** [comment]
If nobody haven't started it yet then I can do this change — was recently checking this part of the `status-go` code anyway, so updating it won't be any difficult.

**Comment by alwx** [comment]
I was recently checking the related `status-go` code, so I can do the required update pretty quickly. Feel free to tell me if you've started it already.

**Comment by ilmotta** [comment]
@alwx, you're free to fix this issue, I'm not working on it :)
