### ISSUE TITLE
Different fee is shown for same sum after editing the sum [develop]

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1489]
### Description

*Type*: Bug

*Summary*: 
Max fee to send 10 ETH is shown as "0.0008232" and later is shown as "0.0008232392" if edit the sum. If re-open screen Send transaction then again "0.0008232" is shown as max fee. It happens for non-default fee (e.g. max of min values). I would expect same fee with same precision shown for the same sum.

![changed fee to max](https://user-images.githubusercontent.com/6584810/28471498-96ab801c-6e3d-11e7-80d3-0cd8a2fc2f99.png)

![changed sum back](https://user-images.githubusercontent.com/6584810/28471630-118850ee-6e3e-11e7-9601-e704c9ad3d97.png)

#### Expected behavior
 same fee with same precision shown for the same sum.
#### Actual behavior
Max fee to send 10 ETH is shown as "0.0008232" and later is shown as "0.0008232392" if edit the sum. 

### Reproduction
video: https://drive.google.com/open?id=0Bz3t9zSg1wb7ZkIwSmVpMkVXRVU
- Open Status
- Open 1-1 chat
- send to a contact 10 Ether to get Send transaction screen with Fee
- move fee to be of a max or min value. In my case, I moved to to the most right position (Faster)
- remember the Fee value shown
- edit sum to be sent: make it "1". As a result, fee value is changed
- edit sum again and put it back to initial "10". Check the value for fee

### Additional Information
* Status version: develop 0.9.8-89-g20550b42+
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by janherich** [comment]
@annadanchenko I actually can't reproduce the scenario you described (fee value is the same but precision is different), in my case, precision stays correct, but fee value is (very different) every time I perform steps to reproduce the bug.
What's worse, the fee value is not properly reactive, as after sum is edited, i have to move slider back and forth to get new fee value rendered, otherwise fee for the original sum (before edit) is still shown. As I'm looking at the wallet/bot.js code, this will be probably quite complicated to hunt down.
Tested on simulator, iPhone SE, iOS 10.3.
