### ISSUE TITLE
Allow users to easily dismiss notifications in the Activity Center

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#14901]
# Problem

Users can't clean up notifications in the Activity Center.

### Solution

- The user should be able to swipe left to "remove" a notification from the Activity Center. In `status-go` terms, the user will `dismiss` the notification. On the backend, the notification should be dismissed and marked as read simultaneously. Dismissed notifications are automatically ignored in the client, so the UI should update accordingly without further changes to the app db.
- When the user wants to dismiss a notification that requires some action, like a contact request, the text should dynamically reflect what the negative action is. Dismissing is only for read/unread notifications and dismissing an unread notification without CTA marks them as read automatically (this is probably done in status-go already, but better check). The designs are on the way with more examples, so better check with the Design team first.

<img src="https://user-images.githubusercontent.com/46027/214668385-c7c372cb-a572-460e-90a7-c0918fc48676.png" height="600" />

https://user-images.githubusercontent.com/46027/214668585-f68fd361-6871-4d18-8e0d-81f20a373f5a.mp4

**Comment by VolodLytvynenko** [comment]
Hi @ilmotta thank you for PR and separate thanks for a such detailed description :) PR  is tested and looks good. Only one issue.
If it should work so, as in the expected result then it can be fixed in a separate PR. What do you think?

## ISSUE 1: The push notification is not disappeared if notif is marked as read or deleted

**Preconditions:**
- User_A and User_B mutual contacts 
- Both users are members of a community
- User_B uses Android (IOS pushes are not working now)

**Steps to reproduce:**
1. User_B sends the Status app to the background
2. Go to the community as User_A -> Mention User_B in the message
3. Open AC as User_B
4. Swipe right -> tap 'read'
5. Swip left -> tap 'delete'

**Actual result:**
Push notif is still shown

https://user-images.githubusercontent.com/52490791/221241408-ead3db33-8292-4c10-bf09-d3cb7b01e2f3.mp4

**Expected result:**
Push notify disappeared

**Comment by ilmotta** [comment]
>Hi @ilmotta thank you for PR and separate thanks for a such detailed description :) PR is tested and looks good. Only one issue.
>
>If it should work so, as in the expected result then it can be fixed in a separate PR. What do you think?

So that's good news @VladimrLitvinenko! It makes sense you found `Issue 1` because I haven't tested flows with push notifications. Next time I'll try to include them in my manual tests.

I agree with your suggestion, it would greatly help if we can live with this bug in `develop` while I fix it in a separate PR.

**Comment by VladimrLitvinenko** [comment]
> > Hi @ilmotta thank you for PR and separate thanks for a such detailed description :) PR is tested and looks good. Only one issue.
> > If it should work so, as in the expected result then it can be fixed in a separate PR. What do you think?
> 
> So that's good news @VladimrLitvinenko! It makes sense you found `Issue 1` because I haven't tested flows with push notifications. Next time I'll try to include them in my manual tests.
> 
> I agree with your suggestion, it would greatly help if we can live with this bug in `develop` while I fix it in a separate PR.

@ilmotta ok. Created   a follow up https://github.com/status-im/status-mobile/issues/15186. 
Thanx for your work. Could you merge this PR into develop, please?
