### ISSUE TITLE
User B is able to spam User A with contact requests In case if User A declines CR of User B

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#14947]
Issue has been initially discussed here https://github.com/status-im/status-mobile/issues/14798#issuecomment-1410980434

**Steps:**
1. User A sends CR to User B
2. User B declines User's A CR
3. See if User A is able to resend CR to User B

**Actual result:** User A is able to spam User B with contact requests by removing and re-adding User B on profile page. 

**Expected result:** User shouldn't be able to spam other User with CRs after initial decline. See John's comment here https://github.com/status-im/status-mobile/issues/14798#issuecomment-1406434296

https://user-images.githubusercontent.com/97245802/215874144-bac51972-6ce7-4322-8046-6244b2b18170.mp4

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by John-44** [comment]
@cammellos @pavloburykh @ilmotta see my reply to @MishkaRogachev here https://github.com/status-im/status-desktop/issues/9505#issuecomment-1425769497

I think the above stems from a bit of a misunderstanding of the designs (which is the fault of the desktop designs because the desktop designs are not very clear), I hope my comment on this issue clears this misunderstanding up
