### ISSUE TITLE
"New chat/Setup group chat" button is not visible on small screen devices

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15075]
# Bug Report

### Reproduction

1. Add at lease one contact
2. Open the Chat screen > Press the `+` button > `New chat`
3. Select the contact
4. Check is the button is visible at the bottom of the bottom sheet

#### Expected behavior
The `Chat with ...` / `Setup group chat` button is fully visible on any display size

#### Actual behavior

The button is fully visible only on devices with a display larger than 5"

Examples:

Galaxy Nexus 4.65"
<img width="679" alt="Screenshot 2023-02-13 at 17 05 56" src="https://user-images.githubusercontent.com/67952253/218509707-964ccc82-fa3b-415e-a747-624570b0fdab.png">

iPhone SE 4.7"

https://user-images.githubusercontent.com/67952253/218510531-2b5dcb2d-c5d0-4755-b564-51e442d9e755.MP4

### Additional Information

- Status version: rc1
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
The new chat screen also uses the same design as the [community rules screen](https://github.com/status-im/status-mobile/issues/14955#issuecomment-1420402829). I will create a fix for the position issue, but we should replace the new chat bottom sheet, with a new screen once it's implemented.

https://github.com/status-im/status-mobile/issues/14564 looks outdated, as it is relying on implementation of bottom sheet component. But as we [discussed](https://github.com/status-im/status-mobile/issues/14955#issuecomment-1420402829), we should implement a proper new screen instead of using bottom sheet for these screens.
(We can either update the original issue, or create new one, and also track these usage of those screens)

cc: @J-Son89 @alwx

**Comment by Parveshdhull** [comment]
In the community rules screen, the whole sheet was scrollable till a fixed height, but in this screen, the sheet height is fixed. We can pass a param to control the scrollibility of the sheet itself.
