### ISSUE TITLE
fix component tests

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#15107]
### Summary

follow up from https://github.com/status-im/status-mobile/pull/15071#issuecomment-1433526073

few tests are failing with error: `Cannot find module '@react-native-community/blur' from 'shadow.js.shim.module$$react_native_community$blur.js'`

Guide for using ts-jest with react-native https://kulshekhar.github.io/ts-jest/docs/guides/react-native/

Troubleshooting addresses similar error: https://github.com/kulshekhar/ts-jest/blob/main/TROUBLESHOOTING.md

**Comment by Parveshdhull** [comment]
Hi @yqrashawn, @J-Son89
Error is fixed in https://github.com/status-im/react-native-blur/pull/1, but should we keep this issue open?
Because manually adding lib folder don't look like a robust solution
- We need to keep it updated when we rebase with parent
- I think lib folder is copied from [npmjs](https://www.npmjs.com/package/@react-native-community/blur), compiled lib don't inlcude manual changes made in forked version, so might break at some time

**Comment by J-Son89** [comment]
Yes, It seems so. Seems we need a more long term approach to handle this.
In the interim perhaps this package might be able to be used here?
https://www.npmjs.com/package/patch-package

Or what are the current alternatives?

**Comment by J-Son89** [comment]
hmm, what are some of the potential (long term) solutions for this? 🤔

**Comment by yqrashawn** [comment]
The compiled lib is built from my local machine with the `bob` command

One simple solution is to use GitHub action to automatically publish patched package, for example https://github.com/marketplace/actions/npm-publish
This requires the package got patched to have proper `prepare`, `prepublish` or relevant hooks config or at least a build command
And we need a NPM token and need to manually config the repo to run actions (not by default in forked repo)

One thing I'm not sure about this is there might still be things that required to be compiled locally which requires to be triggered by `yarn install`.
`react-native-status` Node.js binding is one of this and that's why there's `yanr install` in `make test`(tried to call `node-gyp` directly with no luck)

Another one is we can just add `yarn install` to various affected make target, although this may slow things down and there's conflict when running multiple `yarn install` in parallel

**Comment by J-Son89** [comment]
@yqrashawn, curious if you have ever seen/used this package? https://www.npmjs.com/package/patch-package

**Comment by yqrashawn** [comment]
> @yqrashawn, curious if you have ever seen/used this package? https://www.npmjs.com/package/patch-package
> 
> 

The lib folder is generated by `bob build`, so we still need to compile things after we apply the patch (I believe we don't want to have `.min.js` or `.map` in patch)

What's more, this package relies on hooks as well. So we need still need `yarn install`

**Comment by yqrashawn** [comment]
```diff
diff --git a/src/status_im2/contexts/shell/bottom_tabs.cljs b/src/status_im2/contexts/shell/bottom_tabs.cljs
index fcbd24bb0..9da51459b 100644
--- a/src/status_im2/contexts/shell/bottom_tabs.cljs
+++ b/src/status_im2/contexts/shell/bottom_tabs.cljs
@@ -42,7 +42,7 @@
        (animation/load-stack @animation/selected-stack-id)
        (reanimated/set-shared-value (:pass-through? shared-values) pass-through?)
        [reanimated/view {:style animated-style}
-        (when pass-through?
+        (when true
           [blur/view (blur-overlay-params style/bottom-tabs-blur-overlay)])
         [rn/view {:style (style/bottom-tabs)}
          [bottom-tab :i/communities :communities-stack shared-values notifications-data]
```

`run-clojure` do work (no crash/error/warning, bottom tab renders, don't know if the blur view rendered correctly) with above change when there's no `node_modules/@react-native-community/blur/lib`
`shadow-cljs release mobile` no error as well

**Comment by cammellos** [comment]
looks like this has been fixed
