### ISSUE TITLE
Extra filter for generated random usernames (e.g. no "ass" in names)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#1518]
### Description

*Type*: Bug

*Summary*: User gets default random username on account creation. Sometimes this name contains words like "ass", "dumb", "idiotic" etc that can be offensive. We need to filter out such words or re-generate a name if it gets such words. Imagine it happens during live demo. 
![img_2184](https://user-images.githubusercontent.com/6584810/28743719-80d7e284-7451-11e7-9df1-7149223d8621.jpg)

#### Expected behavior
Generated username should not contain offensive words, like "ass", "dumb", "idiotic"
#### Actual behavior
Generated name can get word "ass" in it

### Reproduction

I'm not aware of the way to reproduce as it's random, so as soon as account is created - check if it contains such words

### Additional Information
* Status version: develop 0.9.9
* Operating System: 
Real device Samsung Galaxy S6, Android 6.0.1
Real device iPhone 6s, iOS 10.2.1

**Comment by goranjovic** [comment]
The name is generated using a _adjective adjective animal_ formula, so I guess _ass_ was actually supposed to mean _donkey_.  :)

What I'm going to do is simply remove the inappropriate words from the word lists so that they're not available in the first place. That involves those openly offensive words like idiotic or ass, but while we're here I'll also get rid of words that convey a negative sentiment, imply race, gender, etc. Never mind the demos, it's the first impression a user gets of the app.

**Comment by annadanchenko** [comment]
@jarradh and @goranjovic 
1. As not-native English speaker I see no issues with excluded words listed below. 
2. I’m not sure to what extent we need to filter the “animal names” as any animal might be not OK for some person. I’m fine with filter applied on animal list in this PR even if it might look a bit too strict. 

deafening
each
failing
half
lanky
married
oblong
pale
unaware
warlike
bitter
elderly
weak
weird
single
gross
tremendous
humongous
juvenile
pungent
worse
writhing

**Comment by jeluard** [comment]
Fixed in develop
