### ISSUE TITLE
Push notifications proposal placeholder (was: Integrate with status-go code related to push notification)

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-react#1521]
Implement usage of API described in [Whisper-Push-Notifications](https://github.com/status-im/status-go/wiki/Whisper-Push-Notifications) then integrate this lib  https://github.com/evollu/react-native-fcm

**Comment by oskarth** [comment]
See https://github.com/status-im/status-go/issues/206 and https://github.com/status-im/status-go/wiki/Whisper-Push-Notifications on the status-go side.

**Comment by oskarth** [comment]
Even though this is technically blocked I think we can break down some pieces of work and make progress on the status-react side by mocking some things. I'll start looking into this tomorrow.

**Comment by oskarth** [comment]
@sla-shi Quick question: is using that specific library (https://github.com/evollu/react-native-fcm) a hard requirement for some reason or just a suggestion? It seems to me that we want push notifications to be peer to peer, i.e. not use Firebase, which means they'd probably appear as local notifications mediated by the node status-go is running. If that's indeed the case, the specific library seems like an implementation detail and something like https://github.com/zo0r/react-native-push-notification might work fine too, depending on what is easiest and leanest to get up and running.

**Comment by oskarth** [comment]
Most of the hard work for this piece of work lies on the server-side, as far as I can tell. Since this is a priority for devcon there's no reason we shouldn't make progress on the client-side, concurrently. These are things we have to do regardless of the implementation details with status-go, Whisper, etc. There will be more work later but this is a good start. Starting these sooner or later will also allow us to uncover hidden dependencies quicker. Some things might also be platform specific.

I see three pieces of work, two of which we can start already:

1. Subscribe logic. This one seems to have a relatively large surface area. Let’s wait with this until it is clear how we want to deal with topics, encryption, etc.

2. The specific push notification. We can mock whatever we’ll get from status-go and subscribe to a fake event that sends a push notification. This requires some changes in permissions for the app itself, etc. For the time being, we can naively assume the subscription takes the form of something like: `[:push-notification {:chat-id “0xdeadbeef” :preview “preview”}]`

3. Deep linking. Clicking on a push notification should take us to the specific chat screen. IIRC this requires mapping screens to custom URLs.

**Comment by oskarth** [comment]
Work in progress document here: https://docs.google.com/document/d/1OgjnY8ps8lVA4dIohwkfGK9HVt0nZxEWbuNdb7BX5-o/edit#

**Comment by sla-shi** [comment]
@oskarth re: using specific libraries - I captured the initial requirement from discussions in slack channels.
This can be re-visited in the document that you've shared.

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/1599

**Comment by oskarth** [comment]
@sla-shi I think this issue can be deleted since it is currently ill-defined / captured in other issues/docs
