### ISSUE TITLE
Update universal links to reflect the changes in URL structure

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#15325]
### Description

URL structure/payload will change according to these changes https://github.com/status-im/specs/pull/159 

We should change our handling to make sure that the links are handled correctly.
Please keep as much logic in status-go as possible, in order to reuse code between mobile and desktop.

You can ask @felicio for details about the url structure.

cc @felicio @iurimatias 

https://www.figma.com/file/q3kZPl7OpbB7btFK7HG0Mr/Sharing-for-Mobile?type=design&node-id=690-280345&mode=design&t=tuTTqA3k1dD8yqMw-0

**Comment by felicio** [comment]
As of now, the description of this issue is quite vague. Asked for edit/split at https://github.com/vacp2p/rfc/pull/600#discussion_r1213057816.

For reference, and scope, the following is how Desktop team is splitting the work

- https://github.com/status-im/status-desktop/issues/10851
- https://github.com/status-im/status-desktop/issues/10852
- https://github.com/status-im/status-desktop/issues/10892
- https://github.com/status-im/status-desktop/issues/10907
- https://github.com/status-im/status-desktop/issues/10585
- https://github.com/status-im/status-desktop/issues/7957
- https://github.com/status-im/status-desktop/issues/9549
- https://github.com/status-im/status-desktop/issues/8027
- https://github.com/status-im/status-desktop/issues/12245

**Comment by yqrashawn** [comment]
- handle open new link https://github.com/status-im/status-mobile/issues/17431
- universal link in safari auto-trigger app https://github.com/status-im/status-mobile/issues/17550
- loading screen when linked view not loaded https://github.com/status-im/status-mobile/issues/17551
- share community with new link https://github.com/status-im/status-mobile/issues/17585
- share community channel https://github.com/status-im/status-mobile/issues/16318

**Comment by yqrashawn** [comment]
All sub issues are done
