### ISSUE TITLE
Shadow for separating profile cards within profile list does not correspond to the design

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#15434]
Followup of https://github.com/status-im/status-mobile/pull/15376 cc @Parveshdhull 

**Steps:** 

1. Open login page
2. Go to profiles list
3. See if Shadow for separating profile cards corresponds to the designs 

**Expected result:**

https://www.figma.com/file/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=4357-629631&t=145Wfu0uclpKGUkI-0

<img width="259" alt="Onboarding for Mobile – Figma 2023-03-20 13-44-12" src="https://user-images.githubusercontent.com/97245802/226329851-4006f197-86c4-4161-9780-eb39852a6723.png">

**Actual result:** 

**Samsung Galaxy A52. Android 12:**

![photo_2023-03-20 13 53 58](https://user-images.githubusercontent.com/97245802/226331840-8ebce306-6971-434a-8693-c0aaffe7e9f2.jpeg)

**iPhone X, IOS 14.1:**

![photo_2023-03-22 10 14 08](https://user-images.githubusercontent.com/97245802/226840134-78da5b0c-6a6c-482c-85fb-b695a47cf991.jpeg)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by vkjr** [comment]
After a few days of experimenting, I couldn't implement a good-looking shadow. Default react-native shadow gives very strange effect on the half-transparent views. 
Just as an idea for the future, maybe using `LinearGradient`+`HoleView` can make it, but my experiments were unsuccessful. Putting this aside for now due to the low priority and impact of the issue.
