### ISSUE TITLE
QR code is able to be generated without a password typing

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15478]
#### Steps to reproduce:
1. Open app -> Syncing -> tap 'Sync a new device' -> tap 'Setup Syncing'
2. Don't enter any password into 'enter your password' field
3. Tap 'Generate Scan Sync Code' button
#### Actual result:
QR code is generated

https://user-images.githubusercontent.com/52490791/227534893-dfeaf9c6-f221-422e-abe1-d403383be9ee.mp4

#### Expected result:
how it works on the latest nightly:
Validation 'Try your luck again!' is shown 
![image](https://user-images.githubusercontent.com/52490791/227534796-5fed2767-87c8-4527-b7d4-420662134938.png)

CC: @qfrank

**Comment by Samyoul** [comment]
Will be addressed with implementation of https://github.com/status-im/status-go/issues/3303

**Comment by qfrank** [comment]
> Will be addressed with implementation of [status-im/status-go#3303](https://github.com/status-im/status-go/issues/3303)

I'm afraid it won't be addressed with implementation of https://github.com/status-im/status-go/issues/3303 (or you have better solution?🙂), i think we'd better add some validation for input password on the frondend side, some improvements we could do to improve user xp:
- length of input password should >= 6 chars
- when input password not valid, the button `Generate Scan Sync Code` should be disabled.. 
- add an extra input field to confirm input password

 this [PR](https://github.com/status-im/status-go/pull/3350) already added validation on local pair config, it also check if the passed password is empty. because passed password is encrypted with sha3(empty value can be also encrypted with sha3, corresponding sha3 value is 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470), just check password if is empty is not enough, it won't detect if original plaintext password is empty. Also i think it's not a good idea to add checks to see if password value is 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 or some else sha3 value in the backend.
 
 @Samyoul

**Comment by pavloburykh** [comment]
> I'm afraid it won't be addressed with implementation of [status-im/status-go#3303](https://github.com/status-im/status-go/issues/3303) (or you have better solution?🙂), i think we'd better add some validation for input password on the frondend side, some improvements we could do to improve user xp:
> 
> * length of input password should >= 6 chars
> * when input password not valid, the button `Generate Scan Sync Code` should be disabled..
> * add an extra input field to confirm input password

@qfrank thanx for you comment. JFYI, current QR generation screens is just temporary implementation. New screens will look like this https://www.figma.com/file/V6nlpAWIf2e1XU8RJ9yQPe/Syncing-for-Mobile?node-id=675-177939&t=UZ9g6k4ZuNiPNEQZ-0

**Comment by qfrank** [comment]
> > Will be addressed with implementation of [status-im/status-go#3303](https://github.com/status-im/status-go/issues/3303)
> 
> I'm afraid it won't be addressed with implementation of [status-im/status-go#3303](https://github.com/status-im/status-go/issues/3303) (or you have better solution?🙂), i think we'd better add some validation for input password on the frondend side, some improvements we could do to improve user xp:
> 
> * length of input password should >= 6 chars
> * when input password not valid, the button `Generate Scan Sync Code` should be disabled..
> * add an extra input field to confirm input password
> 
> this [PR](https://github.com/status-im/status-go/pull/3350) already added validation on local pair config, it also check if the passed password is empty. because passed password is encrypted with sha3(empty value can be also encrypted with sha3, corresponding sha3 value is 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470), just check password if is empty is not enough, it won't detect if original plaintext password is empty. Also i think it's not a good idea to add checks to see if password value is 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 or some else sha3 value in the backend.
> 
> @Samyoul

oh, i missed something for status-go, we should check password if valid for DecryptKey. 🤦‍♂️

**Comment by Samyoul** [comment]
> Also i think it's not a good idea to add checks to see if password value is 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 or some else sha3 value in the backend.

@qfrank I agree with you, inspecting for specific values of a password that are not empty or nil is problematic. It could lead us into checking for other things
