### ISSUE TITLE
The 'play' button does not respond if chat is reopened and audio 'play' button is tapped in the list of pinned 

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15536]
Follow up for https://github.com/status-im/status-mobile/issues/13530

#### Steps to reproduce:
1. Record the audio -> send it
2. Pin current audio
3. Open list of pinned
4. Close list of pinned
5. Reopen the chat
6. Open list of pinned one more time
7. Tap 'play' button

#### Actual result:
'Play' button does not respond

https://user-images.githubusercontent.com/52490791/228841039-e69133e6-6e59-4b6f-91a2-3d5153b0a69e.mp4

#### Expected result:
'Play' button responds

#### Devices: 
- Android studio emulator: Pixel 3 XL, Android 10
- Real iPhone: iPhone pro max 11, os: 16

**Comment by briansztamfater** [comment]
@ibrkhalil I don't know if you made progress on this, but as we are redesigning the whole component in #13530 we should fix this issue there, I don't think is worth fixing issues in an old component

**Comment by ibrkhalil** [comment]
> @ibrkhalil I don't know if you made progress on this, but as we are redesigning the whole component in #13530 we should fix this issue there, I don't think is worth fixing issues in an old component

Thanks for letting my know Brian!
I was working on it the whole day today .. But if it's going to be replaced then I don't think I should continue
Finding:
`ChatPinnedMessaged `call on status-go doesn't return the audio or the image information

**Comment by ibrkhalil** [comment]
Thanks for letting my know Brian!
I was working on it the whole day today .. But if it's going to be replaced then I don't think I should continue
Finding:
`ChatPinnedMessaged` call on status-go doesn't return the audio or the image information

**Comment by briansztamfater** [comment]
@ibrkhalil @VladimrLitvinenko confirming that will be fixed in #13530, audio uri is dynamically built with mediaserver port, audio path and message id so as far as I know that is not needed to be returned from status-go. I am assigning this issue myself and will be sure that this is tested in #15594.

**Comment by briansztamfater** [comment]
@qoqobolo just to confirm, can we close this one? It should have been fixed in #15594 cc @VladimrLitvinenko

**Comment by qoqobolo** [comment]
> @ qoqobolo just to confirm, can we close this one? It should have been fixed in https://github.com/status-im/status-mobile/pull/15594 cc @ VladimrLitvinenko

@briansztamfater yes this issue is fixed, I'll close it. Thank you!

However, we rechecked another bug from https://github.com/status-im/status-mobile/pull/15594 - with the frozen play button after background - on several Android devices on Nightly just in case, and it turned out that it is still reproducible, but not always (that's why the fix in the PR worked fine for me).

Here is an example of when it reproduces:

https://user-images.githubusercontent.com/67952253/236413553-43d87383-604c-41c0-9da8-a0542f27334e.mp4

And here is when it works fine:

https://user-images.githubusercontent.com/67952253/236413603-cb755520-c928-435c-a741-bf92e6bb0b74.mp4

The new issue is logged here so we don't lose it: https://github.com/status-im/status-mobile/issues/15819.
It is not a critical one, but it would be nice if someone looked at it if possible.
