### ISSUE TITLE
Status bar font turns white after background or opening a chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#15590]
# Bug Report

## Problem 

If the device is in light mode, then the status bar becomes invisible on the home screens after the background or opening a chat.
Relogin fixes the issue.

**Steps:**
1. Open Status
2. Send the app to the background 

https://user-images.githubusercontent.com/67952253/230332752-1275d923-d618-47fd-879c-f6ecdf1ae9d9.mp4

**or**
3. Open a chat/community

https://user-images.githubusercontent.com/67952253/230333430-c1baca3b-947d-447e-aae1-a9e33d32c240.mp4

### Additional Information

- Status version: RC 1.22
- Operating System: Android, iOS

**Comment by Parveshdhull** [comment]
Hi @qoqobolo @churik,
The issue should be fixed in latest release build.

### Testing
The issue should be fixed for both light and dark app themes, but as mentioned in https://github.com/status-im/status-mobile/pull/15598, the theme needs to be provided at the time of root initialization. So if the theme changes after login, then the behavior will be the same, until the account relogin.
