### ISSUE TITLE
Remove identicoin and replace it with user picture if available or the initials of a user

### ISSUE THREAD

**Issue by churik** [status-im/status-react#15714]
# Bug Report

## Problem 
Currently, we're still using the identicoin in a lot of places, which should be replaced with the initials of the user when the profile photo is not set and otherwise with the user picture.
Places, where the identicoin is still used:
- activity centre
- contact list
- profiles of users (still old UI is used, not sure worth fixing here)
- own profile  (still old UI is used, not sure worth fixing here)

#### Expected behavior

![IMAGE 2023-04-21 14:48:54](https://user-images.githubusercontent.com/4557972/233640101-662578ad-c5b0-4bb5-8eda-ae6a7c2c8c56.jpg)

#### Actual behavior

Contact list:
![IMAGE 2023-04-21 14:49:27](https://user-images.githubusercontent.com/4557972/233640219-b4cd35f3-8c27-47a9-81bf-5c4e0ad5d36b.jpg)

Activity center:
![IMAGE 2023-04-21 14:50:00](https://user-images.githubusercontent.com/4557972/233640332-0035781d-e915-47d3-9908-3386c914c50f.jpg)

Another user profile:
![IMAGE 2023-04-21 14:50:21](https://user-images.githubusercontent.com/4557972/233640377-9c7b70bc-5b25-4205-bd90-276d997e1d2c.jpg)

Own profile:

![IMAGE 2023-04-21 14:52:26](https://user-images.githubusercontent.com/4557972/233640767-6f2c9f50-d8ad-4352-abbb-523f60286fa3.jpg)

- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
Hi @alwx, @churik this issue extends a bit further in that the current method we use to generate the user initials is currently done in the quo2/user avatar component. However @cammellos and I realised it would be better to generate these initials in Status Go because otherwise we have to parse the url to check whether the user has a valid image and if not then we generate the users initials (more details in the linked issue below) , creating these initials in Status Go is much cleaner and then makes the use of the user avatar much simpler.

Status Mobile issue:
https://github.com/status-im/status-mobile/issues/15751

Status Go issue: 
https://github.com/status-im/status-go/issues/3429 - @jo-mut is currently working on this.
