### ISSUE TITLE
Incorrect `keyboard-height` on Android

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15758]
Since upgrading to react-native v 0.67.5 in [that commit](https://github.com/status-im/status-mobile/pull/15486) I have noticed the value of `window-height` on my Android device has changed. The `window-height` value used to include the `status-bar-height`. After that commit, it does not include the `status-bar-height`. This issue happens on my Android device, but works fine on Emulator. This change in `window-height` causes some UI problems, for example in the maximized composer. 

#### Expected Result
(from Emulator Pixel 3 API 30, Android v 11)
<img width="424" alt="Screenshot 2023-04-26 at 16 01 17" src="https://user-images.githubusercontent.com/29354102/234568813-030ab043-3509-4996-b0b9-af79901e40e7.png">

#### Actual Result
(from Samsung galaxy Note 10 Lite, Android v 11)
![Screenshot_20230426-160035_Status Debug](https://user-images.githubusercontent.com/29354102/234568769-66291a79-6033-4333-b410-33123f322110.jpg)

**Comment by OmarBasem** [comment]
Hi @Parveshdhull, any updates on that issue?

**Comment by Parveshdhull** [comment]
Hi @OmarBasem, I am currently on off time, So didn't got much time to look into the issue.

I can work on this later. Also Please feel free to reassign if you want to work on it.

**Comment by Parveshdhull** [comment]
hi @OmarBasem, I checked 3 devices and window-height is same, before and after upgrade

| Type                           | Device with Notch | Device without Notch | Emulator Without Notch |
|--------------------------------|-------------------|----------------------|------------------------|
| Shell (Real device height)                      |               765 |                  672 |                781.090 |
| Before Commit Window-height    |               732 |                  672 |                781.909 |
| After Commit Window-height     |               732 |                  672 |                781.909 |
| Status Bar before commit       |             32.33 |                   28 |                  49.09 |
| Status Bar height after commit |             32.33 |                   28 |                  49.09 |

So issue with composer height is not happening due to that. Probably there are some new changes after rn upgrade which is causing that issue.

Also, just to be sure, are you using same device as before for checking, because as you can see devices with notch doesn't include status bar height by default, and this is known issue. More information on that:
https://github.com/status-im/status-mobile/issues/14633 https://github.com/status-im/status-mobile/pull/14639#issuecomment-1366992260 https://github.com/status-im/status-mobile/issues/15164

**Comment by OmarBasem** [comment]
Thanks a lot @Parveshdhull for checking this issue. 
Yes, I am using same device as before.

> Probably there are some new changes after rn upgrade which is causing that issue.

I am going to double-check if the RN upgrade is the first commit where this issue is happening. And whether the commit right before it is not cauing the issue.

**Comment by OmarBasem** [comment]
@Parveshdhull it is indeed caused from the RN upgrade. 

Here is how it looks the [commit](https://github.com/status-im/status-mobile/tree/88b9aa14e8df63a7e83f55935d674157a5a61fa4) right before the upgrade:

![Screenshot_20230508-140921_Status Debug](https://user-images.githubusercontent.com/29354102/236801669-9db7682f-e2b8-4858-a358-95543571dc96.jpg)

And here is how it looks the [commit](https://github.com/status-im/status-mobile/tree/3bd4038089ebc4094728fd0fef7a5d5830653553) that upgrades RN ([PR](https://github.com/status-im/status-mobile/pull/15486/files)):
![Screenshot_20230508-142441_Status Debug](https://user-images.githubusercontent.com/29354102/236801768-66ef59ff-2110-497b-acf3-1376a6a29760.jpg)

I have also noticed one of the QAs having this issue on their device. You can see in the video in that [comment](https://github.com/status-im/status-mobile/pull/15818#issuecomment-1538043950) at second 00:12 when the composer is maximized that it doesn't look right.

**Comment by Parveshdhull** [comment]
`window-height` is still [same](https://github.com/status-im/status-mobile/issues/15758#issuecomment-1536075612), maybe something else changed during upgrade?

**Comment by OmarBasem** [comment]
Oh.. it seems it's happening on a few devices only.

**Comment by OmarBasem** [comment]
@Parveshdhull This issue is reproducible on Samsung S23 [Android 13] (which is the latest Samsung line-up). So I think this issue needs to be fixed. I will try to investigate more what's wrong.

I see there are issues in `react-native` repo regarding this problem: https://github.com/facebook/react-native/issues/23693#issuecomment-475130896

**Comment by OmarBasem** [comment]
@VladimrLitvinenko can you tell me which Android device were you using in that video: https://github.com/status-im/status-mobile/pull/15818#issuecomment-1538043950

**Comment by VolodLytvynenko** [comment]
> @VladimrLitvinenko can you tell me which Android device were you using in that video: [#15818 (comment)](https://github.com/status-im/status-mobile/pull/15818#issuecomment-1538043950)

@OmarBasem Real device: Huawei p20 light, android 9

**Comment by Parveshdhull** [comment]
> I see there are issues in react-native repo regarding this problem: https://github.com/facebook/react-native/issues/23693#issuecomment-475130896

Research notes on this issue:
https://github.com/status-im/status-mobile/issues/14633
https://github.com/status-im/status-mobile/pull/14639#issuecomment-1366992260
https://github.com/status-im/status-mobile/issues/15164

**Comment by OmarBasem** [comment]
> I checked 3 devices and window-height is same, before and after upgrade

@Parveshdhull can you let me know the devices you checked on

**Comment by OmarBasem** [comment]
So the problem is actually from the keyboard height. 

Keyboard height before upgrade: `267`
Keyboard-height after upgrade: `294`

The difference between these 2 values is `27` which is exactly the status-bar height on that device, which made me think it's an issue with window-height and status bar height. Not sure if it is somehow related to the status bar height or just a coincidence.

**Comment by OmarBasem** [comment]
So a workaround for this is to subtract the keyboard's event `screenY` position from the `window-height`. This should give the right keyboard height.
