### ISSUE TITLE
App not refreshing on code changes

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#15862]
Sometimes when starting the app freshly (new window, `make run-clojure`, `make run-metro`, etc) (iOS or Android), and doing some code changes and saving, nothing happens. The app does not refresh.

No errors are shown in `metro` or `shadow-cljs`.

**Comment by flexsurfer** [comment]
but do you see "Compiling.." in shadows-cljs logs ?

**Comment by Parveshdhull** [comment]
Did you restarted app?

**Comment by Parveshdhull** [comment]
> Did you restarted app?

Means, is your debug app connected to your current metro instance or using old cache or somethign. I have seen similar bug, when emulator already has app running and I create new instances for `make run-metro` and `make run-clojure`
https://github.com/status-im/status-mobile/assets/17097240/6ec676de-064c-484e-94e1-b73b337273c7

**Comment by flexsurfer** [comment]
oh right that happened to me as well, on Android, for some reason, it silently uses some cached version, that's annoying, so you need to make sure when you run the app on Android emulator it downloads code from metro, you should see it in metro logs

**Comment by OmarBasem** [comment]
> but do you see "Compiling.." in shadows-cljs logs ?

@flexsurfer Yes, shadow-cljs compiles

**Comment by OmarBasem** [comment]
> Did you restarted app?

@Parveshdhull this happens to me on a fresh start. I then have to shut everything, and restart again.. :/

**Comment by flexsurfer** [comment]
still make sure it downloads code from metro after start  `BUNDLE  ./index.js `

**Comment by ilmotta** [comment]
I can reproduce this problem many times in a day. The loading spinner stays there forever and the code doesn't reload entirely. Then I need to re-save the file with a dummy whitespace or anything and then when I request shadow-cljs to reload again it picks up everything. It's a ceremony I got used to, but it sucks, and it existed since the first time I disabled auto hot-reload from shadow.

I once tried to investigate and solve the problem, but gave up because I thought it was just me. I don't use hot reload in the sense of reloading on every file save, so that's why I thought this issue was just mine and never bothered reporting. I have the `SHADOW_AUTOBUILD_ENABLED` env var set to `false`.

**Comment by OmarBasem** [comment]
@ilmotta I would like to know if you use multiple devices when developing. I use 2 devices, while most other people use 1 device and do not face many of those DX issues i am facing

**Comment by ilmotta** [comment]
@OmarBasem, I once worked a month in or so in status-mobile with two devices on the same machine and I stopped because it was a bit too resource heavy and I was constantly confused and usually ran adb commands pointing to the wrong device. I could go back to this dev flow, but since then I use a smartphone as the second device. Never more than 2.

> I use 2 devices, while most other people use 1 device and do not face many of those DX issues i am facing

That's probably it, you and me are doing some things that other contributors aren't, so we pay the DX price, that's how it is. If we want to solve some of the problems we're reporting, I guess we'll need to fix them ourselves or adapt our flows somehow (which sucks).

One of the best things we can do when raising these issues is report exactly how to reproduce, whenever possible. If others can't reproduce and they don't have the problem, then... we end up where we are.

My comment is not very optimistic, sorry about that. Don't listen to me ;)

**Comment by ilmotta** [comment]
Btw @OmarBasem, I'm interested in going back to this problem *eventually*, when I set my mind to it. I once spent hours drilling down into a lot of stuff, even the shadow-cljs internals. But it was way back when I wasn't used to the mobile codebase, maybe now I'd be able to fix this issue.

**Comment by OmarBasem** [comment]
@ilmotta I was looking again into the shadow-cljs sync problems (which can also be the root cauase of those `metro` issues), and I found that [probable fix on SO](https://stackoverflow.com/questions/59416137/often-seeing-repl-command-timed-out-in-cider-with-shadow-cljs-and-react-native). Do you know if it is possible to add that fix to our project?

> its a bug in react-native in that it doesn't disconnect websockets when reloading the app so shadow-cljs thinks the "old" app is still running and tries talking to it (but it never replies) I opened an issue on the RN repo but it was closed due do inactivity for a year or so. nobody cared I guess.

**Comment by flexsurfer** [comment]
> Do you know if it is possible to add that fix to our project?

yes possible
