### ISSUE TITLE
Allow user to edit link previews after messages are sent

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#15906]
# Feature

Depends on https://github.com/status-im/status-mobile/pull/15891

Users should be able to edit link previews after sending messages. [Figma > Composer for Mobile](https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=8370-500969&t=QlvKXMgLhyP6j9iK-0)

The previews displayed in the composer and in the chat after updating the message should reflect the current (edited) text, not the original one.

## Implementation

The majority of the implementation will be in status-go, if not everything.

**Comment by igor-sirotin** [comment]
We discussed with @benjthayer and @jrainville that we might want to use functionality to "post-add the previews" to the sent message.

Currently when composing a message user could paste a link and very quickly send the message, before the preview has been fetched. We could fix this problem by blocking the sending, but this is a bad UX. 

It would be nice if we could send the message immediately and when the previews are fetched, push them to the message. Direct "edit message" functionality is not good to use here, because it will contain the whole message, but maybe we could have a **separate message type for updating link previews**?

**Comment by ilmotta** [comment]
> We discussed with @benjthayer and @jrainville that we might want to use functionality to "post-add the previews" to the sent message.
> 
> Currently when composing a message user could paste a link and very quickly send the message, before the preview has been fetched. We could fix this problem by blocking the sending, but this is a bad UX.
> 
> It would be nice if we could send the message immediately and when the previews are fetched, push them to the message. Direct "edit message" functionality is not good to use here, because it will contain the whole message, but maybe we could have a **separate message type for updating link previews**?

@igor-sirotin, while I agree this can be an interesting idea to explore, I can't help but think we should keep the overall feature as simple as we can and only solve this problem much later after the MVP, if ever.

WhatsApp and Signal in mobile devices do what we currently do i.e. attempt to unfurl the URL right before the message is sent, and if the URL couldn't be unfurled in time, both sender and receiver won't see previews. Of course we should be aware of differences, for instance, WhatsApp and Signal don't allow users to edit messages.

If we consider that WhatsApp & Signal users are happy with the way they behave, I think we'll be fine for a long time with the current behavior/implementation. But having said that, it's obviously up to other people to make such feature decisions.
