### ISSUE TITLE
The avatar and [+] button for creating a community/chat is not visible for synced user 

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#15969]
caused by merging https://github.com/status-im/status-mobile/pull/15860

### Steps to reproduce:
1. User_A generates a sync QR 
2. User_B scans the QR to be synced
3. User_B checks elements after onboarding

### Actual result:
- [+] button is not visible for 1-1 chat and community creation
- The Profile avatar is not visible 

https://github.com/status-im/status-mobile/assets/52490791/0b68e8a3-c0e2-4792-8cd5-65a183080881

![image](https://github.com/status-im/status-mobile/assets/52490791/c9fe3849-fbc0-40ab-a531-72ffd20b2b66)
![image](https://github.com/status-im/status-mobile/assets/52490791/d2fd02c6-86ea-4fb3-8786-3d0bc80c4f63)

### Expected result:
- [+] button is visible for 1-1 chat and community creation
- The Profile avatar is visible 
![image](https://github.com/status-im/status-mobile/assets/52490791/a063dc94-4e2a-4b81-bb6b-0ab27b239871)

CC: @jo-mut

**Comment by churik** [comment]
Important note: 
if sync is made Mobile > Mobile: the buttons are visible after re-login
if sync is made Desktop > Mobile: **buttons are not visible at all**

https://github.com/status-im/status-mobile/assets/4557972/a1b52550-5361-4f28-a0a0-8b721ec5df9b

**Comment by qoqobolo** [comment]
And since profile colors probably cause the issue, it might be worth mentioning that some profile colors differ between desktop and mobile.
Here is an example.
The `di_test` user was created (and recovered later) on desktop and synced on mobile and you can see the difference between these blue colors.

![photo_2023-05-25_11-52-47](https://github.com/status-im/status-mobile/assets/67952253/c68fc59b-c3fd-417b-85fe-0560346613ae)
