### ISSUE TITLE
Messaging - In Chat - Communities Links (UI) not working and not updated accordingly to the community changes

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16098]
In a chat when a Communities link is shared, the link itself is clickable and works.. however the UI is not working

Some issues are:
- not updating when a community info is updated
- if link is shared by copy and paste then the preview should show (but currently does not)

See the example for "To cancel request" community
![IMG_32DD96785060-1](https://github.com/status-im/status-mobile/assets/22799766/6d5ce99a-0351-4153-83ff-40730257def3)

**Comment by J-Son89** [comment]
cc @churik

**Comment by J-Son89** [comment]
As per @cammellos, about this feature request:
currently user will not be listening to updates, only if they join the community.
This is done because you don't want a user to send you a link, and immediately start listening for updates to that community, as that's costly.

So this feature is probably not ideal to have

**Comment by churik** [comment]
The problem is that it can be (and it is) an issue for communities with permissions - they should be updated accordingly, as otherwise, user can join the community when they do not have permission to do that.

It is working on the desktop side, so likely it is issue to reopen when we're prioritizing links in chat view and token gated communities.

Added a label to easily find it for re-opening.

**Comment by churik** [comment]
The another thing to mention with token-gated community is that if permissions have been changed and the user do not match them anymore:
- user should be kicked from community automatically
- community page should be updated eveywere, including community links
