### ISSUE TITLE
[Android] The top of the screen flickers when closing a community with a community banner 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16138]
# Bug Report

## Problem 

Pay attention to the top area of the screen. It is visible both in dark and light modes. 

https://github.com/status-im/status-mobile/assets/67952253/dabc0c6b-b825-4791-9bfb-5ff923f1c093

### Reproduction

1. Create a community on desktop, add a banner image
2. Join the community on mobile
3. Open the community > close the community

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by briansztamfater** [comment]
I think this also happens when closing a chat. See video:

https://github.com/status-im/status-mobile/assets/18485527/60ec2270-b232-4f7e-bf82-ee91d7817ba3

Relevant part in 0.25x because it may be difficult to see at first glance (it is more noticeable in device than in the actual recording):

https://github.com/status-im/status-mobile/assets/18485527/59653da7-139d-4149-bcba-bc66e54c7734

**Comment by cammellos** [comment]
@alwx are you still looking into this?

**Comment by alwx** [comment]
Just played with it on both Android and iOS, got a feeling that the issue might've been gone after I merged the recent changes to the top bar. @qoqobolo can you please check and verify?

**Comment by qoqobolo** [comment]
@alwx yes, you're right, the issue is gone. 
Thank you
