### ISSUE TITLE
Add new system messages in chat history when accepting a contact request

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16254]
# Bug Report

## UPDATE

For now, we only should show the `[Alicia] is now a contact` message both for sender and receiver of CR after the CR approval. 

Design: https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=1694%3A380446&t=53g6tG6gOO7nUzqh-1

<img width="366" alt="Screenshot 2023-06-13 at 12 56 52" src="https://github.com/status-im/status-mobile/assets/67952253/acaf9d62-7604-41d5-b410-d336d44e1339">

Additional requirement:

> Contact request card and "You sent a contact request to..." message should not appear in the conversation, only in notification center, so we can hide/delete from here

---
Three scenarios where new systems messages are needed:

#### 1. Alice sends CR to Bob for the first time

1. Bob receives a notification in AC
2. 1-1 chat is NOT opened for both users
3. Bob accepts CR
4. 1-1 chat is created for Bob and Alice
5. Alice can see her message sent with CR and the system message “Bob now is a contact”
6. Bob can see Alice’s message received with CR and 

#### 2. Bob removes Alice from contacts 

1. The input field is disabled in the chat for Bob and Alice
2. Alice can see “Add Bob as a contact to send message” in place of the input field (this will be a clickable button) and the system message “Bob removed you as a contact”
3. Bob can see “Add Alice as a contact to send message” in place of the input field (this will be a clickable button) and the system message “Alice removed as a contact”

#### 3. Alice sends another CR to Bob

1. Bob receives a notification in AC
2. 1-1 chat is opened for both users BEFORE the CR is accepted
3. Bob can open chat and accept/reject CR inside the chat (there will be corresponding buttons)
4. Bob can see the system message “Alice sent you a contact request” and the message received with CR from Alice below it
5. Alice can see the system message “You sent a contact request to Bob” and the message sent with CR to Bob below it

### Designs

Sender side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A515046&t=867Xk6LqWfKYzLK9-1

Receiver side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A600326&t=867Xk6LqWfKYzLK9-1

**Comment by cammellos** [comment]
This is a feature added by desktop, they are system messages indicating your status.

There are some designs for system messages here, but I don't see anything for contact requests https://www.figma.com/file/PPWkgOYlZZDxZv5SDGsZVV/Posts-%26-Attachments-for-Mobile?type=design&node-id=6538-427715&t=jmOhurtEKZ6AWcnN-4 

@pedro-et @John-44 are there any designs ready to be implemented? otherwise we can hide those for the time being


thanks

**Comment by flexsurfer** [comment]
SENDER:
1)
```clojure
:text "@0x040d1b8935ef46b7f5befeeb0ef067a17a4c04a245571cb8bccd9f3f3d028c4a345a5e7d32c444e87eb51edea3916ee2d5a07e16cacdfe233fe1cf862f71298eb5 added you as a contact"
:content-type 15
```
2) 
```clojure
:text "You sent a contact request to @0x040d1b8935ef46b7f5befeeb0ef067a17a4c04a245571cb8bccd9f3f3d028c4a345a5e7d32c444e87eb51edea3916ee2d5a07e16cacdfe233fe1cf862f71298eb5
:content-type 15
```
3)
```clojure
:text "Please add me to your contacts"
:content-type 11
```
RECEIVER:
1)
```clojure
:text" You added @0x04c2881b4d283d8eedc08373e8bc5ec4022205ae4d133cc05c51909988574e858a34ece63996c79896f5db44bb1f688af83d582c893239bf81994ab623996f1d1d as a contact"
:content-type 15
```
2)
```clojure
:text "@0x04c2881b4d283d8eedc08373e8bc5ec4022205ae4d133cc05c51909988574e858a34ece63996c79896f5db44bb1f688af83d582c893239bf81994ab623996f1d1d added you as a contact"
:content-type 15
:deleted? true
```
3)
```clojure
:text "@0x04c2881b4d283d8eedc08373e8bc5ec4022205ae4d133cc05c51909988574e858a34ece63996c79896f5db44bb1f688af83d582c893239bf81994ab623996f1d1d sent you a contact request"
:content-type 15
:deleted? true
```
4)
```clojure
:text "Please add me to your contacts"
:content-type 11
```


SYSTEM_MESSAGE_MUTUAL_STATE_UPDATE = 15; is not implemented on mobile

**Comment by flexsurfer** [comment]
lots of questions

**Comment by flexsurfer** [comment]
@cammellos any thoughts on how this should be implemented? i would say we should just show these messages, but for some reason for the receiver they are deleted, and the description in this task has only one message instead of two in the current implementation, should we refactor status-go or ? cc @MishkaRogachev

**Comment by flexsurfer** [comment]
status-go: https://github.com/status-im/status-go/pull/3519
desktop: https://github.com/status-im/status-desktop/issues/10395

**Comment by cammellos** [comment]
@MishkaRogachev might know why they are deleted, it's not a behavior I would expect

**Comment by MishkaRogachev** [comment]
Hi! @flexsurfer we can set up a meeting in which I could explain how it was implemented and what the problems might be.  Here is the short summary: 

There are 3 kinds of new messages. These are all local system message type  `ChatMessage_SYSTEM_MESSAGE_MUTUAL_STATE_UPDATE`. Messages are generated locally, both on the sender and receiver sides. And there are six conditions when we use this message:
  1) When we send a CR to a contact, we add a `MutualStateUpdateTypeSent` message.
  2) When we receive a CR from a contact, we add a `MutualStateUpdateTypeSent` message.
  3) When we accept the CR from a contact, we *delete* previously created `MutualStateUpdateTypeSent`and add a `MutualStateUpdateTypeAdded` message 
  4) When we handle an accepted CR previously sent to a contact, we also  *delete* the previously created `MutualStateUpdateTypeSent` and add a `MutualStateUpdateTypeAdded` message.
  5) When we remove a contact, we add `MutualStateUpdateTypeRemoved`.
  6) When we get removed by a contact, we add `MutualStateUpdateTypeRemoved`.
  
  That can probably cause som problems mentioned before:
  - Response from add/remove contact endpoints can contain more than 1 message
  - As i can see mobile client shows `Message deleted for everyone` for soft deleted messages. Here we can switch to hard delete or update existing `MutualStateUpdateTypeSent` instead of delete/add

**Comment by flexsurfer** [comment]
hey @MishkaRogachev thanks, and you don't show a soft deleted messages on desktop? that would be strange

**Comment by MishkaRogachev** [comment]
> don't show a soft deleted messages on desktop?

Yes. I think the main thing here is to agree on the requirements between the teams and it will not be difficult to change the code

**Comment by flexsurfer** [comment]
waiting for status-go and design

**Comment by MishkaRogachev** [comment]
> waiting for status-go and design

Status-go PR in progress: https://github.com/status-im/status-go/pull/3640/

**Comment by flexsurfer** [comment]
designs are ready:
Sender side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A515046&t=867Xk6LqWfKYzLK9-1

Receiver side
https://www.figma.com/file/7KIYbhoqNGAIFonE0w9TDz/Messages-for-Mobile?type=design&node-id=8364%3A600326&t=867Xk6LqWfKYzLK9-1

**Comment by MishkaRogachev** [comment]
https://github.com/status-im/status-go/pull/3640 <- ready
