### ISSUE TITLE
[Android] Horizontal frames are not centered within the camera box and a bulge appears at the end of the frame line

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16278]
follow up for https://github.com/status-im/status-mobile/pull/16206#issuecomment-1590861340
Related to comment https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS/Feedback-for-Mobile?type=design&node-id=1929-154137#429224561

### Steps to reproduce:
1. Open 'Sign in by syncing' page
2. Enable the camera

### Actual result:
- The horizontal frames are not in the middle of the camera box
- Bulge is shown at the end of the frame lines
![image](https://github.com/status-im/status-mobile/assets/52490791/46b5239a-4b1c-4b5e-aca8-57a6c5eae860)

### Expected result:
- Framing lines should be in the middle of the camera box
- The end points has to be round, not flat
![image](https://github.com/status-im/status-mobile/assets/52490791/e21a8520-8ec9-40b5-8ee0-0f40aee94c2d)

### Device:
- Real device: Pixel 7a, Android 13
- Android Emulator: Pixel 6 API 31. v12

**Comment by VolodLytvynenko** [comment]
how it looks on Android Emulator: Pixel 6 API 31. v12

https://github.com/status-im/status-mobile/assets/52490791/fb4b2fef-9cdc-4c89-b0d3-42ecfb74f574

**Comment by ulisesmac** [comment]
White tips have been addressed, but still there's an issue with the alignment of the frame because of different device's DPI, I am not sure, but I think it's not possible to center for all devices.

Make sure to test in different devices while solving this issue, a comment about it: https://github.com/status-im/status-mobile/pull/16716#issuecomment-1650692350

**Comment by churik** [comment]
I think for now it is not a priority anymore,  reopen if still relevant.
