### ISSUE TITLE
Autorotation not working for Android devices when an image is opened

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#16402]
### Steps to Reproduce:
1. Send an image in any chat
2. Open the image
3. Rotate the device to trigger auto-rotation.

### Actual Result:
When an image is opened, auto-rotation does not work on Android devices. The image does not rotate according to the device's orientation.

### Expected Result:
When an image is opened, auto-rotation should work

### Devices:
- Real device: Pixel 7, Android 13
- Android emulator: Pixel XL API 29

### ENV: 
Nightly [27 Jun 2023]

**Comment by OmarBasem** [comment]
Yes it is currently disabled due to a bug in an underlying library https://github.com/wix/react-native-navigation/issues/7726

**Comment by ilmotta** [comment]
I'm closing this issue because as @OmarBasem explained we would need to fix the RNN bug, but this was and still is outside our scope. There are conversations about removing RNN, but this will also probably take a long time to get done (if we ever do).

For anyone checking this issue, feel free to reopen in case the RNN bug is fixed.
