### ISSUE TITLE
Link preview is not resolved on message editing

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16728]
**Steps:**

1. Send text message in any chat
2. Start editing message
3. Paste any link during editing
4. Wait until link preview is fetched in composer
5. Send edited message
6. See if link preview is shown for sent message

**Actual result:** link preview is not shown

[Status-debug-logs (42).zip](https://github.com/status-im/status-mobile/files/12104707/Status-debug-logs.42.zip)

https://github.com/status-im/status-mobile/assets/97245802/40d66e29-26fc-4163-ad6e-fb00172474bf

**Expected result:** link preview is shown

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
Blocked by https://github.com/status-im/status-mobile/issues/16457

**Comment by Samyoul** [comment]
## Show link oembed when adding a link to an edited message.

### User Story

As a user I want to see link previews any time a link is shared so that I have a consistent message experience.

Feature: **Messages**

#### Background:

- GIVEN I have an account
  - I open the app
  - I am logged in
  - I am on a chat screen

#### Scenario: *Sending a message containing a link*

- GIVEN I am composing a message
- AND I have added a link to the message
- AND I allow the application to make http calls
- THEN I see an oembed for the added link in the message preview
- WHEN I send the message
- THEN I see the message in the chat
- AND I see the link preview / oembed below the message.

#### Scenario: *Receive a new message containing a link*

- GIVEN I receive a message containing a link
- THEN I see the main message the containing link(s)
- AND I see an oembed card for each link below the main message
- AND oembed appears even if making http calls is disallowed
- WHEN I tap on the oembed card, the app opens the link in my default browser

#### Scenario: *Editing a message and adding a link*

- GIVEN I am editing a message
- AND I have added a link to the edited message
- AND I allow the application to make http calls
- THEN I see an oembed for the added link in the message preview
- WHEN I send the message
- THEN I see the message in the chat
- AND I see the link preview / oembed below the message.

#### Scenario: *Receive an edited message containing a link*

- GIVEN I receive an edited message containing a link
- THEN I see the main message the containing link(s)
- AND I see an oembed card for each link below the main message
- AND oembed appears even if making http calls is disallowed
- WHEN I tap on the oembed card, the app opens the link in my default browser
