### ISSUE TITLE
Implement Quo2 Profile/ Collectibles component

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#16743]
Designs: https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=2010-35589&mode=design&t=PIeoXJ2JSSVejvAj-4

Should be implemented according to best practices
https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

Include component spec tests
https://github.com/status-im/status-mobile/blob/develop/doc/component-tests-overview.md

Communicate with design team before starting to make sure there is no unknown requirements and to understand the interactions.

You can use mock data for the preview.

The component should be added in the Graph group in the Quo2.0 preview screen

 **Check with design team before starting**

**Comment by smohamedjavid** [comment]
This issue is already completed in https://github.com/status-im/status-mobile/pull/14803


Based on the response from the design team:
> In case of a collection, for the MVP, we show them as single collectibles, without grouping them together

For MVP, we will show the collectables without grouping them together. So, we will be using this same component but with one image. 

I created a PR https://github.com/status-im/status-mobile/pull/16837 for adding the `on-press` prop to help us for dispatching navigation events when we will start building screens.
