### ISSUE TITLE
Account removal is possible without authentication

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-react#16749]
# Bug Report

## Problem 

Before logging in, it's possible to remove any account from device. It's not even required to input any password.
I think such feature should be secured with account authentication.

<img width="565" alt="image" src="https://github.com/status-im/status-desktop/assets/25482501/da130f81-3fd1-45bd-bbc0-0cbb6cd7a47e">

#### Expected behavior

Account removal is only possible after authentication.

#### Actual behavior

Account removal is possible without authentication.

### Reproduction

1. Open Status
2. Create an account, if you don't have any
3. Click the meatball button next to an account
4. A menu with "Remove this account from device" opens.

**Comment by Parveshdhull** [comment]
Hi @igor-sirotin,
Thank you for reporting the issue. We discussed this with the design meeting and this is expected behaviour. Because,
1. Even if we hide account removal behind authentication, someone who has access to your device can always clear data of the app. (Account is gone)
2. And by allowing users to remove accounts from his/her device without authentication, we are allowing him/her to get rid of accounts that are not accessible anymore. (Password forgotten/Owner of the particular account/profile is not available anymore)

**Comment by igor-sirotin** [comment]
@Parveshdhull
I agree, these arguments make sense. I have no claims if that have been discussed and decided already 🙂 
I also now think that we have kinda same behaviour on Desktop, but I never complained there 😄
