### ISSUE TITLE
Extra frames at the end of the "Generating keys" animation 

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16827]
# Bug Report

The issue was originally found and reported by @Francesca-G in [this comment](https://github.com/status-im/status-mobile/pull/16816#pullrequestreview-1556336990). 

One point: I'm not sure that the process of generating and saving keys always takes the same time. In that case, what should we show when one animation cycle is completed?

## Problem 

There's a frame that shouldn't be there at the end of the `key saving` animation, as you can see after the key has been grabbed by the end and goes inside the device the particles appear once again at the end of the animation, for a couple of frames.

https://github.com/status-im/status-mobile/assets/122543089/d5728659-0b11-4289-995e-6662ca549684

The animation should end here:
![IMG_0292](https://github.com/status-im/status-mobile/assets/122543089/50423df8-1c05-499a-b02a-90247a92ce2b)

### Additional Information

- Status version: nightly 1/08
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
This issue is happeneing due to loop being enabled in the library that we use to show transparent videos
I have a branch [here](https://github.com/status-im/status-mobile/pull/17000) fixing it with a [fork](https://github.com/status-im/react-native-transparent-video/pull/2) of that library
And I am going to ask @briansztamfater to take a look as he built that library.
