### ISSUE TITLE
Update "Page Nav" component to support the "Wallet Networks" type

### ISSUE THREAD

**Issue by smohamedjavid** [status-im/status-react#16946]
# Feature

### Description

The "Page Nav" component needs to be updated to support the "Wallet Networks" type.

<img width="300"  src="https://github.com/status-im/status-mobile/assets/19339952/2add0f8e-9c6c-4018-b562-4bf261488266">

### Design

[Link to Figma](https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=159%3A6045&mode=design&t=kFyYCJ2r6DsZsfP5-1)

### Acceptance Criteria

Should go through design review.

**Comment by J-Son89** [comment]
@smohamedjavid I think this can be a duplicate as @ulisesmac is already working on refactoring this component. 
but this should definitely be taken into consideration when adjusting this component 👍

**Comment by ulisesmac** [comment]
> @smohamedjavid I think this can be a duplicate as @ulisesmac is already working on refactoring this component. but this should definitely be taken into consideration when adjusting this component 👍

Yes! I'm about to create the PR! :)

The problem is that Wallet Networks type depend on the component to display wallet networks which is not implemented  yet :cry: 

It depends on the Network dropwdown component:
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=21704-197486&mode=design&t=PMSTorYYKMrpF8L2-4

![image](https://github.com/status-im/status-mobile/assets/90291778/2040bcaa-2241-40d4-8e2b-b0b51984b50f)

**Comment by smohamedjavid** [comment]
We have an open PR https://github.com/status-im/status-mobile/pull/16982 for the "Network Dropdown" component. We can work on this issue once it gets merged 👍
