### ISSUE TITLE
Composer button colors changes on focus

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#16940]
When focusing on the input, the color of the composer buttons changes and becomes a bit darker.

This might be due to the blur effect.

https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#521605711 feedback

**Comment by J-Son89** [comment]
@Francesca-G, @mariocnovoa I looked into this issue with @OmarBasem. It seems there is no issue here.
The composer changes to a blur view when the composer is unfocused and has empty content - this is causing the appearance of a color change but it is configured right as far as the designs show.
See the designs here:
https://www.figma.com/file/wA8Epdki2OWa8Vr067PCNQ/Composer-for-Mobile?type=design&node-id=3101-348599&mode=design&t=rKDKOJbj1VH224Ny-0

https://vimeo.com/727812151

**Comment by Francesca-G** [comment]
@J-Son89 If you look at the screenshot I used for the review I wasn't in scroll state, I was about to type, so it should be "Keyboard" state:
<img width="396" alt="Screenshot 2023-08-09 alle 13 39 14" src="https://github.com/status-im/status-mobile/assets/122543089/90434066-b4a8-43c2-b066-391812a73754">

This is the "Scroll" state with blur that you mentioned:
<img width="396" alt="Screenshot 2023-08-09 alle 13 38 30" src="https://github.com/status-im/status-mobile/assets/122543089/06aa144f-006b-48ed-b36a-cb74e912c1cc">

Implementation still looks darker compared to both of them, as you can see:
<img width="396" alt="Screenshot 2023-08-09 alle 13 40 16" src="https://github.com/status-im/status-mobile/assets/122543089/4e6b2bd6-0f6e-4211-920d-dc08fcbe6be6">

I don't know if blur is altering the color, but the color looks darker even when the composer doesn't have any blur.
Hope this helps :)

**Comment by J-Son89** [comment]
Hi @Francesca-G, yep that is a separate issue - I have fixed that here:
https://github.com/status-im/status-mobile/pull/16902

**Comment by J-Son89** [comment]
@Francesca-G can we close this issue now? 🤔

**Comment by Francesca-G** [comment]
> @Francesca-G can we close this issue now? 🤔

If the issues are being addressed in separate instances we can close this one :)

**Comment by J-Son89** [comment]
@Francesca-G - this issue _"@J-Son89 If you look at the screenshot I used for the review I wasn't in scroll state, I was about to type, so it should be "Keyboard" state"_, was already fixexd in https://github.com/status-im/status-mobile/pull/16902

the initial issue 
_"When focusing on the input, the color of the composer buttons changes and becomes a bit darker.
This might be due to the blur effect.
https://www.figma.com/file/Tf5nfkYvpbnNCo4rKLK7lS?node-id=3679:38431&mode=design#521605711 feedback"_
seems like a non-issue as the color will change when blur view is triggered due to scrolling - as it is in designs. 

So there will be no separate issue opened as everything has been addressed (as far as I can see)

**Comment by J-Son89** [comment]
Unless there is something I have missed? 🤔

**Comment by Francesca-G** [comment]
> @Francesca-G - this issue _"@J-Son89 If you look at the screenshot I used for the review I wasn't in scroll state, I was about to type, so it should be "Keyboard" state"_, was already fixexd in #16902
> 
I was talking about this one

Looks good to me :)

**Comment by J-Son89** [comment]
perfect, thanks @Francesca-G! :)
