### ISSUE TITLE
Rounded edges of color sections of identity rings

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#16954]
# Bug Report

## Problem 

The edge of the color sections now has a radius that shouldn't be there.

<img width="541" alt="Screenshot 2023-08-09 at 15 40 20" src="https://github.com/status-im/status-mobile/assets/67952253/36f429a8-5b61-42ff-b964-676e934ef7a9">

#### Expected behavior

<img width="416" alt="Screenshot 2023-08-09 at 15 41 22" src="https://github.com/status-im/status-mobile/assets/67952253/18ff6858-a100-4b69-a4cb-c2a529291d35">

### Additional Information

- Status version: nightly 9/08
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
It actually always was like that. Previously the line was thinner and it was hard to see it but the algorithm hasn't changed.
Investigating what can be done with that.

**Comment by alwx** [comment]
Removing myself from the issue because I'm off next week (to give someone else a chance to work on it)
Some investigation results:
There is no easy way of doing it. What might work is adopting a technique from here https://stackoverflow.com/questions/76690354/draw-round-corners-in-canvas-with-drawarc but I tried and achieved no success yet.
