### ISSUE TITLE
User receives PNs on all types of messages in group chat

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#16972]
User should receive PNs in group chat only in case of replies and mentions. Currently PNs are generated by all types of messages.

**Preconditions:** User A and User B are members of the same group. User A has enabled notofocations.

**Steps:** 

1. User B sends regular message in group. 
2. See if User A receives PN

**Actual result:** User A receives PN

https://github.com/status-im/status-mobile/assets/97245802/0e4b1e38-1b4b-489a-a998-ac05f3976fcc

**Expected result:** User A should not receive PN

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by cammellos** [comment]
Is this really the desired behavior? I believe discord/whatsapp do it differently when it comes to private group chats (as a user, I would like to be notified if someone writes in a private group chat, at least by default)
cc @John-44 @pedro-et

**Comment by pavloburykh** [comment]
> Is this really the desired behavior? I believe discord/whatsapp do it differently when it comes to private group chats (as a user, I would like to be notified if someone writes in a private group chat, at least by default) cc @John-44 @pedro-et

In case if we decide that user SHOULD receive PNs - then should we add notifications in AC for such messages and also show unread counters instead of unread badges? 

Currently we generate PNs  + AC notifs + unread counters in group chats only in case on mentions/replies.

**Comment by ilmotta** [comment]
Hey @pavloburykh, since this issue has been resurrected recently in our mobile board I took a look at it. It seems that, as @cammellos said, the _default behavior_ for group chats can be to send PNs on every message, not just mentions or replies. This behavior, for example in Telegram, depends on each user's settings.

So in Telegram, if the option `Notifications and Sounds > Notifications for chats > Groups` is enabled, then when I'm invited to a newly created group or even in one I'm already a member, I will always get PNs on all types of messages. Only if I disable the option I'll only get PNs on mentions and replies. We can also assume a substantial portion of Telegram users don't disable notifications for group chats, which means sending PNs for all types of messages in groups is actually the expected behavior for these users.

In the end, I think the default behavior could be to either always send PNs or not, thus I think this issue can be flagged as an improvement or a bug, depending on our perspective. But I'm inclined to think this is not a bug and that we can close it for the moment since we don't have the capacity to make this improvement.

Do you think this is a reasonable outcome for the issue?

**Comment by pavloburykh** [comment]
> Do you think this is a reasonable outcome for the issue?

@ilmotta I totally agree we do not have capacity for this right now and overall I agree that current behaviour can be considered as expected. 

The only reason why I have not closed this issue long time ago is this [question](https://github.com/status-im/status-mobile/issues/16972#issuecomment-1674887844). But this is super minor and doe not matter for now. 

I believe we can just close this ticket. Thank you.
