### ISSUE TITLE
update group-avatar component

### ISSUE THREAD

**Issue by codemaster115** [status-im/status-react#17013]
# Problem

Follow-up of #16931 
Update the `size` property to receive any valid number

## Implementation

Refactor group-avatar component to receive any valid number as the `size` property

**Comment by smohamedjavid** [comment]
@codemaster115 - I have reverted the commit 673b1afc3a9edf35202ea8c238f0a899fefef17f to fix the crashing of the app due to invalid sizes passed to the `Group Avatar` component across the codebase.

Reopening this issue as the sizes API changes need to be updated across the codebase.

<hr />

**EDIT:** 

Steps to reproduce:

Have at least one group chat. Try to log in to the app.

<img width="300" src="https://github.com/status-im/status-mobile/assets/19339952/90cb68bc-c051-4ada-b8f4-af2b17622592" />

```log
Invariant Violation: [439,"RCTView",11,{"width":"small","height":"small","alignItems":"center","justifyContent":"center","borderRadius":"<<NaN>>","overflow":"hidden"}] is not usable as a native method argument

This error is located at:
    in RCTView (at View.js:32)
    in View (created by quo2.components.avatars.group_avatar.view.view_internal)
    in quo2.components.avatars.group_avatar.view.view_internal (created by quo2.theme.f_with_theme)
    in quo2.theme.f_with_theme
    in G__33904 (created by status_im2.contexts.chat.home.chat_list_item.view.avatar_view)
    in status_im2.contexts.chat.home.chat_list_item.view.avatar_view (created by status_im2.contexts.chat.home.chat_list_item.view.chat_list_item)
```

**Comment by codemaster115** [comment]
@smohamedjavid Thanks for your checking. I will address it.
