### ISSUE TITLE
Chat input overlaps the last message on IPhone 14

### ISSUE THREAD

**Issue by churik** [status-im/status-react#17112]
# Bug Report

## Problem 

https://github.com/status-im/status-mobile/assets/4557972/e02f936b-773b-47c5-b4b4-cfe05e04213f

- Status version: nightly 25/08/23
- Operating System: iOS 16.6 (iPhone 14 Pro) 
Can't be reproducible on IPhone 12  mini, Iphone 10. 

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @churik, Thank you very much for reporting the issue.
The issue is also not reproducible in the iPhone 14 Pro simulator.

1. Sorry I am not able to get the whole context from the video, did you open composer while messages are scrolled to this position, or they auto-scrolled on keyboard opening?
2. Is the issue consistently reproducible in your device? If this is the case I can create a PR and we can try a few fixes. wdyt?

**Comment by Parveshdhull** [comment]
Oh I see if messages are scrolled to this position, they should auto scroll to correct position on sending message, but that's not happening. Reproducible in simulator. I will look into this.
