### ISSUE TITLE
memorize camel-snake-kebab.core

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#17292]
camel-snake-kebab.core is slow, if we use it it should be memorized. in worklets for example

**Comment by flexsurfer** [comment]
cc @Parveshdhull

**Comment by Parveshdhull** [comment]
Hi @flexsurfer,
Thank you very much for finding the issue and pinging.
Looks like most of the worklets functions are converting the kebab case to the camel case in the `js` code itself
(changed in https://github.com/status-im/status-mobile/pull/14855),
the only exception is the `floating-screen-gesture-on-end` function. Will fix this one too. Thank you

**Comment by flexsurfer** [comment]
so we could remove camel-snake-kebab dep ?

**Comment by Parveshdhull** [comment]
Current use case of `camel-snake-kebab.core` in code
(if we can get rid of uses in these 4 instances, we can remove library)

1. ns `status-im2.contexts.quo-preview.preview` fn ` humanize`
2. ns `test-helpers.component`
3. ns `utils.worklets.shell` fn `floating-screen-gesture-on-end`
4. event: `:chat.ui/cache-link-preview-data`

1st and 2nd should not affect app performance as they are just quo-preview and test-helpers
3rd is very easy to remove, just have to move conversion to js
4th not sure, why we need and how hard it will be replace, need to check

**Comment by ilmotta** [comment]
Is this issue still relevant @flexsurfer @Parveshdhull ?

**Comment by ilmotta** [comment]
@Parveshdhull, since the time of your comment a few things changed for the better cc @flexsurfer @ulisesmac:

- CCs in the wallet team implemented memoization on `csk/->kebab-case-keyword` and `csk/->PascalCaseKeyword`. We can use these utilities when appropriate.
  
https://github.com/status-im/status-mobile/blob/838c85cd202f31ac65e3b28c3281c22343fc77c2/src/utils/transforms.cljs#L69
  
- The old link preview data is being deleted in https://github.com/status-im/status-mobile/pull/21603

As Parvesh said, the non-prod code using csk is harmless.

Then we have this other point:

> ns utils.worklets.shell fn floating-screen-gesture-on-end

This is also now only using `clj->js`, not `csk` anymore.

------

So this issue can be closed and we don't need to remove the library if we use it with memoization (I'd still avoid it if possible, but it's more usable with memoization).

Shall we close as completed @flexsurfer ?
