### ISSUE TITLE
Images are not sent if added during message editing

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17395]
**Steps:**

1. Send a text message
2. Open message aditing
3. Add image/images during editing
4. Send edited message
5. See if images were sent

**Actual result:** images were not sent

**Expected result:** currently editing feature is not implemented with images. This is a reason why we do not show edit button for messages containing images. So in this case we probably need to disable Add image button when editing a message until we implement this feature. 

https://github.com/status-im/status-mobile/assets/97245802/4564579e-a1f7-4c96-81db-8d43cf3cff66

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by SilentCruzer** [comment]
Can I work on this issue?

By disabling the button do you mean to hide it completely during editing similar to the audio button, which is only visible in composing a new message and not visible in editing?

To disable the images we need to disable both the camera and pick-from-gallery buttons, which would mean during editing no action buttons will be working since the other two buttons (reaction button and format button) are not yet implemented. 

So during editing should we hide all four buttons or make the images button result in a pop-up saying "to be implemented"?

**Comment by pavloburykh** [comment]
> make the images button result in a pop-up saying "to be implemented" 

@SilentCruzer from my perspective this option will work. The one thing I would propose is to set up pop-up text for camera and pick-from-gallery buttons  to **"temporary unavailable for editing"** instead of just "to be implemented". Cause these buttons are actually implemented and work in other flows except of editing. 
сс @cammellos
