### ISSUE TITLE
Sometimes chat gets stucked with history loading state (skeleton) and app gets frozen (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17426]
Unfortunately there are no specific steps yet. The issue occurs randomly. 

I have faced it once while testing https://github.com/status-im/status-mobile/pull/17417 cc @Parveshdhull . 

Below attaching the video and logcat. 

[logcat_004.log.zip](https://github.com/status-im/status-mobile/files/12728902/logcat_004.log.zip)

[Status-debug-logs (65).zip](https://github.com/status-im/status-mobile/files/12728950/Status-debug-logs.65.zip)

https://github.com/status-im/status-mobile/assets/97245802/53b3b6d8-9c2c-4a5b-a268-32a804e2a508

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by Parveshdhull** [comment]
Hi @pavloburykh, Thank you very much for reporting the issue.

It's most probably caused by the use of https://github.com/react-native-masked-view in the animated loading skeleton.
I faced a similar issue in the debug version, (randomly and in Android only).

Once the chat screen is loaded we replaces the static loading skeleton with an animated one and probably that freezes.
Maybe in Android, we keep a static loading skeleton and avoid replacing it.

I can create a PR, but as it happens randomly not sure we can test it reliably.

**Comment by Parveshdhull** [comment]
Created the PR: https://github.com/status-im/status-mobile/pull/17432, hopefully it will fix the issue :crossed_fingers:

**Comment by Parveshdhull** [comment]
If we can confirm masked-view is cause of this freeze, we need to remove it and re-implement animated loading skeleton without it.

**Comment by Parveshdhull** [comment]
Adding for reference:

Issue is also happening in IOS: https://github.com/status-im/status-mobile/issues/20599
