### ISSUE TITLE
Sometimes PN does not redirect user into correct chat if some other chat was opened at the moment of redirection (Android)

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17790]
Followup of https://github.com/status-im/status-mobile/pull/17721 cc @yqrashawn 

Reproducing on Android 12, Samsing Galaxy A52. Bug is not reproducible every time

**Preconditions:** User A (Android) turns on push notifications

**Steps:** 

1. User A opens 1-1 chat with User B
2. User A closes the app
3. User B sends mention/reply to User A in community channel
4. User A taps on PN 
5. See if User A is redirected into community cahnnel

**Actual result:** sometimes User A remains on 1-1 chat screen and is redirected to the channel. At the same time, the message in channel appears as read despite User A in fact has not opened the channel. 

https://github.com/status-im/status-mobile/assets/97245802/5ecbbb36-928a-4491-beb9-7dd446452a13

[Status-debug-logs (76).zip](https://github.com/status-im/status-mobile/files/13226198/Status-debug-logs.76.zip)

**Expected result:** User A should be redirected to the right chat upon PN. 

### Additional Information

- Status version: nightly 
- Operating System: Android

**Comment by Parveshdhull** [comment]
Hi @yqrashawn,
when we are navigating to 1-1 chat, we always pop-to-root. But we don't do this in case of community chat (because we need to keep the community screen open). ([reference](https://github.com/status-im/status-mobile/blob/fb8a7d2d8e133d63077eb17b9caac10f9b779807/src/status_im2/contexts/chat/events.cljs#L219))

Still, we have `(close-chat false)` in the `navigate-to-chat` event that should have closed the current 1-1 chat (even if the view is not destroyed).
I didn't look much into the issue and am not sure why `current-chat-id` didn't update while navigating, still, the issue might be related to this.  We probably need to `pop-to-root` before navigating to community chat from notification.
