### ISSUE TITLE
Communities – All channels should have a category

### ISSUE THREAD

**Issue by FFFra** [status-im/status-react#17911]
# Feature Issue

[Figma Design](https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=7898-522759&mode=design&t=K8JlC5NndcDKJBdv-0)

### User Story

Using the Desktop App, create a Channel and add a Category:

![image](https://github.com/status-im/status-mobile/assets/5999878/24c057ea-6b1a-4adb-8662-bdd5e0e64747)

The category design should be consistently reflected in the mobile interface as follows:

![image](https://github.com/status-im/status-mobile/assets/5999878/210123e1-8fde-4df4-a983-b0fe2502efb2)

### Description
The primary goal of this issue is to integrate the 'Channels' category, currently present in our desktop application, into our mobile app, ensuring that the design, especially the dividers based on these categories, is consistently reflected across both platforms.

### Acceptance Criteria

– Follow Figma Design
– Implement the necessary adjustments or developments in the mobile app
– Improved user navigation and aesthetic appeal in the mobile app, mirroring the desktop app's established design.

### Notes

– Please, be aware that in Mobile Figma this feature is treated as "Divider label"/"Parent component"
– Attention should be paid to the responsiveness of the design elements, particularly the dividers, to ensure they adapt well to different mobile screen sizes.

**Comment by ilmotta** [comment]
Channel sections/categories are already integrated in the mobile app. I think we can make the issue more clear by saying something like "uncategorized channels should be grouped in a default category". I'm checking now with designers if this is actually what we desire, because I saw on Figma that we have a design for uncategorized channels, and they don't have a default category, which in that case means we'll close this issue, but let's wait for confirmation. Figma link https://www.figma.com/file/h9wo4GipgZURbqqr1vShFN/Communities-for-Mobile?type=design&node-id=10580-410118&mode=design&t=FAhlHStdYAfL6L0I-0

**Comment by FFFra** [comment]
issue is not relevant because categories are already integrated into the mobile app.
