### ISSUE TITLE
Sometimes toast about old join community notification starts appearing on every login

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#17955]
There are no reproduction steps yet. Hope attached logs might help. 

For now I have faced the issue only on Android but I don't think it is device specific. It is hard to verify as it happens randomly.

On the video below (recorded on release build) you can see the toast appearing on every relogin. 

[Status-debug-logs (83).zip](https://github.com/status-im/status-mobile/files/13426193/Status-debug-logs.83.zip)

https://github.com/status-im/status-mobile/assets/97245802/bd716afe-e0fe-4bab-80d9-addf26bf1587

### Additional Information

- Status version: release 1.26, nightly
- Operating System: Android

**Comment by cammellos** [comment]
This is most likely a status go fix, notification should not be triggered multiple times.

**Comment by alwx** [comment]
@cammellos I've checked — we actually don't send the notification twice but update the existing notification with `ActivityCenterMembershipStatusAccepted` status and send the update. And it's not very specific to this particular notification — we use the same mechanism for all the other notifications as well.

The case here is that you re-recieve the message when you log out and log in again because we fetch the messages on re-login and process them in `status-im.transport.message.core`. The potential fix is to update the notification again once it's received and processed by the client but it might break things when you use multiple clients simutaneously (let's say mobile and desktop)

My conclusion is that it doesn't actually need to be fixed to not overcomplicate the logic. First of all, it's a rare case — it's not like clients constantly log out and log in again (people usually stay logged in all the time) + it happens only sometimes when they do. I doubt it's `high-priority`, it's not even close to be a "Critical bug", I think it's not even a bug at all because that's how we designed the processing of received messages to work, and there is no fix needed.

cc @churik

**Comment by churik** [comment]
> First of all, it's a rare case

oh, I'd argue that - it is a really common case in terms of our app, as it is getting killed after a certain period of inactivity. 
During testing, we received this message dozens of times, and until the fix with messages (that after background/inactivity/sleeping mode, user sometimes cannot send and receive messages) is not here it is very noticeable. 

And it was not there in previous release, we haven't seen the persistent notification before, so I suppose this is regression

**Comment by alwx** [comment]
@churik could you point out after which particular fix this issue has appeared? That might help figuring out what went wrong with the fix.

**Comment by churik** [comment]
no, I can't unfortunately - just know that we couldn't see this issue in release 1.25 for 100%

**Comment by pavloburykh** [comment]
This issue still occurs and appears to be quite annoying from UX perspective. @alwx are there any updates on this? 

Here is a fresh example from release 2.27 build

[Status-debug-logs - 2024-02-23T151405.168.zip](https://github.com/status-im/status-mobile/files/14385529/Status-debug-logs.-.2024-02-23T151405.168.zip)

https://github.com/status-im/status-mobile/assets/97245802/746d0179-4cf7-46d5-9930-5197f4bee73d

**Comment by alwx** [comment]
@pavloburykh sadly no updates — I tried to investigate it a couple of months ago, didn't reproduce and postponed because there were more important things to do.

**Comment by ibrkhalil** [comment]
I tried to reproduce but unfortunetaly couldn't, Can you help me tell if it's still reproducible?
CC: @pavloburykh

**Comment by ibrkhalil** [comment]
Reproduced it, Nevermind.
