### ISSUE TITLE
App fails to build after reinstalling nix

### ISSUE THREAD

**Issue by OmarBasem** [status-im/status-react#18334]
After reinstalling nix on my Mac (M1), running `make shell TARGET=android` and `make shell TARGET=clojure` fails to run:

```
yarn shadow-cljs watch mobile
Configuring Nix shell for target 'clojure'...
warning: ignoring untrusted substituter 'https://nix-cache.status.im/', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
error: creating directory '/nix/var/nix/gcroots/per-user/omar': Permission denied
make: *** [run-clojure] Error 1
```

Trying to use `sudo` the shell starts, but the app still fails to build because `node_modules` are empty. Trying to run `yarn install` from inside shell fails with error:

```
error https://registry.yarnpkg.com/jsc-android/-/jsc-android-250230.2.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/usr/local/share/Library/Caches/Yarn/v6/npm-jsc-android-250230.2.1-3790313a970586a03ab0ad47defbc84df54f1b83-integrity/node_modules/jsc-android/dist/org/webkit/android-jsc-intl/r250230/android-jsc-intl-r250230.aar'"
```

**Comment by siddarthkay** [comment]
so that we remember why this issue happened, 

it was because @OmarBasem installed nix manually after nuking nix store.
Manual installation installed nix version `2.19.2` locally.

This was fixed with : 
- `make nix-purge` then
- system reboot then
- fresh clone of repo ( because of previous experiments with sudo ) and finally
- `make run-clojure` :)
