### ISSUE TITLE
Wallet - ui bug - Send Flow - select account tabs jumping after closing address input 

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18375]
On the send flow the UI is a bit glitchy.

To reproduce:
1- Go to new wallet
2- select an account
3- hit "send" button
4- select any other tab then the default
5- select the address input,
6- start typing, delete the text and then tap away from the input to revisit the start of the page

Expected Behaviour:
The UI returns to the state at Step 4

Actual: 
Not all tabs render/ the tabs position is off and the screen is a bit jumpy.

https://github.com/status-im/status-go/assets/22799766/8eec05d5-56d4-4c7a-a85f-382f3f56c881

**Comment by shivekkhurana** [comment]
Update: 
I was able to reproduce this error. It happens if you switch the tab to saved or contacts or my address before clicking on input. This is an issue at the component level. The error is: 

```
ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
```

I also verified that setting the `scrollable?` prop to false gets rid of this error.

 
---


Hey, I tried multiple times but I'm not able to reproduce this bug. 
Are you on an old/new device? 

https://github.com/status-im/status-mobile/assets/1925158/4c6fd45a-751c-441d-9825-f3cc63daf608
