### ISSUE TITLE
Confirm button becomes enable after user enters 6 characters to the Password field

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#18393]
# Bug Report

## Problem 
[comment]: # (A problem description)
Our app has several places where we enter user's password: login, biometrics settings, creating wallet accounts etc. Since we use validation rule that user's password should contain at least 10 characters we do not need to confuse user by enabling Confirm button after he entered only 6 of them (characters).

#### Expected behavior
Confirm button on Enter Password popup becomes enable after user enters 10 characters

#### Actual behavior
Confirm button on Enter Password popup becomes enable after user enters 6 characters

https://github.com/status-im/status-mobile/assets/147824399/475378ec-5377-4577-88dc-906749a83e4f

### Reproduction

**Precondition**: app installed and user exist

1. Open Status
2. Put 6 characters into Password field

### Additional Information

- Status version: nightly from January,4
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Hey @mariia-skrypnyk, the UX issue indeed exists. Thank you for reporting. I believe we still need to support 6-9 character passwords because of v1 users, thus we can't enable the button only if the password length is greater than or equal to 10, otherwise we could end up locking out v1 users when they need to type passwords. When a user installs v2 on top of v1, their old passwords are still the same.

Once v2 is better established on the market, we might even offer a migration path to slightly safer passwords by _forcing_ users with 6 character passwords to use at least 10. This is very common in many services. Then, with that in place, we would be able to enable the password button only when there are at least 10 characters. Although I see this _forced password migration_ strategy working, it's a considerable effort for little return.

Therefore, I think it's reasonable to close this issue for the time being.
