### ISSUE TITLE
Wallet: Add support for sending STT (Status Test Token)

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18413]
On the select Asset page, if a user selects Status Test Token as the asset to send the confirm button does not respond.

STT token should work the same as any other token.

**Comment by mariia-skrypnyk** [comment]
Hi @J-Son89 !

Have some update for this issue when Confirm button just does not respond.

Now we have the same situation with ETH at newest nightly build from the 10 of January. So we have no ability to finish a transaction.

**Comment by mariia-skrypnyk** [comment]
@J-Son89 Please use these steps:

1. Login as User A and go to your Wallet -> Receive -> Open QR code of your adress (0xc9fc5177b378063da15c150d420919a6d8b95fa5)
2. Login as User B (has some ETH) go to your Wallet -> Send -> put adress of user A
3. Put amount you want to send
4. Slide to send
5. Enter your Password and tap Confirm


I've tested using both ways: Testnet toggle on/off

**Comment by briansztamfater** [comment]
Hey @mariia-skrypnyk, I've made some modification in the sending logic, can you test on this PR? https://github.com/status-im/status-mobile/pull/18473

I've found the transaction is executing, but even if I select STT token the transaction is executed with ETH instead of STT. So  I want to identify all the issues before starting to work on this.
