### ISSUE TITLE
Wallet - research progressive blur on mobile:

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-react#18457]
Design team are exploring community minted collectibles.
For the list in wallet we need to display the name and the community
They are exploring this idea with progressive blur:
see
<img width="374" alt="Screenshot_2023-12-13_at_17 22 05" src="https://github.com/status-im/status-mobile/assets/22799766/232583f5-7a6c-481d-8984-76552c71f119">

https://www.figma.com/file/HKncH4wnDwZDAhc4AryK8Y/Wallet-for-Mobile?type=design&node-id=7511%3A262793&mode=design&t=W99T7n97EIafY4Dr-1

The idea is to have a blur layer that desapears like a gradient

Research whether this is possible on ios and android.
Document your findings and align with @mariocnovoa in the design team.

**Comment by briansztamfater** [comment]
To explore: https://www.youtube.com/watch?v=oboF_H1MApo

**Comment by J-Son89** [comment]
@OmarBasem - I think we can close this issue now, right? I think you addressed this? although maybe you can add a link to the pr you made/ or some of the results here?

**Comment by OmarBasem** [comment]
This issue is probably out of scope now, but adding my findings: 

Having progressive/gradient blur is possible with the library [react-native-skia](https://github.com/Shopify/react-native-skia). Followed the steps shown in the [linked video](https://www.youtube.com/watch?v=oboF_H1MApo). Below is a demo of what I got: 

https://github.com/status-im/status-mobile/assets/29354102/7c82a694-be4f-4ec2-9325-b64fbe9bd890
