### ISSUE TITLE
Collectibles loading performance

### ISSUE THREAD

**Issue by vkjr** [status-im/status-react#18608]
# Problem

When account has a lot of collectibles collectibles (like [sonnyf.eth](https://etherscan.io/address/0x35f0686c63f50707ea3b5bace186938e4e19f03a)), our interface load them inconsistently - they appear and disappear, order changes and that gives bad user experience.

![Simulator Screenshot - iPhone 13 - 2024-01-24 at 14 25 33](https://github.com/status-im/status-mobile/assets/5786310/d82d87e2-934e-4803-a177-939a3d2cb69a)

That should be fixed.

## Acceptance Criteria

Users shouldn't see collectibles blinking and changing the order while they are loaded

**Comment by ulisesmac** [comment]
Hey @vkjr 
I believe the problem in this issue is not related to performance, it's  about the order we are storing  the collectibles (adding to the beggining instad of adding them to the end of the collection).

btw, I've just wrote an issue about some performance issues:
- https://github.com/status-im/status-mobile/issues/18614
