### ISSUE TITLE
[IOS] App crashes and unsmooth scrolling in the collectibles tab

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18644]
### Steps:
1. Recover a user account with a substantial number of collectibles (be aware, collectibles sometimes are not displayed. You need to wait at least 1 minute after recovering and relogin https://github.com/status-im/status-mobile/issues/18613)
2. add watch only account `0x8d2413447ff297d30bdc475f6d5cb00254685aae`
3. Open  "collectibles" tab to see all collectibles available for all added adresses
4. Scroll through the collectibles list consistently.

### Actual result:
Unsmooth scrolling of collectibles, the app crashes during the process of scrolling collectibles

https://github.com/status-im/status-mobile/assets/52490791/5d378dff-8ac8-4ecb-973e-53982e042c98

### Expected result:
The scrolling of collectibles should be smooth, and the app should not crash during the scrolling process.

### Device:
iPhone 11 Pro max, IOS 16

### Logs:
[logs.zip](https://github.com/status-im/status-mobile/files/14051089/logs.zip)

**Comment by smohamedjavid** [comment]
@VolodLytvynenko - Is the bug reproducible in the latest nightly?

**Comment by clauxx** [comment]
@smohamedjavid I can reproduce it on develop

**Comment by VolodLytvynenko** [comment]
@smohamedjavid still reproducible. But this time when I recovered user with more collectibles than provided user described in step 2. I have changed the description  in https://github.com/status-im/status-mobile/issues/18644#issue-2102272264 and sent you the seed phrase


https://github.com/status-im/status-mobile/assets/52490791/5e494964-daa0-4861-9240-ad6f51efbb8c



[logs.zip](https://github.com/status-im/status-mobile/files/14082181/logs.zip)

**Comment by clauxx** [comment]
The issue with crashing seems to come from using `react-native-fast-image`, caused by excessive memory usage. There's an [old issue](https://github.com/DylanVann/react-native-fast-image/issues/195) there, where rendering tons of large images in a flatlist causes a huge memory jump (usually from quick scrolling) and a crash. They mention the crash happens consistently form >1MB images, and I just checked some random collectible images, and some go beyond 9MB, especially GIFs.

We could fix the crash by going back to using the RN image component until we find a way to show the images without sacrificing performance.

NOTE: FYI The crash is only reproducible on physical devices.

**Comment by smohamedjavid** [comment]
@clauxx -  Thank you for investigating this issue real quick. Apologies, I was actually checking on the simulator (with gesture scroll to simulate fast scroll). I couldn't able to reproduce it. But, I reproduced it on a real device and it crashes as expected.

I guess, it's reasonable to switch back to the RN Image component. I felt that the `react-native-fast-image` library is not actively maintained. It's high time we look for other alternatives with caching support.

EDIT: On quick googling, I found that https://github.com/xerdnu/react-native-blasted-image is an unofficial successor.

**Comment by clauxx** [comment]
> @clauxx - Thank you for investigating this issue real quick. Apologies, I was actually checking on the simulator (with gesture scroll to simulate fast scroll). I couldn't able to reproduce it. But, I reproduced it on a real device and it crashes as expected.
> 
> I guess, it's reasonable to switch back to the RN Image component. I felt that the `react-native-fast-image` library is not actively maintained. It's high time we look for other alternatives with caching support.

Agreed! But I think a new library won't solve the issue entirely. Since we have no control over the size of the original images, might be good to generate lightweight previews on the status-go side. Same should go for GIFs, as they are the heaviest in terms of file size. Maybe just showing the first frame and letting the user know it's GIF or compressing them heavily, but seems like the GIFs and the high res images are the issue at core.

**Comment by clauxx** [comment]
For start, I'd remove the fast-image from the collectibles preview to avoid the crash and add a follow-up issue for the performance issue with large images. WDYT @smohamedjavid @VolodLytvynenko ?

**Comment by smohamedjavid** [comment]
@clauxx - Yes, I guess it's good for now. 

> But I think a new library won't solve the issue entirely.

Not for this case. I generally believe we need an image component with caching support to prevent calling the remote URL repetitively and also displaying the image quickly.

> Since we have no control over the size of the original images, might be good to generate lightweight previews on the status-go side. Same should go for GIFs, as they are the heaviest in terms of file size. Maybe just showing the first frame and letting the user know it's GIF or compressing them heavily, but seems like the GIFs and the high res images are the issue at core.

Totally agree. It's worth discussing with the Desktop team 👍.
