### ISSUE TITLE
 Inability to purchase .stateofus.eth ENS domain

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18760]
### Steps:
1. Recover the user with available STT or SNT.
2. Navigate to Profile -> Legacy Settings -> 'Your ENS Name' section -> Get Started.
3. Attempt to purchase the .stateofus.eth domain ENS.

### Actual result:
The button 'Not enough STT' is displayed, indicating that the user does not have enough STT to proceed with the purchase.

![image](https://github.com/status-im/status-mobile/assets/52490791/6a7846ec-aa3d-4c7d-bde7-438320d489cd)

### Expected result:
The .stateofus.eth domain ENS should be available for purchase

**Comment by John-44** [comment]
Descoped from MVP, as we need to focus on getting our app launched as soon as possible, and it's not worth delaying our MVP release for this item.  

Post-MVP, one of the projects in the backlog is a redesign/rebuild of our ENS support, post MVP this problem will be approached as a coherent project that will aim to fix all of the many, many issues with our current ENS support, and which will at the same time modernise our ENS support.  But this is all for post-MVP.

**Comment by ilmotta** [comment]
I'm closing this issue because prioritizing the new ENS management in the mobile app is not on the horizon, nor bug fixes in the old ENS registration flows (btw they have already been removed from the UI). https://www.figma.com/design/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?node-id=4945-329224&t=n5GiM01GJYdtz3LB-0.
