### ISSUE TITLE
Incorrect Optimism Gas Fee display

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#18780]
### Steps:
1. Recover the user with tokens available on Optimism.
2. Enter a transaction amount on the "send assets" screen.
3. Check the generated fees displayed by the Status App.

### Actual result:
The displayed gas fee is consistently less than $0.01 USD for transactions on the Optimism network. However, upon checking the actual transaction fees on Etherscan, they are substantially higher:
![image](https://github.com/status-im/status-mobile/assets/52490791/a6607fc4-84d3-43a5-ab92-2d30a8979477)

Transaction 1 (0.0001 ETH): Actual fee on Etherscan is $0.25 USD.
https://optimistic.etherscan.io/tx/0xdbb244478ec6e4e399c3d62ad065ae3bf06722bb53c533c81da8afb277e1befe

Transaction 2 (0.0005 ETH): Actual fee on Etherscan is $0.26 USD.
https://optimistic.etherscan.io/tx/0x6710f078abda124678357d14bb70e34dae2e03da78abaabbdc7ccf7dcbd6c749

### Expected result:
The fee corresponds to the actual fee shown in the etherscan

**Comment by briansztamfater** [comment]
@VolodLytvynenko Gas Fee is calculated fine, the problem is that Optimism has also L1 Data Fees and that is not returning from status-go.

If you see the details of the transactions you posted, we can see two different fees.

![](https://github.com/status-im/status-mobile/assets/18485527/437b81ee-65a7-4e1f-a032-d5d8d2f19d2f)

L2 Fees (a.k.a. chain [execution gas fees](https://docs.optimism.io/builders/dapp-developers/transactions/estimates#execution-gas-fee)) are indeed below $0.01, and that is what we are currently displaying is the app.

But for Optimism transactions, we should also take into consideration [L1 Data Fee](https://docs.optimism.io/builders/dapp-developers/transactions/estimates#l1-data-fee). In OP can be requested by serializing the transaction and calling a function in an Optimism Oracle.

Already discussed this with @alaibe and seems we should return this from status-go, so will continue to work on this issue once status-go returns the L1 Data Fee value.

**Comment by VolodLytvynenko** [comment]
> Gas Fee is calculated fine, the problem is that Optimism has also L1 Data Fees and that is not returning from status-go.

Hi @briansztamfater I see. Thank you for figuring it out and sharing it!

**Comment by J-Son89** [comment]
@briansztamfater, @VolodLytvynenko - this issue is still relevant should we close?

**Comment by VolodLytvynenko** [comment]
> @briansztamfater, @VolodLytvynenko - this issue is still relevant should we close?

hi @J-Son89 can't validate it due blocker. For now the fee is not fetched at all https://github.com/status-im/status-mobile/issues/19431

**Comment by briansztamfater** [comment]
I can confirm it is still relevant though
