### ISSUE TITLE
Changes are saved when closing Addresses for permissions screen by swiping

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#18835]
**Steps:** 

1. Open community
2. Go to Addresses for permissions screen 
3. Unselect some address
4. Swipe down the screen
5. Re open Addresses for permissions screen and see if changes are saved

**Expected result:** changes should not be saved unless if user has not tapped 'Confirm changes button'

**Actual result:** changes are saved

https://github.com/status-im/status-mobile/assets/97245802/10dd0755-6fdf-4c0f-91b9-29b71a15cca3

- Status version: nightly 
- Operating System: Android, iOS

**Comment by ilmotta** [comment]
FYI: @ajayesivan this issue is already fixed in the branch I'm working on for editing shared addresses. I had no choice but to fix this.

I'm assigning myself to this issue for visibility.

**Comment by ajayesivan** [comment]
@ilmotta Thanks for letting me know. On my side too, the fix was not intentional, it was just part of [this](https://github.com/status-im/status-mobile/issues/18844), but I haven't resumed my work on that since I think it would be better to wait for your changes to go in. Also, since this is a change that won't affect the user flow, I believe we can wait. Are you making any changes to the way we store things in the database?

**Comment by ilmotta** [comment]
> @ilmotta Thanks for letting me know. On my side too, the fix was not intentional, it was just part of [this](https://github.com/status-im/status-mobile/issues/18844), but I haven't resumed my work on that since I think it would be better to wait for your changes to go in. Also, since this is a change that won't affect the user flow, I believe we can wait. Are you making any changes to the way we store things in the database?

As we talked in private, yes @ajayesivan, lots of changes needed to happen in subs and events to support editing addresses.
