### ISSUE TITLE
No verification when creating a new wallet account without a name

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#18877]
# Bug Report

## Problem 

You can `Slide to create account` even without entering a name. Nothing happens after confirming with password/biometric ID.

_Note: can't check on iOS due to https://github.com/status-im/status-mobile/issues/18876_

https://github.com/status-im/status-mobile/assets/67952253/0c8f8b54-f5ad-43ae-8354-56c7a45aa1f2

https://github.com/status-im/status-mobile/assets/67952253/2981f0a7-687c-4e8c-ade2-cef3858f1e76

### Reproduction

1. Open wallet
2. `Add new account` > leave the name field empty >`Slide to create account`

#### Expected behavior
Error is shown (? couldn't find in figma)

#### Actual behavior
Nothing happens

### Additional Information

- Status version: nightly 16/02
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ibrkhalil** [comment]
I made it default to "Account X" where X is the number of the created account.

**Comment by J-Son89** [comment]
@qoqobolo, we are aware of this. The issue is to do with the slider button not being able to be disabled.

I have the issue tracked here:
https://github.com/status-im/status-mobile/issues/18894

Apologies for not communicating that out further. I do think there are some design improvements needed so I will start that discussion now. However I think we can close this issue to avoid duplicated 👍

**Comment by qoqobolo** [comment]
Sure, closing this one in favor of https://github.com/status-im/status-mobile/issues/18894
