### ISSUE TITLE
Store the share all future addresses preference

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#18976]
This is a technical task only.

We should store `Share all future addresses` in the database, so that it's displayed and retrieved when editing permissions.
Some cursory work has been done in the status-go branch `feature/edit-permissions`

**Comment by ilmotta** [comment]
Hey @cammellos, given the priorities, should we park this feature or do you want to finish it up (maybe you went far already)? If we park it, it's important we remember to feature flag the share all addresses toggle in the UI since it's currently dummy and would confuse users. For that I can create an issue to hide the toggle under a flag.
