### ISSUE TITLE
View only channel permission allows to post messages

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#19041]
**Steps:** 

1. Set View only permission to some channel
2. Join community with User A who meets channel requirements
3. See if User A can post messages in channel

**Actual result:** User A can post messages in chat

https://github.com/status-im/status-mobile/assets/97245802/f1430550-02b9-444b-ab8c-f453926a1134

**Expected result:** User A should only have View permissions

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by pavloburykh** [comment]
@jo-mut hello! Have you started working on this issue already? It turned out that this issue is also logged on Desktop side https://github.com/status-im/status-desktop/issues/13792 and I think it will require some changes on go and Desktop. 

cc @cammellos

**Comment by cammellos** [comment]
I think I can take this one @jo-mut , I know already where the issue is

**Comment by jo-mut** [comment]
I was already working on status-go but havent really found out what exactly is the issue. I think the `canPost` function checks if member saitifies the channel permissions and does not limit the user from posting when the channel is view-only even if the user satisfies the view only permissions and is not a poster. Am not sure if thats exactly where the issue is. Its okay @cammellos to work on it as I have not made much progress on the solution

**Comment by pavloburykh** [comment]
fixed by https://github.com/status-im/status-go/pull/4957
