### ISSUE TITLE
Onboarding - Create Profile screen issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19173]
# Design Feedback 2.27

## [Onboarding] Create Profile screen
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=1%3A32044&mode=design&t=OeK3GHXzoVCNnZog-1)

- **Top bar** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:43248&mode=design#711258443)] on scroll should not be opaque but rather have opacity and blur [previously tracked here status-im/status-mobile/issues/17508]
- **Copy update** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727591458)] in the number of characters 24 ➡️ 20
- **Selected color in picker** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727594581)] has a different border than design making it less visible

<img width="500" alt="Screenshot 2024-03-11 alle 15 10 52" src="https://github.com/status-im/status-mobile/assets/122543089/11ed67c7-9590-4035-8058-442e555056bc">

### Reproduction

1. Open Status
2. Select **I'm new to Status**
3. Select **Generate keys**

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Closing because all problems described below are fixed since 2.30.0.

- Top bar [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=103:43248&mode=design#711258443)] on scroll should not be opaque but rather have opacity and blur [previously tracked here
https://github.com/status-im/status-mobile/issues/17508]
- Copy update [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727591458)] in the number of characters 24 ➡️ 20
- Selected color in picker [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=1:32044&mode=design#727594581)] has a different border than design making it less visible
