### ISSUE TITLE
Make status-go upgrades possible without touching react-native-webview-bridge

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#1917]
### User Story

As a developer, I don't want to have to do go to https://github.com/status-im/react-native-webview-bridge and commit an update status-go commit when I should be able to do it directly from status-react. It's also easy to forget and leads to annoying bugs.

### Description

*Type*: Bug/Tooling

### Solution
*Summary*: Turn these two PRs:

- https://github.com/status-im/status-react/pull/1892/files
- https://github.com/status-im/react-native-webview-bridge/commit/354ec944d5f611bc41db5aee94dc795d4b635b0e

into one.

Or, even better, Specify version as ENV variable in a single place.

**Comment by rasom** [comment]
I was trying to use [`Function`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html) interface (by wrapping `Statusgo.CallRPC` call) in order to do this without adding common dependencies between `react-native-webview-bridge` and `react-native-status`. Unfortunately didn't find the way to use java 8 in android's runtime, maybe just haven't put enough efforts..

**Comment by oskarth** [comment]
FWIW Fix in PR (`+`) version doesn't seem to have worked. See https://github.com/status-im/status-react/pull/1914 where before https://github.com/status-im/status-react/pull/1914/commits/f04f69525eb299debc900ba48779b35430ef5bd1 Android specific bug to previous version existed, and stopped existing after. So `+` doesn't appear to have used the latest status-go version we want.
