### ISSUE TITLE
Posts & Attachments - Reply drawer issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#19278]
# Design Feedback 2.27

## [Posts & Attachments] Reply drawer issues
Figma frame of the Review [here](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj/Release-Reviews?type=design&node-id=8%3A140759&mode=design&t=PQCRedZgtXOKGara-1)

- **Identicon ring** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717888062)] shouldn't be visible (issue closed here but not solved: https://github.com/status-im/status-mobile/issues/17510)
- **Contact icon** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717901895)] isn't aligned with name and date in the message preview
- **Reaction button** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#727493300)] should be a square
- **Pressed state** [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717903885)] of the drawer action is wrong

<img width="500" alt="Screenshot 2024-03-15 alle 13 28 28" src="https://github.com/status-im/status-mobile/assets/122543089/bb5c94b4-36d3-4afd-abce-ce11c1743707">

### Reproduction

1. Open a chat
2. Long press on a message to open the reply drawer

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

[comment]: # (Please, add logs/notes if necessary)

**Comment by yqrashawn** [comment]
can't reproduce visible ident ring and unaligned contact icon




![Image](https://github.com/status-im/status-mobile/assets/15090582/23f75ce1-fc1a-4240-b7b4-a3a2703de3e2)

**Comment by yqrashawn** [comment]
before, after
the thinner one is after

reason: 
1. emojis are texts in rn/text, so height should be set with line-height
1. padding in figma is 10, with border as 1, padding should be 9 in mobile

![Image](https://github.com/status-im/status-mobile/assets/15090582/a8f6297f-dd8a-4948-9e85-790e6993124d)

**Comment by yqrashawn** [comment]
- Pressed state [[comment](https://www.figma.com/file/oznddnBnDbLlLQIaACYNuj?node-id=8:140759&mode=design#717903885)] of the drawer action is wrong

for this one, code is using `quo/menu-item` but in figma it's `quo/drawer-action`

**Comment by yqrashawn** [comment]
there are a lot "drawer actions" that haven't been updated to use `quo/drawer-action` yet, since `quo/drawer-action` was implemented 2 weeks ago
actually, there's no `quo/drawer-action` usage in current dev

- status-im.common.mute-drawer.view, using `quo/menu-items`
- quo.components.drawers.action-drawers.view, using a custom implementation
- ...

Figma link for context drawers https://www.figma.com/file/apCsJHT8J58JXbJD2igtbd/Context-Drawers-for-Mobile?type=design&node-id=791-275811&mode=design&t=Bn4gxwEGoqobemgd-0
Figma link for drawer actions https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?type=design&node-id=1931-31188&mode=design&t=vlfhmcKKNvm3E7Vs-4

features in `drawer-action`  but not in `menu-items`
- customization color
- toggle
- ...

@cammellos should we create issues for this?
