### ISSUE TITLE
No colour gradient on the Edit Profile screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#19290]
# Bug Report

## Problem 
[comment]: # (A problem description)
Screen does not contain gradient that we do have in our design [here](https://www.figma.com/file/PiN0uwRgZj4L9U4N7xO7Xb/Profile-for-Mobile?type=design&node-id=4528-314950&mode=design&t=bt15putrCS23o83W-0).

#### Expected behavior
Gradient is added.
<img width="261" alt="Screenshot 2024-03-15 at 21 07 32" src="https://github.com/status-im/status-mobile/assets/147824399/b419e9a0-968c-45bc-b1ef-fa5c4a34cee3">

#### Actual behavior
No gradient.
<img width="211" alt="Screenshot 2024-03-15 at 21 08 05" src="https://github.com/status-im/status-mobile/assets/147824399/8d87b3af-b472-407a-802a-cfd5a40c9d6d">

### Reproduction

1. Install Status app
2. Go through Onboarding and choose color on Create Profile step.
3. Open Profile -> Edit Profile
4. Look at the top of the screen.

### Additional Information

- Status version: nightly 15/03
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@mariia-skrypnyk I'm closing this issue because in Android we disabled blur, which means we can either display solid or translucent backgrounds, but we can't achieve the expected result from this issue. The expected colored background mentioned in the issue description is shown in iOS because the Edit Profile screen is rendered on top of the main Settings screen, with a profile with a magenta accent color.
