### ISSUE TITLE
Special characters entered into Bio field not matching with Desktop

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#19326]
Related to question https://discord.com/channels/624634427930312714/928625369542713396/1207020237304893478

### Steps:
1. Go to profile
2. Edit profile
3. Open bio option
4. Do the following actions:
- Tap enter to start a new line
- Enter dot, comma or other characters

### Actual result:
The 'special characters are not allowed' validation is shown

https://github.com/status-im/status-mobile/assets/52490791/b21f17d9-a22c-4497-ac1f-9ca4931bc3d8

### Note:
Input from the design team is needed about the exact characters allowed to enter into the bio field to match with desktop.

**Comment by ibrkhalil** [comment]
CC: @Francesca-G

**Comment by VolodLytvynenko** [comment]
will be fixed here https://github.com/status-im/status-mobile/pull/19562#issuecomment-2057172060

**Comment by Francesca-G** [comment]
> Input from the design team is needed about the exact characters allowed to enter into the bio field to match with desktop.

As confirmed by Ben [here](https://discord.com/channels/624634427930312714/1026813762910564393/1229461969170468945) we need to update the mobile bio validation to align with desktop, which you can find here on Figma:
[https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/👤-Profile-%7C-Desktop?type=design&node-id=4621-462245&mode=design&t=LG9XSZBvNjtRoNGC-4](https://www.figma.com/file/ibJOTPlNtIxESwS96vJb06/%F0%9F%91%A4-Profile-%7C-Desktop?type=design&node-id=4621-462245&mode=design&t=LG9XSZBvNjtRoNGC-4)

Also, as Ben suggested we should change the validation message to _Standard keyboard characters and emojis only._ since most users won't know what ASCII is

**Comment by ibrkhalil** [comment]
> [#19303] fix: edit profile design feedbacks #19562

Unassigning myself then, I will assign @mohsen-ghafouri
