### ISSUE TITLE
Empty chat view is opened after reopening the app if you close 1-1 chat from the context menu inside the chat

### ISSUE THREAD

**Issue by qoqobolo** [status-im/status-react#19441]
# Bug Report

### Reproduction

1. Open 1-1 chat 
2. Tap three dots at the top right
3. `Close chat` > `Confirm`
4. Kill the app
5. Open the app

https://github.com/status-im/status-mobile/assets/67952253/59f16f8d-02e4-4b85-a7df-4202761f597c

#### Expected behavior
The app opens on the home screen

#### Actual behavior

Empty chat view is opened

### Additional Information

- Status version: RC 2.28 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by qoqobolo** [comment]
cc @Parveshdhull looks like a navigation issue, maybe you'd like to take a look?

**Comment by Parveshdhull** [comment]
Thank you @qoqobolo for pinging me, the issue should be fixed in https://github.com/status-im/status-mobile/pull/19432, as both block and close chat share same logic (removal of chat)

The issue was happening because we were just removing the chat without closing it. So on the reopening of the app, we were opening that unclosed chat, but it didn't exist anymore.
