### ISSUE TITLE
Chat top bar overlaps and stucks midway

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#19639]
### Summary

- [ ] **1. Chat animation gets stuck mid way while opening keyboard or opening chat with few messages**
![CleanShot_2024-04-08_at_22 44 27](https://github.com/status-im/status-mobile/assets/17097240/f1982727-f35b-418d-ac1e-dcb0b874c3d9)

more details https://discord.com/channels/1210237582470807632/1217173160416382986/1227014363081085002

Maybe we can directly animate to final stage instead of interpolate with scroll. (Please discuss with design team)

- [ ]  **2. Chat avatar overlaps chat title**
we have different animations then design for avatar and that's what causing overlap.
In design animation video, top bar stays at same position but in our case its moving down

https://github.com/status-im/status-mobile/assets/17097240/6d2e26b2-28aa-4562-913d-73f7dab28bf6

- [ ] **3. Top bar overlaps chat avatar when composer is opened in empty chat**
(originally report: https://github.com/status-im/status-mobile/pull/19677#pullrequestreview-2005967578)
Note: this issue is related to animation. As it can be seen in below image, chat avatar position is changed without changing its size etc.
more details: https://github.com/status-im/status-mobile/pull/19677#discussion_r1567586011

<div align="center">
<img src="https://github.com/status-im/status-mobile/assets/17097240/a291af91-4236-496e-a425-54eebb7ad213" alt="Screenshot" height="400"/>
</div>

**Comment by Parveshdhull** [comment]
Thank you @BalogunofAfrica for picking this issue 🙏

As this issue is tracking all the bugs with top-bar, I added another bug originally reported in https://github.com/status-im/status-mobile/pull/19677#pullrequestreview-2005967578.
Please feel free to break issue in smaller issues for fixing or skip any of sub issue to be later fixed by someone else.

**Comment by ilmotta** [comment]
Hey @BalogunofAfrica, just checking, are you working on this issue? If not, could you unassign yourself?

Somewhat related, in terms of priorities, we have now to be more judgmental about the value of animations to our users and ignore most animation issues, unless they are really getting in the way of users. Curious @J-Son89 @smohamedjavid does this paragraph more or less reflect how you are prioritizing animations in wallet screens?

This chat header animation in particular is adding unnecessary complexity since most chats in real life will have at least a handful of messages and then the user won't even see/care about the animation because they won't scroll to the top of the message list. If we face more issues with this header we can consider eliminating this animation entirely. I remember one of the designers was keen on this idea (just so we keep in mind this is a possibility, not saying we should do this now of course).

**Comment by ilmotta** [comment]
@Parveshdhull, about issue 1 `Chat animation gets stuck mid way while opening keyboard or opening chat with few messages`, could you verify if the problem is still present after the recent improvements in the composer and simplifications from https://github.com/status-im/status-mobile/pull/21313? 

Problems 2 & 3 are more about aesthetics, not really a functional bug, and for those we are trying to add the label `ui-polish` and avoid the label `bug`. If it wasn't for problem 1 I would remove the label `bug` from this issue. Overall it's better if we create separate issues for each problem.

Thank you!

**Comment by ilmotta** [comment]
@Parveshdhull, could you re-check this issue to see if it's still relevant? The composer was rewritten, the Jump To button feature was disabled, and the chat has been simplified in https://github.com/status-im/status-mobile/pull/21313, all of which might have fixed this issue. Thank you

**Comment by Parveshdhull** [comment]
Thank you @ilmotta for pinging me. We no longer have a dynamic top bar, so this issue is no longer relevant anymore.
