### ISSUE TITLE
Can't pair with dApp on android with WalletConnect

### ISSUE THREAD

**Issue by clauxx** [status-im/status-react#20083]
# Bug Report

## Problem 
Pairing seems to work fine on iOS but it's unresponsive on Android. When pairing, the 'session_proposal' event is never fired.

Potentially related: https://github.com/WalletConnect/walletconnect-monorepo/issues/4468

#### Expected behavior
 'session_proposal' event is fired when pairing to dApp

#### Actual behavior
 'session_proposal' event is never fired

### Reproduction

1. Connect on https://react-app.walletconnect.com (whatever network)
2. Copy the url
3. Login in the status app
4. Make sure WalletConnect was initialized
5. Run the `:wallet-connect/pair` with the copied url

### Additional Information

- Status version: nightly 
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

**Comment by alwx** [comment]
Seems like the issue is in the current version of WalletConnect because it works fine with this one: https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet_068_5 (which uses the older version of `@walletconnect/web3wallet` `1.8.8` and older version of `react-native` as well) 

However, this one doesn't work:
https://github.com/WalletConnect/react-native-examples/tree/main/wallets/rn_cli_wallet

It shows the popup and expects the pairing to be established but it never happens.
<img width="381" alt="Screenshot 2024-05-28 at 16 00 09" src="https://github.com/status-im/status-mobile/assets/911127/08f2a6cc-523e-4ad3-80ab-5bb6b9d9285c">

**Comment by alwx** [comment]
Reported the issue here: https://github.com/WalletConnect/walletconnect-monorepo/issues/4468

**Comment by clauxx** [comment]
Thank you @alwx! We'll see if we get a response till next week, otherwise we'll have to contact them directly.

**Comment by clauxx** [comment]
@alwx any updates on this?
