### ISSUE TITLE
White panel is shown in dark mode on Android

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20114]
# Bug Report

## Problem 
This issue occurs immediately after creating a profile in dark mode on Android (Google Pixel 7A). I haven't found a workaround, so it almost always shows up. The issue disappears if you switch to another tab but reappears whenever you open any bottom sheet.

#### Expected behavior
no white system panel on dark mode

#### Actual behavior

https://github.com/status-im/status-mobile/assets/4557972/8c8f5def-08cf-49a7-b30f-4ee8b98a755c

### Reproduction

1. It shows just after login to the app
2. It re-appears after opening any bottom sheet

### Additional Information

- Status version: nightly 20/05/24
- Operating System: Android (Google pixel 7A)

[comment]: # (Please, add logs/notes if necessary)
Consider it as must fix for release as it is very visible and easily reproducible on our testing devices.

**Comment by Parveshdhull** [comment]
Hi @churik, Thank you very much for creating this issue.
Please can you confirm if this issue only happens in PR builds (with testnet banner) or also in nightly?

Also, As we want to include this in 2.29, I am removing my assignment for time being because I am busy with jump-to and bridge messages PR.
If no one will pick this issue, I can work on it once those PRs are merged.

**Comment by churik** [comment]
@Parveshdhull @jo-mut it appears on the nightly too once you open any bottom sheet and after this it is always there until you switch the tab. 

https://github.com/status-im/status-mobile/assets/4557972/2b9f51e1-b2cf-4c02-b6ba-8e92c0c17637
