### ISSUE TITLE
Make sure user profile is setup correctly after migrating from v1 -> v2

### ISSUE THREAD

**Issue by cammellos** [status-im/status-react#20203]
As part of making sure the migration from v1 -> v2 is successful, we should make sure the user profile is setup correctly and the user is able to login into the app.

There's a few changes that have been made:

- display name is in v1
- accent color is in v1

Display name could be migrated from the previous 3 words random name, so users will see some continuity.

For this task we should build on top of @qfrank work and make sure that the user can login and the UI works ok (i.e doesn't throw any error etc).

**Comment by ilmotta** [comment]
### Update

Using the PR build https://github.com/status-im/status-mobile/pull/20151, a v1 user (Alice) can successfully login and the app works well at a glance. The v1 user was created using PR build https://github.com/status-im/status-mobile/pull/20123.

1. Alice had 2 separate profiles on v1 and each had one friend accepted as a CR.
2. After installing the newest version of Status, she could see the 2 profiles she had with their 3-word names.
3. She could login successfully on both profiles.

**Problems**

- When going to `Settings > Edit Profile > Name`, the input field is blank, thus not using the 3-word name.
- When Alice opens a chat with one of her friends, her name appears on each message as her public key.
- When Alice edits her profile name, then chats show her display name correctly and not her public key.

**Unrelated bug**:

- After editing a profile name, the `Settings` screen avatar initials are outdated and will only display the new initials if the user closes and opens the `Settings` screen.

**Untested**:

- ENS names from v1 to v2.

**Next steps**:

- Fix the problems identified. They seem to be client-only problems because the 3-word names did flow and were displayed correctly in a few places, just not all.
