### ISSUE TITLE
Text formatting issue if emoji message edited on desktop

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#20352]
# Bug Report

## Problem 
If a message containing only emojis was sent from desktop and edited after that, it's not properly formatted on mobile

#### Actual behavior
Message after edit is shown with  bold upper case
iOS:

https://github.com/status-im/status-mobile/assets/29711298/9c007d1a-2e22-4678-8667-cbef696e1d65

On Android it's also transparent:

https://github.com/status-im/status-mobile/assets/29711298/2cb93e36-4dc8-46f5-8d8e-2771da441372

### Reproduction

1. Create 1-1 chat: desktop user and mobile user
2. Desktop user sends a message - it should be only emojis, without text
3. Desktop user edits this message adding some text
4. Mobile user checks the updated message on mobile 

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Hey @jo-mut: if I'm interpreting things correctly, according to your comment in https://github.com/status-im/status-mobile/pull/20461#issuecomment-2192059789, can we close this issue since the problem originates from status-desktop and they will fix it in issue https://github.com/status-im/status-desktop/issues/15348?

**Comment by jo-mut** [comment]
yeah we could close this, it will be fixed on desktop
