### ISSUE TITLE
[IOS] App crashes or experiences low performance after opening dynamic collectibles

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#20466]
### Steps:
1. add watch only accounts `0x8d2413447ff297d30bdc475f6d5cb00254685aae`, `0x00000000219ab540356cbb839cbe05303d7705fa`, `0x8d51191dd7e371bd88ab9797b11b03da3084de6e`
3. Open  "collectibles" tab to see all collectibles available for all added addresses
4. Scroll through until some dynamic collectibles appear 
5. Open and close a few dynamic collectibles
6. Check app performance

### Actual result:
App crashes or experiences low performance 

https://github.com/status-im/status-mobile/assets/52490791/6be8c721-1ac9-4a4d-8f4e-37ed09ab1afd

### Expected result:
App is not crashed; performance is stable

### Device:
iPhone 11 Pro max, IOS 17

### Logs:
[logs (4).zip](https://github.com/user-attachments/files/15838682/logs.4.zip)

**Comment by smohamedjavid** [comment]
For the time being, let's drop the support for GIFs as we agreed earlier and support only static images/file types.

The crash is due to bloated memory consumption due to dynamic file types (such as GIF) in the list that result in low FPS.

On later releases, we can add a preview like getting the first frame of a GIF (or any dynamic file type) and displaying it in the list and then on the details page, we can display it with no limitation.
