### ISSUE TITLE
ENS name not applied after local pairing the account from status-desktop

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-react#20511]
# Problem

I use `sirotin.eth` ENS name with my account in status-desktop. I used local pairing to pair this account with mobile app. 

After pairing, my display name on mobile is `sirotin.eth`. But
- the identicon ring is there
- I'm able to edit the display name, as it wouldn't be an ENS name

![IMG_3721](https://github.com/status-im/status-mobile/assets/25482501/0307cc59-7a36-4eda-9892-517b38401639)

But I see that there is ENS support in general. `ducheng.eth` doesn't have an identicon ring:
![IMG_3724](https://github.com/status-im/status-mobile/assets/25482501/6d76669d-7f3d-4c41-9cf0-aec3330ba10d)

# App info

App version: `2.29.20425 (20240617141826)`
App commit: c20a2da267973f7403655fe4524dfc9bd4a8fbcd
Node version: `StatusIM/v0.180.30/ios-arm64/go1.21.8`

**Comment by churik** [comment]
I'm adding it to 2.30, would be nice to fix it, as I see from the channels that users do use ENS names and the only way to set it fro mobile is actually through sync in desktop or after upgrade from v1. 
So basically every user with ENS will see this behavior.

cc @ilmotta

**Comment by ilmotta** [comment]
That's correct @churik, we haven't implemented ENS registration and name management, so ENS is only available through syncing from desktop. I take the important bug to fix from this issue is to disable users from editing their names when it's an ENS, is that correct? The other bug about the ring is harmless for 2.30 and seems fine to ignore in case no mobile dev can fix this in time.

**Comment by churik** [comment]
yes, agreed! Thank you!

**Comment by churik** [comment]
postponed due to limited capacity for 2.30
