### ISSUE TITLE
Community channel members' list buggy scroll behavior

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20514]
# Bug Report

## Problem
Cross-referencing with [this GitHub issue](https://github.com/status-im/status-mobile/issues/20465).

Scroll functionality is excessively long compared to the actual list length.

The other problem we see in the video about empty avatars and missing names is tracked in this other issue https://github.com/status-im/status-mobile/issues/20520.

### Expected Behavior

Users should be able to scroll correctly and efficiently throughout the entire member list.

### Actual Behavior

https://github.com/status-im/status-mobile/assets/4557972/37d8daa5-db87-49fc-87db-1ec1bf61174c

### Reproduction
1. Open Status community > Channel > list.

### Additional Information
- Status version: nightly
- Operating System: Android, iOS

**Comment by churik** [comment]
Not an issue for desktop.

**Comment by ilmotta** [comment]
Thank you for reporting @churik. I assigned myself and I'll be focusing first on the bug that I think is the most problematic one, that is, the entire scroll behavior of the member list is broken and quite frustrating to a user. Tomorrow I'll open a PR with the fix.

For the part about displaying empty avatars and empty names I'll investigate separately and get in touch with designers. Ideally this would be a separate a GH issue because this bug is unrelated to scrolling.

**Comment by churik** [comment]
yes, sure - we can reopen new just with handling these empty names. Thank you for input, @ilmotta !

**Comment by ilmotta** [comment]
FYI @churik, I split this issue in two and updated the title and description to match. The other issue about missing avatars and names I linked is this one https://github.com/status-im/status-mobile/issues/20520
