### ISSUE TITLE
{"token": , "chainId"} error on attempt to find some routes

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20899]
# Bug Report
Follow up on https://github.com/status-im/status-mobile/pull/20631

## Problem 
Appeared in the last round of testing https://github.com/status-im/status-mobile/pull/20631#issuecomment-2252377138

On desktop seems there is no error, just "No routes found"

#### Actual behavior
![image](https://github.com/user-attachments/assets/adba0d65-e895-4312-ab77-0718e518edce)

video: 

https://github.com/user-attachments/assets/9d75af98-7d45-417a-87d1-8f36a1d3c870

### Reproduction
In my case, it was an attempt to test fix https://github.com/status-im/status-mobile/pull/20631#issuecomment-2223562369, but seems might just appear in different cases

### Steps:
1. Recover user with available assets on the arb L2 network
2. Attempt to build routes using value input for route building (example: 0.008 eth):
L2 arb  -> L1

### Additional Information

- Status version: roter v2 integration, nightly 27/07 
- Operating System: Android, iOS

Logs: [logs (102).zip](https://github.com/user-attachments/files/16390426/logs.102.zip)

**Comment by VolodLytvynenko** [comment]
in my case, this issue is reproducible in the following steps:

### Steps:
1. Restore the user with available assets except ETH
2. Go to the routes generation page
3. Enter a valid amount

### Actual result:
The error notification is shown

https://github.com/user-attachments/assets/534b5ffa-aec1-4f08-a920-61a28509abf1


### Expected result:
The error notification is not shown


### Logs:
[Status-debug-logs (1).zip](https://github.com/user-attachments/files/16393636/Status-debug-logs.1.zip)

**Comment by VolodLytvynenko** [comment]
This issue is resolved in the new simplification flow https://github.com/status-im/status-mobile/pull/21595
