### ISSUE TITLE
When bridging from mainnet > L2, there are no both `Approve` and `Send` tx

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20923]
# Bug Report

## Problem 
Or there is only `Approve`.

Examples: 
1)  bridge 0.1 Dai Mainnet -> Arbitrum: only `Approve` appeared, send didn't happen
https://etherscan.io/tx/0x1978e325d00889b8d13da43f3a6a596090d5f9bcf31ceaa4200787031182f9b3

2) bridge 10 USDc Mainnet -> Arbitrum: only `Send` happened
https://etherscan.io/tx/0x6e23d44a85bb8f283e02a3c8906fd120c4b12cd27641ecd29ccc858d7b54a6d0 

#### Expected behavior
`Approve` and `Send` (see optimizm for particular account https://optimistic.etherscan.io/address/0xcf2272205cc0cf96cfbb9dd740bd681d1e86901e)

### Reproduction

1. Try to bridge something from Mainnet to Arbitrum

### Additional Information

- Status version: nightly 30/07/
- Operating System: Android, iOS

Logs: [logs (104).zip](https://github.com/user-attachments/files/16428716/logs.104.zip)

**Comment by churik** [comment]
context for testing: 
- DAI contract https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#readContract
- In the read, you can see allowance
The mechanism is as follow: in order for another contract to transfer your token, there is 2 guards:

1 - you are executing the transaction yourself
2 - the contract has allowance

In case of bridge, we say:
call bridge contract and transfer X of my token to hop contract

Before calling the bridge contract, we then need to make approval transaction for hop contract to spend X token.

When testing bridge with DAI:
1 - check the allowance
If < amount to send:
We should send 2 transactions to the blockchain
Approve
Bridge
if > amount to send:
We will send only the bridge transaction

**Comment by briansztamfater** [comment]
It is weird that this only happen for Mainnet to L2 transactions, the logic for building transactions is the same. Have you checked if the same happen on desktop?

**Comment by churik** [comment]
@briansztamfater no we didn't. where we should verify that? (I mean branch or builds)

**Comment by briansztamfater** [comment]
@churik I think status-desktop develop is fine, as long it is stable. If we can verify if this is also happening on desktop, probably we can discard whether it is a status-go bug or mobile bug, and find the root cause easier.

**Comment by churik** [comment]
I tried to do the same on status desktop RC3, I got only `Send to L2` tx without approve:

https://etherscan.io/tx/0xa027364f9d0e4e8d1c098fd57582f162936be1e59eba3a65f8ad01623aa854b1

and I already have approval from a previous attempt from the same account (I used it on mobile)
Either way, if we should have 2 txs - 1 `Approve` and one `Send` - it is not working this way for the desktop while we're bridging from mainnet
<img width="284" alt="Status Desktop 2024-07-31 11-59-41" src="https://github.com/user-attachments/assets/55152377-5225-49a9-b073-485cd0c9c6af">

[geth.log](https://github.com/user-attachments/files/16440544/geth.log)

I guess it is worth to ask @saledjenic or @alaibe

**Comment by saledjenic** [comment]
@churik correct, if you already have an approval, we use it, no need to place another approval tx in that case.

**Comment by churik** [comment]
@briansztamfater @vkjr 

the same happened to USDt - only approve, no send

https://etherscan.io/tx/0x0544aee6285928c207965cd7c1acf8f7daae1eca61a9d63a70d936fb82dff66b

**Comment by briansztamfater** [comment]
@churik @VolodLytvynenko @vkjr 

I think I could reproduce the issue on desktop from my account.

Steps:
1) Got 13 USDT on Mainnet
2) Bridge 11 USDT on Status Desktop 2.30.rc2 from Mainnet > Optimism
3) Confirm transaction
4) Only this transaction appears on Etherscan (https://etherscan.io/tx/0x3829e8edfe0a4103f4cb868f97f1af2c16a9ae73670b1e6610e5f23e7ee1bab9), I am not sure why the tx is not verified and therefore it is shown like 
`Call 0x095ea7b3 Method by 0x4eeB09cf...48efD4305 on 0xFd086bC7...0b69FCbb9`. But `0x095ea7b3` is the approve call (see the screenshot attached).
5) No other transaction is sent after that, tokens stay on the same network

![](https://github.com/user-attachments/assets/4c6f1868-d61b-4b83-9d15-c58ee900b366)


If I retry the operation manually, it executes Send to L2 function (that is correct because allowance is not required due to the previous Approval transaction), but it fails with error `Fail with error 'SafeERC20: low-level call failed'` https://etherscan.io/tx/0x74aeba8534fdb8ccbf3050450d6b2695eba1e3c468f6066005be8c52eedafa5e

In mobile, the approve transaction is actually shown as Approve: https://etherscan.io/tx/0xb38bfbd35fc08713fea0e7032fb3d812255eb97a96d8b11a770315cf3ae3fa09
And the second try succeeds: https://etherscan.io/tx/0x968de054f319fcfec3cbbade29e36d2d4948e78aec2598d30342c6b0af39b5b1


So, to sum up:
- When trying to bridge a token from L1 to L2, there is an issue that makes `Send to L2` function to not be called if tx is chained with an Approve transaction. I was able to reproduce it on both mobile and desktop, so it seems like a status-go bug.
- When executing a bridge transaction on desktop that requires approval, Approve transactions don't show on Etherscan as `Approve`, instead it shows as `Transfer*` or `0x095ea7b3 Method` in the tx detail (https://etherscan.io/tx/0x3829e8edfe0a4103f4cb868f97f1af2c16a9ae73670b1e6610e5f23e7ee1bab9). This doesn't happen when trying from mobile (https://etherscan.io/tx/0xb38bfbd35fc08713fea0e7032fb3d812255eb97a96d8b11a770315cf3ae3fa09), so it seems like a desktop issue, probably on how you are encoding the function (we are using `encodeFunctionCall` from status-go and desktop seems to use their own encoding function).
- When retrying the call on desktop, `Send to L2` transaction fails with error `Fail with error 'SafeERC20: low-level call failed'` (https://etherscan.io/tx/0x74aeba8534fdb8ccbf3050450d6b2695eba1e3c468f6066005be8c52eedafa5e). On mobile, the transaction succeeds (https://etherscan.io/tx/0x968de054f319fcfec3cbbade29e36d2d4948e78aec2598d30342c6b0af39b5b1).
- L2 to L2 seems to work fine on mobile

**Comment by vkjr** [comment]
@briansztamfater @churik @VolodLytvynenko @J-Son89 
So it looks like the problem should be fixed on `status-go` side. Should we delist it from the current mobile milestone and create github issue in `status-go` repo?

**Comment by briansztamfater** [comment]
Maybe @alaibe or @saledjenic could help to detect the issue in status-go side? You can see comments above for more context 👆

**Comment by saledjenic** [comment]
@churik @briansztamfater just to give you a brief context about it... when we want to bridge, that's possible only between different chains, and that's not a direct tx, but instead we're using Hop service to achieve that. That further means that our bridge tx is composed of 2 txs:
1. approve
2. bridge
in some cases if there is already an allowance for the amount you want to send, the first, approve, tx can be avoided (our algorithm checks that), in that case we only do the second tx, which is bridge.

Now there are 6 different bridging based on chains:
- mainnet -> opt
- mainnet -> arb
- opt -> mainnet
- opt -> arb
- arb -> mainnet
- arb -> opt

And as @briansztamfater said in one of above comments, the code is the same for each of them, so theoretically should not be any differences and if one work all should work, ofc if Hop contracts are correct (which is the case).

But... what I noticed is that some networks, like arbitrum doesn't take pending tx into consideration when the app asks for the next Nonce. And what happens then, we always place approve tx first and immediately after it we place bridge tx, assuming that the approve tx will have Nonce X and bridge Nonce X+1, and that's the case for optimism and it works fine there. But on arbitrum for both tx X is returned as Nonce and that's why if an approval needs to be placed, bridge tx always fails. But in the next try (with the same or less amount), since approval is still active and you try the same bridge again, we don't need to place an approval tx, but just a bridge tx, it gets placed well.

So I would say that's the issue, but we need to figure out how to fix it.
Some proposals can be:
1. amend the design and have an explicit Approve button and don't let user to press Bridge button (keep it disabled) till an approval is fully executed
2. have just Bridge button on UI, but update the statusgo side to listen for approval execution then automatically place bridge tx

But that's not small change, we need to consider this with @alaibe and other relevant people.

**Comment by alaibe** [comment]
@saledjenic as we trigger both tx at the same time, can we build the second tx with approve nonce +1 ?

**Comment by saledjenic** [comment]
> @saledjenic as we trigger both tx at the same time, can we build the second tx with approve nonce +1 ?

@alaibe we can try that and see, it should work as long as the first one from some reason fails and then the second one will be stucked, maybe better to implement that once we introduce "cancel tx" feature?

**Comment by briansztamfater** [comment]
> > @saledjenic as we trigger both tx at the same time, can we build the second tx with approve nonce +1 ?
> 
> @alaibe we can try that and see, it should work as long as the first one from some reason fails and then the second one will be stucked, maybe better to implement that once we introduce "cancel tx" feature?

I would vote for add the nonce and nonce+1 if that makes sure bridge is working as expected. If we calculate gasLimit correctly is unlikely Approve transaction will fail. We can prioritize cancel tx for the next iteration. cc @alaibe @saledjenic @churik @J-Son89

**Comment by saledjenic** [comment]
@briansztamfater @J-Son89 @churik the issue with failing tx if more than one tx was placed (bridge with approval, or multi tx) should be fixed by this PR https://github.com/status-im/status-go/pull/5658

**Comment by J-Son89** [comment]
@saledjenic is there some changes on client side to do?
cc @vkjr, @smohamedjavid or @briansztamfater - can one of you work with @saledjenic to integrate any changes if needed?

**Comment by saledjenic** [comment]
If that was previously implemented well, in a way that you're calling `wallet_createMultiTransaction` with proper parameters received as the best router, then no changes are needed on the client side.

**Comment by churik** [comment]
we'll recheck it one more time with the last updates in release, for now due to time/resource constraints, I don't think that we can fix it 2.30.

Deferred;

**Comment by churik** [comment]
seems not the case anymore, can see both 
![image](https://github.com/user-attachments/assets/5d7eba6f-2ab4-4580-98c0-079106c5c74c)


https://etherscan.io/tx/0x42ad2724a534801aa7667d2a9373deef638f99ab4afeaae4bcc2a54fea8a9aa6
https://etherscan.io/tx/0x71d6529e602cf628f330f5802964ead8059b192877365d75d8e9b7f0159aefe2
