### ISSUE TITLE
Router is detecting more assets on account that is really available

### ISSUE THREAD

**Issue by churik** [status-im/status-react#20967]
# Bug Report

## Problem 
I have 4 DAI (3.4 DAI on Optimizm, 1 on ARB) and for some reason I was able to send [tx](https://optimistic.etherscan.io/tx/0x612b27e3de622aeb7538e24e8245dea22644227df87e4cf76b67ce36f63d0553) from wallet bridging 4 DAI on Optimizm (that I do not have) to Mainnet

#### Expected behavior
routes not found

#### Actual behavior
https://github.com/user-attachments/assets/4c2999fc-020b-44e4-8ae4-3badef36220a

### Reproduction

1. Try to send more assets that available in 1 network (bridge flow) 

### Additional Information

- Status version: release 2.30
- Operating System: Android, iOS
- logs: [logs (109).zip](https://github.com/user-attachments/files/16514497/logs.109.zip)

[comment]: # (Please, add logs/notes if necessary)

**Comment by J-Son89** [comment]
it's weird that it is finding the route?
We could block this on the front end by making the max-value the highest amount on **one** network.
e.g in the video the max amount would be 3.41 because that is the highest of the two possible networks to bridge from.

**Comment by briansztamfater** [comment]
This is weird. If route is being found, probably is a routing bug in status-go side 🤔

**Comment by churik** [comment]
Due to time constraints, I'll exclude this one from 2.30. 

Still worth looking if there is a capacity. 

It looks like a bug on the routing side in the balance detection (maybe rounding?).

**Comment by qfrank** [comment]
Feel free to handle this one if you have time. I have a higher-priority issue to deal with. I will take it back if nobody handles it then.

**Comment by shivekkhurana** [comment]
@qfrank Is there investigation needed on this issue or have you identified the bug ?

**Comment by qfrank** [comment]
> @qfrank Is there investigation needed on this issue or have you identified the bug ?

probably need adding validation(check balance) within this [function](https://github.com/status-im/status-go/blob/bb6d5f602b8e472cc7257b650e0c771a82ec4714/services/wallet/router/router_v2.go#L1044), not sure yet, need more investigation to confirm, most relate functions are written by @saledjenic , he would be the best person to add it quickly if he have time @shivekkhurana

**Comment by shivekkhurana** [comment]
This is for 2.31, so we have time. We are not fixing this for 2.30.

**Comment by saledjenic** [comment]
@churik @qfrank this is really weird that the Router is detecting more than you really have. Would like if you can provide the steps for reproducing this in the desktop app?

If I remember well the mobile app won't include bridging in sending transactions for 2.30, right?
But the attached video is displaying that you're sending from optimism to mainnet, which is perfectly fine from the router perspective, that's why I assume that the client side has some bugs.

----

Based on the attached video and the router's perspective it is:
- you have 3.4 DAI on opt, 1 DAI on arb
- you are trying to send 4 DAI to Mainned (while you haven't selected "from" networks)
- than the router will try to:
  - either take all (3.4) from optimism and bridge to mainnet and take the rest (0.6) from arbitrum and bridge to mainnet
  - or take all (1) from arbitrum and bridge to mainnet and take the rest (3) from optimism and bridge to mainnet
- if there are no approvals you should give them and after sending balance should be on the same account on mainnet

any of those 2 scenarios is possible and the router supports them. It's up to a client to constraint the router and tells it what and how to do, like under which limitations to try to find the best route.

----

What you need to ensure in the mobile app, if the mobile app doesn't support multi-chain sending, is:
- if the user tries to send from mainnet to mainnet the router has to receive `disabledFromChainIDs = [10, 42161]` and `disabledToChainIDs = [10, 42161]` input params
- if the user tries to send from optimism to optimism the router has to receive `disabledFromChainIDs = [1, 42161]` and `disabledToChainIDs = [1, 42161]` input params
- if the user tries to send from arbitrum to arbitrum the router has to receive `disabledFromChainIDs = [1, 10]` and `disabledToChainIDs = [1, 10]` input params

and ofc does necessary UI constraints based on that.

**Comment by qfrank** [comment]
I'm unable to reproduce this issue as I got another issue when use bridge, I have 0.11 ETH(0.1 on OP and 0.01 on ARB) , I can't bridge 0.0006 
![IMG_6145](https://github.com/user-attachments/assets/fca6bb97-2477-4f15-993c-814b547ea5d5) @saledjenic

**Comment by saledjenic** [comment]
@qfrank the bridge doesn't work in the testnet mode, and another problem can be that you're trying to bridge a too low value.

**Comment by qfrank** [comment]
I also tried 0.06 , same result.

are you sure bridge doesn't work in the testnet mode? we intend to not support in the testnet mode? @saledjenic

**Comment by saledjenic** [comment]
> are you sure bridge doesn't work in the testnet mode?

yes

> we intend to not support in the testnet mode?

we should, but we don't yet, cause no corresponding hop contracts deployed for testnet mode

**Comment by qfrank** [comment]
As stated in the [comment](https://github.com/status-im/status-mobile/issues/20967#issuecomment-2295370768), the client should obtain more than one result(Best/Candidates). However, as the video demonstrates, one of the routes is sending 4DAI (but max 3.4 on OP in actual) from OP to the mainnet. This reveals that status-go must have a bug regardless of whether the client supports multi-chain sending. It can be assumed that the client passed nil/null for `disabledFromChainIDs` 

and I had some logs related to the params client passed, e.g. 
```
[{:disabledFromChainIDs nil, :sendType 5, :tokenID ETH, :packID nil, :disabledToChainIDs (10 42161), :amountIn 0x1ff973cafa8000, :toTokenID , :username nil, :gasFeeMode 1, :fromLockedAmount {}, :publicKey nil, :addrFrom 0xab924e0dc7f81ad4697eb44230cb002275cef66a, :amountOut 0x0, :uuid 5b359a91-aac9-4989-aab7-cd93fef101ad, :addrTo 0x22a9212fee05135614c98e102d4cc1d0a2fd7048}]
```

@saledjenic

**Comment by saledjenic** [comment]
> The [line](https://github.com/status-im/status-react/blob/6a5e718cd389f61d3708c4372856609afb40d11f/src/status_im/contexts/wallet/send/events.cljs#L534) indicates that the client only selects the first route.

@qfrank the best route should be used always, never the first route, cause in case of multiple routes available the first one may not be the best one.

I see `disabledToChainIDs (10 42161)` which is ok, means mainnet is selected, but if you were trying to send from mainnet to mainnet, then `disabledFromChainIDs` should look the same, and should not be empty.

> This reveals that status-go must have a bug regardless of whether the client supports multi-chain sending. It can be assumed that the client passed nil/null for disabledFromChainIDs

The router supports multi-chain routing, but you have to say what you really want. I don't see any issue in router, it's all about how you use it. Please add `disabledFromChainIDs (10 42161)` and ask for the route and you will see.

**Comment by qfrank** [comment]
If client wants to get these results:
```
either take all (3.4) from optimism and bridge to mainnet and take the rest (0.6) from arbitrum and bridge to mainnet
or take all (1) from arbitrum and bridge to mainnet and take the rest (3) from optimism and bridge to mainnet
```
shouldn't client pass `disabledFromChainIDs` to empty array? @saledjenic

**Comment by saledjenic** [comment]
@qfrank if client wants that, then yes, it should pass empty `disabledFromChainIDs` and the router will find the best for you, but in your case you don't want that. Cause mobile app doesn't support multi-chain transactions for 2.30. By setting `disabledFromChainIDs` to `(10 42161)` you're constraining the router to search for the best route among routes that are generated within the same chain only.

It means if you have no balance on mainnet and you ask for route on mainnet you will get an error saying not enough balance.

**Comment by qfrank** [comment]
> I don't see any issue with router, it's all about how you use it

I won't investigate more if there's no issue with status-go side. However, I remain skeptical 🧐.

**Comment by alaibe** [comment]
Hey, would it be possible to get the input / output of that specific call? This would really help understand and potentially fix the issue?
