### ISSUE TITLE
App crashes after attempt to send collectible #20850

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21061]
### Steps:
1. Go to send a flow of any collectible
2. Confirm collectible sending

### Actual result:
The app crashed after going to a transaction confirmation page

https://github.com/user-attachments/assets/7873d870-96f8-4b3f-bea8-c5d95afa51df

### Expected result:
The collectible is sent (this flow works correctly on the desktop)

### Logs:
[crash.txt](https://github.com/user-attachments/files/16625946/crash.txt)

### ENV:
Nightly 15 Aug

**Comment by churik** [comment]
the issue is not reproducible on release 2.30, so it is likely some recent regression

**Comment by qfrank** [comment]
this crash is introduced by recent status-go [commit](4a78d7c1e92efad62b627dbde45a2bec660a5528) ,commit date: 12/8/2024 

could you help fix it? @saledjenic 

root cause [line](https://github.com/status-im/status-go/blob/4a78d7c1e92efad62b627dbde45a2bec660a5528/services/wallet/router/router_v2.go#L557)

**Comment by saledjenic** [comment]
@qfrank could you please check if this PR https://github.com/status-im/status-go/pull/5736 fixes the crash you are talking about?

**Comment by qfrank** [comment]
> @qfrank could you please check if this PR [status-im/status-go#5736](https://github.com/status-im/status-go/pull/5736) fixes the crash you are talking about?

I'll help creating a mobile PR to check, but I doubt it will fix the panic ... as the root cause line is explict that I mentioned [here](https://github.com/status-im/status-mobile/issues/21061#issuecomment-2293118143):

```
if token == nil {
	chainError(chain.ChainID, token.Symbol, ErrTokenNotFound)
	continue
}
```

`token` is nil, and it's still trying to access `token.Symbol` , I don't see relate modification on this in PR 5736 @saledjenic

**Comment by saledjenic** [comment]
@qfrank I added a new single line commit to that PR, to handle that crash.

**Comment by qfrank** [comment]
> @qfrank I added a new single line commit to that PR, to handle that crash.

relate mobile [PR](https://github.com/status-im/status-mobile/pull/21077) created @saledjenic
