### ISSUE TITLE
[iOS] Not visible status bar on light theme

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21101]
# Bug Report

#### Actual behavior

<img width="274" alt="Screenshot 2024-08-21 at 13 05 39" src="https://github.com/user-attachments/assets/17206c9f-ff09-4865-87e4-610a3033522d">

#### Expected behavior

<img width="262" alt="Screenshot 2024-08-21 at 13 06 16" src="https://github.com/user-attachments/assets/6699297f-2fca-476b-9b10-93b825741ef1">

### Reproduction

1. Login to app 

### Additional Information

- Status version: release 2.30
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
Just checked in iOS in a release build and the bug indeed exists. I think this is an important one to fix for the release. Probably a very recent regression.

@Parveshdhull do you happen to have any idea why this problem is happening? Could you take a look for us? 🙏🏼

**Comment by ilmotta** [comment]
The bug exists in Android too.

**Comment by Parveshdhull** [comment]
https://github.com/status-im/status-mobile/blob/32ddf81a5e3eaaffbd46f5b10b03ce9d48cfff71/src/status_im/navigation/effects.cljs#L72-L77

We update the right theme for root in line 77, but its too late and root at line 72 has wrong value.

1. Solution One: Always manually call :theme/switch before :init-root at all places.
2. Solution Two: Instead of init-root have an event :update-theme-and-init-root. And in this even first we dispatch theme change, then init-root

cc @ilmotta @flexsurfer
