### ISSUE TITLE
Onboarding - Share usage data drawer issues

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21186]
# Design Feedback 2.30

## [Onboarding] **Share usage data** drawer issues

- **Subtitle** [[1](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#934538164)] has an incorrect color
- **Font weight** [[2](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2249-7147#937806404)] of the Privacy Policy link is wrong

#### Expected behavior

<img width="175" alt="Screenshot 2024-09-06 alle 10 40 27" src="https://github.com/user-attachments/assets/e9d559f9-ffc8-46ff-abc0-5d5a8cfc7c79">

#### Actual behavior

<img width="190" alt="Screenshot 2024-09-06 alle 10 41 06" src="https://github.com/user-attachments/assets/74f66294-903a-4242-b139-38ca53922029">

### Reproduction

1. Create a profile in the Onboarding flow

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

**Comment by ilmotta** [comment]
I'm closing this issue because in 2.32 we will rework the usage data flow (related issues under construction) https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=15075-44428&node-type=frame&m=dev

<img src="https://github.com/user-attachments/assets/4206491a-c393-4007-9963-74b681dfdbc1" width="350" />
