### ISSUE TITLE
 "Objects are not valid as a React child" Error Displayed When Attempting to Send Multi-Collectible

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21183]
### Steps:
1. Select a multi-collectible.
2. Go to the sending flow.
3. Proceed with the sending process.

### Actual result:
The error "Objects are not valid as a React child" is displayed  when attempting to send Multi-Collectible

https://github.com/user-attachments/assets/c1b5af1d-b255-4162-ad08-376f64713c53

### Expected result:
The user should be navigated to the multi-collectible sending screen without errors.

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs:
[logs.zip](https://github.com/user-attachments/files/16872873/logs.zip)

### ENV:
Nightly 6 Sep, 2024

**Comment by ulisesmac** [comment]
@smohamedjavid Please add me as a reviewer when the PR is ready, I'd like to know the root cause, I guess it's due to using a component without the hiccup marks or something similar.

**Comment by smohamedjavid** [comment]
Added you as a reviewer @ulisesmac 👍  The bug is caused by the numeric-value method used in the value prop
https://github.com/status-im/status-mobile/blob/cf5a395b291fd218f6ec6b3b5b19ad97dc2c2087/src/status_im/contexts/wallet/send/select_collectible_amount/view.cljs#L50 

this expects a number or string value but receives an object (BigNumber object). A regression from https://github.com/status-im/status-mobile/pull/21136.
