### ISSUE TITLE
No currency of the wallet Balance up to 5-7 sec after user is logged in

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21190]
# Bug Report

## Problem 
[comment]: # (A problem description)

User sees just a number without any currency on his wallet and accounts.
It last 5-7 sec and refresh doesn't help.

#### Actual behavior

https://github.com/user-attachments/assets/7e29e65e-f462-4521-8cef-dffc5f06910b

[logs_currency.zip](https://github.com/user-attachments/files/16905958/logs_currency.zip)

#### Expected behavior

Currency is always visible

### Reproduction

1. Login to app with a user that has balance.
2. Open wallet and look on your amount.

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by smohamedjavid** [comment]
The currencies list is fetched (via the `settings/get-currencies` event) at the time of login. It looks like the delay is actually due to the messenger RPC, it took 24 seconds to start (possibly due to large amounts of community data)

```javascript
Served wakuext_startMessenger            reqid=1 duration=24.01091225s
```
The events called on the success of the login are phased (1, 2, & 3). The phase 1 starts Messenger and navigates the user from the login screen to the home tabs. The phase 2 & 3 depend on the successful response of starting the messenger in phase 1. The currencies list is fetched in phase 2 but the user gets navigated to home tabs in phase 1. It results in this bad UX.

The actual event `settings/get-currencies` doesn't take more than 0.213 ms as it returns the list without any dependency on the logged-in user's data.

```javascript
Served appgeneral_getCurrencies          reqid=45 duration="213.791µs"
```
I believe it should be fine to move this event along with the wallet initialization as we rely on the list for displaying currency symbols in the UI.

cc @ilmotta

**Comment by ilmotta** [comment]
> I believe it should be fine to move this event along with the wallet initialization as we rely on the list for displaying currency symbols in the UI.

@smohamedjavid, it should be fine 👍🏼 The important thing is that we do what you did and double-check the impact of loading too eagerly during login steps.

> The actual event settings/get-currencies doesn't take more than 0.213 ms

The absolute measurement of 0.213ms, seems pretty low, which is good. Just out of curiosity, did you measure this in a release build and in which device?

**Comment by smohamedjavid** [comment]
> The absolute measurement of 0.213ms, seems pretty low, which is good. Just out of curiosity, did you measure this in a release build and in which device?

It's from the release (nightly) build (the logs posted in this issue description). 

On dev build, it takes slightly longer ~0.23ms.
