### ISSUE TITLE
Missing multi-profile button from the settings

### ISSUE THREAD

**Issue by Francesca-G** [status-im/status-react#21213]
# Design Feedback 2.30

## Missing multi-profile button from the settings
When opening the profile settings there should be 3 buttons on the top right, the multi-profile one is missing. It allows the users to switch and select profiles, which is currently only possible by logging out

Figma frame with the review [here](https://www.figma.com/design/oznddnBnDbLlLQIaACYNuj?node-id=2250-15016#937984419)

#### Expected behavior

<img width="300" alt="Screenshot 2024-09-09 alle 09 25 03" src="https://github.com/user-attachments/assets/78046fa0-4550-4a1a-876c-0a2fcf2f5e25">

#### Actual behavior

<img width="300" alt="Screenshot 2024-09-09 alle 09 26 02" src="https://github.com/user-attachments/assets/96816668-64eb-4406-b2d1-4bbb179ca3ba">

### Reproduction

1. Open profile settings

### Additional Information

- Operating System: Android, iOS
- Devices in the screenshots: iPhone 13

**Comment by Demjoo** [comment]
Hi, I would like to contribute to this project by solving this issue. Is it still available?

**Comment by ilmotta** [comment]
@Francesca-G @xAlisher what is the rationale for this feature? I'm calling it a `feature` and not a `bug` because the reported problem is not affecting an existing feature. Features that exist in Figma, but which are not implemented in the source code we don't consider bugs.

How is this new button different from logging out? I'm asking this because I believe switching profiles requires fully logging out.

-----

Edit from my comment:

I remembered now where the flows are defined https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14657-29113&node-type=instance&m=dev

-----

@Demjoo, I'm closing this issue for now. This feature to switch profiles is descoped because we want to keep the existing behavior where a user switches profiles by logging out.
