### ISSUE TITLE
Cannot read properly "toLowerCase of null" error is shown after swap transaction confirmation

### ISSUE THREAD

**Issue by VolodLytvynenko** [status-im/status-react#21406]
### Steps:
1. Go to swap
2. Confirm swap transaction

### Actual result:
 "toLowerCase of null" error is shown after swap transaction confirmation

![Image](https://github.com/user-attachments/assets/210c8167-371e-4655-b41f-cb79df1fa67e)

### Expected result:
The swap transaction is confirmed without error

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[logs (2).zip](https://github.com/user-attachments/files/17306524/logs.2.zip)

**Comment by briansztamfater** [comment]
Sorry, seems I introduced this bug on #21395. I can point you into the problem so you can fix it @clauxx

**Comment by briansztamfater** [comment]
The issue is triggered here https://github.com/status-im/status-mobile/blob/5c44cb639912979b3a905ead6e98a9cecb5cb608/src/status_im/contexts/wallet/swap/setup_swap/view.cljs#L101 when swap data is cleared and the sub is recalculated. We should add some checks on the sub and view or provide a default value.

**Comment by clauxx** [comment]
> The issue is triggered here
> 
> [status-mobile/src/status_im/contexts/wallet/swap/setup_swap/view.cljs](https://github.com/status-im/status-mobile/blob/5c44cb639912979b3a905ead6e98a9cecb5cb608/src/status_im/contexts/wallet/swap/setup_swap/view.cljs#L101)
> 
> Line 101 in [5c44cb6](/status-im/status-mobile/commit/5c44cb639912979b3a905ead6e98a9cecb5cb608)
>  asset-to-pay                     (rf/sub [:wallet/token-by-symbol pay-token-symbol]) 
> when swap data is cleared and the sub is recalculated. We should add some checks on the sub and view or provide a default value.

Is the issue is that the data is cleared before the screen is unmounted? I think would be better to make sure that the clearing happens later on, maybe by delaying the clearing. Or just having the clearing be dispatched when the swap screens are unmounted, which would be the best way to cleanup IMO. @briansztamfater wdyt?
