### ISSUE TITLE
[iOS] Back button doesn't work on Backup settings screen

### ISSUE THREAD

**Issue by mariia-skrypnyk** [status-im/status-react#21481]
# Bug Report

## Problem 
[comment]: # (A problem description)

This issue occurs in our legacy settings, which are no longer actively in use. 
While it's still possible to swipe right and exit the screen, the fact that the button is present but not functioning is still a low-priority issue.

### Reproduction

1. Login to app 
2. Turn on mainnet
3. Go to Profile -> Legacy Settings -> Sync Settings -> Backup settings

#### Actual behavior

Back button doesn't work

![Image](https://github.com/user-attachments/assets/d465dc33-76ad-4984-8c8b-7da2adb87b8c)

#### Expected behavior

Back button works and navigate user to the screen from which Profile was opened

### Additional Information

- Status version: nightly 22/10
- Operating System: iOS

[comment]: # (Please, add logs/notes if necessary)

**Comment by ilmotta** [comment]
@mariia-skrypnyk I'm closing this issue as _not planned_ because we should actually finish rewriting the legacy screens and then I'm sure the back button will work. We might achieve this in 2.32.

We can track progress in this issue https://github.com/status-im/status-mobile/issues/21360, which I have tentatively added to 2.32.
