### ISSUE TITLE
Failed to get dapps connection' error and empty dapp list on relogin

### ISSUE THREAD

**Issue by pavloburykh** [status-im/status-react#21530]
I have already reported the issue here https://github.com/status-im/status-mobile/pull/21379#issuecomment-2414176944 and facing it in release now. 

Previously we have already attempted to fix the issue by https://github.com/status-im/status-mobile/pull/21350 but looks like it still remains. 

At some point app stops getting connected dapps after relogin. There are no exact steps. At first, dapps are fetched successfully, but after some time the issue occurs. 

**Steps:** 

1. Connect to dapp
2. Perform relogin
3. Observe the error
4. Open dapps list
5. Check if connected dapp is displayed

**Actual result:** 'Failed to get dapps connection' error. Dapps list is empty. 

[Status-debug-logs - 2024-10-30T112931.298.zip](https://github.com/user-attachments/files/17569217/Status-debug-logs.-.2024-10-30T112931.298.zip)

![Image](https://github.com/user-attachments/assets/7987aa34-8857-4b5e-ba11-9522b1afb1b0)

https://github.com/user-attachments/assets/ca15d4bf-53b0-4719-bf53-afabd22818c2

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

**Comment by clauxx** [comment]
@pavloburykh it looks like the session was expired (according to the expiration timestamp `Wed Oct 30 2024 10:15:19 GMT+0000 (GMT)`), so it's not supposed to appear in the dapp list anymore. Found the cause for the error toast though, and it should be an easy fix.  

UX-wise, should we show the user a toast when the session has expired, otherwise sessions just look like they disappeared from the list without explanation?

cc: @shivekkhurana @xAlisher @mohsen-ghafouri
