### ISSUE TITLE
Editing message with image from desktop leads to removing image on mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#21540]
# Bug Report

## Problem 
The issue is not reproducible desktop-desktop.
We removed option to edit messages with image on mobile, but it still exists on desktop and leads to deleting initial pictures and duplicating messages in case message comprised several images. 

#### Expected behavior

can see edited message + pictures

#### Actual behavior

![Image](https://github.com/user-attachments/assets/1138887d-1c09-4e83-8c23-74d4b72d4bcb)

### Reproduction

1. Desktop: send message with image to mobile
2. Desktop:  Edit it
3. Mobile: check the messag

### Additional Information

- Status version: 2.31 
- Operating System: Android, iOS

**Comment by seanstrom** [comment]
@igor-sirotin Could you help investigate a piece of this issue?
Specifically, how are we meant to "edit messages" that contain images?

For example, I can see that desktop calls `wakuext_editMessage` when editing a message [here](https://github.com/status-im/status-desktop/blob/9eaf4cc4eab91d207bf1085b6774d70e812de68f/src/app_service/service/message/service.nim#L1160-L1186):

```nim
proc editMessage*(self: Service, messageId: string, contentType: int, msg: string) =
  try:
    let allKnownContacts = self.contactService.getContactsByGroup(ContactsGroup.AllKnownContacts)
    let processedMsg = message_common.replaceMentionsWithPubKeys(allKnownContacts, msg)


    let response = status_go.editMessage(messageId, contentType, processedMsg)

    # ...redacted...
```

And at some point status-go will attempt to apply the changes to the message as an "edit" [here](https://github.com/status-im/status-go/blob/f15c64ced3de797dbf329917188b58ae1ec7f780/protocol/messenger_handler.go#L1831-L1836):

```golang
    editedMessage := originalMessage
    // Update message and return it
    err = m.applyEditMessage(editMessage.EditMessage, editedMessage)
    if err != nil {
        return err
    }
```

And it seems like the message `contentType` changes from image to text, even though on desktop it seems the images are kept inside the message. Could this be because an `EditMessage` does not contain all the image references or the image `contentType`?

I ask because it seems from the desktop UI, the images are not removable when editing a message, so I'm wondering if they're just being kept in the local state of the message. And I'm also wondering if status-go thinks they were removed from the message because the editMessage does not mention the images.

Any help or thoughts about this would be appreciated when you have a moment 🙏

**Comment by igor-sirotin** [comment]
@seanstrom sorry for the delay.
I see it was enabled on desktop in https://github.com/status-im/status-desktop/pull/14481. Let's ping @jrainville for details. Not sure how it works indeed.

**Comment by jrainville** [comment]
It seems there is an issue when restarting the app too: https://github.com/status-im/status-desktop/issues/16741

As you can see in the video, it clearly worked on a live app. I don,t know if something broke in the mean time or if I just never tested with a reloaded app.

I'll start working on it in a few days, so I can report then why it doesn't work. It might be that we need to block editing the message on images, but I'm hoping it's just about making sure we don't overwrite the images on edit.

**Comment by churik** [comment]
will wait until investigation is completed according to previous comments

Moving to 2.33 cc @ilmotta

**Comment by jrainville** [comment]
@churik @seanstrom I fixed the Desktop issue by updating the status-go code to make sure the ContentType of the original message doesn't get overwritten.

You can check it out here: https://github.com/status-im/status-go/pull/6133

You can probably test it to see if it fixes your own issue.

**Comment by seanstrom** [comment]
@jrainville nice stuff!

The mobile issue seems to be resolved on my side 🙌 
Here's a screen capture of editing a message with an image between a desktop and mobile client:

https://github.com/user-attachments/assets/aaba17d8-f0e2-4e26-87cc-038a0b573aa1

**Comment by churik** [comment]
Yes, confirmed, thank you!
