### ISSUE TITLE
Remove Jump To feature

### ISSUE THREAD

**Issue by ilmotta** [status-im/status-react#21570]
## Problem

The features surrounding `Jump To` have been discontinued due to performance issues, but mainly due to the cost of development for a feature that doesn't solve a significant problem users have, especially now that Status doesn't position itself as a super app. Maintaining the always disabled feature flag also has a cost because the code can sometimes be simplified if Jump To didn't exist.

### Acceptance criteria

- Remove all traces of Jump To from status-mobile and status-go. In status-go, also add the necessary migrations to remove unused column(s)/table(s).
- Remove feature flag `:status-im.feature-flags/shell.jump-to`
- Highly suggested to request manual QA due to the amount of code changes and potential for regressions.

**Comment by 86doteth** [comment]
i really hope once the basics like message reliability and performance are fixed and features from v1 like ens settings, chat payments, stickers, keycard and hopefully browser are worked back in this feature can return because this was really what got me excited most about v2, being able to multitask between shitposting in a chat while aping into a mint and/or memecoin concurrently in different tabs while still in the same app really was the dream and what got me to shill this app for years while it was slowly being developed in silence. this could still be worth a poll imo since it was advertised pretty intensely with that banger video almost 3 years ago and was imo the only reason to justify the whole ui overhaul:

https://www.youtube.com/watch?v=G16E2qvySMw

**Comment by 86doteth** [comment]
also i have real doubts about this singular focus lately on trying to compete solely as a wallet. wallets have insane lindy effects in crypto. by default 99% of users will stick to metamask or coinbase with which they can do almost everything that their heart desires and the hardcore degens will only install a few more mobile apps that give access to other niches like solana, ordinals, cosmos etc only because those arent readily available in metamask and coinbase. the only thing that the status wallet has in and off itself compared to this competition is a smoother multi-l2 router which is a very narrow advantage bc all those other wallets have browsers with which you can easily find any bridge app that does the job. in return the status wallet lacks a lot of features such as no hw wallet integration (with own screen), no browser (for easy concurrent aping) and actually much fewer l2s available while its basically as centralized as the rest.

the main competitive advantage imo always has been to keep the wallet integrated with the chat and the jump to feature was the main value driver i saw for the app to convert social activity into quick wallet activities bc no other app can do this. trying to beat the established players at their own game wont work and should be carefully reconsidered

**Comment by ilmotta** [comment]
> this could still be worth a poll imo since it was advertised pretty intensely with that banger video almost 3 years ago and was imo the only reason to justify the whole ui overhaul

Unfortunately, we overhyped way too much in the past @86doteth. In the video you shared there are other features that almost made into the product, some of which we dropped at the last minute, some we even spent precious development time. They all created unnecessary complexity and were never tested with real users. I think nobody would disagree that the Jump To feature is cool and even useful to some, but for nearly two years we focused on building cool stuff and deprioritized the really important issues (e.g. optimizing power consumption, having a reliable push notification solution, etc the list is long). For now and the foreseeable future we don't expect Jump To to return. If it does, it'll have to be rigorously evaluated against other features.

> also i have real doubts about this singular focus lately on trying to compete solely as a wallet

Your feedback is spot on. This is just a temporary strategy while we work on building a more sustainable path forward. Down the line, we're hoping to create tighter integrations between the wallet and the rest of the product. We know the wallet space is crowded, and we don't want Status to be seen as just another wallet, far from that.

Thank you for your feedback 💯
