### ISSUE TITLE
💳 🔁 Add Keycard support to Swap Txns

### ISSUE THREAD

**Issue by shivekkhurana** [status-im/status-react#21619]
# Feature Issue

### User Story

As a Keycard user,
I want to be able to sign native swap txns using my Keycard
**so that** I can call myself a cool kid and my funds stays secure, . 

### Description

If the account being used to sign a swap txn is a Keycard account, the flow should change as per the designs.

Figma: https://www.figma.com/design/YGm3igIOAcwMqUVJWCJ6f1/Keycard-UX?node-id=409-58818&t=VFIzh8BRInCRKpP9-1

### Acceptance Criteria

- [ ] A Keycard account should see "Sign with Keycard" message and Keycard logo when trying to sign a swap txn
- [ ] User should be able to complete txn signing with Keycard

**Comment by alwx** [comment]
hey Javid! 

if you've started working on it already, please don't add it to the existing swaps flow because `wallet_createMultiTransaction` is deprecated now and removed in this PR: https://github.com/status-im/status-mobile/pull/21541

so if you've already started working on this issue please base it on `update-sending-transactions-endpoint branch`
