### ISSUE TITLE
Fastlane, rename en-GB to en-US

### ISSUE THREAD

**Issue by licaon-kter** [status-im/status-react#21665]
ref: https://github.com/status-im/status-mobile/tree/develop/fastlane/metadata/android/en-GB

**Comment by ilmotta** [comment]
Hey @licaon-kter, could you please explain why we should rename `en-GB` to `en-US`? Status in app stores is trying to use the `en-GB` locale as the default. Thanks for reporting the problem.

**Comment by licaon-kter** [comment]
F-Droid uses `en-US` as default

And for Status, it was the default for a while too, right?

else we get this (notice the locale in upper right):

![Image](https://github.com/user-attachments/assets/ada786a2-52cb-4429-8cd9-f87ba253fb3b)

notice the mix of 3 languages:

![Image](https://github.com/user-attachments/assets/4c5b052d-4e49-433c-8c7d-e1f926d4912c)

I guess you can create link to `en-US` and that might work

**Comment by ilmotta** [comment]
Correct @licaon-kter it was the default for a while in Status. We will apply the fix you suggested since it's causing problems for F-Droid users.

**Comment by leoheitmannruiz** [comment]
Actually, I believe these are all F-Droid bugs and you should have been all good moving the metadata to en-GB (at least, concerning the bugs shown here). I've proposed a fix for one of the bugs a few minutes ago, another should be fixed temporarily soon and the third I'm not sure about but I'll investigate it.

Though, you should indeed rename en-GB to en-US, as en-US is the fall back language in the F-Droid ecosystem and some clients and repository browsers will not show the metadata otherwise.

PS: I like your profile picture and sicp-org repository!!

**Comment by leoheitmannruiz** [comment]
And, out of curiosity, why is Status trying to use en-GB as the default locale in app stores?

**Comment by ilmotta** [comment]
> And, out of curiosity, why is Status trying to use en-GB as the default locale in app stores?

@leoheitmannruiz I think it's reasonable to move to en-US for F-Droid. I'll check if we can standardize on en-US in all stores. I believe there's a matter of resource availability from the marketing team and other folks who craft the metadata. Maybe there's more to this that I'm not aware, but I'll update this issue with more details.

**Comment by ilmotta** [comment]
Update: there are legal reasons for Status to keep app stores using `en-GB` as the default locale. We will update fastlane source to use `en-US` as the default locale for the reasons discussed by previous comments. We are no longer using fastlane to update App Store or Google Play, so it will be fine to change for F-Droid.

**Comment by leoheitmannruiz** [comment]
Thanks!
