### ISSUE TITLE
Login screen don't open by default

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-react#21688]
### Summary

On app start profiles screen opens by default, instead of login screen.

Video: https://github.com/status-im/status-mobile/pull/21655#issuecomment-2501285852

**Comment by Parveshdhull** [comment]
> [show-profiles? set-show-profiles] (rn/use-state true)

related to https://github.com/status-im/status-mobile/commit/ac0a115f1ddfb640d37c07b170b1a3d7b4954f7e
cc @ulisesmac

**Comment by ulisesmac** [comment]
@Parveshdhull @ilmotta 

Probably I'm not understanding the bug, but this was expected since we implemented:

This is the PR:
- https://github.com/status-im/status-mobile/pull/21628

The issue:
- https://github.com/status-im/status-mobile/issues/21476

And the figma flow:
- https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14656-26145&node-type=shape_with_text&m=dev

**Comment by Parveshdhull** [comment]
Thank you very much @ulisesmac for providing these links.

> The new solution will always redirect users to the profile selection screen after logout

@ilmotta will know for sure, but we probably want to land the user on the profile section when logging out, not when [starting the app.](https://github.com/status-im/status-mobile/pull/21655#issuecomment-2501285852) (or I am out of context on this one)

**Comment by ulisesmac** [comment]
> , but we probably want to land the user on the profile section when logging out, not when https://github.com/status-im/status-mobile/pull/21655#issuecomment-2501285852 (or I am out of context on this one)

Yeah, the requirement is a bit confusing and the feature has been QAed 🤔

**Comment by ilmotta** [comment]
@Parveshdhull @ulisesmac

My understanding of the agreed requirements are:

1. The user should land in the profiles selection screen whenever the app starts.
2. The user should be redirected to the profiles selection screen after logout from Settings.
3. The user should login with biometrics only after explicitly choosing any of the profiles in the profiles selection screen.
 
I believe point 1 is the one causing confusion? In version 2.31 and previous ones, if the user closed the app and had biometrics enabled, upon reopening the app the user automatically logs in with the last profile. With the new implementation in `develop`, even if the user closed the app while being logged in, they will land in the profiles selection screen and will need to press on the profile to authenticate and login.

I have apps in my phone that do the same as we do in `develop` as of now, so `develop` is not wrong per se. Having said that, I think there's a slight UX improvement if we automatically login when the app starts if the user closed the app and was still logged in because that will eliminate one button press upon reopening the app. 

As you guys know, in 2.31 we have a really bad UX: whenever the user logout they lose their biometrics state and have to re-type the password. This makes using multiple profiles quite cumbersome. This is already solved in `develop` and now I realize it might be better to automatically login in with the latest used profile, but _if and only if_ the user closed the app while logged in with that profile. Contrary to 2.31, if the user was logged out when the app closed, the app should start in the profiles selection screen (as is the case now in `develop` builds).

@ulisesmac @Parveshdhull I suggest one of you reach out to @xAlisher in one of our channels to clarify. I think it's reasonable to keep the current `develop` implementation if we think there's no time to implement further changes, otherwise I shared my personal suggestion, but would be great to get input from designers and yourselves and the QA who reviewed recent PRs in onboarding.

**Comment by Parveshdhull** [comment]
Thank you, @ilmotta, for the detailed response.

> 1. The user should land on the profile selection screen whenever the app starts.

The [designs](https://www.figma.com/design/o4qG1bnFyuyFOvHQVGgeFY/Onboarding-for-Mobile?node-id=14656-26145&node-type=shape_with_text&m=dev) don’t have an explicit flow for app startup, only for a hard/manual log-out. So, it’s unclear from the designs whether the user should always land on the profile section or only after a manual log-out. (We need to check that)

> Now I realize it might be better to automatically log in with the most recently used profile, but only if the user closed the app while logged in with that profile.

Yes, I agree. This seems like a better UX, at least for users who have only one profile (or their main profile).

-----

Thank you, @ulisesmac and @ilmotta. Closing this issue as it's not a bug and is expected behavior for the time being. We can discuss this with the design team to decide whether we want to update it or keep it as is.
