### ISSUE TITLE
"View token requirements" opens an empty bottom sheet for non-token-gated communities (e.g., Status)

### ISSUE THREAD

**Issue by Horupa-Olena** [status-im/status-react#21797]
# Bug Report

### Reproduction

1. Join to Status community
2.  Open context menu via longtap on community
3. Click on **View token requirements**

#### Expected behavior
Hide this option if there are no requirements, or add a placeholder explaining that the community is free to join

#### Actual behavior
"View token requirements" opens an empty bottom sheet

https://github.com/user-attachments/assets/35b2a552-cf5f-4723-bfaf-fd03722570a0

### Additional Information

- Status version: nightly 2.32.0 (20241210021604)
- Operating System: Android, iOS

**Comment by ilmotta** [comment]
I unassigned myself for today to leave room for another CC to pick this up because I'm working on other issues and I would just block this one.

@ulisesmac would it be possible for you to help with this issue since it seems to be related to PR https://github.com/status-im/status-mobile/pull/21247 ?

We want to disable _view token requirements_ feature for 2.32 because we are running out of time for implementation and testing and this is not a critical feature to have right now.

Thank you 👋🏼

**Comment by ulisesmac** [comment]
@ilmotta  Sure! I'll open the PR today.

BTW, I faced that issue while being on testnet mode. That data should be just there. but yes, I'll remove the option
