### ISSUE TITLE
Wrong name is shown in chat and contacts

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2230]
### Description

*Type*: Bug

*Summary*: While testing Discover me and @goranjovic have noticed that wrong account name is shown in contacts and in chat in specific scenario. I have seen the same contact a while ago when I was able to remove wallet chat or something like that. This isssue is sporadic and I don't know exactly how to reproduce it.

#### Actual behavior
![image](https://user-images.githubusercontent.com/28752642/31777418-ad68b64e-b4f6-11e7-9d1c-3c1139257781.png)

### Reproduction

- Create account A on Ropsten
- Send some messages to account B which is on Rinkeby
- Check that messages are not delivered
- Switch Account A to Rinkeby
- Check on account B chat and account name for Account A

Please note there is some time delay for message exchange when being under different networks which should be investigated as well

### Additional Information
* Status version: develop

**Comment by goranjovic** [comment]
`"Revolving Wide Pikeperch"` gets generated when public key is `0` or `nil`

**Comment by goranjovic** [comment]
This specific issue is due to the fact that a chat is started with a contact whose public key is known as null (or possibly zero). This is a bug already.. 

Even though nil public key can only happen in what is an error state already, the rendered name should not look normal, i.e. it should be something like "Unknown" and definitely not "Revolving Wide Pikeperch". Creating a new issue for that - #2329

**Comment by asemiankevich** [comment]
havent seen the issue for a long time already, closing
