### ISSUE TITLE
Contact requests after account recovery

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#240]
Imagine we have _User A_ and _User B_, they have each other in contact's list. When _A_ recovers account, the database is empty, and he doesn't have any contacts. We have to make an exchange of the contact's between _A_ and _B_ to make them able to watch each other's profile's updates again.

**Comment by alwx** [comment]
I am stuck. Going to work on something else and probably switch to thinking about any good solution later.

The problem is I see no way to guarantee security. The only thing we can do after account recovery is to announce that we need contacts. But after that everybody can say "Hey, I am your contact" and there is no way to guarantee that it is true. So it means that almost everybody can be added to your contact list after recovery.
The solution that seems to be obvious in this situation is to use some verification string that was generated before (and, of course, both users should know this string). But the recovered contact has nothing except its address and public key, so we cannot generate the same string one more time without any additional information. Once again, the private sharing of any information between to contacts doesn't seem possible in the case when we have no information about the contact.

The code for sharing unencrypted information is in `feature/#240` branch, but I don't think it is a good idea to use this code now.

**Comment by jarradh** [comment]
Thanks so much @alwx yes, this is hairy, let's put a pin in this for now.

**Comment by jarradh** [comment]
Instead what we'll do is backup the data and chat histories, encrypted, to Swarm and attempt to retrieve them, this depends on us getting Swarm working on device.

**Comment by jarradh** [comment]
Depends on #718

**Comment by lukaszfryc** [comment]
This issue means that when you recover an account, your chatting experience will be very poor since you will not understand who you talking with (no custom names). I'd remove *low-priority* label from this issue.

cc @chadyj
