### ISSUE TITLE
Can restore account with [6 spaces] password [2421]

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2436]
### Description

*Type*: Bug

*Summary*: 6 spaces in Password field is an allowed combination to restore account

#### Expected behavior
Spaces should not be allowed for Restore Account password validation flow

#### Actual behavior
I can restore account with 6 spaces as password and then login

### Reproduction

- Open Status
- Set up a password
- Copy the secure phrase
- Tap Switch Account
- Tap Restore Access
- Enter the secure phrase and enter `6 spaces` as password

### Additional Information
* Status version: 0.9.10-364-g79ff253a+ (1921)
* Operating System: Android, iOS

#### Logs
* TF https://app.testfairy.com/projects/4803622-status/builds/7091938/sessions/2/?accessToken=/0xpsLsEYftld4CUOuUDQx8Ksrw

**Comment by annadanchenko** [comment]
@asemiankevich I think we need one common issue to "sync" the validations done on the account creation step with validations done on account recovery. Now, it's not clear what should happen if there are 5 spaces and 1 letter, only 2 letters etc. So, we need common logic on both steps that is identical no matter if we create or restore account.

See fix for https://github.com/status-im/status-react/issues/1224 - possible this bug is also fixed

**Comment by ghost** [comment]
@annadanchenko could you advice please how can we make up the "common logic". For now looks like that every character is allowed even space.

**Comment by annadanchenko** [comment]
@poiga I mean that if we use some function(s) to verify that a string is a valid password on 'Create account' step then same function(s) should be used to validate the password on 'Recover account' step. I assume it was not the case as more "relaxed" checks were done on recover, e.g. at some point it was possible to create a password with length < 6 chars or as here - it was possible to create password with spaces only. Same things are not possible on create account stage, so I assume we do not re-use validation logic but we should.

**Comment by asemiankevich** [comment]
After converstion with @flexsurfer I am closing this issue as Won't fix
