### ISSUE TITLE
Web3 Filters do not work with status chat bot

### ISSUE THREAD

**Issue by gretzke** [status-im/status-react#2479]
Steps to reproduce:

paste
```
var filter = web3.eth.filter('latest');
filter.watch(function (error, log) {
    if(!error) {
        status.sendMessage(log.toString()); 
    } else {
        status.sendMessage(error.toString());
    }
});
```
into a js file and add as a chat bot

returns a message with:

Error: EOF

**Comment by dshulyak** [comment]
As I understand filters are relying on subscriptions https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB and we don't support them in our transport layer at the moment. In order to support them, we need to switch transport to unix sockets or web sockets or implement subscriptions using signals.

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>

**Comment by mandrigin** [comment]
I think it makes sense to switch to a duplex transport layer.
Then we will also be able to use subscriptions for new messages, etc.

**Comment by mandrigin** [comment]
@dshulyak I took a look at how filters work, and it seems like they rely on polling, and not on pubsub at the moment.
```
INFO [04-24|12:12:29]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":21,\"method\":\"eth_getFilterChanges\",\"params\":[\"0x133197bbc572a5e5871f3f614b45ab0a\"]}"
INFO [04-24|12:12:30]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":22,\"method\":\"eth_getFilterChanges\",\"params\":[\"0x133197bbc572a5e5871f3f614b45ab0a\"]}"
INFO [04-24|12:12:30]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":23,\"method\":\"eth_getFilterChanges\",\"params\":[\"0x133197bbc572a5e5871f3f614b45ab0a\"]}"
INFO [04-24|12:12:31]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":24,\"method\":\"eth_getFilterChanges\",\"params\":[\"0x133197bbc572a5e5871f3f614b45ab0a\"]}"
INFO [04-24|12:12:31]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":25,\"method\":\"eth_getFilterChanges\",\"params\":[\"0x133197bbc572a5e5871f3f614b45ab0a\"]}"
```

**Comment by flexsurfer** [comment]
ok , so filters are not supported in status-go with RPC
and the contract receipts are broken in LES (without RPC).
That makes filters half-useful in that mode too.
