### ISSUE TITLE
Script to bundle local status-go for Android and IOS

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2539]
### User Story

As a developer, I want to build and bundle status-go locally with any platform.

### Description

*Type*: Tooling/Feature

*Summary*: Extend existing script (https://github.com/status-im/status-react/pull/2537) to allow for building on Android and both.

#### Expected behavior
Can bundle local status-go for Android, iOS and both. Also require STATUS_GO_HOME and STATUS_REACT_HOME to be set and respect these, meaning it can be run from anywhere.

This will also be useful for end to end CI (Jenkins) but this is outside the scope of this issue.

#### Actual behavior
Only iOS (pending PR).

**Comment by oskarth** [comment]
Suggested bounty: small or medium.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0x06f287aefdbf07a5ab96e96c4bfd9d795b336ea5](https://etherscan.io/address/0x06f287aefdbf07a5ab96e96c4bfd9d795b336ea5)
Network: Mainnet
Paid to: PombeirP
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pedropombeiro** [comment]
@oskarth where does the Android bundle normally go in the `status-react/modules/react-native-status/android` subtree?

**Update**: I needed to revisit this for another issue, and understood how the Android build is done - delved into Gradle and Maven (not a stack I've dealt with before). I guess one option would be to change the `compile` directive at https://github.com/status-im/status-react/blob/develop/modules/react-native-status/android/build.gradle#L20 so that we have one for release builds that fetches from artifactory, and another for debug builds that fetches from the local maven repository.
