### ISSUE TITLE
Invalid phone number passes validation

### ISSUE THREAD

**Issue by rasom** [status-im/status-react#259]
![2016-09-22 14 13 45](https://cloud.githubusercontent.com/assets/2364994/18753838/3adedaf4-80ef-11e6-97b9-01649c8ed7f1.png)

**Comment by alwx** [comment]
This is the way how libphonenumber is intended to work.
https://github.com/googlei18n/libphonenumber/issues/328

According to this issue, libphonenumber simply ignores 1 or 2 letters inside the number — it happens because the library was originally designed to parse numbers and in order to get all numbers from a webpage they ignore some possible problems inside the number. 
The solution is to also validate a number using regex.
https://github.com/status-im/status-react/pull/277
