### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by shonefos** [status-im/status-react#2616]
[comment]: # If I type something in chat and after that go back and tap on the icon(wallet, Chats, Discover, Contacts) in the menu will open my keyboard, only the second tap will open the desired window.

*Type*: <Bug>

* Operating System: <iOS>
iPhone 6+(11.2)

**Comment by annadanchenko** [comment]
@shonefos thank you for the bug report! Can you, please add steps to reproduce like
- Launch Status
- Sign in
- Open chat with Jarrad
- Tap inside input field, type "Abc" and tap on send button. 
- Tap on button "<" to return to Chats
etc, so we can use them to reproduce the issue.

It would be also great to have a picture of the exact issue (if it demonstrates itself visually) and video of the steps too.

**Comment by shonefos** [comment]
Reproduction : 
* Launch Status app
* Log in
* Open Chat
* Tap on input field "aaaa"
* Tap on Back button
* Tap on Menu icon Contacts

**Comment by shonefos** [comment]
https://www.youtube.com/watch?v=s4Ufnr6kuFc

**Comment by graemerycyk** [comment]
Same issue got another way to reproduce:

* Launch Status app
* Log in
* Open Discover
* Select a DApp from the "All" section
* Press the back button
* Keyboard will appear

Video here -> http://share.xctest.io/Exj2na (ignore the last bit when i take a screenshot)

This isn't always reproducible though, but you can see it occur in the video. I'll keep an eye on this if I have any other ways to narrow the steps down.

**Comment by annadanchenko** [comment]
@shonefos @grycyk It looks like there are some extra conditions to get this issue that are not described. I've tried both scenario following the steps to reproduce and can't reproduce it. I've checked both videos:
1. on https://www.youtube.com/watch?v=s4Ufnr6kuFc I see that starting point is Contacts and Console chat is opened from that location. This is 1st difference from the written steps that say to Log in and open Chat. At the end (when keyboard is shown) I see screen Chats as end point, not Contacts. I would really appreciate, if you can uninstall the app, install it and record the steps from the moment you do 1st sign in. So, all of us can see that the issue is in the navigation and not in special data/settings/other unknowns and we all start from the same place. It might be a good idea to make some pictures/write the data you have before uninstall as it might influence the behaviour. In addition it would be really helpful to get feedback on how often you can reproduce the issue, e.g 5 times out of 5 attempts. 
2. http://share.xctest.io/Exj2na Also do not show all steps done from the beginning. @grycyk please, specify what device/OS is used to reproduce the issue.

At the moment, I see that issue happens and do not doubt it, however we need steps to reproduce that developers can use to investigate, fix and we can use to verify the fix.

**Comment by graemerycyk** [comment]
Yeah like I mentioned in the last part of my previous comment, its not always as expected. Once I have some more time I will dig into it little further, it shouldn't be that hard I think to figure this one out, just a little time and some exploring for the exact issue.

**Comment by shonefos** [comment]
@annadanchenko which phone did you use?

**Comment by graemerycyk** [comment]
iPhone SE, iOS 11.2 Status version 0.9.12

**Comment by annadanchenko** [comment]
@shonefos I have used 2 iOS devices:
Iphone 7 plus, iOS 11.0.3
iPhone 6s, iOS 10.3.3

**Comment by shonefos** [comment]
Very strange situation, I would say it has something to do with user credentials in Wallet Menu.
I can not reproduce what the cause is, but I caught it again.
https://youtu.be/9BMLh7Idqsc

**Comment by graemerycyk** [comment]
I was just able to reproduce this:

Pre conditions:
user must be being signed in and have the Discover tab open

Steps:
open a chat from recent status
double tab on the back button
click another tab Wallet or Chat for example, the keyboard should open up (see video)

*This seems to need to be done very fast, and if first time fails just keep trying these steps*

Video -> http://share.xctest.io/U5B6es

iPhone SE | iOS 11.2 | Status v0.9.12

**Comment by yenda** [comment]
This issue is not relevant anymore after all the design changes and 16 versions since
