### ISSUE TITLE
Status App - Edit Chat option is not working as intended

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2630]
**Description**

 Type: Bug

*Summary*: ...
After sign in to Status App - 
1. Go to **Chats** option.
2. Then click on  Edit option. Edit Chats option will display on screen
3.Please see the attached screenshots.
4. After clicking to edit option  - Delete chat option is displaying.
![screenshot_2017-12-06-18-00-58-337_im status ethereum](https://user-images.githubusercontent.com/20433356/33662496-f3ce70e8-dab1-11e7-8371-5d17395ba1af.png)
![screenshot_2017-12-06-18-01-28-069_im status ethereum](https://user-images.githubusercontent.com/20433356/33662506-fdbf4262-dab1-11e7-9afa-5354fe013ff9.png)
**Expected** 
Should be able to edit.
**Actual** 
Here instead of edit, it's getting deleted.
### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: ... 0.9.12
* Operating System:  
Redmi Note 4 
Android 6.0.1

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by asemiankevich** [comment]
Hi @Monali109 !

What you are describing is expected behavior of the application. So when you are on Chats tab you can click Edit -> Remove selected chat from the list. 

Other option for Edit is when you create group chat - so you can modify chat's name , invite or remove participants. You can add your custom chat name when you are creating it as well as you can change it later - just go to this group chat -> click Profile -> settings. 

![image](https://user-images.githubusercontent.com/28752642/33667325-98b3629e-daad-11e7-9451-9b75e215936c.png)

Can you please give it a try and let me know your feedback? Thank you!
