### ISSUE TITLE
Recover Access is creating another new account 

### ISSUE THREAD

**Issue by Monali109-zz** [status-im/status-react#2632]
**Description**
*Type*: Feature

*Summary*: ...
1.  Open Status app.
2. Click on Recover access option.
3. After that screen will appear as shown in attached screenshot.
![screenshot_2017-12-06-17-54-30-465_im status ethereum](https://user-images.githubusercontent.com/20433356/33663477-2b26de00-dab6-11e7-9e22-56eef1f74743.png)
4. Click on Recover Access option once again. It opens another new account instead of recovering an old one.

#### Expected behavior
I feel instead of creating new account, it should recover the previous one which already created & UserName for that account this option if there on UI, so that will get to know, for which account getting recovered if multiple accounts are there on one device.
& While creating new account it's not validating  password length & Pass phrase 12 words.
#### Actual behavior
Getting created each time new account.
Not validating password length.
### Additional Information
* Status version: ... 0.9.12
* Operating System: Android 6.0.1

**Comment by asemiankevich** [comment]
Hi @Monali109, thank you for your report! As I can see from screenshot this is expected behavior for the application. To recover an account which was created before you need to use your secret phrase that was generated along with your account you are trying to restore. 
Please keep in mind the pass phrase should be exactly the same otherwise new account will be created instead. We also have an open issue https://github.com/status-im/status-react/issues/1228 that would not allow to proceed with recover untill the `Passphrase` field is populated correctly and https://github.com/status-im/status-react/issues/1224 that will add password length checking functionality.
 I hope the flow will be less confusing soon! :)
