### ISSUE TITLE
General repository cleanup

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2668]
### User Story

As a developer, I want to have a clean repository with no old files and clean structure.

### Description

* remove irrelevant files (verify they are not used anymore): (e.g. `CHANGELOG.md`, ..)
* verify if `shim.js` is still used, remove if not
* remove `env/test` and simplify `env/dev/user.clj` accordingly
* migrate `docs` to wiki.status.im

*Type*: Bug

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x60e65748247e8804ba09d036d67424ed800cb1de](https://etherscan.io/address/0x60e65748247e8804ba09d036d67424ed800cb1de)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by placer14** [comment]
I'm happy to start working through these tasks.

**Comment by andytudhope** [comment]
Perfect @placer14. Please go ahead, no need for much permission round here. 

Also, please join https://chat.status.im and ping me there to make sure you have access to edit the wiki. Anyone can - that's why we use it - but if you're doing this then I can prob make your life easier and make sure you changes don't require review there before being published.

**Comment by placer14** [comment]
@andytudhope I'm `mg` on chat.status.im. I could not locate you. Please reach out.

**Comment by placer14** [comment]
@alwx, you've created https://github.com/status-im/status-react/blame/develop/shim.js. Can you help me understand it's importance to the repo and if it can be removed (or maybe moved closer to where its consumed)?

**Comment by placer14** [comment]
@jeluard, what does `dev/test` refer to? If it's a directory, it doesn't appear in the status-react `develop` tree. Maybe it's already been removed?

**Comment by placer14** [comment]
Would it be appropriate to move https://github.com/status-im/status-react/blob/develop/update.sh and https://github.com/status-im/status-react/blob/develop/postinstall.sh into `scripts/`?

**Comment by yenda** [comment]
You can delete update.sh I accidentally committed it in my last commit. postinstall is a npm script not a script for developer so I don't think we want to move it with the dev scripts. shim.js is not really used but it's more because we don't know how to use it. It comes with rn-nodeify and contains shims required for some libs, we just don't use these particular libs ATM.

**Comment by jeluard** [comment]
@placer14 Sorry that was [env/test](https://github.com/status-im/status-react/tree/develop/env/test/) actually.

**Comment by andytudhope** [comment]
What is the status of your work here @placer14? Is there an open PR that I am missing, or are you only working on your own branch?

**Comment by placer14** [comment]
@andytudhope Sorry, I had finished the work but never wrapped it up and posted the PR. I erred on the side of removing less than more as I'm quite new to status and wasn't sure how to exercise all of the moving parts past running the tests and building production. Please let me know if further attention is needed somewhere.

**Comment by pablanopete** [comment]
Is this one still relevant @jeluard ? @placer14 are you still working through this one - is there something specific you were needing other than what's been done so far?

**Comment by poiga** [comment]
@pablanopete I have PR submitted on this - #2911. Still waiting to be reviewed by @yenda .
