### ISSUE TITLE
No send message shown in chat if sending from wallet

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2696]
### Description

*Type*: Bug

*Summary*: send Funds to a contact from wallet -> no new send message is shown in the chat as well as no chat created if this is the very fisrt message

#### Expected behavior
new send message is shown in the chat

#### Actual behavior
no new messages are shown in the chat

### Reproduction
- Open Status
- Open Wallet
- Tap Send
- Type some valid amount, e.g. 1234
- From Contacts select Jarrad
- tap on Sign transaction and proceed

### Additional Information
* Status version: last develop
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@janherich is there any news on this? Will it be fixed in new protocol ? I really want to have this fixed soon

**Comment by asemiankevich** [comment]
Per Jan comment:
Ok, so this is something which I already answered long ago (we discussed about it with @roman as well), it's basically not possible to do it with current code - you can't easily create artificial `/send` message without actually going through the bot send process, but you don't want that because you are sending through wallet
What we really need is to ditch bot code handling sending altogether and always use just wallet for that, `/send` command will just hook into that and it will be only visual shortcut (opposed to going through wallet only)

This code rework will also help us to get /send and /request for tokens in place so i marked this as high prio however it is blocked for now as I am not clear with the swarm i should assign the issue to.

@jeluard @rasom could this issue be included in any of existing swarms and taken care of?

**Comment by jeluard** [comment]
@asemiankevich Most probably will be solved when improving bot API

**Comment by goranjovic** [comment]
Now that we have Clojure generated payment messages we can do the following:

- Send a 1:1 message to the whisper id of the recipient after every successfully sent transaction, whether it was from Wallet Send or from Chat /send. If whisper id is not available (e.g. if the user pasted the address of a non-Status user), then no chat message is sent, which is fine.
- Remove the `execute-stored-command` kludge since we only needed to continue the interrupted bot command code in order to send out the payment message. If it's done in the same way for both chat and wallet payments, we don't need this any more.
- Clean up any other hotfixes we had in place because of "message from previous payment shown" bug.
- Re-enable amount and symbol in Chat Send screen, again not constrained by the command code any more (review this decision with UX)
