### ISSUE TITLE
Allow feature flags to be turned on/off

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2731]
### User Story

As a developer, I want to turn on/off feature flags from a simple developer screen

### Description

Some features part of a developer release are hidden behind a statically set flag. As a developer I want to be able to change the value of those flags from a simple screen. Restarting would then allow me to see relevant changes.

See [config.cljs](https://github.com/status-im/status-react/blob/develop/src/status_im/utils/config.cljs) for more details about how those flags are currently used.

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1000.00
Contract address: [0x463b19444da90a9fae2913cd4d2a0548107f667b](https://etherscan.io/address/0x463b19444da90a9fae2913cd4d2a0548107f667b)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by pablodip** [comment]
@jeluard Some questions about this:

* Why exactly do you want to change those values from a screen instead of from code? So that you can do it in a production build?
* If that is for a production build, how should this screen be made visible in the app?
* Why would restarting be necessary for changes to be applied? Because of some particular startup process?
* Where do you think the state of these config values should be saved?

**Comment by jeluard** [comment]
@pablodip This requires some special screen so would be only available from development releases. Goal is to change their value without having to rebuild the app.
Those flags are currently stored in `env` files packaged in the app and read during startup.

**Comment by t4sk** [comment]
I am going to try this issue

**Comment by t4sk** [comment]
PR is in WIP. I've created a list of TODO. I would appreciate any feedback.
