### ISSUE TITLE
Avatar in 1-1 chat is not updated after setting it up in User Profile

### ISSUE THREAD

**Issue by churik** [status-im/status-react#2754]
### Description

*Type*: Bug
*Summary*: 
when you start a chat with user A and than user A set up or change profile photo - it does not affect to Chats with user A.

#### Expected behavior
user avatar is updated in "Chats"

#### Actual behavior
user avatar leaves the same
![dev_ava](https://user-images.githubusercontent.com/4557972/34101579-ca093a54-e3ee-11e7-801d-e68aa3010192.png)

### Reproduction

- Open Status with user B
- start chat with user A
- change profile photo in user A account
- check  "Chats" tab in user B account
- reopen app
- check  "Chats" tab in user B account

### Additional Information

* Status version: 
 nightly 18/12 develop build.
0.9.10-458-ga7f8526c+ 

* Operating System: Android, iOS
reproducible for real GalaxyS7, IPhone 7

**Comment by annadanchenko** [comment]
Can reproduce on nightly build (jan 21). If avatar is not changing on last step: wait for 1 minute on Chats screen or open 1-1 chat with a, send text message and return to Chats.

See on 00:16 profile picture is shown and on 0:19 it's gone https://app.testfairy.com/projects/4803590-status/builds/7549901/sessions/9/?accessToken=WPEoZE2nOtBHGBa8dYggxkucnDc

(user A: real galaxy s6, user B real iphone 6s)

**Comment by dmitryn** [comment]
I'm able to reproduce this. The reason for this bug is that we receive `contact-request` message which triggers `:contact-request-received` event that dispatches `update-contact!` event.

Quickfix would be comparing contact `last-updated` and message timestamp and do not run update if message is older. But this looks more like workaround so i have more general question - why do we process `contact-request` event for contact that already added? https://github.com/status-im/status-react/blob/develop/src/status_im/protocol/handlers.cljs#L495
