### ISSUE TITLE
Improve specs report readability

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2755]
### User Story

As a developer, I want to easily understand `specs` error (both in terminal and in app) 

### Description

*Type*: Feature

Errors generated by `specs` are pretty hard to decypher (especially because of how we use specs).

![specs](https://user-images.githubusercontent.com/359723/34108257-b3ba97dc-e3ff-11e7-9c0f-b17a9dbbd6c6.png)

It would help to get human friendly error messages (in terminal too).

Some libraries that might help with that:

* https://github.com/bhb/expound
* https://github.com/athos/Pinpointer
* https://github.com/alexanderkiel/phrase

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 4000.00
Contract address: [0x08e1451d4f34cd67e9b4647bccb251483eeec6d7](https://etherscan.io/address/0x08e1451d4f34cd67e9b4647bccb251483eeec6d7)
Network: Mainnet
Paid to: pablodip
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by foopang** [comment]
@jeluard I think `Phrase` does not serve this purpose well because the target audience for generated messages are end-users of an application not developers. 

Between `Expound` and `Pinpointer`, `Expound` seems more mature and more configurable. By default, it doesn't display the errors very clearly readable IMO, see screencap.

![screenshot from 2017-12-19 12-54-11](https://user-images.githubusercontent.com/4666757/34141424-1341713c-e4bc-11e7-9dc1-61c8ba9c89a8.png)]

I want to try `Pinpointer` too, but I have trouble setting it up:

`No such namespace: clojure.test.check, could not locate clojure/test/check.cljs, clojure/test/check.cljc, or JavaScript source providing "clojure.test.check" in file file:/home/pang/.m2/repository/org/clojure/clojurescript/1.9.946/clojurescript-1.9.946.jar!/cljs/spec/test/alpha.cljs`

**Comment by jeluard** [comment]
@foopang Actually the target is developers and this is to help us debug faster. The red screen is not shown to end users.
This is for the very specific subset of `app-db` related errors. For this case I believe we can do a little better and I would expect to be able to see errors at the key level (as we are mostly interested by first level `app-db` issues). So something that would pinpoint me which key is wrong and why.

Still it makes sense to start reflection about how to improve user level errors so if you have some thoughts how it could be done beyond using a framework that would be appreciated!

About your error: we don't use `test.check` yet so you might have to include this dependency?

**Comment by foopang** [comment]
@jeluard Is this what you are expecting?
![screenshot from 2017-12-19 19-30-45](https://user-images.githubusercontent.com/4666757/34155241-80bf3302-e4f3-11e7-9512-cb4d3906f7a7.png)

**Comment by jeluard** [comment]
@foopang It is, yes!

**Comment by andytudhope** [comment]
Fixed by https://github.com/status-im/status-react/pull/2770
