### ISSUE TITLE
null is not an object (evaluating 'c.greaterThanOrEqualTo') error when trying to send an amount through the wallet screen when changing a network

### ISSUE THREAD

**Issue by Kimoa85** [status-im/status-react#2865]
Type: Bug

Summary:
null is not an object (evaluating 'c.greaterThanOrEqualTo') error when trying to send an amount through the wallet screen when changing a network

Expected behavior
Error shouldn't appear, if there is a network issue there should be a valid\relevant error, otherwise, no error should appear

Actual behavior
Error appears

Reproduction
Create an account, switch to a different network, enter your wallet and select send, try entering a numeric value - Error is shown.

Additional Information
Status version: release 0.9.12
Operating System:
Xiaomi redmi note 4, android 6.0.1

**Comment by asemiankevich** [comment]
Hi @Kimoa85 ! I assume this is due to missing validation (maybe), so you are trying to send funds with 0 balance (switching to another network will renew your balance to 0 until you /faucet funds there again).
I am not able to reproduce the issue in latest nightly, I am seeing `Insufficient funds` tooltip in all the cases performed:
- created account on ropsten -> faucet funds -> switched to rikeby with RPC-> tried to send
- created account on ropsten with RPC-> faucet funds -> switched to rikeby  with RPC -> tried to send
- created account on Rinkeby with RPC -> tried to send

cc @annadanchenko

**Comment by asemiankevich** [comment]
i cant reproduce it
