### ISSUE TITLE
Deleted 1-1 chat reappear in 'Chats' list after next user log in

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#2870]
***Type***: Bug

***Summary***: When I delete 1-1 chat(s) with previously read messages I had with another contacts (so no Unread message counter displayed on Chat screen), after I log out and log back in - all deleted chats reappear and display all messages I had with the contacts, that were deleted, - like they were Unread. 
The main issue is that we should not resurrect deleted 1-1 chats at all.

#### Expected behavior
No deleted 1-1 chat appears if to log out and log back in to account
#### Actual behavior
Previously deleted 1-1 chat appears if to log out and log back in to account

### Reproduction
https://app.testfairy.com/projects/4803622-status/builds/7392267/sessions/24/?accessToken=IFcF1Epo0dBaEz2royLWr5qBAS4 - from 02:23

1) Open Status on Device1
2) Open Status on Device2
3) Create UserA on Device1
4) Create UserB on Device2
5) UserA adds UserB in contacts.
6) UserA sends message to UserB
7) UserB navigates to 1-1 Chat with UserA to read the message.
8) UserB navigates back to 'Chats' list. Confirm no unread messages counter present.
9) UserB deletes the chat with UserA
10) UserB logs out
11) UserB logs back in and stays on Chats list.

Status version: 0.9.10-503-g3e940b5b+ (develop)
Operating System: Android 7.0 (Samsung J7 real device), iOS 11.1.2 (iPhone X)

**Comment by dmitryn** [comment]
It was an attempt to fix that https://github.com/status-im/status-react/pull/1343

**Comment by janherich** [comment]
True, that was my first PR for status. The root cause of the issue is the fact, that we have to create new 1-1 chat whenever we receive new chat message from contact X, even if chat with contact X was already deleted before - the reason is that we can't know if upon deleting some chat, we don't want to ever receive message from deleted contact in the future.
If that would be relaxed (it's ok to never receive message from contact whose 1-1 chat was deleted), it would be very simple, we would just flag the chat as deleted and check incoming message against it.

**Comment by dmitryn** [comment]
@janherich right, 1-1 chat just gets deleted from db and i don't see way to track it. So when new message arrives, chat gets inserted back. Instead we can set it as "inactive" to track it was deleted.
