### ISSUE TITLE
Jenkins: Get nightly to build in under 10m

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2880]
### User Story

As a developer, I want CI to run fast so I can quickly get feedback and ship quicker.
As a tester, I want the same thing.

### Description

*Type*: Feature/Devops

*Summary*: Make (successful) nightly build run in under 10m on average.

#### Expected behavior
Nightly build in <10m.

#### Actual behavior
Nightly build in 14-20m.

Source: https://jenkins.status.im/job/status-react/job/nightly/buildTimeTrend

### Solution

Figure out biggest blockers to build time: see https://github.com/status-im/status-react/issues/1708 for some leads.

For example, switching to yarn and vendoring / not resetting everything all the time is likely to improve build time. Additionally, consider not just build time but also queue time and how we can reduce this.

**Comment by oskarth** [comment]
Can also get some support from Clojure devs, but a lot of it is just playing around with tooling and getting build steps to run, not much domain specific knowledge.

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/2933

Also more generally for just local (reliable) build this is the best I can do to actually make sure env works. It takes 8-12m depending on Internet speed. yarn, vendoring and a bunch of other stuff can probably help here.

```
#--------------
# Experiment
# time (make clean && make deps) => 12m.
#--------------
clean: ##@experiment Clean
	rm -rf node_modules
	npm cache clear --force
	rm -rf package-lock.json
	rm -rf build

deps: ##@experiment Deps iOS
	npm install
	cd ios && pod install && cd ..
	lein deps && ./re-natal use-ios-device real && ./re-natal use-figwheel && lein re-frisk use-re-natal
	mvn -f modules/react-native-status/ios/RCTStatus dependency:unpack
```

cc @rasom @v2nek

**Comment by v2nek** [comment]
Few days ago i've started thinking about this, and as first try changed build cores for iOS from 1 to 3. This increased build speed a little: from 8-9 minutes to 6-7 minutes.

Also we can add some more memory to jvm (default value is 1024).

There are lots of other tools that could be used to increase speed.
this http://biercoff.com/how-to-crazy-easily-speed-up-your-npm-install-speed/
on nightly gives decrease in speed from 50s to 41s

We can try using https://www.npmjs.com/package/npm-cache to build. On the second run npm-cache install went from 50s to 12-13 seconds.

We also can try to benefit from using docker to precompile image that will be used to build application by itself. It will increase build time, since we dont need to download all dependencies every time, no need to clean up, etc.
This need to be tested properly.

Can we use gradle setting `org.gradle.parallel=true` ?

I will do some more testing on this hypotheses, feel free to offer something else to test.

**Comment by v2nek** [comment]
Tested setting 
```
org.gradle.configureondemand=true
org.gradle.parallel=true
```
this decreased android build step from 5+ minutes to 1 minute 20s.
However this build need to be tested.

**Comment by v2nek** [comment]
There is no speed improvements in 
`
OTHER_SWIFT_FLAGS="-Onone -Xfrontend -warn-long-function-bodies=100 -Xfrontend -warn-long-expression-type-checking=100 -Onone" SWIFT_WHOLE_MODULE_OPTIMIZATION=YES
`
that are recommended by 
https://jobs.zalando.com/tech/blog/improving-swift-compilation-times-from-12-to-2-minutes/
https://discuss.bitrise.io/t/ios-builds-slow-any-solution-to-speed-it-up/61/17
https://stackoverflow.com/questions/40406392/speed-up-xcode-swift-build-times
etc.

**Comment by oskarth** [comment]
Great ideas @v2nek!

**Comment by v2nek** [comment]
We also may want to try https://jenkins.io/blog/2017/09/25/declarative-1/
this may provide some speed improvement if build machine is not utilised.

also i've removed `#org.gradle.parallel=true` from settings, as it seems to be making build to fail.
Removed both options.
