### ISSUE TITLE
Implement PN informational message for Android users (Onboarding)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#2905]
### Description

*Type*: Feature

*Summary*: this is a feature request. I want Android users to be informed about Push Notifications enabled feature. Just from user side - i even dont know about PNs while on Android and iOS informs me about it right after i start the app.

#### Expected behavior
We have this security alert on iOS saying about PNs. Its just a system notification but we can try to implement something in terms of onboarding for Android platform

![image](https://user-images.githubusercontent.com/28752642/34564890-c149ce82-f169-11e7-9369-888d16f58e80.png)

#### Actual behavior
Nothing informs about PN feature while being on Android platform

**Comment by mandrigin** [comment]
One side note about how iOS behaves.

The dialog on the screenshot is a system dialog. If a user presses "Don't Allow" in there (even by mistake), it won't be possible for the app to request the notification permission again (until a user resets her phone). 
That's why FB Messenger or WhatsApp show this [ugly full-screen dialog](http://www.thepicky.com/images/2017/01/Turn_on_whatsapp_notifications.png) if you disable them.

How to mitigate that?
One of the solutions is to precede this dialog with a custom UI (some more thorough details can be found [there](http://blog.hurree.co/blog/ios-push-notification-permissions-best-practises)).

**Comment by asemiankevich** [comment]
@mandrigin right as I said above its system message for sure. We need to think about it, maybe @andmironov has some thoughts :)
