### ISSUE TITLE
Solve intermittent node_modules/web3/dist/web3.min.js (No such file or directory)

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#2937]
### User Story

As a developer, I want to have a reliable build process so I can focus on gettin work done.

### Description

*Type*: Bug

*Summary*: Fix build scripts and instructions so that `node_modules/web3/dist/web3.min.js` is always present.

#### Expected behavior
`node_modules/web3/dist/web3.min.js` (and more broadly, `node_modules/web3/`) should always be present when running `npm install` or equivalent.

#### Actual behavior
[comment]: # (Describe what actually happened.)

### Reproduction
- Follow build steps outlined in https://wiki.status.im/Building_Status
- Notice that `lein prod-build` sometimes results in

`Caused by: java.io.FileNotFoundException: node_modules/web3/dist/web3.min.js (No such file or directory)` and `web3` isn't installed.

### Additional information

This bug leads to hacks like https://github.com/status-im/status-react/blob/develop/Jenkinsfile.nightly#L8-L17, as well as countless questions and time wasted for people on Riot / core contributors.

Possible leads: https://github.com/ethereum/web3.js/issues/1041 as well as moving to yarn.

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 250.00
Contract address: [0xc21c7737d9498f82d200825445d3fc6421edeaf3](https://etherscan.io/address/0xc21c7737d9498f82d200825445d3fc6421edeaf3)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/2937/4cc7ff6db6b3cf81c669cb0204864ab25d6789728b8a60cd6f54130f5071f6fc/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by v2nek** [comment]
This was solved by https://github.com/status-im/status-react/pull/2877

**Comment by andytudhope** [comment]
Ah, gahd damn. Have just funded it as well... OK then, will work to undo it manually, thanks @v2nek

**Comment by oskarth** [comment]
@v2nek This is not a solution, it's a hack to get around the root of the problem. See the additional information section in the issue.

@andytudhope Leave it be, please.

**Comment by stephengroat** [comment]
@oskarth `yarn` definitely work better than `npm`, but i think the real issue here is the use of the `sh` function while not checking the return code. you can exit on a non-zero return code, showing build failed. does anyone know what package the `sh` function is out of?

**Comment by oskarth** [comment]
@stephengroat This can happen locally too though, so not just a Jenkins config issue. But I'm all for checking return codes. One can just wrap shell command in it and check return code I think. Here are some docs https://jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#code-sh-code-shell-script

**Comment by stephengroat** [comment]
even though Jenkins sets the `-e` flag in its `sh` command, [`e` is ignored in bash loops](https://unix.stackexchange.com/questions/65532/why-does-set-e-not-work-inside). i've run into it before, makes debugging impossible

since `yarn` can interpret `package.json` and seems to run a lot smoother, i'd try installing it locally on the jenkins boxes and switching out `npm` for `yarn` in all of the scripts. might help some. i'd make a pr, but since the jenkins boxes seem locally configured, i don't know if it would help too much

**Comment by alwx** [comment]
Already fixed: https://github.com/status-im/status-react/pull/4974
