### ISSUE TITLE
Simplify our figwheel config

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#2999]
### User Story

As a developer, I want to rely on a clean figwheel configuration

### Description

Our current figwheel conf is retrieved by some code from project.clj. This is pretty complex, brittle and makes `project.clj` unnecessarily big. Migrate relevant conf to the figwheel ns.

Tasks:
* remove lein-figwheel plugin
* migrate all figwheel conf from `project.clj` to `figwheel` ns

*Type*: Feature

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x3a8045bf9d2d4d2d0333a6bedea3382c83f52b1d](https://ropsten.etherscan.io/address/0x3a8045bf9d2d4d2d0333a6bedea3382c83f52b1d)
![QR Code](http://7d1f0959.ngrok.io/qr/status-im/status-react/bounty/2999/09772a5030d1a723dde376df908a466a8435f20b4d069da394ce34ba766a1a4c/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [http://7d1f0959.ngrok.io](http://7d1f0959.ngrok.io) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
