### ISSUE TITLE
Fullscreen browsing experience

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#3005]
### User Story

As a user, I want to have a fullscreen browsing experience with basic refresh control.

### Description

In *Home* tab, clicking on a DApp or website opens a fullscreen browser with some basic control. See https://projects.invisionapp.com/share/KXEWN9XHM#/screens/268744353
Clicking a web link in chat also opens this browser.

Closing a browser will either redirect you to the Home tab or the originating chat.

*Type*: Feature

**Comment by annadanchenko** [comment]
as discussed: Refresh functionality is out of scope in this PR.
Other features seem to be ok: can open url from chat, can Open url from "Start new chat" screen, can open DApp. Full browser screen is shown. If use links inside page then can open other pages and use <- and -> to navigate back and forward. Sometimes if tap on line in ios then it's opened in Safari (known https://github.com/status-im/status-react/issues/1200 ). Also not always can see <- when new page is loaded (might be because it's loading - will create separate bug to show loading state). If tap back then can return to chat if link was opened from chat. If it was opened from "Start new chat" screen then return to Home
