### ISSUE TITLE
[Perf] User story 1: Time lags navigating through different app views after log in when user has a lot of sent/received messages 

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3095]
***Type***: Bug

***Summary***: This is a follow up to #2852 to investigate it further and fix the time lags that user experience right after log in to account with a lot of already received messages when navigate between different screens. 
On 0.9.12+ app version, user account with 1000+ sent/received messages, on Samsung Galaxy S6 emulator, according to https://github.com/status-im/status-react/pull/3045#issuecomment-358315939 seen delay when switching between different screens (Chats -> Wallet -> Chats -> Add new contact -> Chats -> Profile -> Discover -> ...) after log in up to 5 seconds.

In #3045 we added buffer to process incoming messages asynchronously which fixed the crash happening on 0.9.13 app version with the user having 1000+ messages.

This issue dedicated to investigation and complete getting rid of the time lags after log in at all. So that it would not matter for user if he just logged in or used the app for a while - delay between switch from one screen to another should be on similar time level.

#### Expected behavior
No time lags while navigating through different app screens right after user logged in

#### Actual behavior
Time lags while navigating through different app screens right after user logged in

### Reproduction
**Precondition**: User exist and has more than 100 messages sent/received (actually it's even enough 20 messages - depends from device)

1) Open Status
2) Log in to account
3) Navigate through different screens (Profile -> Chats -> Wallet -> Chats -> 1-1 chat -> Back to Chats -> etc)

### Additional Information
* Status version: 0.9.13 from 19th of January (or latest develop 0.9.10-598-g0b035cfa+ from 19th of January)
* Operating System: Android and iOS

TF session with develop 0.9.10-598-g0b035cfa+ build: (From 01:00 till the end) https://app.testfairy.com/projects/4803622-status/builds/7527113/sessions/37/?accessToken=rZSJ6cZQT1BHqjLQr3GoE/1d9VQ - pay attention to taps visible on display and when the actual screen loads

### Additional Information 2 (after new protocol changes - UI is much better but issue still present)
* Status version: develop  0.9.16-2-g1abd3c1a+ (15th of April nightly build)
* Operating System: Android and iOS

TF session: https://app.testfairy.com/projects/4803622-status/builds/8101280/sessions/23/?accessToken=IZiFqBK9ZcBRYCBDbkbuzGFD2Vw

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 0.00
Contract address: [0x1e56f4a4f306a8d3b928b858109f9acd5551213d](https://etherscan.io/address/0x1e56f4a4f306a8d3b928b858109f9acd5551213d)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3095/ea4f48fa6632eb84e5065ad12fc71acf0eedf2b8f9e91c8dacb3f880675966df/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by oskarth** [comment]
This issue is quite old. It might be useful to reformulate it with current more precise impact of it. It also doesn't directly impact chat reliability, which is P0 for chat team. It is however directly impacted by work done in mobile team / 83-energy-efficient.

@rasom @mandrigin @janherich what are your thoughts on this issue?

**Comment by Serhy** [comment]
This issue is outdated with description and it's current results. 

Instead of update again a description here it was reviewed, re-tested and described in two separate new issues: https://github.com/status-im/status-react/issues/4195 and https://github.com/status-im/status-react/issues/4193

**Comment by Serhy** [comment]
Closing it since https://github.com/status-im/status-react/issues/4193 duplicates current issue but with updated results.
