### ISSUE TITLE
Improve "View profile" label that leads to Chat settings screen

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#3386]
### Description

*Type*: Bug

*Summary*: When you open menu of a group chat, the first button says "View profile". It opens Chat settings so I suppose it should be renamed to "Chat settings".

#### Expected behavior
Button that opens Chat settings should have more clear name. Like "Chat settings".

#### Actual behavior
Button is named "View profile".

### Reproduction

- Open Status
- Create a group chat
- Open the group chat
- Click on group chat menu button

### Additional Information
* Status version: 0.9.11d693
* Operating System: iOS and probably Android
* Tested only on iOS 11.2 (iPhone 6)

**Comment by jeluard** [comment]
@lukaszfryc According to the [mockups](https://app.zeplin.io/project/5a55d587ba304eed4d2c942f/screen/5a70319abc98f394488e37ae) it's called `View profile`.

@denis-sharypin Can you comment on that?

**Comment by denis-sharypin** [comment]
It confuses because action link has one name but the following screen has another. When @goranjovic  merges new design for a group chat settings screen it won't have a title and this small problem will be solved. Nevertheless, we can improve clarity and give the button a name: `Group info`. It would have much more sense. If we could make it on the scope of this issue it would be awesome. 

<img width="812" alt="screenshot 2018-02-27 09 58 28" src="https://user-images.githubusercontent.com/6559881/36719239-ceb398c2-1ba4-11e8-9369-c878305d3b38.png">
