### ISSUE TITLE
Status logo (and other screens) are collapsed when user has active call on the background

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#3392]
### Description

*Type*: Bug

*Summary*: Status logo (and other screens) are collapsed when user has active call on the background

#### Expected behavior
no glitches

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/36469736-4f0a9f76-16f9-11e8-9aaf-4f3c450ba329.png)

### Expected 

Here is how Viber behaves:
![image](https://user-images.githubusercontent.com/28752642/36471983-66df7420-1701-11e8-955a-761efa8a8a30.png)

### Reproduction

- Open Status
- Have incoming call and move it to background
- Pay attention to status screens

### Additional Information
* Status version: latest nightly
* Operating System: Android, iOS

**Comment by mandrigin** [comment]
@asemiankevich the logo is expected (try launching other apps that have a logo in the centre when you have an active call).
For the screen, yes, we need to go through them and make sure they work with the call.
Also, Viber isn't a great example, you see that their nav bar is half cut-off.

**Comment by lukaszfryc** [comment]
I think this is common for 90% of the apps. I'll addd `low-severity` and `low-priority` labels

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x1141b66875e56b473856447964f4eb8eea72f210](https://etherscan.io/address/0x1141b66875e56b473856447964f4eb8eea72f210)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3392/461a6095e0ed7ad04396f1e705c9cfddd15546819044c45d4b83d92afb5aabcf/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by asemiankevich** [comment]
@pablanopete please revoke bounty and close issue. Thanks
