### ISSUE TITLE
New 1-1 chat starts with deleted chat history

### ISSUE THREAD

**Issue by Marina-Kovalevich** [status-im/status-react#3527]
### User Story

As a user, I expect that I won't see chat history from deleted 1-1 chat when I start new one.
As there is no button in 1-1 chat "delete history" - so I expect that chat history will be deleted as chat itself.

*Type*: Bug

*Summary*: 
1-1 Chat history is uploaded when start new chat after deleting it 

#### Expected behavior
New chat is started with no chat history.

#### Actual behavior
After deleting 1-1 chat and starting new chat with the same user - chat history appeares in new chat.

### Reproduction
- Open Status
- Tap on Start new chart
- Send anyone from contacts several messages and recieve some
- Delete chat
- Start new chat again

### Additional Information

* Status version:  2018/03/06 03:19:52 UTC

* Operating System: Android

**Comment by asemiankevich** [comment]
@denis-sharypin this is expected behavior for now taking into account we have offline inboxing enabled for 1x1 chat. So when i delete 1x1 chat and start it again i will see all the previous messages. However the second part probably looks reasonable - do not see any option to clear 1x1 chat history for now. What do you think? do we want it? It normally exists in regular messages

**Comment by chadyj** [comment]
We will add the option to delete history covered https://github.com/status-im/status-react/issues/3988
