### ISSUE TITLE
Add 'Selectable' to a Text component on profile and wallet screens

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#3616]
### User Story

As a user, I want to have an opportunity to copy contact codes and wallet address manually.

### Description

*Type*: Feature

Afer a long press, I would like to have an opportunity to copy contact codes and wallet adress through a native platform instrument for iOS and Android. I believe it could be done by adding props `Selectable` to a Text component. Docs: https://facebook.github.io/react-native/docs/text.html#selectable

![slice](https://user-images.githubusercontent.com/6559881/37578810-a29064a4-2b6d-11e8-9298-db780674bcb6.png)
(pic for iOS, on Android it should show its native instrument)

### Reproduction
All three codes that have to be copyable could be found here:

1. User contact code
- Open Status
- Tap `Profile tab`
- Tap `Share my contact code` button
- See Contact code below QR code

2. Wallet address
- Open Status
- Tap `Wallet tab`
- Tap `Receive transaction` button
- See Wallet address below QR code

3. Friends contact code
- Open Status
- Tap `plus button` on a `Home tab`
- Tap `Start new chat`
- Choose contact ex. Jarrad
- See contact profile and contact code on it 

### Additional Information
* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0xb2fc4379141bc90d5e24b5458730ba10078529f4](https://etherscan.io/address/0xb2fc4379141bc90d5e24b5458730ba10078529f4)
Network: Mainnet
Paid to: go1t
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by denis-sharypin** [comment]
@foopang  Do you feel like you can fix this? :)  I really like your contribution!

**Comment by foopang** [comment]
@denis-sharypin Thanks! I will keep an eye on it. I feel that it is a very beginner-friendly task, I guess you may wanna let new contributors work on it first. 
I will quickly submit a PR after a couple of days if no one else is picking up the task :)

**Comment by annadanchenko** [comment]
It's possible to copy values for Contact code and Address so it's OK. 
However, when long tap on these fields in iOS then there is no selection shown, only "Copy" is shown. So user does not see what's selected: https://s3.amazonaws.com/testfairy/screenshots/4803590/7949991/93617113/10_fb7e2d530c6566841f4b853da0423bec72bf8861_o.jpg 
On the design, there is selection and Copy. 
See video (after 00:40) https://app.testfairy.com/projects/4803590-status/builds/7949991/sessions/4/?accessToken=UkeTixXMtI4-5NRr2sy0uV9fhPA

**Comment by go1t** [comment]
@denis-sharypin I can pick this up but just wondering one thing, wouldn't it be a better experience to make this text copied-on-tapped (and on tap we show a little small popup with the text "Address copied to clipboard" or something)? It's less tap that way and there are no other possible actions intended for this text too.

**Comment by denis-sharypin** [comment]
@go1t I thought about that. But decided to go with this solution bc it's simpler and quicker from implementation pov and such behavior consistent and native to the mobile platforms. Otherwise, I need to create a custom alert, then provide animation for this alert and behavior is not consistent with our patterns (it's a button behavior but we don't have buttons here). Later we will probably add a small button to this address which allows to copy this or even replace it with ens username. 

Would be great if you pick up this.

**Comment by go1t** [comment]
Got it. I think the implementation would be about the same since normal `selectable` prop can't provide the highlight behavior (as far as I've searched), so we would need to use TouchableHighlight either way. 

But yeah I agree that adding a copy button would make the most sense. I also have some experience in UI design so I can give this approach a shot as well if you are not available to design this yet. But I can keep going in the original direction as well if you want.

**Comment by denis-sharypin** [comment]
@go1t  thanks! I would happy if we go in the original direction right now.

**Comment by flexsurfer** [comment]
@go1t @denis-sharypin @jeluard guys lets find some compromise because current solution from @go1t is over complicated for this issue, let's just implement standard os copy paste: long tap, select all, copy, wdyt?

**Comment by denis-sharypin** [comment]
Let's add only `Selectable` to the text and that's it

**Comment by go1t** [comment]
@flexsurfer @denis-sharypin @jeluard There are four ways we can go about here:
1. Add `selectable` prop only. This gives no highlight in any state.
2. Add `selectable` prop along with a no-op `on-press` or `on-long-press`. This will give the highlight during the press, but the highlight will go away when the touch is released.
3. The way I'm doing right now, which would give the highlight behavior as the design provided. The reason it's so complicated is because I have to provide an unhighlighting behavior. But if we can compromise by having the text stay highlighted until it's tapped again, things will be MUCH simpler.
4. Replace this Text component with a TextInput (with editable = false and multiline = true). This will give a very similar behavior to the OS's. The image below is after a long tap (no styling yet)
![image](https://user-images.githubusercontent.com/6373626/39598564-daf0c584-4f10-11e8-9e2e-97585c069864.png)

If we can go with the 3rd option with compromise, it will be just the matter of adding an atom to the text component and that's it (essentially a couple extra lines). The 4th option is as simple as adding a selectable prop as well, as it's just replacing the Text with TextInput. Probably need to add some styles but that's it. That's why I think either the 3rd option or 4th option is the better way to go here.

What do you think?

**Comment by jeluard** [comment]
@go1t With option 2, can end users still copy the address content?

**Comment by go1t** [comment]
Yes. It’s just going to be a little confusing since the highlight would show up briefly then go away when the tooltip is there.

But yeah the behavior of option 1 and 2 is an issue on react-native side that has been there for quite a while :/

**Comment by jeluard** [comment]
Can we disable the tooltip? Essentially we need a simple way to copy the address.
@denis-sharypin WDYT?

**Comment by go1t** [comment]
We definitely can. You can see our discussion in the comments above as well.

**Comment by denis-sharypin** [comment]
@jeluard I personally don't want to introduce a new pattern right now (tap on something — get visual confirmation that it's copied with transition animations) 
Initially, this task was proposed as a quick fix using native platform instruments. 
We will def propose some design updates later when we have resources.

**Comment by jeluard** [comment]
@go1t Sorry I guess we will go with your option 4. then, if you can make it look like initial screenshots.

**Comment by go1t** [comment]
got it!
