### ISSUE TITLE
Cleared message history reappears in Group and Public chats with all received messages

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#3719]
***Type***: Bug

***Summary***: Cleared chat history reappears after contact re-log in with all received messages prior chat history in the Group/Public chat

#### Expected behavior
No reappearance of cleared message history after re-login in Group and Public chats
#### Actual behavior
Reappearance of cleared message history after re-login  in Group and Public chats with all **received** messages

### Reproduction

- Log in to Status on Device 1 and Device 2 as 'Contact 1' and 'Contact 2' respectively
- Contact 1 adds Contact 2 in contacts 
- Contact 1 creates Group Chat with Contact 2
- Contact 1 and Contact 2 joins the same Public Chat (e.g. `newprotocolworks`
- Contact 1 sends 10 messages in Group Chat
- Contact 1 sends 10 messages in Public Chat
- Contact 2 navigates to Group Chat and clears it's history
- Contact 2 navigates to Public Chat and clears it's history
- Contact 2 re-logins and stays on Home screen

### Additional Information
Status version: b33bd65
Operating System: Android and iOS

#### Logs
TF session with logs from Android (Contact2 in above scenario): https://app.testfairy.com/projects/4803622-status/builds/7985879/sessions/49/?accessToken=DvEKf92szvy4Hiq7cE5z2cq7zw8

**Comment by cammellos** [comment]
@Serhy I can replicate in current develop (public chats), can you do the same?

**Comment by yevh-berdnyk** [comment]
@Serhy, @cammellos, I've also reproduced it in nightly build

**Comment by Serhy** [comment]
Retested the scenario from description on 323rd Jenkins nightly build and could not reproduce it on Android and iOS.

**Comment by janherich** [comment]
The issue is fixed in `experiment/new-protocol-app` branch @Serhy .
It was little bit more tricky, because the root cause of the issue (which is for sure present in develop as well, it's just not reproducible 100% of time) is the fact the we need to know past message ids to be able to reject them when they are received again - once we truly hard delete messages from app-db and realm, there is no way to know that we ever received them - so when we start app again, request messages from offline inbox servers and those old messages are received (we unfortunately can't rely on offline inboxing being accurate and only delivering messages which were sent to us while we were offline, we always just receive *all* the messages and it's our responsibility to filter out those we already have), we have no way to distinguish that we don't want to receive "cleared" messages, so they are received and displayed again.
The (hacky) solution is not hard delete messages when clearing history, only set the `:show?` property to false, that way they will be effectively hidden from UI, while we still have knowledge about them and can protect against receiving them again.
Much better and more efficient solution would be to rely on last clock value for such things, but as it won't work for public/group chats currently, we can't use it, but we should revisit the implementation in the future.

**Comment by Serhy** [comment]
Thanks a lot, @janherich for clarification! 
So as the the issue in Develop and new-protocol-app and fixed in the experiment/new-protocol-app - we can close the issue after new-protocol is merged and we validate bug is gone in Develop. 

However, I'll check it in scope of `experiment/new-protocol-app`.

**Comment by Serhy** [comment]
In the next builds Android: https://i.diawi.com/xXkFsd and iOS: https://i.diawi.com/dTtQ2K (194th Jenkins build) issue not reproduced anymore! 
The only exception is that I wasn't able to check GroupChat on non-admin side due to app crash - described in https://github.com/status-im/status-react/issues/3702#issuecomment-378319563 

Once it passes develop along with the test covered GroupChat - we are good!

<blockquote><div><strong><a href="https://i.diawi.com/xXkFsd">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://i.diawi.com/dTtQ2K">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

**Comment by Serhy** [comment]
Tested in latest nightly - can't reproduce anymore. Cleared message history in Group/Public chat doesn't re-appear.
Happy to close it!
