### ISSUE TITLE
Error when removing DApp

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3841]
### Description

When removing DApp from chat list by swiping and tapping Delete icon, error is thrown:

```
re-frame: no handler registered for effect: "', { ns: null,
04-11 17:21:31.566 17161 17292 E ReactNativeJS:   name: 'remove-browser',
04-11 17:21:31.566 17161 17292 E ReactNativeJS:   fqn: 'remove-browser',
...
```

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open any DApp
- Close DApp
- Open Home screen
- Swipe over DApp
- Tap Delete icon

### Solution

Seems like we don't have `remove-browser` fx but having `data-store/remove-browser`

https://github.com/status-im/status-react/blob/0bf41ace67436db65389b750079ff78e4b56607d/src/status_im/ui/screens/browser/events.cljs#L73

### Screenshot

<img width="414" alt="screenshot 2018-04-11 20 20 38" src="https://user-images.githubusercontent.com/23836/38632801-74294b9c-3dc6-11e8-9ed1-c9a34d78cb6d.png">

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xb9d815634d068875191a161a71c1a8532b1d0679](https://etherscan.io/address/0xb9d815634d068875191a161a71c1a8532b1d0679)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3841/4766404e49d67d92b5fe4eda66c05c635890e60f7574d471228f3da6375a702f/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by dmitryn** [comment]
Closing this manually as related PR has been merged.

**Comment by endenwer** [comment]
@dmitryn How can I claim this bounty? There is no my claim for this bounty in activity page. Maybe this because I set payment details after submitting bounty. So I lost the reward?

**Comment by dmitryn** [comment]
@endenwer there is no way to claim it after PR has been merged. 
Your reward will be processed manually by @andytudhope

**Comment by andytudhope** [comment]
Hey @endenwer - sorry about the confusion on this one and thanks so much for submitting a good fix!

Here is your payment: https://etherscan.io/tx/0xcc0ef39f9fc0363c23eb07d11fe4d7659c404975fac9309e965a8aeb164f6fb0

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://etherscan.io/tx/0xcc0ef39f9fc0363c23eb07d11fe4d7659c404975fac9309e965a8aeb164f6fb0">Ethereum Transaction 0xcc0ef39f9fc0363c23eb07d11fe4d7659c404975fac9309e965a8aeb164f6fb0</a></strong></div><div>Ethereum (ETH) detailed transaction info for 0xcc0ef39f9fc0363c23eb07d11fe4d7659c404975fac9309e965a8aeb164f6fb0</div></blockquote>
