### ISSUE TITLE
Fix mailserver configuration change

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#3913]
When the mailserver configuration is changed:
- make sure that  the previous mailserver is disconnected from peers (will involve json_rpc API)
- the new one is added (should already be done by calling initialize-offline-inbox)
- do not logout  when saving mailserver config

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 1370.00
Contract address: [0xfc444a89aa6ebc6458a0067f13e768dc921f012f](https://etherscan.io/address/0xfc444a89aa6ebc6458a0067f13e768dc921f012f)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/3913/271b0f8c69c5d9732405eac2ffb491856914cbcd4772d4b392d9094e892f33fe/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by debragail** [comment]
intialize-mailserver does not exist.  please define.

**Comment by debragail** [comment]
should init-mailserver and stop-mailserver function like init-whisper and stop-whisper?

**Comment by debragail** [comment]
ping @yenda

**Comment by yenda** [comment]
I updated the issue according to recent changes
