### ISSUE TITLE
Use :npm-deps false to speed up Figwheel startup

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-react#3932]
### Description

Latest version of ClojureScript supports `:npm-deps false` compiler option.
It might speed up Figwheel start by 20-45 seconds https://github.com/bhauman/lein-figwheel/pull/678
https://twitter.com/mfikes/status/986040242997284865?s=09

### Solution

Add `npm-deps false` compiler option to dev builds. Compile builds for ios and android. Check if it increases Figwheel perfomance.

<blockquote><img src="https://pbs.twimg.com/profile_images/909773383902142464/0JAdYoeO_400x400.jpg" width="48" align="right"><div>Twitter</div><div><strong><a href="https://twitter.com/mfikes/status/986040242997284865">Mike Fikes on Twitter</a></strong></div><div>“If you have a ClojureScript project where there also just happens to be a node_modules directory sitting there that ClojureScript itself doesn’t actually use (for example for React Native), :npm-deps false will be your new best friend. (It saves me 20 to 45 seconds of startup.)”</div></blockquote>

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 375.00
Contract address: [0xfda8e90578d0408f7d4f3e3f4dc3b469efa2e16c](https://etherscan.io/address/0xfda8e90578d0408f7d4f3e3f4dc3b469efa2e16c)
Network: Mainnet
Paid to: endenwer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by debragail** [comment]
Can you post the current performance metrics and logs?

**Comment by debragail** [comment]
https://github.com/bhauman/lein-figwheel/pull/678

**Comment by dmitryn** [comment]
I don't have one. It's actually in scope of this issue to collect and compare such metrics.

**Comment by debragail** [comment]
It looks like you use he node_modules folder according to this file:

findSymlinkedModules.js.patch

/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @format
 * @flow
 */

const path = require('path');
const fs = require('fs');

/**
 * Find symlinked modules inside "node_modules."
 *
 * Naively, we could just perform a depth-first search of all folders in
 * node_modules, recursing when we find a symlink.
 *
 * We can be smarter than this due to our knowledge of how npm/Yarn lays out
 * "node_modules" / how tools that build on top of npm/Yarn (such as Lerna)
 * install dependencies.
 *
 * Starting from a given root node_modules folder, this algorithm will look at
 * both the top level descendants of the node_modules folder or second level
 * descendants of folders that start with "@" (which indicates a scoped
 * package). If any of those folders is a symlink, it will recurse into the
 * link, and perform the same search in the linked folder.
 *
 * The end result should be a list of all resolved module symlinks for a given
 * root.
 */
module.exports = function findSymlinkedModules(
  projectRoot: string,
  ignoredRoots: Array<string> = [],
) {
  const timeStart = Date.now();
  const nodeModuleRoot = path.join(projectRoot, 'node_modules');
  const resolvedSymlinks = findModuleSymlinks(nodeModuleRoot, [
    ...ignoredRoots,
    projectRoot,
  ]);
  const timeEnd = Date.now();

  console.log(
    `Scanning folders for symlinks in ${nodeModuleRoot} (${timeEnd -
      timeStart}ms)`,
  );

  return resolvedSymlinks;
};

function findModuleSymlinks(
  modulesPath: string,
  ignoredPaths: Array<string> = [],
): Array<string> {
  if (!fs.existsSync(modulesPath)) {
    return [];
  }

  // Find module symlinks
  const moduleFolders = fs.readdirSync(modulesPath);
  const symlinks = moduleFolders.reduce((links, folderName) => {
    const folderPath = path.join(modulesPath, folderName);
    const maybeSymlinkPaths = [];
    if (folderName.startsWith('@')) {
      const scopedModuleFolders = fs.readdirSync(folderPath);
      maybeSymlinkPaths.push(
        ...scopedModuleFolders.map(name => path.join(folderPath, name)),
      );
    } else {
      maybeSymlinkPaths.push(folderPath);
    }
    return links.concat(resolveSymlinkPaths(maybeSymlinkPaths, ignoredPaths));
  }, []);

  // For any symlinks found, look in _that_ modules node_modules directory
  // and find any symlinked modules
  const nestedSymlinks = symlinks.reduce(
    (links, symlinkPath) =>
      links.concat(
        // We ignore any found symlinks or anything from the ignored list,
        // to prevent infinite recursion
        findModuleSymlinks(path.join(symlinkPath, 'node_modules'), [
          ...ignoredPaths,
          ...symlinks,
        ]),
      ),
    [],
  );

  return [...new Set([...symlinks, ...nestedSymlinks])];
}

function resolveSymlinkPaths(maybeSymlinkPaths, ignoredPaths) {
  return maybeSymlinkPaths.reduce((links, maybeSymlinkPath) => {
    if (fs.lstatSync(maybeSymlinkPath).isSymbolicLink()) {
      const resolved = path.resolve(
        path.dirname(maybeSymlinkPath),
        fs.readlinkSync(maybeSymlinkPath),
      );
      if (ignoredPaths.indexOf(resolved) === -1 && fs.existsSync(resolved)) {
        links.push(resolved);
      }
    }
    return links;
  }, []);
}

**Comment by debragail** [comment]
Also I don’t know react native tooling that well but it seems to be an issue with 16:

https://github.com/facebook/react-native/issues/15371
