### ISSUE TITLE
Messages with certain occurance of elipsis(as three periods) gets rendered as link.

### ISSUE THREAD

**Issue by yalu** [status-im/status-react#4073]
Messages (at-least in public chats) with elipsis(as three periods) gets rendered as link. clicking open in browser crashes the  app.

### User Story

As a chat user I am in the habit of writing lots of elipsis in messages i write. 

### Description

*Type*: Bug

When i sent a test message in #status public chat in couple of recent nightlies, due to my habit, I accidentally bumped into this bug, whereby the messages with elipsis gets turned into link for no reason.

#### Expected behavior
Message with elipsis renders as normal text message.

#### Actual behavior
Message gets turned into link. 

### Reproduction
Send a message like so "test...test...".

- Open Status
- Login
- Open #Status public chat
- Send message "test...test..." (without the quotes)

### Solution
Don't know.

### Additional Information
* Status version: im.status.ethereum-c145c8.apk
* Operating System: Android/Leneage OS 15.1 for oneplus_2

**Comment by Serhy** [comment]
I'm wondering if we can use (if we are not yet) https://www.npmjs.com/package/react-native-autolink (Autolinker.js) to parse message content. If it won't have an impact in performance degradation on chat screen - lets use it, instead of custom regexp. 
``` 
urls: {
        schemeMatches : true,
        wwwMatches    : true,
        tldMatches    : true

    stripPrefix : false,
    stripTrailingSlash : false,
    newWindow   : false,
```
does the job pretty well and most of the issues with highlighting non-URI related text could be solved (i checked it here http://greg-jacobs.com/Autolinker.js/examples/live-example/)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 700.00
Contract address: [0x6a72825daa1234b7238c7a4b963488ecf581ea89](https://etherscan.io/address/0x6a72825daa1234b7238c7a4b963488ecf581ea89)
Network: Mainnet
Paid to: trybeee
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
