### ISSUE TITLE
Can't leave a chat ? Unhandled Promise Rejection

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#414]
Just added someone, went to chat with them, then tried to press back button and got this Unhandled Promise Rejection
Pressing physical back button brings me out of application, to launcher

![unhandled-promise](https://cloud.githubusercontent.com/assets/2714786/19956711/8dd11bea-a1ca-11e6-846c-71c29bd54951.png)

**Comment by jarradh** [comment]
![unhandled-full-error](https://cloud.githubusercontent.com/assets/2714786/19956754/d2c809fc-a1ca-11e6-9d59-0ba5bdfb0019.png)

**Comment by alwx** [comment]
This problem is described and already fixed, but not merged to React Native.
https://github.com/facebook/react-native/issues/10236
https://github.com/facebook/react-native/pull/10421

For now, we can simply ignore it because yellow boxes won't appear in the release. After RN update the problem will probably be gone.

**Comment by jarradh** [comment]
> After RN update the problem will probably be gone.

sure... :)
