### ISSUE TITLE
Updates on signing phrase and password popups

### ISSUE THREAD

**Issue by denis-sharypin** [status-im/status-react#4162]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I don't want to be confused by messing up a password and signing phrase.

### Description

*Type*: Improvement

Current problems with the signing phrase popup are:

1. Confusing UI. This came up from UXR sessions: users tried to type signing phrase into the password field. 
2. Tied to a specific layout. Confirmation and cancel buttons currently take place outside popup that triggered a problem with the implementation of this popup for different use cases (sign a message to login into Dapp, also it could be used in the `paid master node` feature)

#### Expected behavior

![slice](https://user-images.githubusercontent.com/6559881/39766860-99c96ede-52e5-11e8-8be9-9f60c5863937.jpg)

Mockups in Zeplin — https://app.zeplin.io/project/5a55d587ba304eed4d2c942f?seid=5af2c256e817e05b24908352
(provide your email to be added to a Zeplin project) 

Prototype with logic and animations 
https://www.dropbox.com/s/kbkpjiw8xw23cv5/17_signing%20phrase%20popup.mov?dl=0

#### Actual behavior

![image](https://user-images.githubusercontent.com/6559881/39766847-907e7b76-52e5-11e8-9946-38a03e1d9b56.png)

### Reproduction

- Send transaction

### Additional Information

* Operating System: Android|iOS

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0xdca8e4e8bbebceb51245aa11a96c805e93514c35](https://etherscan.io/address/0xdca8e4e8bbebceb51245aa11a96c805e93514c35)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4162/b20871a0e3d6b7a0cac2c69f2740d780e9b39a7f37e76a0af36288c477a16de0/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by denis-sharypin** [comment]
FYI: design and scope of the issue are outdated. Will be updated soon

**Comment by goranjovic** [comment]
Closing as outdated
