### ISSUE TITLE
Show Opt Metrics screen right after login

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4253]
### User Story

As a user|, I don't want to be distracted especially when I use the app for the very first time, so I have a good user experience

### Description

*Type*: Bug

*Summary*: We need to improve Opt Metrics screen appearance which is shown after I create or recover the account. It is shown after ~1 second after I create an account (not each time but in some cases) and ~2 seconds when I recover it (it happens more often) so I see the Home screen for a while and then this screen appears. I find it personally a bit distracting.  We need to show this screen right after the user is logged (for new or recovered account) so he won't see the Home screen before.

#### Expected behavior

Opt Metrics screen is shown right after login (for new and recovered account flows)

#### Actual behavior
Home tab is shown for a second and then Opt Metrics screen pops up and distracts me

### Reproduction

- Open Status
- Create account
- Recover account

### Additional Information
* Status version: develop
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x466c39f86d248989c8518a5275c4d4cede672896](https://etherscan.io/address/0x466c39f86d248989c8518a5275c4d4cede672896)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4253/0d16a0967d84cedbc12a8771ab6aaf41f2bbc880648a9b7a77d4013d4b4b091d/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by chadyj** [comment]
Closing since this feature is no longer in the app
