### ISSUE TITLE
Can't transfer funds from Status to Metamask account (Ropsten - Ropsten)

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4297]
### User Story

As a user I want to transfer funds easily between Status and Metamask

### Description

*Type*: Bug

*Summary*: Error shown when trying to scan and send funds from Status to Metamask account

#### Expected behavior

No erros, I can scan the Metamask code with Status and proceed. NOTE: works in Mainnet -> Mainnet

#### Actual behavior

Ropsten -> Ropsten

![image](https://user-images.githubusercontent.com/28752642/40113274-957e953e-5911-11e8-9d74-c2a293595187.png)

![image](https://user-images.githubusercontent.com/28752642/40113365-e2cf3dc0-5911-11e8-938f-01b8f7245772.png)

### Reproduction

- Open Status
- Open Metamask account
- Wallet - > send transaction - Chose recipient - Scan code
- Scan the Metamask code to send funds

### Additional Information
* Status version: nightly
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 920.00
Contract address: [0x5da381c23d7cdba2b38b7a55ef87e28d97a57f6a](https://etherscan.io/address/0x5da381c23d7cdba2b38b7a55ef87e28d97a57f6a)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4297/655427de6f3d1147a3018d268764e8a47a8c46562fe6cd58f6576ade06e7f55b/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by jeluard** [comment]
This is due to MetaMask not fully implementing the [EIP681 standard](https://eips.ethereum.org/EIPS/eip-681). To be compliant, an extra identifier related to ropsten should be present.

To mitigate this status could show a warning and allow users to proceed anyway.

**Comment by t1MZXxBn6pAAtTqKTy5UotdeMqBw2CfGrUF** [comment]
TESTFAIRY_ENABLED=1
STUB_STATUS_GO=0
ETHEREUM_DEV_CLUSTER=1
OFFLINE_INBOX_ENABLED=1
LOG_LEVEL=debug
LOG_LEVEL_STATUS_GO=info
JSC_ENABLED=1
QUEUE_MESSAGE_ENABLED=1
RN_BRIDGE_THRESHOLD_WARNINGS=0
MIXPANEL_TOKEN=3f2e1a8970f159aa2a3d5dc5d65eab38
TESTFAIRY_TOKEN=969f6c921cb435cea1d41d1ea3f5b247d6026d55
POW_TARGET=0.002
POW_TIME=1
DEFAULT_NETWORK=mainnet_rpc
INSTABUG_TOKEN=758630ed52864cbad9c5eeeac596c60c
DEBUG_WEBVIEW=1
INSTABUG_SURVEYS=1
GROUP_CHATS_ENABLED=0
FORCE_SENT_RECEIVED_TRACKING=1
SPAM_BUTTON_DETECTION_ENABLED=1
MAINNET_WARNING_ENABLED=1

**Comment by Neurone** [comment]
@jeluard I think there is a misunderstanding:
- @asemiankevich is scanning a QR code representing an ethereum address, not a _transaction request_
- The problem is clearly in MetaMask: if you scan a plain QR code - i.e. generated by Etherscan - it works well
- MetaMask [_blindly_ inserted the "ethereum:" prefix a year ago](https://github.com/MetaMask/metamask-extension/pull/1592) as a quick and dirty fix to support a [_strange behaviour_ of Coinbase](https://github.com/MetaMask/metamask-extension/issues/1558), they were not trying to implement EIP681 (it didn't even exist at that moment)

I think Status **should not change its correct behaviour to follow the mistakes of others**, and  even changing an error message to a simple warning could reduce security for non-tech-savvy user.

**Comment by jeluard** [comment]
The idea is to not hard fail when reading a transaction request missing the network id. Which is the majority of QR code around AFAIK.

**Comment by Neurone** [comment]
Yes. In fact it works well and it does not hard fail if it is on the mainnet, because missing network id means mainnet. But if the user is on another network (i.e. ropsten) I'm sure it is better continuing to hard fail (maybe with a more clear popup message) then sending a warning and let the user proceed.

**Comment by PaulRBerg** [comment]
Sorry if this is not the best place to ask, but this issue still appears on the bounties [platform](https://openbounty.status.im/app#/). Is it still available? It seems to be moved to "PR Submitted", but all I see is the MetaMask EIP-681 issue opened. Is it that Status won't even temporarily update its codebase and this issue simply sits in limbo until MetaMask fixes their stuff?

**Comment by jeluard** [comment]
@PaulRBerg It's not sorry :(

**Comment by pablanopete** [comment]
To be revoked @andytudhope
