### ISSUE TITLE
ensure discover status are signed and verified

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#436]
Statuses in discover should be tamper-evident

**Comment by jarradh** [comment]
ethereum/web3.js#392 describes how this should work, a message comes along with signature and address of signer. Then use `ecrecover` to regen the address, if it doesn't match we should discard immediately and not propagate the message.

**Comment by jarradh** [comment]
Probably not a bad idea to generalise this and add to every message we're sending around.

**Comment by alwx** [comment]
This task is painful. I've spend this day working on it, but still don't have any good result.

The biggest problem is `ethereumjs-util` package doesn't work with React Native (for the same reason we need to use `react-native-crypto` instead of `crypto`). I've tried to replace it with `elliptic` (https://github.com/indutny/elliptic), and had a success, but there is some work left to be done.

The second problem is web3.eth.sign requires the account to be unlocked (https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign), which means that we need to ask user for a password each time user sends a status or store user's password somewhere. To be honest, I don't really like both options.
Anyway I am going to spend a bit more time (no more than 2-3 hours) investigating this problem before switching to https://github.com/status-im/status-react/issues/550

**Comment by jarradh** [comment]
Okay let's put a pin in this after alpha

**Comment by jarradh** [comment]
Initial thoughts on this is, our ability to `sign` should be available from login, but this method should be treated like `sendTransaction` and the ability for the user to remember (which isn't implemented).

As for the `react-native-crypto` yeah it sounds like we should adapt this in the manner you've already started, perhaps we can expose it to jail.

Thanks for identifying the hurdles!

**Comment by farazdagi** [comment]
@jarradh I can expose `SignWithPassword` method (which is available in private go-ethereum API), if this makes things easier.

Or, alternatively, as you've said, we can intercept calls to `Sign`, and notify application upwards, so that user's password can be obtained, and then in `CompleteSign` signing attempt is made (and `Sign` is unblocked with success or error response).

**Comment by jarradh** [comment]
https://github.com/flyswatter/js-eth-personal-sign-examples

**Comment by alwx** [comment]
wow
thank you, @jarradh. will check it soon

**Comment by alwx** [comment]
I've updated the code — now PR #822 uses `personal_sign` and `personal_ecRecover` and everything works fine.
However, `personal_sign` requires a password as the third argument. According to the example (https://github.com/flyswatter/js-eth-personal-sign-examples/blob/master/index.js), it works without password in MetaMask, so this task probably requires some changes in Go code (@farazdagi, please, take a look).

Alternatively, we can obtain a user's password and use it without asking, but I am not sure that it is a good idea.
