### ISSUE TITLE
Amount field is limited to 21 characters 

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4404]
### Description

*Type*: Bug

*Summary*: Can't enter 18 digits after the comma for the 4-digit amount, for example, I want to send or request `1000,111111111111111111` tokens

#### Expected behavior

I am able to send any valid amount with the 18 digits limit after a comma, no matter how many digits before comma I have, for ex `1000,111111111111111111` . See also other 2 restrictions in comment https://github.com/status-im/status-react/issues/4404#issuecomment-397707306

#### Actual behavior
The field is limited so entering `1000,111111111111111111`  is not possible

### Reproduction

- Open Status
- Open wallet
- Having 2000 tokens try to send 1000,111111111111111111 
- Try to request 1000,111111111111111111

**Comment by mandrigin** [comment]
@asemiankevich I'd say that is an `xs` size bounty :)

**Comment by asemiankevich** [comment]
@mandrigin thanks!

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 500.00
Contract address: [0xc757cdbdf804f9c636cac6ee2005249d0def7fe5](https://etherscan.io/address/0xc757cdbdf804f9c636cac6ee2005249d0def7fe5)
Network: Mainnet
Paid to: goranjovic
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by oskarth** [comment]
Why is this a beta blocker? Seems like a minor ish bug to me.

**Comment by annadanchenko** [comment]
@chadyj @oskarth This issue is only one example of having 21 characters as a limit for Amount field. The other consequences are:
1. If you copy/paste amount longer than 21 characters then field silently cuts it to first 21 characters. For example: 
12345678.123456789012345678 is transformed to 
12345678.123456789012 
The more characters you will have before the comma the more will be cut at the end of sum. 
2. If you typed or pasted long "tail" before entering main part 0.123456789012345678 and then try to edit sum and modify it's "head" from 0 to 1000 you will not be able to do this because field does not react on your typing. So you need to guess that all sum should be deleted and you need to type most significant amount first.

imo, we need to fix this artificial limit that results in narrowing user choices and in case of pasting long amount into actual loosing its last part without any warning to the user.

**Comment by chadyj** [comment]
Followed up with Anna:
* Low probability of users encountering this
* Low impact for negative consequences (eg loss of funds, crashes, etc)
* Therefore not a beta blocker, but we will work on it after beta
* This is a reminder that the beta isn't perfect, and we should communicate this to users in release notes, etc.

**Comment by asemiankevich** [comment]
send / request huge amounts looks good to me, was able to do so from wallet and 1x1 chat
