### ISSUE TITLE
Add indicator of unread messages (OSX dock bar)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4433]
### User Story

As a user, I want to see so that that I have unread messages in app

### Description

*Type*: Feature
*Summary*: add the red badge of unread messages, like 
![unread](https://user-images.githubusercontent.com/4557972/40484398-1ef740a6-5f64-11e8-8177-ce0c100d1262.png)
Not implemented in mobile.

**Comment by EugeOrtiz** [comment]
Just to clarify, this is in the OS Dock. Aesthetically speaking, it should follow the standard OS X guidelines. Let me know if you need an actual design for this.

**Comment by dmitryn** [comment]
It probably makes sense to wait for https://github.com/status-im/status-react/pull/5330 https://github.com/status-im/status-react/issues/4432 to be done since this issue requires communication with native API. For OSX this could be:
```obj-c
[[NSApp dockTile] setBadgeLabel:[NSString stringWithFormat:@"%d", newCount]];
```

Maybe it makes sense to add this code to snorenotify repo https://github.com/status-im/snorenotify/blob/master/src/plugins/backends/osxnotificationcenter/osxnotificationcenter.mm to avoid routine of creating new module just to make single API call.

@MaxRis what do you think?

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/snorenotify">status-im/snorenotify</a></strong></div><div>Snorenotify is a multi platform Qt notification framework. Using a plugin system it is possible to create notifications with many different notification systems on Windows, Mac OS and Unix and mobi...</div></blockquote>

**Comment by maxhora** [comment]
@dmitryn extending Snorenotify should be great idea!

**Comment by maxhora** [comment]
p.s. current logic to show notifications through Snorenotify is not what we want: currently, it shows first 3 unread messages; but we want it dynamically update last 3rd unread message to the latest received one.
Above internal logic might have side effect on detecting of correct amount of unread messages on `osxnotificationcenter.mm` low level.

**Comment by maxhora** [comment]
it has more sense to start working on this after https://github.com/status-im/status-react/pull/5330 will be merged (I expect this will happen next week)

**Comment by chadyj** [comment]
@dmitryn This is unblocked now, right?

**Comment by dmitryn** [comment]
@chadyj right, going to update it to the latest develop and send it to review.
