### ISSUE TITLE
Error Invalid address is shown twice when scanning incorrect wallet address on iOS

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#4455]
### User Story

As a user, I want to be notified about scanning invalid wallet QR code so that I can close error dialog tapping it once.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Error pop up is shown twice when scanning invalid wallet QR code for sending transaction from wallet

#### Expected behavior
Error pop up is shown only once

#### Actual behavior
Errors `Invalid address...` and `Network doesn't match...` are shown twice. User should click `OK` button two times to close the error pop up

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Open wallet
- Click `Send transaction` button
- Click `Choose recipients` -> `Scan QR code` and scan some not valid code (i.e public key code or wallet with another network selected)

### Additional Information
* Status version: `09c11e90 (5aae87a)`, nightly build from May 25
* Operating System: iPhone 8+, iOS 11.3.1

**Comment by status-open-bounty** [comment]
Current balance: 0.000000 ETH
Contract address: [0x2bc8d5a0eebb45805f32357058522b38178abd5b](https://etherscan.io/address/0x2bc8d5a0eebb45805f32357058522b38178abd5b)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4455/2fc6f4608ca0d2731907f2be150c86990eb212a7901b37160fc0e0689674020b/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
