### ISSUE TITLE
Add visual marker indicating start of unread messages in chat

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#4607]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see a horizontal indicator in chats whenever there are unread items so that I can clearly see where I need to start reading to pickup on unread items (especially important when you have a public chat with dozens of unread items). cc @andmironov 

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: 

![image](https://user-images.githubusercontent.com/138074/40887670-5f80d55c-674c-11e8-93e7-d74b50210f45.png)

**Comment by rachelhamlin** [comment]
Have a few Instabug requests for this! In the future it would be awesome if we could start users where they left off.

**Comment by andmironov** [comment]
we had UI explorations about this, will prep up some mockups and share

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xbf4d6f5d0442fd0e05a973f266d059ba088c16e9](https://etherscan.io/address/0xbf4d6f5d0442fd0e05a973f266d059ba088c16e9)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4607/8d66f14ce7b8bb84845e2261a15c59b097ce6d1643181c38c708dcef1e21df87/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by andmironov** [comment]
working on it, will share today

**Comment by andmironov** [comment]
https://github.com/status-im/status-react/issues/4690

**Comment by andmironov** [comment]
https://github.com/status-im/status-react/issues/4691

**Comment by andmironov** [comment]
https://github.com/status-im/status-react/issues/4694
