### ISSUE TITLE
Restore account from JSON keystore

### ISSUE THREAD

**Issue by pablanopete** [status-im/status-react#4614]
### User Story
As a advanced user, I want to be able to restore my accounts from more than a mnemonic key recovery. To include JSON Keystore, private key plain text etc. 

### Description
In Status I would like to be able to restore my account that holds all of my ERC721 tokens that was previously generated with a json keystore into status. Alternatively I would like to be able to put my private key in plaintext as a restoration mechanism as well as an advanced option.

example of another mobile wallet that allows this convenient feature for advanced users

![img!UNITO-UNDERSCORE!1818](https://user-images.githubusercontent.com/18363825/40891789-85c8ce90-6751-11e8-96b6-8c3055590599.jpg)

#### Actual behavior
I can only restore my other account from mnemonic phrase

### Solution
Design input needed on a place where this can be done from the recover account section

**Comment by 26000** [comment]
@pablanopete could you possibly tell what wallet is on the screenshot? i want to generate an ethereum address which i wouls be able to access from anywhere, at least status.im and mist. i currently see no way to do it, you aren't able to import an account from seed to mist or import a keyfile to status. and metamask seeds seem to be incompatible with status.

**EDIT:** i was wrong, status.im just displays something which is not a wallet address on the login screen so i thought it hasn't imported it successfully.

**Comment by DarthJahus** [comment]
Hello, I'd like to add up my voice to this query.

Status being an "explorer for decentralized applications", it should consider as many ways as possible to transfer people from actual wallet solutions (like MetaMask, MyEtherWallet/MyCrypto, etc.) because people would like to keep the same address through their devices, or – if they have already signed up to some DApps – would like to keep their account when they migrate to Status.

MetaMask offers a mnemonic backup only when set up for the first time. If the user haven't written down his mnemonic, he can still get his raw Private Key, and in this case, can't use it in Status.

MyEtherWallet and MyCrypto use JSON KeyStore and raw private keys. There's no easy way to derivate a menomonic from there. Hence, people who initially have their tokens, ether and DApp accounts linked to that wallet can't use them on Status.

**Comment by DarthJahus** [comment]
Any word from the devs regarding this feature request?

**Comment by StatusSceptre** [comment]
There's been multiple asks of this as an advanced option for users as someone mentioned in a status channel they have a private key they'd like to import into status that's derived from a master seed on metamask but they cannot currently import that wallet. @denis-sharypin @errorists @andmironov could you help provide a small mockup of this as an advanced option to integrate as a bounty? (options for private key, keystore)

Want to make sure the community has functionality they've requested.

**Comment by pablanopete** [comment]
Another user story from the community this will help 

"Mostly issue is I created/verified a peepeth account, so was trying to log into it through status; But as the 2nd wallet was made within metamask it's hard"

In this case the metamask account was created through the same master seed but a separate wallet (private key) and cannot be recovered to use in status.

**Comment by denis-sharypin** [comment]
сс @rachelhamlin

**Comment by StatusSceptre** [comment]
Just a comment here, can put on whatever priority level needed as I know there are certainly more pressing isssues. Just keeping this here as documenting this for the community because it’s been asked of me so many times.

**Comment by rachelhamlin** [comment]
FYI @StatusSceptre I totally see the value in this, but - @denis-sharypin is prioritizing keycard & teller network right now, I believe.

@denis-sharypin are you booked out on those swarms for the time being, or can you provide screens for a bounty? Feels like at least a medium bounty to me.

Also worth CC'ing @guylouis. Guy Louis, this user request to support JSON keystore has been idling for a while. Do we have any development bandwidth to consider it?

**Comment by denis-sharypin** [comment]
I think this stuff is more related to a profile area of work. And @andmironov is in charge for it. @andmironov dude, will you have time for this?

**Comment by guylouis** [comment]
@rachelhamlin I clearly see the value in this too. 
I also think we have more pressing issues in the coming weeks to tackle though. Keycard/Wallet team is pretty much fully focused on getting to a Keycard integration MVP point.

**Comment by StatusSceptre** [comment]
all, do we want to continue and add a bounty to this, or remove it?

**Comment by guylouis** [comment]
If the point is about using this private key as the master seed of the HD tree as an alternative to mnemonic, it's more of an onboarding question than a wallet one. My feeling is that we want to make onboarding as simple as possible, and I wouldn't complexify it with another way to import the master seed. 

On the other hand, as part fo the multiple account management across status and in the wallet, we know we want to be able to monitor any public key (even outside the HD tree), and we could think of extending that and import a keypair (public & private key) outside the HD tree too. This would answer the need, and would be a better answer since a user could still use his Status identity and use this keypair also. This keypair would be treated as a single keypair, and not a new HD tree of course. This is actually exactly what metamask does.

what do you think of it ?

**Comment by rachelhamlin** [comment]
Ding ding. To that end, not something to bounty right now.

**Comment by StatusSceptre** [comment]
ok, removing label and wiping off the bounty tracker, add it again if you want it back into consideration.

**Comment by leafcutterant** [comment]
I'd like to join those who have been asking for this, I believe, quite essential wallet functionality.

Status is basically useless to me without this.

**Comment by vitorgomesgomes** [comment]
nice

**Comment by vitorgomesgomes** [comment]
nice

**Comment by vitorgomesgomes** [comment]
bug bounty
