### ISSUE TITLE
Change Return keyboard button to Done while setting user name

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4650]
### Description

*Type*: Bug

*Summary*: It makes sense to change the "return" button to "Done" in this screen:

<img src="https://user-images.githubusercontent.com/7532782/41024008-46ff4c9c-696e-11e8-9128-19f545bed4d6.png" width="200">

### Reproduction

- Open Status
- Click create new account button
- Provide password and password confirmation and go to next step

### Additional Information
* Status version: June 6
* Operating System: Android, iOS

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x0eb699a99a8c325bf6dc04f39e0948db2675ac63](https://etherscan.io/address/0x0eb699a99a8c325bf6dc04f39e0948db2675ac63)
![QR Code](https://openbounty.status.im/qr/status-im/status-react/bounty/4650/3e482db134ff49e45ecd750b6ff38394ed3d1cf5239526217733efaf5f5e7f30/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by pablanopete** [comment]
@lukaszfryc will this be relative to rebounty once we open new bounties?

**Comment by lukaszfryc** [comment]
@pablanopete yes!
