### ISSUE TITLE
Do not fetch messages when new account is created

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4765]
### Description

*Type*: Bug

*Summary*: It seems like there is no reason to fetch messages while new account is created. Please correct me if I'm wrong.

#### Expected behavior
Status doesn't initiate messages fetching when new account is created.

#### Actual behavior
<img src="https://user-images.githubusercontent.com/7532782/41403754-f3bbc67e-6fc5-11e8-8401-fba65bc1a2ed.png" width="200">

### Reproduction

- Open Status
- Create new account

### Additional Information
* Status version: nightly, June 14
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
cc @yenda

**Comment by janherich** [comment]
@lukaszfryc @yenda I quickly checked the code and here are my findings:
The label `Fetching-messages...` is not super accurate ad it actually means fetching mailserver topics - and even with no chats present, there is a fixed discovery topic (used for contact exchange) which has to be fetched.
So either we actually differentiate that by introducing two labels, one `Fetching messages...` and second `Fetching incoming contact requests...`, with only the second one show for situation with no chats present and some screen priority when both are happening at the same time (more complicated solution although probably the "correct" one), or super simple solution would be to just change the label to `Fetching messages and incoming contact requests...`, so it's clear why it's happening even with no chats present. 
I understand that it's still strange to see it with completely fresh account, since there is (almost) no way anybody could send contact request to such account.

**Comment by lukaszfryc** [comment]
Or, do not show it when the discovery topic is being fetched. So show only "Fetching messages..". At least until we know how to properly handle account recovery (https://github.com/status-im/status-react/issues/4745)

**Comment by mandrigin** [comment]
shouldn't be an issue with partitioned discovery topic
