### ISSUE TITLE
Toggles ("Bootnodes", "Development mode", "Save password until login") are shown as enabled when they are disabled until app restart

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#4779]
### Description

*Type*: Bug

*Summary*: Bootnodes (Profile -> Bootnodes) are being enabled when development mode is turned ON. It happens only on iOS, Android works fine.

#### Expected behavior
Bootnodes are not enabled when dev mode is ON. They can be enabled only by a user switching the "bootnodes enabled" toggle.

#### Actual behavior
Bootnodes are enabled when dev mode is ON.

### Reproduction

- Open Status on iOS 
- Go to Profile
- Turn on dev mode
- Open Bootnodes settings

### Additional Information
* Status version: nightly, 15 June
* Operating System: iOS

**Comment by lukaszfryc** [comment]
The toggle on iOS is broken in general I think. Here is another scenario:
1. Install app, create account and enable dev mode
2. Log out
3. Create another account, the dev mode toggle shows ON but in reality the development mode is off

It maybe that it has nothing to do with bootnodes. They are still disabled even though the toggle shows ON.

We're checking if we can log if bootnodes are enabled or not and show it in logcat.

cc @annadanchenko

**Comment by lukaszfryc** [comment]
I'm removing "release" label since it's not a blocker for upcoming release (0.9.22).

**Comment by churik** [comment]
Also it affects "Save password until login"(after merging https://github.com/status-im/status-react/pull/5617).
Third scenario:
- turn off "Save password until login"
- log in
- Go to Profile, tap on Advanced
- Turn on development mode
- Log out

*Expected behavior:* "Save password until login" is turned off

*Actual behavior:* "Save password until login" looks as turned on (toggle is enabled; but actually it is turned off, which is visible after app restart)
