### ISSUE TITLE
Inconsistent currency conversions when selecting different "Main currency" options

### ISSUE THREAD

**Issue by GeorgiG** [status-im/status-react#4793]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*:  I've noticed some improper currency conversions on the "Wallet" when switching the "Main currency" options from the "Profile" menu.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
Always to see proper conversions. 

#### Actual behavior
[comment]: # (Describe what actually happened.)
They are wrong for some currencies. 

Here are a few examples considering USD 51.11 as a reference amount I'll be converting from:

* Switch to BGN - Status displays 141.36 BGN which is incorrect! The correct conversion should equal to ~ 84.49 BGN.
* Switch to AFN - Status displays 132 AFN. The correct value should be ~  71.55 AFN
* Switch to BMD - Status displays 0 BMD. The correct value should be ~ 51 BMD
* Switch to BND - Status displays 31.68 BND. The correct value is ~ 70.28 BND.

Please note that I haven't gone through all of the available currency options so the list above is incomplete. Please also note that some of the conversions are fine (like USD to EUR for example). 
I've checked all of the mentioned as improper conversions with at least 2 of the top currency conversion calculator results on Google. 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

1. Open Status
2. Log in
3. Make sure that your "Wallet" have some assets. Request some if it doesn't.
4. Take a note of the current "Total value" of your "Wallet". 
5. Navigate to "Profile" -> "Main currency" and select a different one. 
6. Go back to the "Wallet" menu and check the "Total value"

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- Check/Update the API and the implementation.

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 

Android - 0.9.19 (6034)
iOS - 0.9.19 (6031)

[comment]: # (Android or iOS.)
* Operating System: Android and iOS

![usd](https://user-images.githubusercontent.com/5781465/41506820-af43a862-722d-11e8-9992-9f7c9fec49a0.png)

![bgn](https://user-images.githubusercontent.com/5781465/41506822-b44d0e70-722d-11e8-996e-fc3ef8da7fab.png)

**Comment by annadanchenko** [comment]
@GeorgiG thank you for the bug report! 

BMD issue was fixed in https://github.com/status-im/status-react/issues/4508 and is already available in nightly builds (can be found in https://status-im.github.io/nightly/ but only Android build can be installed atm) 

Can you re-check if it's https://min-api.cryptocompare.com issue for the rest of currencies mentioned, please? We are using this 3rd party service to show currencies.

<blockquote><div><strong><a href="https://status-im.github.io/nightly/">Status.im Nightly Builds</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://min-api.cryptocompare.com/">CryptoCompare API for Developers: The only free cryptocurrency data API for over 100 exchanges and 4000 coins (BTC,ETH,XMR + 4000 other cryptos)</a></strong></div><div>The best API for getting free cryptocurrency live pricing data, OHLC historical data, volume data, tick data or block explorer data from multiple exchanges and blockchains. We have integrated with over 90 exchanges, 1800 coins and have over 22,000 trading pairs listed. Whether you are looking for live streaming data or historical tick data we are the one-stop shop for the whole cryptocurrency space.</div></blockquote>

**Comment by GeorgiG** [comment]
You're welcome, @annadanchenko! :)
I can confirm that it is an issue on their side, not on Status. 
Please find attached a screenshot for your reference. My initial wallet calculations were for 0.1 ETH and the screenshot shows the values for 1 ETH. 

![cryptocompare](https://user-images.githubusercontent.com/5781465/41507424-deb786ba-723a-11e8-8f2f-a9ac31310843.JPG)
