### ISSUE TITLE
Error Unmaskable.unmask defined for type: null

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#4858]
### Description

*Type*: Bug

*Summary*: Error `No protocol method Unmaskable.unmask defined for type: null` shown when seding txn to dapp (in my case - test dapp , requesting ADI tokens twice one by one)

#### Expected behavior
no errors 

#### Actual behavior

this error means that password was sent as null. It shouldn't depend on contract, more likely has something to do with user input

![image](https://user-images.githubusercontent.com/28752642/41654759-231bf64c-7493-11e8-81d7-fa3d04acf846.png)

**Comment by annadanchenko** [comment]
Can reproduce on release build https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/6/

### Description

*Type*: Bug

*Summary*: `No protocol method Unmaskable.unmask defined for type null` error popup is shown after tapping several times on Sign transaction button if Send transaction screen is opened from DApp

Note: on iOS after getting such error nothing happens if user tries to tap on other DApp or app buttons, so need to restart app to proceed working with it

#### Expected behavior
Can tap only once on Sign transaction button, after this button is disabled

#### Actual behavior
`No protocol method Unmaskable.unmask defined for type null` error popup is shown after tapping several times on Sign transaction button 
### Reproduction
iOS: https://app.testfairy.com/projects/4803590-status/builds/8502922/sessions/4394588605/?accessToken=vCsHkQZFMJOimRXFJEi2Hka01OE
- Open Status, switch to ropsten network
- open Test Dapp -> Assets -> request STT. As a result, Send transaction screen is opened
- provide correct password and quickly tap several times on Sign transaction button 
- check errors if any shown after or before Got it screen


### Additional Information
* Status version: release
* Operating System: found on Android and iOS



<blockquote></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803590-status/builds/8502922/sessions/4394588605/?accessToken=vCsHkQZFMJOimRXFJEi2Hka01OE">TestFairy: Status 0.9.21 (6096) @2018</a></strong></div></blockquote>
