### ISSUE TITLE
Correct font (San Francisco) is missing

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/status-react#4860]
**Issue:**
"San Francisco", the OSX native font is missing 
Download SF > https://developer.apple.com/fonts/

**Problem:**
Without the proper font displayed, sizes, spacing, and measurements don't match the design specifications.

**Expected results:**
Users should be able to see all content in the app displayed using SF font (as specified in the designs).

**Comment by churik** [comment]
@EugeOrtiz  what is it about? Where is it missing and what should be done regarding this issue?

**Comment by EugeOrtiz** [comment]
@churik I added more details, let me know if it needs to be more clear.

**Comment by rcullito** [comment]
@MaxRis @vkjr any idea where the right place is to drop this font in for QT to pick up? 

Had experimented with changing the font but could only get system-wide fonts such as Helvetica to show up in place of Roboto rather than from a custom file. Thanks!

cc:
https://github.com/supermarin/YosemiteSanFranciscoFont
https://github.com/AppleDesignResources/SanFranciscoFont

**Comment by vkjr** [comment]
@rcullito, I checked in Qt, not additional fonts installation needed, setting font.family to "SFProText" is enough.
Let me check if we have a bug on `react-native-desktop` side...

**Comment by vkjr** [comment]
@rcullito, I checked, we have a correct implementation of `fontFamily` property in `react-native-desktop`.
But as I noticed, `react/text` is not a direct referencing of a `Text` component, it is a function that requires you to move font styling in a separate function argument. Here is how you can achieve desired behavior:

```
 [react/text {:style      styles/message-text
                 :font {:font-family "SFProText"}
                 :selectable true}
     text]
```

Here I used `SFProText` fontFamily, since it is mentioned in zeplin files. Probably you should also set it here and reference from that file:
https://github.com/status-im/status-react/blob/desktop/src/status_im/desktop/platform.cljs#L5

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by rcullito** [comment]
:ok_hand: perfect, thanks for looking into it @vkjr. Yes had tried just updating it at the platform level but had not applied the styling to the `react/text/` element itself so thank you for that!

**Comment by rcullito** [comment]
@vkjr, realizing I meant to ask that although font-family is implemented correctly, we'd still need to include "SFProText" in a place where it could be referenced though, right? It looks like through http://doc.qt.io/qt-5/qfontdatabase.html 

Currently there are a couple of possible font directories, one in both `status-react` and `react-native-desktop`, but I'm not totally sure how this would be incorporated into the above library. 

<blockquote><img src="//d33sqmjvzgs8hq.cloudfront.net/wp-content/themes/oneqt/assets/images/favicon.ico.gzip" width="48" align="right"><div><strong><a href="http://doc.qt.io/qt-5/qfontdatabase.html">QFontDatabase Class | Qt GUI 5.11</a></strong></div></blockquote>

**Comment by vkjr** [comment]
@rcullito, later for linux probably we will need to support adding of a new font through the assets. But it looks like for mac you don't need need to install "SFProText" since it is one of a system fonts (as I understood).

On my mac abovementioned code works perfectly and changes the font in the messages list. Didn't it work for your mac?

**Comment by rcullito** [comment]
@vkjr I'm on linux :) so will look into adding the font through the assets. Thank you for clarifying that it works natively on Mac though!

**Comment by vkjr** [comment]
@EugeOrtiz, will we have the same font for both Linux and Mac?

**Comment by EugeOrtiz** [comment]
Good question @vkjr ! Actually, the SF is only for Apple OS and products:

_"A. Limited License. Subject to the terms of this License, you may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS or OS X operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS or OS X."_

What is linux's default font?

**Comment by vkjr** [comment]
@EugeOrtiz, have no idea :)

**Comment by rcullito** [comment]
@EugeOrtiz Ubuntu has its own font https://en.wikipedia.org/wiki/Ubuntu_(typeface), and then I think beyond that it's pretty scattered! Roboto appears to work ok as the default (which is what was already in place to use as the app font) 

<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ubuntu.svg/1200px-Ubuntu.svg.png" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Ubuntu_(typeface)">Ubuntu (typeface) - Wikipedia</a></strong></div></blockquote>

**Comment by EugeOrtiz** [comment]
@rcullito Hmm yes, Ubuntu doesn't look good for this. Arial should be OK too. Can we have two screenshots of how Roboto and Arial look like in comparison? Thanks!

**Comment by rcullito** [comment]
@EugeOrtiz sure! Arial should work fine. Most of the sytem-wide fonts tend to be on there. I'll upload here :+1:

**Comment by rcullito** [comment]
cc @EugeOrtiz 

Some of the fonts are styled inline, so the ones that change here are the lines starting with:
"Status is an open source..."
and
"Status is built with..."

Hope this helps!

## Arial 

![arial](https://user-images.githubusercontent.com/909156/42464061-ecf69b3e-8375-11e8-9222-cbeaf0c91056.png)

## Helvetica

![helvetica](https://user-images.githubusercontent.com/909156/42464065-f0190216-8375-11e8-8f17-484343e95f55.png)

## Roboto

![roboto](https://user-images.githubusercontent.com/909156/42464075-f8640240-8375-11e8-8be1-ddaa3dcde789.png)

**Comment by vkjr** [comment]
@EugeOrtiz, have you made a decision regarding font on Linux?

**Comment by EugeOrtiz** [comment]
@vkjr @rcullito  I would go with Arial for Linux, and SF for OSX.

Here is an example of how the chat screen looks with Arial >> **zpl.io/amnlnEv** (Zeplin)

For Linux, we should replace all the SF font-weight: semibold & font-weight: bold  to **bold** in Arial.

**Comment by vkjr** [comment]
Update on this issue:

I checked on mac, Qt font database has following font families from SF:
```
".SF Compact Display"
".SF Compact Rounded"
".SF Compact Text"
".SF NS Display"
".SF NS Display Condensed"
".SF NS Symbols"
".SF NS Text"
".SF NS Text Condensed"
```

As I understand, this is not enough to cover our needs, because in the code we are referencing family fonts with different weights:

```
(def fonts
  {:light         {:font-family "Roboto-Light"}
   :default       {:font-family "Roboto-Regular"}
   :medium        {:font-family "Roboto-Medium"}

   :toolbar-title {:font-family "Roboto-Regular"}
   :roboto-mono   {:font-family "RobotoMono-Medium"}})
```

So, as @rcullito mentioned earlier, we need to have a possibility to add custom fonts to the application database. Will investigate this.

**Comment by vkjr** [comment]
@EugeOrtiz, in status-react we use 4 types of fonts: light, regular, medium and monospace.

Apple provides downloadable versions of San Francisco font and I found there light, regular and medium versions (no monospace). 
Also among fonts installed on my computer I see no monospace or light version of Arial font.

Could you please point me, where can I download lacking fonts? 
Thanks.

**Comment by vkjr** [comment]
Update: I checked the code again and it looks like "light" font referenced but not used anywhere. And "monospace" font used only in a wallet which is not in desktop yet.
So maybe we can go with existing fonts for now and get back when we need more.

**Comment by chadyj** [comment]
> So maybe we can go with existing fonts for now and get back when we need more.

👍 Sounds good

**Comment by EugeOrtiz** [comment]
Just to clarify, we don't use light or monospace (yet) on desktop. @vkjr is it possible then to add SF on OSX and Arial on Linux then?

**Comment by vkjr** [comment]
@EugeOrtiz, yes, PR already created - https://github.com/status-im/status-react/pull/5435
