### ISSUE TITLE
"Couldn’t connect to mailservers" if I set custom date/time  (for mailservers A, B, E, F)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#4940]
### Description

*Type*: Bug

*Summary*: custom date/time (for me Android) cause "panic: runtime error: slice bounds out of range" on some mailservers

#### Expected behavior
mailservers are running

#### Actual behavior
receive "Couldn’t connect to mailservers" ~every 1 min

### Reproduction

- Open Status
- Open  Settings>General Management> Date and Time
- Turn off Automatic Date and Time
- Set date in past (yesterday)
- Change time and set 24-h format
- Go to Status
- Open Profile > Advanced
- Change Mailserver to A, B, E or F
- Log in

### Additional Information

* Status version: [release build 14](https://jenkins.status.im/job/status-react/job/public-beta-1-testfairy/14/)
* Operating System: Android
### Logs
[Log.log](https://github.com/status-im/status-react/files/2134445/Log.log)

**Comment by cammellos** [comment]
I will be addressing the `status-react` side, so that we won't be querying the mailserver with the wrong parameters, which we believe it causes the crash.

The peer won't be able still to connect to the mailserver, as we don't support peers with clock skews for now I believe (status-go to confirm), but should not crash the mailserver in the current state.

**Comment by churik** [comment]
Is not reproducible anymore
