### ISSUE TITLE
Support mailserver pagination in app

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-react#5019]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want the app to request a number of historic messages from the mailserver instead of a fixed time window so that the app stays responsive and doesn't request a ton of old messages that I don't care about. For that we need to leverage the work done in https://github.com/status-im/status-go/issues/1036.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The app should start requesting the last 100 messages from the mailserver, and stop paginating if we know that the next messages are older than 24 hours (exact numbers are subject to change based on testing). 

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
- I open the app on #status
- Messages are fetched in pages, but since there was a lot of discussion in the channel because of beta, only 100 messages are returned from the mailserver and we don't ask for a second page.

#### Actual behavior
[comment]: # (Describe what actually happened.)
- I open the app on #status
- Messages from the last 7 days are fetched, resulting in a lot of traffic and load on the mailservers.

**Comment by pedropombeiro** [comment]
No longer blocked as the beta fleet mailservers have been updated to a recent status-go version.

**Comment by chadyj** [comment]
Love this feature! Let's make sure to roll it on desktop and mobile :)

**Comment by pedropombeiro** [comment]
> Love this feature! Let's make sure to roll it on desktop and mobile :)

I'd expect (and hope) that at this level of the architecture, it would be very hard to not do so, since this is not UI-related.

**Comment by chadyj** [comment]
@PombeirP @yenda We can close this right?

**Comment by pedropombeiro** [comment]
I believe so. By the way, I think the OP is actually incorrectly formulated because it assumes we can ask for last X messages, which is wrong, we can only deal with time windows.

**Comment by yenda** [comment]
We don't support the pagination at the moment as it was not a problem as much as the slowness of fetching messages one by one, topic by topic

**Comment by chadyj** [comment]
Ah I thought it was supported, but only set to 1 day?

**Comment by pedropombeiro** [comment]
Yeah, that's my current understanding as well. It's supported in the mailserver API, but we're only making use of it to get the first page of 24h

**Comment by yenda** [comment]
No pagination is something different, it is related to cursors. If you provide a limit to your messageRequest, you will receive only this number of messages from the mailserver at most and a cursor to pass in your next request to get the next x messages. But it doesn't mean anything from the app perspective because that could be 500 messages that you can't decrypt. 

I didn't implement the use of cursors at all for now because that wasn't a performance problem, on the contrary the problem was that messageRequests were done per topic, for 24h time periods, and messages were sent by the mailserver one by one over TCP which was very slow. Now we can request all topics at once and receive messages in batches so it is much more efficient and we can start thinking about using these cursors again.

**Comment by cammellos** [comment]
this has now been implemented

**Comment by pedropombeiro** [comment]
@cammellos do you have a link to the PR you could drop here, for traceability?

**Comment by cammellos** [comment]
sure, https://github.com/status-im/status-react/pull/7073
