### ISSUE TITLE
Entering a blank URL creates a dead end

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#5199]
### User Story

As a user, I want to be able to quit the browser when I've entered a blank URL.

### Description

*Type*: Bug

*Summary*:  Reported on [Instabug](https://insta.co/bugs/76JOnnzPdk7nm4ZnSx3UYg).

When you hit enter on the browser bar without inputting any text, you get stuck on the next screen. The "X" button throws an error: 

<img src="https://user-images.githubusercontent.com/15470435/42803216-9ba1d452-89a5-11e8-8b72-7d43deb83bd6.PNG" width=250/>

#### Expected behavior
User can quit out of the browser at any time.

#### Actual behavior
Error blocks user from leaving. Must quit and restart app. 

### Reproduction

- Open Status
- In the browser bar, hit Go/Enter
- Try to close out using the "X"

### Additional Information
* Status version: 0.9.22
* Operating System: iOS

#### Logs

See [Instabug](https://insta.co/bugs/76JOnnzPdk7nm4ZnSx3UYg)

**Comment by Serhy** [comment]
It's not reproduced for me on iOS and Android 7, Android 6 in latest nightly.
But I can reproduce on 0.9.22, yes. 
So this issue is fixed and won't appear in next release (0.9.23).

A minor thing on Android is that when I submit empty URL - we keep an empty Browser item on Home screen. But this is a separate one. 

Closing this issue.
