### ISSUE TITLE
Add Contacts is getting "Unknown Address" 

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#523]
- Created an account, went to profile, copied address `ebde7dd1ee0c55e2d8212707758affdbbe602c02`
- Switched Users to went to add contact by address
- Go Unknown Address

Why? Is server down?
We can't have this happening when we launch alpha.

**Comment by alwx** [comment]
It happens because we register our user (by calling `http://api.status.im/sign-up`) only when user sends its phone number. So technically registration is not finished until this step, and our server knows nothing about the user, thus it is impossible to find them by address. 

There are several possible solutions:
1. Don't allow to create a user without a phone number;
2. Send user data without a phone earlier (right after account creation).

**Comment by jarradh** [comment]
let's do option 2, phone should never be mandatory

mental note to self we should move this to an onchain registry, revisit when implementing identity system

**Comment by jarradh** [comment]
second thoughts, leave it as is and lets change add contact form to say Public Key instead of Address
