### ISSUE TITLE
No push Notifications w/o Google Play Services

### ISSUE THREAD

**Issue by ghost** [status-im/status-react#5254]
### User Story

As a user of Android AOSP / LineageOS, I would like for Status to be as functional with the Google Play services, as it is without this centralised component.

### Description

[comment]:
*Type*: Bug

[comment]: 
*Summary*: I am not seeing any notifications when receiving a message.

**Comment by annadanchenko** [comment]
@GustavMarwin can you provide more info and describe the exact scenario when notification is not received, please? For example: user A sends user B message "hi" in 1:1 chat when user B has app running on background. User A has B in Contacts list, user B has A in Contacts list. For both users app runs on Galaxy S7, Android 7.0. App version 0.9.22

**Comment by ghost** [comment]
@annadanchenko : so I think there's no need to go deep into troubleshooting to understand that at this point in time, Status notifications cannot work properly outside of the Google Play ecosystem due to the fact that Status will quickly get suspended by Android and will have no way to check for new messages nor to display notifications.

Signal solves that by keeping a notification displayed at all times, it's quite efficient apparently.

Now I'm happy to do testings for you on an Android without GCM (like AOSP or LineageOS) and report any detail you need. But again at this point, it just can't work for the reasons I've mentioned.

**Comment by pedropombeiro** [comment]
This is not an easy problem to address, considering how much work goes into making a solution that is reliable and at the same time, battery and network topology-friendly. This is one of the reasons why the [Push Notifications v2 swarm](https://github.com/status-im/ideas/tree/master/ideas/086-push-notif-v2) still does not address it directly, merely taking the opportunity to allow for future extensibility in terms of PN providers. As a result, I haven't yet done much work to explore possible solutions, but here are some alternatives to GCM that I'm aware of (any additions to this list are welcome):
- [Pushy](https://pushy.me) based on MQTT seems interesting, but is a paid and centralized solution;
- [XMPP](https://xmpp.org/extensions/xep-0357.html), see discussion in https://stackoverflow.com/questions/1243066/does-android-support-near-real-time-push-notification/5695867#5695867. This would require further investigation, ideally we'd find a good open source library, but we might need to integrate the server component on the incentivized mailserver to act as the intermediary.

@GustavMarwin as you rightly mention, it is possible to have a persistent notification to keep the application alive and allow polling, although it is less efficient for every app to do this in parallel, rather than grouping all those needs into something like GCM and having a single TCP connection serving everyone. Nonetheless, it could serve as a first stepping stone towards a more mature and resource-friendly solution.

The way we plan to allow for extensibility of PN providers in PN v2 is by relying on [gorush](https://github.com/appleboy/gorush) and contributing to the project an additional PN platform (currently supports GCM and APN).

<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/1243066/does-android-support-near-real-time-push-notification/5695867">Does Android support near real time push notification?</a></strong></div><div>I recently learned about the ability of iPhone apps to receive nearly instantaneous notifications to apps notifications to apps.

This is provided in the form of push notifications, a bespoke proto...</div></blockquote>

**Comment by ghost** [comment]
@PombeirP : I'm so, so glad to see you already have a bit of a plan for this.

So as mentioned, Signal uses this persistent notification method and it works ok in the context of Android without Google services. But most importantly Signal has some major issues when used without those Google services, issues where a fix exist but the lead maintainer is ignoring those for an unknown reason [1]. Point being, there's currently no properly secure and private messenger in a functional state on Android devices without Google services today, but there are definitely people in need of such service [2-4]. Hence my hope for Status to fill that void hopefully soon.

[1] https://github.com/signalapp/Signal-Android/issues/7638
[2] https://drewdevault.com/2018/08/08/Signal.html

[3] https://old.reddit.com/r/signal/comments/95wfe2/i_dont_trust_signal/
[4] https://old.reddit.com/r/privacytoolsIO/comments/95y6ct/drew_devault_on_why_he_doesnt_trust_signal/

<blockquote><div><img src="/avatar.png" height="14"> Drew DeVault’s Blog</div><div><strong><a href="https://drewdevault.com/2018/08/08/Signal.html">I don’t trust Signal</a></strong></div><div>Occasionally when Signal is in the press and getting a lot of favorable discussion, I feel the need to step into various forums, IRC channels, and so on, and explain why I don’t trust Signal. Let’s do a blog post instead.</div></blockquote>
<blockquote><img src="https://www.redditstatic.com/icon.png" width="48" align="right"><div><img src="//www.redditstatic.com/desktop2x/img/favicon/favicon-16x16.png" height="14"> reddit</div><div><strong><a href="https://old.reddit.com/r/signal/comments/95wfe2/i_dont_trust_signal/">I don't trust Signal • r/signal</a></strong></div><div>0 points and 12 comments so far on reddit</div></blockquote>
<blockquote><img src="https://www.redditstatic.com/icon.png" width="48" align="right"><div><img src="//www.redditstatic.com/desktop2x/img/favicon/favicon-16x16.png" height="14"> reddit</div><div><strong><a href="https://old.reddit.com/r/privacytoolsIO/comments/95y6ct/drew_devault_on_why_he_doesnt_trust_signal/">Drew DeVault on why he doesn't trust Signal • r/privacytoolsIO</a></strong></div><div>45 points and 29 comments so far on reddit</div></blockquote>

**Comment by ghost** [comment]
@PombeirP Do you need a hand with this? I'd be happy to fund a Gitcoin issue on this matter that I consider particularly important.

**Comment by maedoredyti** [comment]
I suspect the problem is somewhere else. I tried to find out what education does the moxi have. What schools did he graduate from? What high school and what university/polytechnic? Wikipedia and google in general are silent about his education but he calls himself a cryptographer or researcher. One could be tricked he is mathematician or software engineer. Maybe he simply does not understand what do you talk about? He knows something as a self taught person in one particular branch but university education gives not only education but also a 360 degrees way of thinking.
After watching dr House nobody has a right to call himself a doctor even if one can select proper pills for one ot two diseases.

**Comment by maedoredyti** [comment]
I suspect the problem is somewhere else. I tried to find out what education does the moxi have. What schools did he graduate from? What high school and what university/polytechnic? Wikipedia and google in general are silent about his education but he calls himself a cryptographer or researcher. One could be tricked he is mathematician or software engineer. Maybe he simply does not understand what do you talk about? He knows something as a self taught person in one particular branch but university education gives not only education but also a 360 degrees way of thinking. Maybe he is stubborn because he is uneducated.

for example Bruce Schneier's CV : (Wikipedia)
"Bruce Schneier is the son of Martin Schneier, a Brooklyn Supreme Court judge. He grew up in Flatbush, attending P.S. 139 and Hunter High School.[6] After receiving a physics bachelor's degree from the University of Rochester in 1984,[7] he went to American University in Washington, D.C. and got his master's degree in computer science in 1988.[8] He was awarded an honorary Ph.D from the University of Westminster in London, England in November 2011. The award was made by the Department of Electronics and Computer Science in recognition of Schneier's 'hard work and contribution to industry and public life'."

**Comment by pedropombeiro** [comment]
@GustavMarwin thank you, I think the issue right now is prioritization. Although this is important work, right now there is work going on that supersedes this, such as implementing Perfect Forward Secrecy.

**Comment by ghost** [comment]
@PombeirP : Absolutely, I understand and have no doubt the priorities you set are what is best for this project. I just wanted to express that I am willing to financially support the project (as far as an individual contribution can be expected) should you feel that it would make a positive difference, very much in the same spirit as Augur did. Thank you for the awesome work you do.

**Comment by pedropombeiro** [comment]
Thanks @GustavMarwin, and kudos for being such a stellar supporter!

**Comment by ghost** [comment]
Hey @PombeirP - It would seem Conversations.im has solved this problem neatly and efficiently, what do you think of this approach? https://conversations.im/#optimizations - It's not perfect, but it looks pretty good.

<blockquote><img src="https://conversations.im/cover_square.png" width="48" align="right"><div><strong><a href="https://conversations.im">Conversations - Jabber/XMPP client for Android</a></strong></div><div>An open source instant messaging client. Easy to use, reliable, battery friendly. With built-in support for e2e encryption, group chats and media transfer.</div></blockquote>

**Comment by pedropombeiro** [comment]
Hi @GustavMarwin, yeah, of course it is possible, but it's always going to require a separate persistent connection that's not reused by other apps (like GCM) and will require quite a bit of work to optimize so that we don't consume too much power/data on mobile devices, while at the same time ensuring we do it in a decentralized way.

**Comment by ghost** [comment]
There's currently no perfect solution so I'll keep sharing devs stories of those who are trying to tackle this problem with different approaches if that's useful to you / the project?

The most recent one is Tutanota, it's a good read too: https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html

I don't use Tutanota (but starting to consider it now), however I do use Conversations.im which, like them, does not rely on GCM; I don't know if the Conversation app strategy is easily replicable but again although not the idea design we both would like to see, it works great and my battery is virtually unaffected. I wonder but don't pretend to have the answer, if this would be a good short/mid-term solution until a proper open-source, decentralised, push notification system comes to life.

<blockquote><img src="/assets/favicon.ico?v=8j6PKzW9Mk" width="48" align="right"><div><strong><a href="https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html">How Tutanota replaced Google’s FCM with their own notification system | F-Droid - Free and Open Source Android App Repository</a></strong></div><div>As mentioned in This Week In F-Droid 17, Tutanota is now on F-Droid.In this special post Ivan fromTutanota, tells us the story.Hi, I’m Ivan and I am developi...</div></blockquote>

**Comment by pedropombeiro** [comment]
Hey @GustavMarwin, for sure all the articles you manage to send will become food for thought when the time comes to implement this, so thank you for sending them our way, it will only help make the outcome better!

**Comment by pedropombeiro** [comment]
This is important, bot.

**Comment by ghost** [comment]
Hey @PombeirP ! Any updates on this by any chance?
Today the situation is very similar to what it was back when this issue was created: there's only one messaging app that works well on LineageOS w/o Google Play and it's Conversations.im - Not only that, it's also very efficient on resources being used.
Edit: scratch that, there's also Riot.im, although it uses a fair bit more battery.

**Comment by pedropombeiro** [comment]
Hi @GustavMarwin ! I'm afraid we haven't started it yet, there are still some building blocks we are in the process of putting in place before attacking this.

**Comment by ghost** [comment]
This seems like an interesting development: https://forum.xda-developers.com/showpost.php?p=78688208&postcount=5495

**Comment by ghost** [comment]
This could maybe be used: https://gotify.net/

**Comment by hesterbruikman** [comment]
@Serhy this seems like one to test with the emulator without Google Play Services

**Comment by Serhy** [comment]
I've tested latest develop build (19th of May) on Genymotion emulator: Galaxy S7 with Android 7.1 And there are no GooglePlay Services installed. 

Notifications are working for me, pop-up about new message received in 1-1 chat appears like on real devices with gplay service installed.

**Comment by hesterbruikman** [comment]
Thanks @Serhy ! Closing this. We can reopen if we get bug reports from real devices w/o Google Play services
