### ISSUE TITLE
 Define a proposal for a basic CLI

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#5315]
### User Story

As a user, I want to have a basic CLI to interact with a running Status instance. First step is to define what we plan to implement.

### Description

*Type*: Feature

This [proposal](https://gist.github.com/jeluard/7611c538887565a9c16429522bdeb8c5) can be used as a basis for discussion.

Plan is to:

* align with Embark and others DApps devs needs
* publish proposal to discuss to engage with the community
* finalize the proposal

**Comment by alwx** [comment]
Current status of it: 
We talked to Iuri, and I also looked at how Embark is organised now. Agreed that the previous implementation contained everything we need, but the basic set of features can be minimal and the list created by you already includes everything we need at the beginning.
And we don't even need to invent something here — the previous solution was good enough. The only problem is that it doesn't work anymore, all features for debugging were removed from `status-react`, and we need to carefully re-implement them.

More importantly, if we decide to continue with a web server, we don't even need a cli. The idea is the following — we can simply run a web server and accept some specific requests. Which means that instead of using some third-party tools we can easily use POST and GET requests.

The only tricky part is discovery, it's probably not that important, but I am going to check it as well.

**Comment by alwx** [comment]
Investigated a bit more, found these three options: https://gist.github.com/alwx/a911408984791e0e9a80d1ac4302443c

Of course, some of them can be combined. Technically, we can also combine all these options and/or use some options as a fallback.

<blockquote><img src="https://avatars1.githubusercontent.com/u/911127?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/alwx/a911408984791e0e9a80d1ac4302443c">status-dev-cli 2.0: Discovery process</a></strong></div><div>status-dev-cli 2.0: Discovery process</div></blockquote>

**Comment by rachelhamlin** [comment]
@jeluard @alwx can we close this issue based on https://github.com/status-im/status-react/commit/b283ffe4afb9256bade2a81faccefc6e9672763e?

**Comment by jeluard** [comment]
@rachelhamlin We definitely can!
