### ISSUE TITLE
Avoid code duplication across multiple Jenkinsfiles

### ISSUE THREAD

**Issue by maxhora** [status-im/status-react#5424]
### User Story

As developer, I want to have single place with Jenkins script code reused by multiple Jenkinsfiles ( we have currently separate Jenkinsiles for PRs and nightly builds )

### Description

*Type*: <Feature>

*Summary*: 

Possibility to reuse groovy Jenkins script code across multiple Jenkinsfiles should be investigated.

note: this might be applicable for Mobile jenkins builds as well

**Comment by maxhora** [comment]
@jakubgs it seems you have resolved this issue, isn't it? :+1:

**Comment by jakubgs** [comment]
Almost, there are still two files that I need to work on:

* `Jenkinsfile.upload_release_android`
* `Jenkinsfile.upload_release_ios`

Those also need to use the declarative format and re-use stuff from `.groovy` scripts.

**Comment by chadyj** [comment]
`Jenkinsfile.upload_release_android` and `Jenkinsfile.upload_release_ios` remaining

**Comment by jakubgs** [comment]
I've discussed this with @mandrigin and we should probably re-think how releasing for Android and iOS works.

* Android - Currently the `Jenkinsfile.upload_release_android` job publishes publicly right away
* iOS - And `Jenkinsfile.upload_release_ios` requires manual approval which takes a while

This is the main reason for the split between the files. What @mandrigin said sounds much more sensible:

>Maybe only RCs should be uploaded to TF/Internal and everything else should be done manually

Also

>we should not rebuild anything for Android

Which also makes sense, since we can just upload an exisitng build.

**Comment by yenda** [comment]
@PombeirP is it something your recent PR fixes ?

**Comment by pedropombeiro** [comment]
@yenda No, it was only focused on Desktop. So for desktop the logic is all in the bash script and is reused by the Groovy files, but that is not yet the case for the mobile platforms.

**Comment by churik** [comment]
Not a priority anymore

**Comment by jakubgs** [comment]
Actually, this has been already done with all the `groovy` files:
https://github.com/status-im/status-react/tree/develop/ci
