### ISSUE TITLE
Do not show "Unknown token" error when token is not selected in Wallet assets

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5500]
### Description

*Type*: Feature

*Summary*: When a token is not selected in Wallet, there is an error shown in the chat when user tries to send it. The error does not explain what should be done to send the token. 

<img src="https://user-images.githubusercontent.com/7532782/44098283-13b0f2ac-9fe0-11e8-8d06-f3dfed93895c.png" width="200">

Maybe we could get rid of this error and allow user to proceed to the send transaction screen even though the token is not enabled in Wallet -> Manage Assets. Alternatively, we could improve copy of the error.

#### Expected behavior
Unknown token error should not appear when token is not selected in Wallet -> Manage Assets. User can proceed to the send transaction screen.  

#### Actual behavior
Unkown token error appears when the token is not selected in Wallet -> Manage Assets. User has no idea what to do next.

### Reproduction

- Go to Wallet and disable some token like STT (ropsten) or SNT (mainnet)
- Have 1-1 with someone and receive "/request STT" from him/her
- Click on "Send" button on the message

### Additional Information
* Status version: 0.9.26
* Operating System: Android, iOS

**Comment by lukaszfryc** [comment]
@goranjovic wdyt? Can we not show this error but instead allow user to proceed to the send transaction screen?

**Comment by goranjovic** [comment]
@lukaszfryc The problem is that there is a lot of tokens and we intentionally do not try updating wallet balances and tx histories for most of them (the ones not enabled) - to conserve battery and network usage. I initially had the same idea, to only show the enabled ones in the popup, but to accept all if typed, but had to revert because of this.

One thing we could possibly do is show a different error message in this case (when token exists and is supported by Status, just not enabled at the moment).

Btw, how do you know that you even have WGN if it's not enabled?

**Comment by lukaszfryc** [comment]
> One thing we could possibly do is show a different error message in this case (when token exists and is supported by Status, just not enabled at the moment). 

@goranjovic we could have:

"Unknown asset"
"Please enable WGN token in Wallet"

**Comment by lukaszfryc** [comment]
@obi2020 is this a good copy to use?
