### ISSUE TITLE
iOS AppCritique vulnerability found: Disables App Transport Security

### ISSUE THREAD

**Issue by corpetty** [status-im/status-react#5504]
### Note: 
This is an issue created from the [Dark Labs AppCritique](https://appcritique.boozallen.com/) Static Analysis Report performed on Aug 14, 2018 on Status version 0.9.26 build 6382

Some of these may be purposeful and taken care of.  If so, please provide reasoning here and it will be closed upon review.  This issue will then serve as a reference for future potential vulnerability disclosures. 

### Description
The app globally disables App Transport Security (ATS) for all
domains. ATS is a security feature which ensures the app
establishes secure network connections. The app can utilize
insecure HTTP connections when ATS is disabled, allowing
interception and modification of data by third parties. ATS is
supported in iOS 9.0 and later.

[OWASP: 2016-M3-Insecure Communication](https://www.owasp.org/index.php/Mobile_Top_10_2016-M3-Insecure_Communication)

### Platform
iOS nightly build: Status version 0.9.26 build 6382

**Comment by mandrigin** [comment]
We can't really enable ATS right now because we have a DApp browser built-in which allows any URL.
Even though it makes sense to disallow plain-http connections for normal users, DApp developers might want to use it and I think it should exist as an option.

So, I would close this one as a choice we make "by design".
