### ISSUE TITLE
Can't add custom bootnode or network. "Save" button is inactive

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#5814]
### Description

*Type*: Bug

*Summary*: Even though a bootnode address is provided, the "Save" button in the add bootnode screen is still inactive. In result, users can't add custom bootnodes. Same happens when adding custom network. It worked fine on nightly from Sep 11 (`bd3f95`) but stopped working in `ca1490`.

This issue is related to https://github.com/status-im/status-react/issues/5813.

### Reproduction

Custom bootnode:
- Open Profile -> Advanced -> Bootnodes and click "+" to add custom bootnode
- Provide  name and `enode://a8a97f126f5e3a340cb4db28a1187c325290ec08b2c9a6b1f19845ac86c46f9fac2ba13328822590fd3de3acb09cc38b5a05272e583a2365ad1fa67f66c55b34@167.99.210.203:30404` as custom bootnode 
- Try to click Save

Custom network:
- Try to add custom ropsten network `https://ropsten.infura.io/iMko0kJNQUdhbCSaJcox` 

### Additional Information
* Status version: `ca1490`, https://ci.status.im/job/status-react/job/nightly/689/
* Operating System: Android, iOS

<blockquote><img src="/static/c32cacaf/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/689/">status-react » nightly #689 [Jenkins]</a></strong></div></blockquote>

**Comment by yenda** [comment]
From a UI perspective the custom network thing is tricky, because the current behavior is that the app closes if it wasn't able to connect properly to the network, and you end up in a loop where the app closes every time you login and you can't fix your network config. Maybe we should at least allow the user to cancel that and change his settings
