### ISSUE TITLE
Contact Management

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#585]
at the moment it is not clear how we should delete or move a contact between groups.

we also have no way to create/remove/edit groups

**Comment by andmironov** [comment]
What do you think of this?

![contact_management](https://cloud.githubusercontent.com/assets/3115606/21528070/dfbd6e4e-cd40-11e6-8b3f-5f6dd71b6830.png)

**Comment by jarradh** [comment]
looks great, how does add group look on Android and iOS? how do we delete a group?

**Comment by andmironov** [comment]
UPD
![contact_management2](https://cloud.githubusercontent.com/assets/3115606/21540097/e3be8866-cdbd-11e6-9f80-573a2f3e46bc.png)

**Comment by jarradh** [comment]
nice! okay I assume deleting a contact froma group would make them ungrouped ? then deleting a contact from ungrouped would delete them?

**Comment by andmironov** [comment]
Yep, also "ungrouped" would be useful for people who just don't like grouping. Notice that the ungrouped group can also be sorted, but does not have a header in the list (Like all other groups have: Dapps 45 or Favourites 14) what do you think about that?

**Comment by jarradh** [comment]
love it!

**Comment by andmironov** [comment]
Great! I will add it to Zepling then

**Comment by andmironov** [comment]
All of them https://zpl.io/Z1Oh6MV 
+ all've also added them one by one with the contact-management_ prefix (13 screens)

**Comment by rabbit** [comment]
these look fantastic. a few suggestions to interpret as you wish:

- if "delete group" does not delete the group then simplify the language and remove the hint. sounds like you mean to say "leave group"
- in general destructive actions should have a little more space since mobile users may have large fingers or fumble, feels a bit tight between add group and delete group.
- for the bottom menu bar, the singular "chat" sounds more like an action (ie: what do I want to do? chat. vs what do I want to do? chats.) contacts doesn't read that way to me.
- might want to check with a color contrast app to ensure all the text is readable for those without clear vision or color blindness. that top right "Group Members: 3" the 3 looks borderline to me
- love the way selection looks on list items (see? I can be nice)
- there's no view for "add group members" but going on the plural of members I would expect the multiple select view, if it's a one at a time operation singularize it.
- "Create Group" and "Change Group Order" both begin with "C" and end with "e". humans parse words predominantly by beginning and end letters, consider renaming "Change Group Order" to "Reorder Group" or similar to create more visual separation at a glance.

**Comment by flexsurfer** [comment]
Contacts screen
- [x] Contacts options button 
- - [ ] icon for Android
- [x] Menu ios 
- [ ] Menu android (requered new react native component https://github.com/jaysoo/react-native-menu)
- [x] Edit mode
- [ ] icons
- [ ] colors
- [ ] android animated header

Search
- [ ] search icon on search
- [ ] "live search" (filter)

New contact 
- [x] done

New Group
- [x] done

Contacts List
- [x] selection
- [ ] search
- [ ] new native toggle component needed 


Edit group
- [ ] in progress

Reorder group
- [ ] in progress
