### ISSUE TITLE
Create LES fleet for Ropsten

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-react#5891]
We need 3 VMs, each running a full geth node with LES server enabled.

Fleet name: `ethdev.les`

geth params to enable LES server: 
```
--lightserv 90 --lightpeers 200
```

**Comment by jakubgs** [comment]
Here's what I got:
https://github.com/status-im/infra-misc/commit/3a347d8e134e83a2e21b36e77b47408bff820ce7
Hosts:
https://consul.status.im/ui/do-ams3/services/les-geth-full

They have 800 GB storage, should be enough for a short while, since this is an experiment.

Tell me if I need to change anything.

<blockquote><div><strong><a href="https://consul.status.im/ui/do-ams3/services/les-geth-full">Sign In</a></strong></div></blockquote>
