### ISSUE TITLE
Increase tap surface and feedback

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#5907]
### User Story

As a user I want any gesture based interactions on mobile to be easily discoverable and provide me with feedback to know if my action is succesful.

### Description
It ocasionally takes people multiple attempts to open the profile of someone in a public chat to invite them to a 1:1 chat. The tap area seems smaller than it needs to be and gives no feedback on tap. This issue is intended to review the design specification and implementation.

*Type*: Usability issue

#### Expected behavior
For elements that are tappable to have a sufficiently large tap surface (44x44) and indicate whether they are selected.

#### Actual behavior
Tap surface too small and not responsive

### Additional Information
Unclear if this issue is caused by design specs / implementation or both.
Issue came up in UX testing RRR820180906T3I3.1
https://docs.google.com/presentation/d/10qb5jRXwRT9lYkxrn8Ui5Bov_JRuf1WBaPqSXd0ZAtY/edit#slide=id.g41d28d5cd7_19_37

<blockquote><img src="https://lh6.googleusercontent.com/_vO60E7Z21r_Wt8D2EvcpUodrA1wl1klLexYshNEYeZK_zD30zGKxUXmt4JEUnlGwjOVjw=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/presentation/d/10qb5jRXwRT9lYkxrn8Ui5Bov_JRuf1WBaPqSXd0ZAtY/edit?usp=embed_facebook">Report RRR8 Chat & Command</a></strong></div><div>Hester Status 17 / 09 / 2018 UXR findings Chat & Command RRR8 Sept 6th 2018</div></blockquote>

**Comment by errorists** [comment]
To kick this off, what is the current size of the touchable area for user avatars in public chats? Is it 36? Because if so, we should increase it like so 
<img width="615" alt="screenshot 2018-09-20 at 08 28 17" src="https://user-images.githubusercontent.com/4932774/45799845-2cb29580-bcaf-11e8-9287-0c582ae64dbf.png">

Also, the touchable should provide visual feedback on touch, can we change it to TouchableOpacity ?
