### ISSUE TITLE
Add animation to sent messages

### ISSUE THREAD

**Issue by errorists** [status-im/status-react#5985]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to see sent messages animate so that I can distinguish incoming messages from old messages at a glance and draw my attention to new messages.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Messages in chat should gently animate in after sending, to give a more pleasant and conversation-like chat experience than the harsh binary way they're introduced now.

#### Expected behavior
Every new message in chat is animated in, growing in scale and opacity before appearing fully.

#### Actual behavior
Messages appear without any animation, which is a noticeable UI downgrade from other chat apps.

### Solution

![screen recording framer](https://user-images.githubusercontent.com/4932774/46003361-9fa57d00-c0b0-11e8-95c4-d91cfb20ea0b.gif)

• Once sent, a message begins at 0 opacity and 0.25 scale
• The message then animates to 1 opacity and 1 scale, from its lower right corner - X axis origin: 1, y axis: 1 (blue messages sent by me) or lower left corner - X axis origin: 0, Y axis: 1 (white messages, sent by others)
• Animation should follow an easeOutQuart bezier curve with values (0.165, 0.84, 0.44, 1), and a duration of 400ms

A prototype to play with the animation https://framer.cloud/xAIfg

thanks!

<blockquote><img src="https://framer.cloud/xAIfg/1/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/xAIfg">Status Send Messages</a></strong></div><div>This project was made with Framer, a design tool for turning original concepts into working prototypes.</div></blockquote>

**Comment by wolfgangshilei** [comment]
Hi, @errorists. I recorded a demo implementation of this feature on the iOS simulator. 

![final-effect](https://user-images.githubusercontent.com/38782954/46188496-11cdca00-c31c-11e8-89ea-3ad8a6e14c18.gif)

In the demo, the animation does not start from Y axis = 1 as required in the spec. It actually starts from Y axis = 0.5. Below is a slowed and decomposed animation along the Y axis.

![scaley-only](https://user-images.githubusercontent.com/38782954/46188703-4e4df580-c31d-11e8-82a6-2cc25c7a1b65.gif)

Apart from this, the implementation conforms to the requirements in the spec.

Here is the reason:
RN view's anchor point for scaling is (0.5, 0.5) and this cannot be changed (or can it be?). Thus, in order to achieve the scaling effect described in the spec, I need to use a combination of several animations. Take the X axis for example, 
![scalex-only](https://user-images.githubusercontent.com/38782954/46188615-c9fb7280-c31c-11e8-929a-fec01b3ba87a.gif)
This effect is achieved by scaling and translating on the X axis simultaneously. Since the width is fixed, I can know beforehand exactly how much to translate.

Unfortunately, the same trick is unavailable on the Y axis since the height is dynamically calculated based on the content of the message.

Here are my conclusions:
1. If there is any solution to achieve the exact effect described in the spec which I failed to achieve, it would be great if you could share.
2. If my current solution is OK for you, please let me know. Then I will finish the implementation and create a PR.
3. If my solution is unacceptable, please let me know anyway.

Thanks

**Comment by errorists** [comment]
First of all, a huge thank you for doing the due diligence and research into whether it's possible @wolfgangshilei ! I've did some research and my understanding is that for whatever reasons React Native doesn't support the `transform-origin`  prop yet, required to achieve this effect. Workarounds mention `transformMatrix` but it's deprecated, so I'm out of ideas. Strange, because seems like such a simple thing that was made available to us on every other platform since as far as I can remember. 

I might look into calculating deltas so that we're both scaling and transitioning the object in X and Y axis, maybe that will work. For now, we're still looking for a solution that would result into the exact effect, so again thanks for trying but the proposed solution with scaling only the X axis isn't right.

**Comment by wolfgangshilei** [comment]
@errorists, thanks for your reply.
After some further research and experiment, I managed to achieve the expected effect.

The key to my solution is to use RN's native view's onLayout callback to retrieve the height of the rendering component. In the callback, set the height to the parent view's state, which will result in a re-render with the updated height value, which in turn can be used to perform the animation properly.

However this approach renders the component twice. Though the first render can be made invisible, it does incur a very short delay before the animation starts; it can also cause potential performance issues according to the RN's official document on the use of such pattern.

A short demo on iOS simulator:
![final-effect-2](https://user-images.githubusercontent.com/38782954/46201036-bdd7db00-c345-11e8-8f81-36c30eec077c.gif)

I'd be glad to hear your opinions, cheers.

**Comment by Swader** [comment]
Reopening

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
