### ISSUE TITLE
Fix random-id cofx

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#6017]
# Problem

The `:random-id` cofx is currently a random-id that was generated with our RNG, but since it is a single value, composing fx producing functions that need a random number could lead to reuse of that number

# Solution

Replace the current `:random-id` cofx by one that returns the RNG function instead.

# Acceptance criteria

the `:random-id` cofx has been replaced

**Comment by janherich** [comment]
@yenda I would actually like to keep the `:random-number` cofx, maybe name it so it's clear it's fixed in scope of handler call (maybe `:handler-local-random-number` ?).
It's sometimes very advantageous to rely on that fact.
I propose to introduce another cofx named `:random-number-generator` which will return RNG function.

**Comment by yenda** [comment]
Could you give an example of a case were that would be more advantageous than a random-number-generator ?
