### ISSUE TITLE
PN API

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6085]
### User Story

As a developer, I want a simple standalone API to send PNs to an identified chat. 

### Description

*Type*: Feature

*This is related to PN v1.*
*Privacy and Security must **not** be degraded by eventual changes required to implement this feature.*

DApps might want to send some PNs from external process to a status chat. This allows to inform in an asynchronous way a user of an action to be taken, irregardless of status/some DApp running.

Following points should be considered:
* can extra data be sent to provide more info when *visualizing* the PN ?
* can extra data be sent to provide more info when *user hits* the PN? (e.g. redirect to a specific DApp)

Some idea: natively support universal links in PN in such a way they can be visualized?

**Comment by jeluard** [comment]
@oskarth Any insights you would want to share?

**Comment by oskarth** [comment]
> can extra data be sent to provide more info when visualizing the PN ?

This data must be considered unencrypted by default, since Firebase/Google has it in plaintext. Thus the decision was made to just call it "You have a message!". This is also how Signal does it. A workaround would be to send encrypted payload, then intercept it at client. To do this right is a bit tricky and requires iOS/Android specific solutions, and might not be 100% doable because a node has to start in background etc.

cc @PombeirP @yenda @mandrigin  @rasom  on this topic as well.

> can extra data be sent to provide more info when user hits the PN? (e.g. redirect to a specific DApp)

Similar answer as above. Possibly it's a bit different if you are in app since node actually started, which simplifies some problems.

As for universal links, I'd start by trying to encrypt it, have a generic handler for opening it, decrypt it and then go to specific screens. For public chats it _might_ be OK to send in plaintext, but we should be very careful about this as we are leaking information to Google about what public chat that person is being sent.

**Comment by jeluard** [comment]
@oskarth Right for 2. I was thinking we could redirect to the right chat / DApps after hitting the PN.

**Comment by flexsurfer** [comment]
@jeluard 
> * can extra data be sent to provide more info when _visualizing_ the PN ?

there are only two fields when _visualizing_
`"title": string`,
`"body": string`
so all _visual_ information from Dapp should be in these strings

> * can extra data be sent to provide more info when _user hits_ the PN? (e.g. redirect to a specific DApp)

yes, there is a data field for extra data
`data | map (key: string, value: string)`

we could provide some API for Dapps how they can use this field for status

**Comment by flexsurfer** [comment]
it looks like to implement this we need to run our own HTTP server with some rest API, because to be able to send PN sender needs to be authenticated in firebase and have a key. And also Dapp should provide user's firebase token to be able to send PN, so this API doesn't look simple

**Comment by flexsurfer** [comment]
so it may work next way
1) Dapp asks user permission to be able to send him notification
2) User shares his token 
3) Dapp sends a notification using Status notifications API
`https://api.status.im/send-notification(user token, dapp-id, title, message ... etc )`

**Comment by oskarth** [comment]
Why would we host our own HTTP API ? Didn't we talk about this at least dev call? https://status.im/whitepaper.pdf decentralized push notification market use case.

cc @PombeirP 

<blockquote></blockquote>

**Comment by oskarth** [comment]
>  I was thinking we could redirect to the right chat / DApps after hitting the PN.

Yeah sure, just be aware not to leak any info this way. I.e. encrypted message or make sure anonymized in some fashion.

**Comment by jeluard** [comment]
@oskarth Context is specifically around using our current PN architecture
