### ISSUE TITLE
Allow contract address to be specified via ENS

### ISSUE THREAD

**Issue by jeluard** [status-im/status-react#6172]
### User Story

As a developer, I want to provide a token contract address as ENS name.

**Comment by Swader** [comment]
Keeping this alive, is important.

**Comment by jeluard** [comment]
@Swader Do you know some contracts identified using ENS? I know very few.
How do you see this being useful for you?

**Comment by Swader** [comment]
I always bind every contract I develop to an ENS address. This is to prevent fraud and make sure people add the right token, rather than a slightly different one on a similar address sent to them by a malicious actor. But this is probably blocked by the general inability to add custom tokens in general, no? Or is that underway somewhere? I missed it if so, and wrote about the desire for this [here](https://discuss.status.im/t/listing-custom-assets-and-tcring-their-verification/918).

**Comment by jeluard** [comment]
Yes that was more an issue for internal uses! Now would be useful once users can declare their custom token too.

**Comment by Swader** [comment]
Ahh, I see. Internally I don't see a use for this. User-facing, very much so once we can add custom assets.

**Comment by churik** [comment]
Obsolete and will be re-considered in the redesigned app.
