### ISSUE TITLE
Apply design to chat replies 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6216]
### Description

*Type*: Bug

*Summary*: several details are missed in current chat replies implementation (https://github.com/status-im/status-react/pull/6117)

Initial design: zpl.io/a3l8dgY (Zeplin)

Screenshot:
![sample](https://user-images.githubusercontent.com/37297779/45289609-e8283c80-b4ed-11e8-8f7a-bfebf4075be3.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

#### Actual behavior
<img width="348" alt="np_d" src="https://user-images.githubusercontent.com/4557972/46671511-aa4a3100-cbdd-11e8-9b82-b515ac1c8f25.png">

### Reproduction

- Open Status
- Join any chat
- Click on message to select it for reply

### Solution

*Summary*: 

- [ ] apply new design to close button
- [ ] fix issues where last visible row is cut and there is no border in the top left corner (see screenshot in Actual behavior)
- [ ] provide and implent design for long reply messages 
<img width="568" alt="in_full" src="https://user-images.githubusercontent.com/4557972/46671655-fbf2bb80-cbdd-11e8-986c-51add2acceec.png">
- [ ] fix issue where is no margins if user name is too long 
<img width="238" alt="no_margin" src="https://user-images.githubusercontent.com/4557972/46672296-b59e5c00-cbdf-11e8-9473-f6f201a67095.png">

### Additional Information

* Status version: nightly 09/10/2018
* Operating System: Mac OSx

**Comment by SlizkovaGanna** [comment]
Another issue to reply for the UI of desktop chat replies:

Type: **Bug**

Summary: On desktop, when replying to a message of the user, in reply bubble in message input area, that icon is displayed as a square, not a circle.
It's especially visible when there's a profile icon set.

Reported separately from #6216 , since it's not an inconsistency with design.
I could not find any design references for this on , https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=0%3A1 but it should be consistent with mobile.

**Expected behaviour**

The icon displays as the circle (the same as in the chat) for mobile (iOS and Android)

<img width="454" alt="image" src="https://user-images.githubusercontent.com/43638377/49455365-ba524b80-f7ef-11e8-9221-4c82b76cee76.png">

**Actual behaviour**

The icon displays as a square (original image used), and looks inconsistent

<img width="678" alt="image" src="https://user-images.githubusercontent.com/43638377/49455397-cb02c180-f7ef-11e8-9bd9-9aaec91aa8dd.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/43638377/49455424-d524c000-f7ef-11e8-93ab-c5dcecacef18.png">

**Reproduction:**

Open desktop app on device A
Start 1-1 chat/join a public chat with a user who has a profile icon set
Click on the message to quote it


<blockquote><img src="/file/MRYBI5axcTwL4Ft8xAYhFOfy/thumbnail?ver=thumbnails/081fc3d9-2730-4ead-8fcb-484f0da270a0" width="48" align="right"><div><img src="https://static.figma.com/app/icon/1/favicon.svg" height="14"> Figma</div><div><strong><a href="https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop">Figma</a></strong></div><div>Created with Figma</div></blockquote>

**Comment by EugeOrtiz** [comment]
Here are the [latest designs ](https://www.figma.com/file/MRYBI5axcTwL4Ft8xAYhFOfy/Desktop?node-id=803%3A428)(Figma) for replies:

![replies - writing a reply](https://user-images.githubusercontent.com/37297779/49736528-3540b980-fc69-11e8-84f4-326e669cac7e.png)

**Comment by churik** [comment]
Can be closed since we aiming to use same ui for mobile and desktop
