### ISSUE TITLE
If a contact code is used in channel field then it cannot be used again

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-react#6251]
I made a mistake and pasted the contact code for a person into the chat name field and opened that chat. I then deleted that chat and tried using the same code in the correct contact code field, but it just opens the chat with the name of that contact code.

**Comment by churik** [comment]
@jakubgs AFAIK it was fixed, so if I correctly understood you paste name by mistake to "Topic" field (for public chats) and then trying to add this contact code to "Contact code" field.
If so, you shouldn't be able to do this anymore because validation for  "Topic" field was fixed.
I couldn't reproduce it anymore. Can you confirm it?

**Comment by jakubgs** [comment]
Looks fixed, now I get a warning about not using contact codes. Nice!
