### ISSUE TITLE
Prep Github Releases

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6273]
With the first desktop beta release coming up we would like to make the releases available on https://github.com/status-im/status-react/releases. This is convenient, findable, and a convention for many projects.

Currently there are over 4300 releases. These have no context and are automated for every build and tag.

Let's prep these things:

- Stop these automated releases
- Clear out all 4k+
- New release can be manual now
- [future] Eventually we can use the Github Release API and integrate with our Jenkins workflow. 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by jakubgs** [comment]
Those are not "4300 releases", those are "release points", and this is apparently a GitHub feature:
https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/td-p/6255
>each tag creates a release point but does not actually create a release. Releases themselves are created when you add release notes to a tag. However, as you noted, tags that don't have a release associated with them do still show up on the releases tab, albeit in a very different style. I can see how this could be confusing.

We create a lot of `build-[0-9]` tags like `build-8943` because we use them to track build numbers that are using when adding metadata to iOS/Android releases. The script that does that is [`scripts/build_no.sh`](https://github.com/status-im/status-react/blob/develop/scripts/build_no.sh). Those have to be tracket in a global way and using Git tags was the simplest way. We could possibly replace that method with something else and remove all those tags, and in effect remove all those "release points", but that's gonna be a bit of work.

I'll have to figure out a reliable way of tracking build number globally without using Git.

<blockquote><div><strong><a href="https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/m-p/6255#M2054">Tag without release</a></strong></div><div>For our projects, we are using tags which seem to create releases associated with every tag. Is there a way to stop creation of releases with each tag?  I understand releases at the core are based on tags.   Related discussion: https://stackoverflow.com/questions/28496319/github-a-tag-but-not-a-rele...</div></blockquote>

**Comment by chadyj** [comment]
Thanks @jakubgs. I'll close this issue then. We can still use the release feature and try to improve as we go.
