### ISSUE TITLE
3 dots and material design add contact button overlap

### ISSUE THREAD

**Issue by jarradh** [status-im/status-react#629]
![73f0d7d01262f27ec4d4cbaff56b02f4_original](https://cloud.githubusercontent.com/assets/2714786/21708030/327b85ea-d407-11e6-94d2-65425dd4e3f9.png)

```
epowerj [10:47 AM]  
I found this annoying UI thing where the big plus button overlaps with a contact. I can't scroll since there is only one contact at the moment.

jarradhope [10:47 AM]  
thats a really good point @epowerj

jarradhope [10:47 AM]  
i wonder what the material design solution is for that

epowerj [10:48 AM]  
In Telegram, the plus button slides off screen automatically

jarradhope [10:48 AM]  
slides off screen when?

epowerj [10:48 AM]  
Hold on, let me check

epowerj [10:51 AM]  
So on default, the button is there

[10:51]  
When you start scrolling down, it disappears

[10:51]  
It reappears when you scroll up

jarradhope [10:52 AM]  
and when you can't scroll ?

epowerj [11:06 AM]  
@jarradhope I don't actually know

[11:06]  
when you have only a few contacts, it's not a problem because they're at the top of the screen

[11:07]  
..actually, even when the plus button is covering a chat, it doesn't get in the way because telegram doesn't have the three dots at the right of a chat

jarradhope [11:10 AM]  
@epowerj a chat != contact

epowerj [11:11 AM]  
In telegram, it's the same thing

epowerj [11:13 AM]  
you can see options and stuff after you open the chat, even if it it's empty

jarradhope [11:14 AM]  
cool, we'll take a look and see if we can improve on what we have :slightly_smiling_face:

epowerj [11:15 AM]  
there are just so many ways of doing a chats
```

**Comment by jarradh** [comment]
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/106
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/111

**Comment by andytudhope** [comment]
I think that you could also increase the padding at the bottom of the page (which might just fix the fab buttons positioning) because it is cutting off the last of your contacts no matter how many you have. This is scrolled as far as I can down:

![image](https://cloud.githubusercontent.com/assets/13001517/21721886/ecf8f3e6-d432-11e6-81ba-c081d5f0695c.png)

I also seem to be having that same issue lefteris was having with not being able to add some contacts once a chat is open with them. Lavenderblush is actually Simon, but I can't add him... (Is there another issue for this is all I am asking).

**Comment by jarradh** [comment]
Yeah I agree that will be the easiest solution, on second point we have issue #636

**Comment by flexsurfer** [comment]
fixed in https://github.com/status-im/status-react/issues/585, we have edit mode for editing contacts
![image](https://cloud.githubusercontent.com/assets/11790366/23122549/b85f313e-f775-11e6-939c-244a92b3510d.png)
