### ISSUE TITLE
Unknown is shown for reply messages sent from latest nightly if one of the users updated from release

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6298]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

*Summary*: if `user A` and `user B` have a chat, where `user A` used released version and `user B` latest nightly (12/10/2019) when `user A` upgraded to latest nightly, `User B` will see "Unknown" for all messages that were sent in reply to `User B` until upgrade.

#### Expected behavior
no "Unknown"

#### Actual behavior
<img width="185" alt="usrr" src="https://user-images.githubusercontent.com/4557972/46876702-ac172d00-ce47-11e8-828c-b2c7529b367b.png">

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
*Preconditions*

- `User A` has release installed;
- `User B` has latest nightly(12/10/2018) installed.

*Steps:*

1) `User A`: Open Status 
2) `User A`: Join to any chat (i.e. #test) 
3) `User A`: Send message 
4) `User A`: Open Status
5) `User B`: Join to the same chat (i.e. #test)
6) `User B`: Send message `1234`
7) `User A`: upgrade to latest nightly (12/10/2018)
8) `User A`: reply to meassage `1234`
9) `User B`: check history

NOTE: not reproducible for messages that are sent after upgrade and for User A.

### Additional Information
* Status version: nightly 12/10/2018
* Operating System: Android, iOS, desktop
* TF session for `User B` on step 9 (36:30): https://app.testfairy.com/projects/4803590-status/builds/8625434/sessions/4403817526/?accessToken=saTKxNTAkSYImdKewgi01sCJrWM

**Comment by janherich** [comment]
As we changed the way how message-id is calculated in the latest nightly (due to reorganising code), there is unfortunately no way to retrieve old ids and replies will be broken between versions. 
As a band-aid, I will open PR which will hide quoted message when it can be found (so the reply is displayed as a normal message), in the future, we will be more careful and properly lock the protocol to avoid such things.
