### ISSUE TITLE
Analytics daily messaging users showing 0

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6314]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a community member, I want to view usage stats so that I can see how Status is being used.

### Description

Daily whisper users are displayed at https://analytics.status.im/#messages but in the last few days daily users are showing 0.

@adambabik recently changed how metrics are stored so we need to make an adjustment for the chart.

![whisper_distinct_users_daily-2](https://user-images.githubusercontent.com/116099/46951135-5fba3000-d087-11e8-8b4e-c55982291584.png)

#### Expected behavior
daily messaging users shown

#### Actual behavior
0 stats

### Reproduction

- Go to https://analytics.status.im/#messages

<blockquote><div>analytics.status.im</div><div><strong><a href="http://analytics.status.im/">Analytics for Status</a></strong></div><div>Analytics for Status</div></blockquote>

**Comment by adambabik** [comment]
Where can I take a look at the source code of this chart?

**Comment by chadyj** [comment]
> Where can I take a look at the source code of this chart?

https://github.com/status-im/analytics-dash

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/analytics-dash">status-im/analytics-dash</a></strong></div><div>Contribute to status-im/analytics-dash development by creating an account on GitHub.</div></blockquote>

**Comment by adambabik** [comment]
https://github.com/status-im/analytics-dash/blob/7d5db8d1b68b1db629d3b22cccd7e6fb344ba11c/prometheus.py#L100-L105 needs to be fixed and use https://prometheus.status.im/graph?g0.range_input=4d&g0.expr=increase(shh_unique_authors_total%5B1d%5D)&g0.tab=0.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/analytics-dash">status-im/analytics-dash</a></strong></div><div>Contribute to status-im/analytics-dash development by creating an account on GitHub.</div></blockquote>

**Comment by chadyj** [comment]
Thanks @adambabik 

Also to confirm, can we do Weekly and Monthly users too? (that are not simply aggregations of daily)

**Comment by adambabik** [comment]
That metric has started being collected a few days ago so not really. Unless analytics tool will have some embedded database where it can pour and combine data from the previous and the new metrics.

**Comment by tersec** [comment]
I'm disinclined to add such ephemerally useful complexity, especially since going too far back, before the @chadyj 's addition of several channels for monitoring, creates internal discrepancies which undermine the data's utility/quality due to https://github.com/status-im/infra-eth-cluster/commit/6a42ca8f55bc554d933fccbfff478f00f68802dd. Furthermore, there's no data accessible to me prior to September 30th/October 1st at this point.

**Comment by chadyj** [comment]
Whatever you guys decide it would be very useful to have daily, weekly, and monthly resolution. It can be hard to spot trends on a daily level (eg things drop on weekends), but weekly and monthly is a consistent period that allows us to see proper trends at different timescales.

Fingers crossed we can have it :)

**Comment by adambabik** [comment]
Then we just need to wait a bit and we will have this data for weekly/monthly resolution :)

Having said that, if we want to be sure that this data does not get lost, we need backups. Prometheus is persistent but usually the flow is that data is exported from Prometheus to some other system that is "more" persistent.

**Comment by tersec** [comment]
Data getting lost seems like a legitimate concern -- it's already gotten lost between various configuration changes so far. It might not have to be as easily queryable, but depending on Prometheus alone seems suboptimal.

**Comment by chadyj** [comment]
Might it be simpler to warehouse/store the data with something like https://aws.amazon.com/simpledb/ or https://cloud.google.com/datastore/ for simple storage and queries?  

Or do we have something suitable already deployed @jakubgs? 

<blockquote><img src="https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png" width="48" align="right"><div><img src="https://a0.awsstatic.com/main/images/site/fav/favicon.ico" height="14"> Amazon Web Services, Inc.</div><div><strong><a href="https://aws.amazon.com/simpledb/">AWS | Amazon SimpleDB – Simple Database Service</a></strong></div><div>Amazon SimpleDB is a simple database storage solution that allows developers to simply store & query data items via web services requests, saving time.</div></blockquote>
<blockquote><img src="https://cloud.google.com/_static/7e8fbbc4f5/images/cloud/icons/favicons/onecloud/favicon.ico" width="48" align="right"><div>Google Cloud</div><div><strong><a href="https://cloud.google.com/datastore/">Datastore - NoSQL Schemaless Database  |  Cloud Datastore
       |  Google Cloud</a></strong></div><div>Cloud Datastore is a highly-scalable NoSQL database for your web and mobile applications.</div></blockquote>

**Comment by tersec** [comment]
A couple of questions about how to use this schema:

- Is it by design that there's no overall count from `increase(shh_unique_authors_total[1d])`, or is there, and I'm missing it? Because as these are just counts per chat, they can't really be added. I've generally set this up in a two-stage way, such that there's some intermediate representation that obeys a semigroup, or, ideally, a monoid such that one can combine intermediate results without losing accuracy. I've used both MinHash (useful for intersections, though there are ways to do that well with HyperLogLog; consider, e.g., retention metrics for use cases for intersections) and HyperLogLog (a good, standard, approach, which has lossless unions but usually suboptimal intersections) approaches to this as approximations, if it's too expensive to store source lists directly. Alternatively, one can place in addition to the per-chat results a whole-chat result, but that doesn't generalize (e.g., combining language communities' chats in a more freeform way). Or, maybe all people want is per-chat, or using the biggest chat as a proxy?

- Different data centers have different results. `ac-cn-hongkong-c` seems to dominate. Is that the one that should be used? Should they be added, or otherwise combined?

**Comment by adambabik** [comment]
If we want to keep the unique number of people participating in the chats thorough day, week, month, we need to unfortunately store the numbers somewhere. The problem is that the counter can be restarted any moment. To get an increasing counter you can do `shh_unique_authors_total{source="slave-01.ac-cn-hongkong-c.metrics.hq",fleet="eth.beta"}` but then if the container backing up the number restarts, it will drop to 0.

The metrics that we can get from Prometheus always right are rates. For example, number of unique participants per hour/day/week.

For more advanced analysis we need some backing up software like e.g. InfluxDB.

> Different data centers have different results. ac-cn-hongkong-c seems to dominate. Is that the one that should be used? Should they be added, or otherwise combined?

The metric must be identified by source and fleet, so something like `shh_unique_authors_total{source="slave-01.ac-cn-hongkong-c.metrics.hq",fleet="eth.beta"}` can be used. It should not matter which source is used but it does matter which fleet is used. I just checked and all source within a fleet are equal.

**Comment by tersec** [comment]
The rate is all that matters here, so that's fine.

**Comment by chadyj** [comment]
Any update @tersec?
