### ISSUE TITLE
Cover #6283 issue by automated test

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#6384]
### Description

Issue https://github.com/status-im/status-react/issues/6283 need to be covered by autotest.
Instead of creating a separate one we can extend already existing test_send_transaction_from_daap to wait for balance update on Wallet main screen.

**Comment by hetvart** [comment]
@Serhy 
as far as I got the issue #6283 the problem is not in balance update in wallet but in navigation to a recently visited or unknown chat screen whereas we expect to return back to Status Test DApp screen.

The test you mentioned is aimed to check whether we can send a tx from Status Test DApp and verify this tx appears in network.

Based on this I prefer to follow atomic style checks and add a separate test case with the steps described in the mentioned issue (Reproduction2), wdyt?

1. Open Status and create an account
2. Join public chat (e.g. #cryptopeople)
3. Open SimpleTestDapp -> Assets
4. Request Ropsten ETH (skip if you have ETH already)
5. Advanced -> Transaction Fee -> Tap Done button
6. Sign transaction

Actual result: Contact navigated to #cryptopeople public chat

**Comment by Serhy** [comment]
@hetvart thanks for raising it. 
Agree to have a separate test dedicated to this scenario. There are also "key-points" in above scenario (2nd and 4th in https://github.com/status-im/status-react/issues/6384#issuecomment-431033147) which we need to cover which would be redundant to update test_send_transaction_from_daap.
Created https://ethstatus.testrail.net/index.php?/cases/view/5654



<blockquote><img src="https://static.testrail.io/5.5.1.3746/images/favicon.ico" width="48" align="right"><div><strong><a href="https://ethstatus.testrail.net/index.php?/cases/view/5654">Login - TestRail</a></strong></div></blockquote>

**Comment by hetvart** [comment]
@Serhy 
thank you!

**Comment by Serhy** [comment]
Closing as it was done.
