### ISSUE TITLE
Message history is not fetched for desktop (reproducible on some accounts)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#6410]
### Description

*Type*: Bug

*Summary*: when you join to channel, history for last 24h is not fetched for desktop. For example, if you join to channel #a from mobile, send several messages here and then join to #a in desktop - you cannot see these messages.
Reproducible for my account only on desktop. 

Cannot reproduce it on fresh or restored account, only on existing installation (using it from nightly to nightly, so every day after unlocking screen I'm losing all history when I was AFK).

#### Expected behavior
history for last 24h is fetched, can see "From IOS" message

#### Actual behavior
no history is fetched; channel is empty

### Reproduction
*Prerequisites:* account `User A` on desktop app, `User B` on mobile app

- as user B: open Status, join any public channel (i.e. #chuone), send message (i.e. "From IOS")
- as user A: log in, join #chuone, check history.

You can check that channel is not empty by any other new user (works on both mobile and desktop)

### Additional Information

* Status version: nigthly 19/10/218
* Operating System: Mac OSx

#### Logs

* Video: http://take.ms/bFXQj
* Geth.log: [geth_messages.log](https://github.com/status-im/status-react/files/2495228/geth_messages.log)
* StatusIm.log: 
[status_messages.log](https://github.com/status-im/status-react/files/2495233/status_messages.log)

Feel free to ping me for mnemonic phrase or any other data that can help to debug an issue.

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=XwVppwjR86Lh2hiOq2I1CGQuYppWRo&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/XwVppwjR86Lh2hiOq2I1CGQuYppWRo">File "screencast 2018-10-19 12-17-36.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by yenda** [comment]
@churik could you check that this problem isn't caused by hongkong mailserver ?

**Comment by churik** [comment]
@yenda 
used  mail-02.do-ams3.eth.beta mailservers

**Comment by yenda** [comment]
This error in the log is definitely the reason why no history is being fetched, but there isn't enough information for me to figure out how your account got to that state.
Could you try to find a reproducible way to get an account that gets into that state ?

 ``` "ERROR [status-im.utils.async:19] - failed to run task Error: transport-inbox-topic.topic must be of type 'string', got 'null' (null)"```

**Comment by churik** [comment]
@yenda 
can I have any clue on what it can be related?
Chat or message amount, contact requests, or reasons can be the same as here: https://github.com/status-im/status-react/issues/6114?

**Comment by 0xc1c4da** [comment]
I haven't received any private messages or any public chat history on mobile or desktop unless i'm online ( I know because i still receive push notifications). If it's public chat history I seem to get only 24 hours at most but I have rather dramatic inconsistencies in public chat history when comparing desktop and mobile

**Comment by oskarth** [comment]
This is just a feeling, but it seems to me like we've had a few incidents last few weeks that have lead to less reliability, both "perceived" and real. This leads to a loss of trust for users, including core contributors.

Perhaps we can get to the root of the problem, and see what we can do to stop it in the future? For example, changes to mailserver logic could probably be inspected under more conditions before merging, as well as testing upgrade paths rather than dumping that responsibility on users (breaking changes in a Discuss thread, rather than dealing at it at install script level).

Aside from the HK node, I haven't seen any indications of problems on the cluster level last month or so. That could of course be completely wrong, but it seems to me like it's mostly client side issues.
