### ISSUE TITLE
Ensure TF recovery phrase security vulnerability post mortem trigger is correct

### ISSUE THREAD

**Issue by oskarth** [status-im/status-react#6416]
1. Checkout commit before presumed trigger https://github.com/status-im/status-react/pull/5521/files
1. Change TestFfairy token to new one (check with QA, cc @annadanchenko)
1. Create and recover account
1. Check TF to ensure that we identified the trigger correctly

This is important as we want to make sure we identify the trigger correctly, as well as communicate it correctly and confidently. As we are pushing to get the disclosure document out soon it'd be good if we did this as soon as possible.

<blockquote><div><strong>[TestFairy data leak post-mortem - CodiMD](https://notes.status.im/8tqS2rHUS0O3AgBMWyEe7Q?view)</strong></div></blockquote>

**Comment by oskarth** [comment]
^ @rasom @yenda @dmitryn do either of you want to take this one?

**Comment by annadanchenko** [comment]
APP Token value can be found in https://app.testfairy.com/settings/  section "SDK App Token". To access TF use shared LastPass account from Shared folder

**Comment by dmitryn** [comment]
@oskarth i can look at this one

**Comment by dmitryn** [comment]
@annadanchenko could you send me TF token on Status app please?

**Comment by dmitryn** [comment]
It seems not possible to make Jenkins build from commit that was while ago due to Jenkins pipeline changes, so i reverted TF version to 2.10.0 on current codebase 
https://github.com/status-im/status-react/commit/ef222c3ad5432ece227a96d567ed72a454cd5418
and made custom build https://ci.status.im/job/status-react/job/combined/job/mobile-android/5594/ that showed that seed phrase is **NOT hidden** on TF session https://app.testfairy.com/projects/4803622-status/builds/8634022/sessions/4404429482?source=latest-sessions

Not sure why is that, but i cannot confirm that upgrading from 2.10.0 to 2.14.1 (https://github.com/status-im/status-react/pull/5521)  caused the issue.

<blockquote><img src="/static/ff3fc112/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/combined/job/mobile-android/5594/">status-react » combined » mobile-android #5594 [Jenkins]</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8634022/sessions/4404429482?source=latest-sessions">TestFairy: Login</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
Seems like TF version upgrade was not the real reason of bug.

Found another PR https://github.com/status-im/status-react/pull/6171 that removed `hideView` call https://github.com/status-im/status-react/pull/6171/files#diff-7376277fc14fd1b6ec5162eb03d9c233L21

/cc @corpetty 

<blockquote><img src="https://avatars2.githubusercontent.com/u/2364994?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/6171">[#6162] fix passphrase validation by rasom · Pull Request #6171 · status-im/status-react</a></strong></div><div>fix #6162
status: ready</div></blockquote>

**Comment by dmitryn** [comment]
Actually it was 11 days ago. I'm going to revert that commit and check it on TF 2.14.1 version.

**Comment by dmitryn** [comment]
Revision 1cb5828ce6e3079971a1edbfa25b2603758f2a12
TF 2.14.1
Android
https://app.testfairy.com/projects/6688250-statusdebug/builds/8634169/sessions/4404442924

Revision 6e0d18f76de3b79cae57360119a584f8fbfd6c7c
TF 2.10.0 
Android
https://app.testfairy.com/projects/6688250-statusdebug/builds/8634147/sessions/4404441326

I'm having weird results.
Checked both revisions (before and after upgrade to 2.14.1) - passphrases are hidden on both.
Cannot build and check iOS because there are issues with building it locally for those revisions.

@asemiankevich do you remember what devices were affected by this? https://github.com/status-im/status-react/issues/5567

<blockquote><div><strong><a href="https://app.testfairy.com/projects/6688250-statusdebug/builds/8634169/sessions/4404442924">TestFairy: Login</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://app.testfairy.com/projects/6688250-statusdebug/builds/8634147/sessions/4404441326">TestFairy: Login</a></strong></div></blockquote>

**Comment by dmitryn** [comment]
If anyone could help to reproduce the bug, here is `.env` with updated TF token to use:

```
TESTFAIRY_ENABLED=1
ETHEREUM_DEV_CLUSTER=1
RPC_NETWORKS_ONLY=0
LOG_LEVEL=debug
LOG_LEVEL_STATUS_GO=info
FLEET=eth.beta
RN_BRIDGE_THRESHOLD_WARNINGS=0
POW_TARGET=0.002
POW_TIME=1
DEFAULT_NETWORK=mainnet_rpc
TESTFAIRY_TOKEN=b8f779816eacb3998b58ee0b2644f85519af6744
INSTABUG_TOKEN=758630ed52864cbad9c5eeeac596c60c
DEBUG_WEBVIEW=1
INSTABUG_SURVEYS=1
GROUP_CHATS_ENABLED=1
CACHED_WEBVIEWS_ENABLED=1
EXTENSIONS=1
HARDWALLET_ENABLED=0
PFS_ENCRYPTION_ENABLED=0
DEV_BUILD=1
```

TF credentials to access dashboard are in shared account.

**Comment by dmitryn** [comment]
@rasom could you please help to reproduce the bug https://github.com/status-im/status-react/issues/5567? 
I've checked out both revisions https://github.com/status-im/status-react/issues/6416#issuecomment-431468664 (before and after the 2.14.1 upgrade) 
and they both hide the passphrase.

**Comment by oskarth** [comment]
@dmitryn @rasom Any luck with this?

**Comment by dmitryn** [comment]
@oskarth no, i couldn't reproduce this issue. Both revisions (before and after upgrade to 2.14.1) hide the passphrase view (meaning that `hideView()` API works there)

**Comment by corpetty** [comment]
I am currently OoO right now until Thursday.  I will dig into the current post-mortem and try and figure out what happened by going into some more resolution.  Thank you @dmitryn for testing both versions to verify that was the trigger.  

We'll learn how this happened one way or another.
