### ISSUE TITLE
1-1 chats are restored when recovering an account

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6417]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: For a recovered account all 1-1 chats with messages received during last 24 hours are restored

#### Expected behavior
No old 1-1 chats are restored 

#### Actual behavior
All 1-1 chats restored with messages 

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account
- Get some 1-1 chats with received messages
- Read all messages (unread messages counter disappeared)
- Delete all app data 
- Recover the account 

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: Oct 19 nightly build - 0.9.30 (11016); node 0.16.3
* Operating System: Android, iOS, MacOS

**Comment by chadyj** [comment]
Ah have enjoyed this "feature" as I get chat and message history on a new device.

Why is the expected behaviour that no chats should be shown (if indeed there are recent chats)?

**Comment by yevh-berdnyk** [comment]
@chadyj I remember we removed restoring of chats but unfortunatelly I can't find an issue/PR
@annadanchenko maybe you can advise?

**Comment by lukaszfryc** [comment]
I'd say it's better to **not** restore messages when account is recovered. It's because this feature is works only partially. Only incoming messages are restored. There are no outgoing messages and contact requests. Therefore, I think it's better to not restore them at all to avoid confusion.

We should promote devices paring more. Like auto-pairing or in-app suggestions to sync devices. See discussion about it https://github.com/status-im/status-react/issues/6898#issuecomment-442778754

**Comment by mandrigin** [comment]
I don't think that is a bug, maybe we just need to make sure that we notify a user correctly. So, tbh, I don't see anything to be fixed there.
Also, with device sync, you get much more than that.

feel free to reopen if you disagree.
