### ISSUE TITLE
 Request message stays opened after it was answered with required amount

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6418]
### Description

*Type*: Bug

*Summary*: Request message remains  opened (send button is active and clickable) even i have sent required funds

#### Expected behavior
Once request is answered - send button is not active

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/47222849-741c6680-d3c0-11e8-95a7-62266724fdf3.png)

### Reproduction
- Open Status
- Go to 1x1 chat
- Send request message to device A
- As device A answer the request by tapping `send` and filling out required amount
- Pay attention to the request message

**Comment by janherich** [comment]
@asemiankevich Just to clarify, the bug happens on latest develop/nightly, correct ?

**Comment by asemiankevich** [comment]
@janherich yes i just used https://status-im.ams3.digitaloceanspaces.com/StatusIm-181019-101134-7d0c65-nightly.apk that should be latest nightly 

<blockquote></blockquote>

**Comment by janherich** [comment]
@goranjovic I investigated the bug and the cause is that when sending ropsten eth, asset in params is filled with "ETH" symbol (even if it's actually `ETHro` from command suggestions list), while request doesn't go through wallet, so it stays `ETHro`.
As a result of this, the check condition for clearing the request (if the response `/send` command has the same asset and value) is never true due to `ETH`/`ETHro` mismatch, so the request is not considered answered.
I believe this is bug on wallet part, as the asset selector in wallet correctly lists the asset as "ETHro", but it's filled incorrectly by wallet.

**Comment by asemiankevich** [comment]
thanks for investigation @janherich ! @goranjovic please take a look

**Comment by churik** [comment]
still reproducible on nighlty 21/07/2019

**Comment by asemiankevich** [comment]
no commands in chats now
