### ISSUE TITLE
Public chat that was re-opened should not be empty

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6454]
### Description

*Type*: Bug

*Summary*: 

If a public chat is removed from the chat list and then reopened again, its content is empty. There is "Fetching messages" but the old messages (before removing the chat) do not appear. I think it's counter-intuitive and the app should display old messages when public chat is re-opened. 
I'd say old messages should be displayed even though the user has cleared the chat before removing it. So basically joining/re-opening a public chat should fetch all messages.   

### Reproduction

- Join public chat with some messages
- Remove it
- Join the same public chat again
- User should see historical messages (currently 7 days of history) which is not the case

### Additional Information
* Status version: Oct 22, nightly
* Operating System: Android, iOS

**Comment by chadyj** [comment]
Deleting the chat history was intentional and flagged by @adambabik in https://github.com/status-im/status-react/issues/4215 as a security-related feature.  @adambabik Can you elaborate on the use case here?

It seems to make sense if a user "deletes" the chat then it shouldn't be "un-deleted". Perhaps a "leave chat" command is a better fix for users that want to leave a chat and return to it later.

**Comment by adambabik** [comment]
This is about removing stuff you chatted about without a need to remove the application completely. It was meant to provide additional privacy and security as messages stored on the device are decrypted and encrypted again on the database level.

> It seems to make sense if a user "deletes" the chat then it shouldn't be "un-deleted". Perhaps a "leave chat" command is a better fix for users that want to leave a chat and return to it later.

"Leave chat" sounds good. We should make a distinction here I believe. Other use case is to "silence chat" and "Leave chat" might cover this.

**Comment by lukaszfryc** [comment]
> It seems to make sense if a user "deletes" the chat then it shouldn't be "un-deleted". Perhaps a "leave chat" command is a better fix for users that want to leave a chat and return to it later.

I think having 2 options like "Delete chat" and "Leave chat" will only create confusion. Personally, I do not see a reason why I should not see a history of a public chat when I join it again. Imagine, I deleted #status chat but decided to join it after few days. I'd assume that I can scroll it to see all historical messages.

Maybe we should treat 1-1 chats differently than group/public chats. Meaning, if I delete 1-1 chat, all messages I sent are removed from mailservers (btw, we can't control external mailservers, can we?). But, should it be the case for public chats as well? I don't think so. 

Re clear chat, it's quite obvious for me - it will clear my **local** messages so that I will never see them again unless I will reinstall the app (https://github.com/status-im/status-react/issues/4215).

**Comment by bhauman** [comment]
There is a simple straightforward solution for this. This is to delete the messages but not change the `deleted-at-clock-value` which is essentially a marker that says messages have been deleted up to this point. This mark is meant to capture the idea of choosing to clear the history.

The problem is that the code is currently conflating the idea of clearing the history with deleting the chat. This is not whats intended if you use the app and experience it.  Deleting the chat means deleting the chat not marking all the current messages as things I never want to see again. 

One thing to note is that delete the chat can also provide a means of reseting a chat in case there is a a state problem in the chat, however if we "delete" the chat and but keep metadata that is specific to this application and the chat like `deleted-at-clock-value` it prevents users from following this time honored pattern of turning it off and on again. It also opens us up to upgrade problems.

**Comment by bhauman** [comment]
I would further add that is seems the security concern is removing the messages from the persistent datastore and not about the messages in memory.

**Comment by yenda** [comment]
Medium priority for the discussion.
