### ISSUE TITLE
Do not display logs by default in release builds; make it possible to enable in the UI

### ISSUE THREAD

**Issue by vitvly** [status-im/status-react#6569]
### Description
We should disable all logs by default. However, it should be possible to temporarily enable logging via advanced settings in Profile.

**Comment by chadyj** [comment]
Decision: Completely disable logging for alpha release.
Optional for release or to be done later: add toggle to enable/disable logging

**Comment by vkjr** [comment]
@chadyj, @siphiuel  we can fully disable logging but should we allow user to somehow enable them for debugging? Or we should prevent release from printing logs in any case, because that can be insecure?

Actual implementation depends on this. Currently all clojurescript logs eventually come through the qt app and logged by it. Additionally qt app has own logs, for example from react-native-desktop internals.
If we don't want to have logs at all, for release builds we can conditionally comment out logging process in `desktop/main.cpp` file. 
If we want logs to show up only on request, for release builds we can disable logging categories with `QLoggingCategory::setFilterRules()` method, but user will be able to enable logs by setting `QT_LOGGING_RULES` env var manually.
wdyt?

**Comment by chadyj** [comment]
The second option sounds good.

**Comment by chadyj** [comment]
After the release can we follow up with this issue https://github.com/status-im/status-react/issues/5848 which has the UI to disable logs.
