### ISSUE TITLE
The link is not clickable when formatted with asterisks or tildes

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/status-react#6705]
Type: **Bug**

Summary: The link is not clickable when it was sent wrapped up with asterisks (*) or tildes (~)

**Expected behaviour**

The link should be clickable no matter the format

**Actual behaviour**

The link is not clickable when it was sent wrapped up with asterisks (*) or tildes (~), for sender and a recipient both

**Reproduction**

1. Open Status
2. Start 1-1 chat/public chat
3. Copy a valid link and paste it, wrapped up with asterisks (*) or tildes (~)
4. Try clicking on your link to open it, as a sender or a recepient

**Additional Information**

Status version: Develop (d2160e)
Operating System: iOS 12.0, MacOS 10.13.4

**Comment by janherich** [comment]
This is actually intended behavior - due to bad performance of nested `text` nodes in RN, we unfortunately have to be more restrictive and can't allow hierarchic text formatting, meaning that something can be bold and link and the same time, etc.
So the current logic is to always take the outermost "wrapping" modifier, so if some text is formatted as bold/italic/codequote, anything inside (tag, link, other formatting) is not taken into account.
