### ISSUE TITLE
Show unread count instead of 9+

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6749]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a chat user, I want to see the real unread message count so that I can know how many unread messages there are.

### Description

Status currently shows unread message counts as `9+` when there are more than 9 unread messages. In common usage this means that chats always tend to show 9+ and offer no context or insight into how many messages are actually unread.  It could be 10 or 945.

By showing the true count we can better inform users to how active a chat is and help them understand how many unread without the need to go into each chat. 

#### Expected behavior
Chat badge count shows actual number if more than 9

#### Actual behavior
Shows 9+

### Solution

For both mobile and desktop.

Discussion: We may want to show 999+ or 9999+ or some upper limit otherwise it could go a bit nuts?

cc @errorists

**Comment by errorists** [comment]
Here are mobile badges for reference
<img width="580" alt="slice" src="https://user-images.githubusercontent.com/4932774/48609294-cdf25b00-e983-11e8-8021-22289163f826.png">

cc @EugeOrtiz for desktop

@chadyj should this include the total unread badge next to the Home icon (space constrained but it's doable) and the badges next to the 'Back' arrow when inside a chat (space constrained and not doable, we can't add additional digits there)? Honestly, I always found the badge next to 'Back' arrow totally unnecessary but that's me :) after 1000 we can also do 1K+, 2K+, to cap it at a reasonable 3 character limit. Otherwise, 999+ sounds ok.
