### ISSUE TITLE
No automatic scroll to cursor location for long messages

### ISSUE THREAD

**Issue by carlbennetts** [status-im/status-react#676]
When a user types a long message, there is no automatic scroll to the cursor location (so that the focus remains on the text just typed).

https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/83

<img src="https://s3.amazonaws.com/instabug-pro/states/files/44499923/screenshots/e7ce38af9df29d3dd35093d3c6ff1c1a_original.jpg?1483628078" width="320">

**Comment by viebel** [comment]
Starting to work on this issue...

**Comment by jarradh** [comment]
You should assign it to yourself and add the label `in progress`

**Comment by viebel** [comment]
OK. Will do for next one

**Comment by flexsurfer** [comment]
reproduced on Android 6, not reproduced on iOS

**Comment by viebel** [comment]
Thanks for the info @flexsurfer. I'm currently working on it.

**Comment by alwx** [comment]
This bug is much trickier because this bug is related to the bug in React Native (https://github.com/facebook/react-native/issues/6552). Switching from `onContentSizeChange` to `onChange` solves one problem, but leads to another — `onChange` fires only when a user enters text via a keyboard thus the suggested fix leads to problems with emoji picker and pasting text to the input.

The best thing we can do is to
1) Change label from `beginner` to `intermediate` because this task means fixing React Native, not our code;
2) Postpone it a bit and let @viebel work on another task instead.

Thanks for your job, @viebel, but unfortunately this task is not that easy as it sounds and looks.

**Comment by viebel** [comment]
FWIW, I have discovered  that the same missing autoscroll bug occurs also with a fixed height multi-line textview (works fine on iOS but no autoscroll and Android).
