### ISSUE TITLE
Metadata leak in push notifications

### ISSUE THREAD

**Issue by chadyj** [status-im/status-react#6772]
# Problem

Reported by @hesterbruikman:

If a message sender has their mobile OS language settings set to a supported language (e.g. Korean or Spanish) the notification of the recipient is shown in this language, regardless of the anguage the recipient has set in their OS. E.g. Jinho sends a message to Philio while Jinho's phone is set to Korean, Philip receives a notification in Korean while his phone is set to English.

# Acceptance Criteria

Push notifications should not reveal metadata

cc @mandrigin @corpetty @rasom @PombeirP @corpetty

**Comment by pedropombeiro** [comment]
This is yet another instance where we see it's better to rely on the [`data` field for the payload](https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload) instead of `notification` field (another being e.g. https://github.com/status-im/status-react/issues/3451). We should be sending a silent notification (only `data` filled in) and getting that to trigger an intent on our mobile app, which would be responsible for decoding the payload and actually displaying a localized message.

**Comment by chadyj** [comment]
@PombeirP Thanks for taking a look. Will you be able to take this?
Looks like there is at least a quick fix here and perhaps a broader PN improvement?

**Comment by pedropombeiro** [comment]
I'll take a look and try to make it backward-compatible with older clients.

**Comment by pedropombeiro** [comment]
@chadyj another thing we're sending in the PN as hidden metadata is the sender pubkey address and the chat-id (which in a 1:1 seems to be one of the interlocutor's pubkey address). Ideally, we'd want to send those values hashed (or maybe there's a better approach @corpetty?) and then do a lookup on the receiver end (same thing btw if we send a message ID, which we should add to the payload to enable current/future scenarios).
Is it something we want to address in this PR as well (move to using hashes of addresses)?
