### ISSUE TITLE
Unable to manage assets in wallet

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/status-react#6825]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Unable to enable/disable assets lists in wallet, nothing happens when trying to open manage assets list 

#### Expected behavior
Assets list with checkboxes is shown 

#### Actual behavior
User stays in the wallet, assets list is not shown

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create an account or recover an existing one
- Navigate to wallet and set up it if needed
- Click 3 dots button in the upper right corner
- Click Manage Assets

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3 (12790); node 27700aa2 (Nov 21 nightly build)
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
@flexsurfer could it be broken by this extension hook for wallet?

**Comment by antdanchenko** [comment]
@jeluard, @asemiankevich the issue has been introduced in #6783 please do not merge the PR before getting 100% (except of known issues from develop) e2e tests passed

**Comment by asemiankevich** [comment]
@antdanchenko it was marked `skip-manual-qa` which i was trying to avoid. My bad i did check extension but not the app.

**Comment by jeluard** [comment]
@antdanchenko How about having PRs blocked while e2e tests do not pass?

**Comment by antdanchenko** [comment]
@jeluard here is a topic  https://discuss.status.im/t/block-a-pr-from-merge-if-e2e-tests-fail/786 for tracking the progress upon the feature implementation
Would be great if you can help us in getting this done asap :)

<blockquote><img src="https://discuss.status.im/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/block-a-pr-from-merge-if-e2e-tests-fail/786">Block a PR from merge if e2e tests fail</a></strong></div><div>Hi all,  The topic is created for tracking progress and steps upon the workflow implementation  Steps:    bugs in develop should be fixed for getting 100% passed tests:   https://github.com/status-im/status-react/issues/6825 https://github.com/status-im/status-react/issues/5975    Each PR should be rebased on latest develop automatically in order to test integration part (@jakubgs can you help us with that?)    Use PRs branch for running e2e tests instead of develop (@Anton  will implement that) ...</div></blockquote>
