### ISSUE TITLE
[Next] button is hidden under keyboard when creating account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#6846]
### Description

*Type*: Bug

*Summary*: This issue contains several cosmetic improvements:
- `next` button is overlapped on Android when suggestions are enabled for keyboards. Also, it depends on keyboard size, for ex SWIFT keyboard is bigger than default one and it hides the Next button almost completely
- missing `Done` button on android keyboard
- missing `Done` button on iOS keyboard

#### Expected behavior

- keyboard does not hide this Next button
- both android and ios keyboards contain this Done button which could be used as Enter

@errorists @denis-sharypin please suggest something here if possible

#### Actual behavior

![image](https://user-images.githubusercontent.com/28752642/48913159-a53cfa80-ee88-11e8-9f1d-d07e756fa8d5.png)

![image](https://user-images.githubusercontent.com/28752642/48913176-b128bc80-ee88-11e8-8e3a-1c76d100a69e.png)

![image](https://user-images.githubusercontent.com/28752642/48913199-bf76d880-ee88-11e8-8e51-41b035d7872d.png)

### Reproduction

- Open Status
- Start creating account untill the step with entering name

**Comment by errorists** [comment]
I believe the keyboard should have the blue 'go' button since it's the one indicating forward progress, whereas done is more like 'I'm finished, peace out' ;) Now, if the keyboard overlaps the toolbar then we have a rather serious issue on hand since we rely on this pattern quite a lot in the app, can we confirm this can't be fixed? Maybe we hardcode the value or something else that's stopping the toolbar to appear directly above the keyboard?
