### ISSUE TITLE
Create appium group chat tests

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6884]
**Task**
Create E2E tests for group chats based on [TestRail test scenarios](https://ethstatus.testrail.net/index.php?/suites/view/48&group_by=cases:section_id&group_order=asc) (critical tests section).

**Details**
Use existing code like `create_group_chat`, `NewGroupChatButton`.

**Comment by lukaszfryc** [comment]
I will take care of it this week.

**Comment by lukaszfryc** [comment]
I'd like to automate following test cases in the scope of this GHI:
 
  |   | C3994 | Can create new group chat |   |   |  
  |   | C3993 | Can send text message in group chat |   |   |  
  |   | C3997 | Can delete group chat |   |   |  
  |   | C3998 | As admin of group chat can add new member |   |   |  
  |   | C3999 | As newly added member in group chat: can see new messages from old members, can send messages to chat that will be seen by old members 
  |   | C5674 | Can see system messages in group chats

@hetvart I feel like creating separate tests for each of these cases is a waste of time. E.g. if I want to cover deleting a group chat, I first need to create one. So C3997 will cover C3994 as well. I know that we decided to have atomic tests but don't you think that it's a bad idea for long e2e tests? 

From my experience, it's better to have longer "user flows" that cover different scenarios along the way same as user does when he interacts with the app. For instance, have a single longer flow where the 1st user creates a group chats, sends a message, adds a new member. In the meantime, the 2nd user replies to the message and checks system messages ("you were added to the group chat", etc.). At the end, admin removes the chat. All of the steps can be logged as a test output. 

WDYT about it? How would you go about automating the above cases?

**Comment by hetvart** [comment]
I think it could work, except С5674 - it's a "self-contained" test case.
one more is C3999 - it may require a separate predefined group chat with a long history which is available always
@Serhy what do you think?

**Comment by lukaszfryc** [comment]
But this would require changing the testrail test cases, right? Is it OK to do it or we need to stick to "atomic" tests?

**Comment by hetvart** [comment]
> But this would require changing the testrail test cases, right? Is it OK to do it or we need to stick to "atomic" tests?

the answer to your question is ambiguous and complex. The simple test the better. 
Meanwhile, an e2e test might reflect a large user flow/case. You should define by yourself what's the best solution here.

Some common verifications like create a chat, send a message to it, delete it are logical steps belonging to one scenario. In my opinion, those ids I mentioned in my previous comment seem to be separate tests.

**Comment by Serhy** [comment]
> I think it could work, except С5674 - it's a "self-contained" test case.
> one more is C3999 - it may require a separate predefined group chat with a long history which is available always
> @Serhy what do you think?


“Atomic tests” approach gives us, on the first place, more manageable, flexible, detailed coverage for manual needs. 

I also agree that ‘Delete chat’ test covers ‘Create chat’ test which might look as redundant. However, it’s unavoidable for both automation and manual functional app testing. 

For automation it’s even better to split the tests as for me! For example: 
Precondition for ‘Create group chat’ test is: Contact exist in the list of contacts.
So we need need to add user in contacts first so that we could create group chat. We can do it by adding user from public chat(1) and by copy-paste public key(2).
And so case (1) could be used for ‘Create group chat’ test and case (2) for ‘Delete group chat’
See what I mean?
Or, what if we remove ‘Delete group chat’ as a feature in future? In that case we need to edit test scripts. But in a case of having separated tests - we simply decorate the test to @skip.it and ‘Create group chat’ keep going do the job.

In my opinion for us, the atomic test separation makes the best sense for manual and automated test needs :)

**Comment by lukaszfryc** [comment]
I've been doing both (atomic) user story tests and [user journey tests](https://martinfowler.com/bliki/UserJourneyTest.html) in the past. I think both have pros/cons and maybe suitable depending on the needs. 

I agree with you that it's better to automate atomic tests first and only then have some journey tests if needed. Let me create separate autotests for those test cases.

Btw, from my experience the more low level (integration) the atomic tests are the better. Ideally, they are owned by devs and if possible, automated below UI level.
