### ISSUE TITLE
Emoji reactions to chat messages

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-react#6960]
### Description

*Type*: Feature

*Summary*: Users should be able to add/remove emoji reactions to messages. All chats and messages should be supported including own messages, send/receive commands and replies. SNT kudos are not in scope of this issue.

<img src="https://user-images.githubusercontent.com/7532782/49282915-9eb61080-f490-11e8-95b5-99ed7a527302.png" width="200">

Interactive designs: https://framer.cloud/ObAKy

#### Acceptance Criteria

TBD

### Additional Information
* Operating System: all platforms

<blockquote><img src="https://framer.cloud/ObAKy/3/framer/social-1200x630.png" width="48" align="right"><div><strong><a href="https://framer.cloud/ObAKy">Threads and Reactions</a></strong></div><div>Press and hold on messages to get reactions, click to open threads. 👯‍♂️ 
feedback: maciej.stateofus.eth </div></blockquote>

**Comment by lukaszfryc** [comment]
@errorists should reactions appear on long press? If yes, how it will look like on iOS? Will there be another buttons "Add reaction", "Remove reaction"? Maybe the "reactions sheet" should appear/hide on simple tap? 

<img src="https://user-images.githubusercontent.com/7532782/49283132-33b90980-f491-11e8-8841-de9a70ba4c60.png" width="200">

Also, could you add figma link here when the final design is ready?

**Comment by errorists** [comment]
Mobile designs are [available here in Figma](https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=1244%3A9109). @lukaszfryc both the iOS and Android Action Sheet menu will be made obsolete by our own [bottom sheet component](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=5%3A220) that aims to unify the design across both platforms, I say good riddance :) But that's beside the point anyway since it's not the right fit for the reaction interface being so disconnected from the message and covering it altogether. That's why the long press menu should behave exactly like in the prototype, there are two tooltips appearing above the message: one bottom tooltip for actions like Reply, Copy — and I'll also propose to replace the share we have now with a much more useful forwarding in a separate issue — and another top tooltip for housing reactions. 

Outside the scope of this issue: including Forward inside the action menu, SNT reactions.

**Comment by hesterbruikman** [comment]
@yenda @errorists : can we close this issue? seems to be worked on here: https://github.com/status-im/status-react/issues/7118

**Comment by errorists** [comment]
@hesterbruikman hey as long as this insanely-cool-can't-live-without feature is tracked and on our radar, I don't mind, sure! :)

**Comment by hesterbruikman** [comment]
Closing to merge into https://github.com/status-im/status-react/issues/7118
