### ISSUE TITLE
Mailserver spec RFC

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#6962]
I wrote a draft for mailserver usage and future api spec, RFC 

Ideally as stated the proposed API would benefit from being implemented in go as there is probably mean to fullfil requirements with much less bloat than on clojure side.

# Problem

In whisper, messages are passed around in whisper enveloppes. A whisper envelope only contains the minimal amount of information required for transporting its message. It doesn't contain information about the sender or recipient of the message and the message is encrypted.

Status sends messages with a ttl (time to live) of 10 seconds. That means that if you are disconnected from the network for more than 10 seconds, you will not receive the messages that you missed after you disconnected if their ttl expired before they reached you when you reconnected. 

Mailservers are the current solution Status uses to solve this problem. 

A mailserver is a whisper node that keeps all the whisper enveloppes it receives from peers for a period of time. By using a direct P2P connection you can send a request for messages to a mailserver and it will forward to you all the whisper enveloppes including those with an expired ttl that match your request criteria.

The request uses a bloomfilter to mask what topics are requested, just like Status does when connecting to regular whisper nodes. This makes it less expensive in terms of bandwidth than requesting all of the messages, but provides a higher degree of privacy.

The distinction between bloomfilters and filters is important: 
- the bloomfilter is used by the mailserver to decide weither a message should be sent or not based on its topic.
- the filters are used on the whisper client side and provided with a topic and decryption key. Each filters tries to decrypt received messages that match its topic. If no filters are added no messages are received. If a message matches the filter topic but cannot be decrypted it is ignored.

# Mailserver client requirements

## Connection

- The client MUST add a mailserver as a peer and MUST mark it as a trusted peer in order to make message requests and receive the messages, because only a trusted peer can send messages with an expired ttl

## Request

A message request includes an array of topics that are turned into a bloomfilter by the `.requestMessages` method. The mailserver will send all the messages that match that bloomfilter. The client will receive all the messages that match the added filters. 

- The client MUST wait for all filters to be added before making a request. Otherwise the messages sent by the mailserver won't be decrypted and received by the client.

- The client MUST make a new request whenever the user logs in or the client is back online after being temporarly disconnected from peers.

- The client MUST make a new request everytime a filter is added during a session. If the filter's topic was already requested because it was used in another filter the messages matching the new filter would have been ignored.

# Mailserver client API

## Current API

`web3.shh.requestMessages` is used to request messages. It takes the following arguments:
- `topics`: an array of topics to be requested
- `mailServerPeer`: the address of the mailserver
- `symKeyID`: the symmetric key id of the symmetric key used for the request.
- `timeout`: the timeout in seconds for the request. status-go implementation of whisper client sends a `mailserver.request.expired` signal if it doesn't receives a confirmation from the mailserver that the request has been completed after the timeout expires
- `from`: timestamp in seconds, all messages matching the bloomfilter and more recent that this will be sent
- `to`: timestamp in seconds, all messages matching the bloomfilter and older than this will be sent

This is currently the only client API to mailserver. A mailserver client MUST keep track of added filters, previous requests per filter, and network connectivity in order to fulfill the previous requirements.

- Connection to mailserver can be done with an rpc call to `addPeer` admin method, as well as `web3.shh.markTrustedPeer`.
- The client CAN obtain the symKeyID by generating the sym-key from the mailserver password using `web3.shh.generateSymKeyFromPassword` method, the symKeyID being returned in the callback.
- The client CAN use the callback of `web3.shh.newMessageFilter` to keep track of added filters.

## Proposed API

Status-go could simplify the usage of mailservers by implementing the previous requirements. Other benefits would be reducing the communications related to mailserver connection and requests between status-go and the clients.

List of things the mailserver modules should be concerned about:
- filters: make a request when user logs in, after ALL filters have been successfully added after initialize is called, make a request when a filter is successfully added
- logout: stop all mailserver related activity when user logs out
- connectivity (number of peers connected): make a request when it goes from 0 to n

### `status.mailserver.initialize(mailserverList, requestOptions, callback)`

- `mailserverList`: the list of mailservers is passed as first argument. Try to connect to all mailservers in the list and only keep a connection to the one with lowest latency.
- `requestOptions`: same as `web3.shh.requestMessages` method
- `callback`: feedback channel for logs and errors, could use signals instead. MUST INCLUDE:
  - connection attemps and latency for mailservers
  - connection success and selected mailserver
  - requests made
  - errors

- intialize CAN be called more than once during a user session if he whishes to change some parameters
- timestamp for last request MUST be persisted per topic, adding a new filter to a topic MUST reset that timestamp

### `status.mailserver.request(requestOptions, callback)`

- `requestOptions`: same as `web3.shh.requestMessages` method
- `callback`: feedback channel for logs and errors, could use signals instead.

- `mailserverList`: the list of mailservers is passed as first argument. Try to connect to all mailservers in the list and only keep a connection to the one with lowest latency.

- request CAN be used to force a `messageRequest`
- clients SHOULD only use it for specific use cases, basic history management MUST already be handled my `initialize` method
### TODOS

- describe signals from status-go and how to use them

**Comment by yenda** [comment]
@mandrigin @PombeirP @dmitryn @dshulyak @bhauman  @oskarth

**Comment by dshulyak** [comment]
looks good, i suggest to have different API though

instead of a single method `status.mailserver.initialize(mailserverList, requestOptions, callback)`, i suggest to have 2.

first will be called every time when user changes list of selected mail servers. it can be called initialized, but currently i created a binding with name UpdateMailservers. see https://github.com/status-im/status-go/pull/1295. We need persistent connection with mail server as a part of different functionality, so establishing it before making actual requests makes more sense. wdyt?

second one is for making a request, pretty much the same as we have. but instead of providing a mail server peer with a request parameter, we will use any from selected list that is also connected. also this method will wait for establishing a connection as a part of given timeout. it doesn't do it currently.

another thing i suggest is to stop counting peers on the status-react side. just retry requests until success. and show to the user error provided as a response. internally we will wait for connection to be established, and try different peers if they will be provided.

>  and MUST mark it as a trusted peer in order to make message requests and receive the messages, because only a trusted peer can send messages with an expired ttl

this is obsolete. whisper marks peer as trusted before making a requests. not sure when it changed, but it is definitely the case atm.

**Comment by yenda** [comment]
> second one is for making a request, pretty much the same as we have. but instead of providing a mail server peer with a request parameter, we will use any from selected list that is also connected. also this method will wait for establishing a connection as a part of given timeout. it doesn't do it currently.

the proposal is to completely remove the concern of requesting messages from the client there wouldn't be a need for it. The rules for when a request is made are described

> first will be called every time when user changes list of selected mail servers. it can be called initialized, but currently i created a binding with name UpdateMailservers. see status-im/status-go#1295. We need persistent connection with mail server as a part of different functionality, so establishing it before making actual requests makes more sense. wdyt?

I'm a bit worried about requiring persistent connection to mailservers because mailservers are supposed to be a temporary solution and relying on them for other features will make it harder to go away from them. I will have a deeper look at it.

> this is obsolete. whisper marks peer as trusted before making a requests. not sure when it changed, but it is definitely the case atm.

so that means I can remove that from the current code? Will test.

**Comment by yenda** [comment]
@dmitryn I also updated the last part of the RFC, `initialize` can be called multiple times if the user changes the list of mailservers to try to connect to.

**Comment by dshulyak** [comment]
> the proposal is to completely remove the concern of requesting messages from the client there wouldn't be a need for it. The rules for when a request is made are described

what if we will decide to fetch more history when a user scrolls up? the proposal seems too restrictive. why not to separate management of the connections and requests?

> I'm a bit worried about requiring persistent connection to mailservers because mailservers are supposed to be a temporary solution and relying on them for other features will make it harder to go away from them. I will have a deeper look at it.

well they are not atm, and we probably won't get rid from them until new protocol. you can check discussion https://github.com/status-im/status-go/issues/1276 and https://github.com/status-im/status-go/issues/1278. it seems that we have to either refactor completely mail server communication, so that they provide confirmations when user is offline, and change a substantial part of a current chat protocol. or to follow decisions made in those two issues.

**Comment by yenda** [comment]
> what if we will decide to fetch more history when a user scrolls up? the proposal seems too restrictive. why not to separate management of the connections and requests?

we can add such method later for this kind of cases but it's not useful at the moment. Such feature would require more discussion anyway  it adds lots of other complication personally I don't like the idea

**Comment by dshulyak** [comment]
> we can add such method later for this kind of cases but it's not useful at the moment. Such feature would require more discussion anyway it adds lots of other complication personally I don't like the idea

anyway, i don't understand the reason to make mail server connection management and history requests strongly coupled. and hide all history requests somewhere in status-go codebase.

what is wrong with an alternative that I suggested, offload connection management to status-go and do requests whenever you need, but keep them in status-react?

**Comment by yenda** [comment]
@dshulyak the only point of mailservers is to fetch message history so it makes sense if they are coupled. 

I agree with the case for having a requestMessages method for special cases like the feature mentionned.
However that doesn't mean the client should have to handle all the standard cases. As described in the RFC there is no need to know about the concept of chat or anything for the mailserver to make sure history is requested properly, it's only about topics and filters. And those can be better managed on go-side.

**Comment by mandrigin** [comment]
@yenda why do we have the same `requestOptions` in both methods? I would agree with @dshulyak and remove it from the initialization. All the signals that we get to trigger the mailserver requests are coming from the OS, and that's react part.

**Comment by adambabik** [comment]
I think we can try this approach for mail servers first and learn from it. I am not sure about offloading these "standard cases" to status-go because (1) it's hard to identify all standard cases, (2) there will always be special cases when we need to provide the API so we basically spread the logic between two components. There will be also different standard cases for mobile and desktop.

A more comprehensive vision is that the app is not aware of Whisper at all. It would only have the API with methods to handle messages. One of these methods can be used to request for historic messages but it might be not even aware of "historic" messages just messages.

Obviously, the peers management and connectivity would be moved to status-go completely but some feedback important from the UX perspective could be provided (e.g. users would like to see if they are connected to the network at all).
