### ISSUE TITLE
MVP 2 ens username in chat

### ISSUE THREAD

**Issue by yenda** [status-im/status-react#7114]
# Problem

As a user, I want my ens username to be displayed in chats I participate to.
As a user, I need to be able to specify my ens username.
As a user, I need to be able to distinguish simple usernames from ens usernames.

# Implementation
- ens username is sent with the messages
- if the user was previously unknown, the ens username is verified against the contract

# Acceptance Criteria

## MVP
- ens usernames replace username in chats

## An issue is created for 100% feature completion with following criteria

There is two edge cases are not accounted for in the MVP: 
- what should happen if I release my ens username?
- what should happen if I decide to use a new ens username?

**Comment by yenda** [comment]
@andmironov is there any designs already regarding the user stories?
for this feature to work out we need to be able to distinguish username from ens usernames in chat, and the user needs to be able to set his ens-username somewhere

**Comment by andmironov** [comment]
cc @errorists 
I wonder if it should be display name shown if specified, even if the user has a ENS username?

**Comment by yenda** [comment]
The simplest solution would be to merge the two, one could specify his ENS username as display name. We could add a "show in public chats" checkbox. The ens username would simply be a "verified" display name

**Comment by andmironov** [comment]
We should be really thoughtful and consistent about which name is used where, since the hierarchy is not 100% transparent.

- Every user has an **account name** (e.g Attractive Salty Seal). Used as a human-readable contact code
- Some users have a **display name**. May or may not be specified by user. May or may not be revealed to other users
- Some users have a **ENS username**. Used as a unique user identifier. 

Here are the new profile designs with and without those specified:

<img width="1255" alt="p" src="https://user-images.githubusercontent.com/3115606/50093480-d5767f80-0221-11e9-91f5-28e667851806.png">

Questions i dont have answers to:
- If a ENS username exists it might replace the account name ?
- How the user should be shown in chat?

**Comment by yenda** [comment]
also a user can have multiple ens usernames, but for those who already registered one, the app can't know it, the user have to enter them somewhere

**Comment by andmironov** [comment]
>also a user can have multiple ens usernames

this complicates this even more :-) please let's not rush into implementation, this requires some time for UX research. There are not too many apps with such a complex identity structure

cc @hesterbruikman

**Comment by rachelhamlin** [comment]
I'd suggest we use _ENS names only_ for default display in chat/profile—it increases the utility of the username.

Stateofus.eth names should have preferential treatment, displaying in chat as `Rachel` and not `Rachel.stateofus.eth`. Other ENS names could present as `rachel.otherdomain.eth` (if and when there is a time that other ENS names have Whisper IDs associated). 

If at some point ENS registration is built into onboarding (potentially even for free), we could do away with non-unique display names entirely. This has the double benefit of making impersonation more difficult. 

What we want to enable with this feature right now is this:
- As a user with an ENS name _with_ Whisper ID associated, I want the option to set my name to public by default, so that anyone can see my ENS name in chat and on my profile.
- As a user with an ENS name _without_ Whisper ID associated, I want to be offered the option to edit my name and associate my Whisper ID (via the ENS DApp*), so that I can then set it to be public.

Following that:
- As a user who is displaying my ENS name publicly, I want the option to revert back to using my anon name by default.

Is that clear? I'll respond to the edge cases raised by @yenda in a subsequent post.

_*This update flow exists in the ENS DApp, we'd just need to link to it._

**Comment by rachelhamlin** [comment]
Also side note: This is somewhat required to make Tribute to Talk useful. Without it, you're never going to be able to identify people you want to contact (if Attractive Salty Seal is Brad Pitt, he can just hide that from me forever by not adding me as a contact, and I'm not going to pay tribute to Attractive Salty Seal).

**Comment by rachelhamlin** [comment]
@yenda 

```
also a user can have multiple ens usernames, but for those who already registered one, the app can't know it, the user have to enter them somewhere
```

On this, can the app detect any of a user's names, or does it require manual input?

**Comment by hesterbruikman** [comment]
@andmironov fyi

This implies that an existing ENS username needs to be selectable as Display name in the new Profile screens.

**Comment by yenda** [comment]
> @yenda
> 
> ```
> also a user can have multiple ens usernames, but for those who already registered one, the app can't know it, the user have to enter them somewhere
> ```
> On this, can the app detect any of a user's names, or does it require manual input?

it requires manual input that can then be validated by the app

**Comment by rachelhamlin** [comment]
@andmironov @yenda @hesterbruikman maybe we can hop on a call this week to talk about our options here?

**Comment by hesterbruikman** [comment]
@rachelhamlin Following up on Status today
