### ISSUE TITLE
Linux build can't start

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7128]
# Problem

After mark build as executable I still can't open file.
Last nightly build, that I can start  is [nightly 15/01/18](https://ci.status.im/job/status-react/job/nightly/853/)
Now I don't see any new processes are launching when I tried to start build.

Video: http://take.ms/0Ummm

<blockquote><img src="https://api.monosnap.com/rpc/file/download?id=Rh3bYmyV2luTQjZsgbQ5La9qVFc66G&type=preview" width="48" align="right"><div>Monosnap screenshot tool</div><div><strong><a href="https://monosnap.com/file/Rh3bYmyV2luTQjZsgbQ5La9qVFc66G">File "screencast 2018-12-18 11-14-37.mp4"</a></strong></div><div>Monosnap — the best tool to take & share your screenshots.</div></blockquote>

**Comment by vitvly** [comment]
Also there are no logs/data whatsoever created.

**Comment by jakubgs** [comment]
Seems like the last working version is:
https://ci.status.im/job/status-react/job/nightly/853/
Built from: ffdbedd04956da7da0af8d3337040ac6ce348abb

<blockquote><img src="/static/9b8798e5/favicon.ico" width="48" align="right"><div><strong><a href="https://ci.status.im/job/status-react/job/nightly/853/">status-react » nightly #853 [Jenkins]</a></strong></div></blockquote>

**Comment by rachelhamlin** [comment]
@PombeirP is this something that you could take a look at? I believe it's a blocker for the desktop alpha release, which we'd like to push before the holidays.

**Comment by pedropombeiro** [comment]
@rachelhamlin Sure, I'll switch to that.

**Comment by pedropombeiro** [comment]
A few initial findings:
- no matter which commit I build locally (even the one that was used to generate the last working nightly) presents the same problem.
- running the built AppImage under gdb I can see that it starts reportApp and stops shortly after.
- I extracted both the working AppImage and the locally built one (same commit) and they have different contents in `/usr/lib` (e.g. `libboost_system.so.1.58.0`, `libselinux.so.1`, `libwayland-client.so.0`, among others are no longer present), which leads me to believe there were external changes to dependencies which are not under source control. @siphiuel @MaxRis Have there been recent changes to `StatusImAppImage_20181208.zip` or `linuxdeployqt-continuous-x86_64.AppImage` that might explain this? I see that the modified date of `linuxdeployqt-continuous-x86_64.AppImage` is Saturday, which would be consistent with when we started seeing problems.

![image](https://user-images.githubusercontent.com/138074/50230859-c91f2d80-03ad-11e9-93fb-f7173f0c0bd7.png)

I would suggest that we avoid replacing those external files, and instead update the filename in `build-desktop.sh`, so that builds are reproducible.

**Comment by pedropombeiro** [comment]
OK, found the real issue:
![image](https://user-images.githubusercontent.com/138074/50231495-3c756f00-03af-11e9-874b-ca09788f0c37.png)
For some reason, `AppRun` symlink on the generated AppImage is pointing to `reportApp` instead of `Status`. If I manually run `Status` it works fine.

**Comment by churik** [comment]
possible to fix?

**Comment by pedropombeiro** [comment]
> possible to fix?

Very easy, but I'd first like to understand what caused this change. cc @siphiuel @MaxRis

**Comment by rachelhamlin** [comment]
Thanks for hopping on this one @PombeirP!
