### ISSUE TITLE
App Crash on launching on the iOS app after updating 

### ISSUE THREAD

**Issue by mariapaulafn** [status-im/status-react#7147]
[comment]: # (Please replace ... with your information. Remove < and >)

### Hi, I updated my mobile status and the app crashes with a problem on encryption key message. 
Choosing one of the two options (see screenshot) just takes me back to that error notification.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Update app
- Open
- Yeah, not working

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: latest version
[comment]: # iOS
* Operating System: iOS latest
![img_6777](https://user-images.githubusercontent.com/27913589/50243170-c122b600-03cc-11e9-97e5-5ee8ac17fe3a.png)
 version

#### Logs

[comment]: # (if on Android please replicate bug whilst running adb logcat)
```
...
```

**Comment by pablanopete** [comment]
Also had a friend report this same issue after recent hotfix 
![fcb81599-408f-4a59-9126-9bde6ee12e87](https://user-images.githubusercontent.com/18363825/50263589-31850380-03dc-11e9-835a-eb77df0fc182.jpeg)

**Comment by rasom** [comment]
hm, two different errors btw

**Comment by rasom** [comment]
@mariapaulafn what was the previous version on your device? Did you install nightlies?

**Comment by rasom** [comment]
Unfortunately, we can do nothing about this,  realm databases are completely removed on @mariapaulafn device... there is a way to get a file with the private key (using app like `iExplorer`),  but better if they can just restart the app and restore account using passphrase...

[This issue is already fixed in develop](https://github.com/status-im/status-react/commit/c506521778161e10d6d154dfc2ed975426711c82), but unfortunately after `0.9.32` release...

**Comment by mariapaulafn** [comment]
@rasom I don't really remember. I should have updated last around 2 months ago. I updated again yesterday, and this happened. Will recover from passphrase!
