### ISSUE TITLE
e2e test builds against PRs are not triggered automatically

### ISSUE THREAD

**Issue by antdanchenko** [status-im/status-react#7248]
# Problem

The job https://ci.status.im/job/end-to-end-tests/job/status-app-end-to-end-tests/ is not triggered automatically by the probot when a PR is moved into `TO TEST` section on https://github.com/status-im/status-react/projects/7

# Notes
There are 2 possible reasons:

1. apk file for e2e test should be named pr_number.apk during `upload to SauceLabs` stage, (e.g. 7172.apk), but apks have different naming template right now (e.g. StatusIm-190109-111218-4a30f4-e2e.apk) cc @jakubgs 

2. However I don't see any build which was triggered by the probot for ~12 days, it seems that probot is not triggering them at all, cc @PombeirP

**Comment by pedropombeiro** [comment]
If I take https://github.com/status-im/status-react/pull/7242 as an example, the reason that the test build wasn't triggered by Probot is that the PR isn't considered mergeable (`Merging is blocked`):

```
2019-01-10T09:51:43.542606+00:00 app[web.1]: 09:51:43.542Z DEBUG probot: pullRequest.mergeable_state is blocked, considering state asundefined
2019-01-10T09:51:43.542805+00:00 app[web.1]: 09:51:43.542Z  WARN probot: trigger-automation-test-build - State is 'undefined', ignoring { owner: 'status-im', repo: 'status-react', number: 7242 }
```

**Comment by jakubgs** [comment]
>apk file for e2e test should be named pr_number.apk during upload to SauceLabs stage, (e.g. 7172.apk), but apks have different naming template right now (e.g. StatusIm-190109-111218-4a30f4-e2e.apk)

Okay, so I think I know what the problem is:
https://github.com/status-im/status-react/blob/develop/ci/android.groovy#L28
If the `CHANGE_ID` is checked from parent job, and the new PR CI setup does not run those via a parent job.

I'll make a PR.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>a free (libre) open source, mobile OS for Ethereum - status-im/status-react</div></blockquote>

**Comment by pedropombeiro** [comment]
So I guess we have to decide if we want to enforce GPG commit signing or not...

**Comment by jakubgs** [comment]
Fix for wrong filename: https://github.com/status-im/status-react/pull/7249
With this the filename will be: `${changeId}.apk`

**Comment by antdanchenko** [comment]
@PombeirP I think that we can trigger them whenever PR is in `TO TEST` section and has an apk for e2e tests <img width="779" alt="screen shot 2019-01-10 at 12 13 38 pm" src="https://user-images.githubusercontent.com/12611990/50961754-36b40a80-14d1-11e9-8cef-1e28138d08ae.png">
Without waiting for the mergeable_state

**Comment by pedropombeiro** [comment]
OK @antdanchenko fixed Probot (a lot had changed since the last time it was working!)
