### ISSUE TITLE
Syncing Stalls

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#725]
Syncing issue occurs on both iOS and Android.
Does not seem to be any consistency as to when syncing stalls, some report at 0%, some at 99% or anything in between.

Neither relaunching nor reinstalling Status does not appear to fix issue.

Some iOS users (https://instabug.com/applications/status/beta/bugs/80?status=New) reporting overheating issues during stall.

Some users report the following message occurring after syncing stall

```Error on param suggestions [{:command {:description "Launch the browser", :color "#ffa500", :name "browse", :params [{:name "url", :type "text", :value nil}], :type :command, :title "Browser", :has-handler false, :fullscreen true, :suggestions-trigger "on-send"}, :content "c ", :chat-id "wallet"} {:error "ReferenceError: 'call' is not defined"}]```

![image](https://cloud.githubusercontent.com/assets/25023739/21959934/be393cea-db3b-11e6-9240-5c0dcb48cea9.png)
![image](https://cloud.githubusercontent.com/assets/25023739/21960030/16226514-db3f-11e6-8852-ba8ead76f84b.png)

Android:
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/189
https://instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/186

iOS:
https://instabug.com/applications/status/beta/bugs/97?status=New
https://instabug.com/applications/status/beta/bugs/94?status=New
https://instabug.com/applications/status/beta/bugs/86?status=New

**Comment by Jas0n-F** [comment]
@jarradh - I see ```[Error: Invalid JSON RPC response: ""]``` in the logs. Even though this syncing issue does not always cause a crash, does this mean it is related to #652?

**Comment by jarradh** [comment]
the syncing issue would be a symptom of the crash, it's very possible. let's leave this open and @rasom @farazdagi @alwx can look at it this week

**Comment by rasom** [comment]
Regarding syncing on iOS: it is very slow, it has never been fast. One of the reasons for this is that syncing doesn't work in background atm, so when a user opens another app or locks screen syncing stops. I don't see any other problems in reports related to iOS here, seems that `status-go` was functioning there.

So for iOS we need to figure how to make synchronization working in the background, at least I don't know how else we can improve this.

**Comment by alwx** [comment]
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

According to this doc, it should be easy to move parts of our code to background tasks on iOS. It's, of course, better to do this anyway (I can do it tomorrow) but this particular problem will unlikely be solved this way.

**Comment by farazdagi** [comment]
- The only hand I can give from `status-go` side of things is tweaking the "confirmed" block, so that the sync starting point is very close to the current block i.e. total sync time is diminished as there's not much to sync.
- I suppose it is wise to do this anyway, so that app does not have too long of a cold start (which currently exists, when app first starts and chaindata is not in sync)

Thoughts?

**Comment by alwx** [comment]
@farazdagi am I right that the idea is to tell a user that the syncing is over before it's over? But according to the description syncing sometimes stall at 0%, and I am not sure that the suggested tweak will help to solve this problem.

**Comment by farazdagi** [comment]
No, @alwx I am not talking about telling user that sync is done before it is done. 

With LES (light ethereum) protocol, we start with some "safe point/block" and from that point pulling blockchain headers, up until the current block (at this moment, sync is done). From time to time, that safe point is updated (by Geth team, safe point is hard-coded), so that syncing is not from zero to the current block. 

So, I wanted to explore the ways for us to set that "safe point" i.e. what instead of using starting block that is 10000 blocks away from the current, we are to start with a block that is, say, 100 blocks away (thus full sync will be faster, as only headers for those 100 blocks will be pulled). 

I can incorporate that setting of the starting block to the `!reset` command (command I am working on atm, it will allow to reset chaindata folder). This will give us two things: 
 - resetting will be cheap, as re-sync will be relatively fast 
 - re-sync will be only manually triggered on reset (so that if everything is intact we do not force users to sync, even those 100 blocks).

**N.B.** Please note that I have little idea on why sync stalls on 0%, and my solution is although related to the original issue, is most probably not the exact fix for the issue (the aim is just improve sync experience overall, and adding that suggestion to this issue seemed appropriate).

**Comment by alwx** [comment]
@farazdagi got it, thanks for the detailed explanation.

I like the solution you suggest, let's try it 👍

**Comment by rasom** [comment]
btw, if I remove any `.ldb` file from `testnet/lightchaindata` synchronization stuck at `0%` without any chance for "resurrection". Something like this shouldn't happen on iOS, but idk, maybe it is possible that some applications could remove files related to geth on Android

**Comment by rasom** [comment]
Another thing that we should check here, what happens if the storage is exhausted but syncing is not finished

**Comment by Smokyish** [comment]
Could this issue be related to this one: https://github.com/ethereum/go-ethereum/pull/3568 ?

> A hang in the light client is resolved (#3568)

**Comment by rasom** [comment]
@Smokyish it could be a problem for us, but I don't think that it's related to this bug because while geth is not synced account doesn't contain any eth on balance and user will not be able to make a transaction in app. As I understood from https://github.com/ethereum/go-ethereum/issues/3562 geth stopped syncing after transaction attempt

**Comment by rasom** [comment]
Just checked how syncing behaves when the storage is empty on Android: it stops, but besides this app functioning fine. So this shouldn't be a problem for us.

**Comment by annadanchenko** [comment]
Reports from versions earlier than 0.9.3 for Syncing stalls:
* iOS
https://dashboard.instabug.com/applications/status/beta/bugs/117
* Android
https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/235
