### ISSUE TITLE
Status desktop clients crash in some cases

### ISSUE THREAD

**Issue by jinhojang6** [status-im/status-react#7259]
# Problem
Some status desktop users cannot use the desktop client on Windows. There are 4 cases.

1) A user received an error message as below (Windows 7 32bit)
![](https://user-images.githubusercontent.com/41753422/51070342-8b9c7180-15f4-11e9-8c76-b0aba652445c.png)

It does not support 32 bit operating systems

2) A user received an error message as below (Windows 10 64bit)
![](https://user-images.githubusercontent.com/41753422/51070172-a3262b00-15f1-11e9-8538-cd173e8b51f0.png)

It says 'Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.' The only option that the user can choose it not to run this program.

I found a similar case on [StackOverflow](https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro)

3) Some users received an error message as below (Windows 10 64bit)

"We were not able to decrypt your data, you might need to create new account and erase your old data by tapping “Apply”. Clicking on “Cancel”, will try again"

The users cannot make progress from this step.

4) Some users clicked on the Status Desktop icon on Windows but it does not respond. They can find the program on 'Task manager' and the process is running although it shows nothing. (Windows 7 & 10)

# Notes
All the cases have resulted from Windows.

# Future Steps
The root cause should be figured out and fixed from the next version on.

**Comment by cammellos** [comment]
@PombeirP could you please triage this? you probably have the most knowledge about windows builds.
Thanks!

**Comment by pedropombeiro** [comment]
@jinhojang93 a few thoughts:
1. Windows 7 is not yet supported, neither are 32-bit Windows platforms, so that's expected.

2. The SmartScreen dialog has a link which expands a section which allows you to run the application. There are two things we could do here to avoid the user having to deal with this dialog (as per Microsoft's [blog post](https://blogs.msdn.microsoft.com/ie/2010/10/13/stranger-danger-introducing-smartscreen-application-reputation/)) cc @rachelhamlin @jarradh:
    - Digitally sign the app with an Authenticode signature;
    - Apply for a Windows Logo.
3. 
4. Are there any logs created in `%LOCALAPPDATA%\Status`?

**Comment by jinhojang6** [comment]
@PombeirP Thank you for your detailed answers.

1. I let the users know that. Thank you

4. I haven't received any log information from them. There are quite many people experienced the same error like this. It is running on the 'Task manager' of Windows but it shows nothing.
