### ISSUE TITLE
Add decimal point to numeric keyboard during Kyber exchange

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7330]
### User Story

As a user, I want to enter a decimal number when inputting the amount of token to exchange using the incredible new Kyber extension.

### Description

*Type*: Bug

*Summary*: Currently, the numeric keyboard used to enter a token amount in the Kyber swap wallet extension does not contain a decimal point. As I own less than 1 full unit of many tokens, it's imperative that I am able to enter a decimal number here. 

#### Expected behavior
Decimal point on keyboard

#### Actual behavior
<img src="https://user-images.githubusercontent.com/15470435/51617014-98da2a00-1f2b-11e9-88c4-7bf556a57923.png" width=200/>

### Reproduction

- Install Kyber extension: https://status-im.github.io/pluto/try.html?hash=QmPzBb1siNHz8MtsMXHz7gq92KRTbHW3VHbCJGEiPYvrVr
- Open Status wallet
- `Exchange Assets`
- Select a token
- Enter amount

### Additional Information
* Status version: Nightly 23/1/19
* Operating System: iOS XS

**Comment by jeluard** [comment]
Fixed in https://status-im.github.io/pluto/try.html?hash=QmRQ8iJ4duBvkkrNs52V3Nh5Yunhaq671DQCRgNXoMKKET

<blockquote><img src="/pluto/img/favicon.png" width="48" align="right"><div><strong><a href="https://status-im.github.io/pluto/index.html">Pluto · A grammar for data manipulation</a></strong></div><div>A grammar for data manipulation</div></blockquote>

**Comment by rachelhamlin** [comment]
Looks good!
