### ISSUE TITLE
Transaction appearing twice in transaction list

### ISSUE THREAD

**Issue by Jas0n-F** [status-im/status-react#738]
iOS user reporting transaction with same transaction ID appearing under 'Transactions' at the exact same time.

Unclear as to whether or not two transactions are actually processed or not.

![image](https://cloud.githubusercontent.com/assets/25023739/22051791/95d43cf2-ddaa-11e6-90fe-065c7b2116ec.png)

https://instabug.com/applications/status/beta/bugs/99?status=New

**Comment by rasom** [comment]
This bug is reported for app version `0.9.2 (118.957)`, this is 957th commit https://github.com/status-im/status-react/commit/85a48072ceec2e2c71a083ed249e4496ed9edf4c (Nov 30, 2016)

This bug was fixed here https://github.com/status-im/status-react/commit/0916cc6119c9d759cd6625c25ed63322d6899f3d (Dec 1, 2016)

I checked it again, cannot reproduce in `develop`
