### ISSUE TITLE
Unread count still does not disappear after messages are sent

### ISSUE THREAD

**Issue by naghdy** [status-im/status-react#7497]
# Problem
As a user I expect that when I send a message in 1:1 or group chat, that the unread message count disappears.

See attached a screenshot. The top three 1:1 chat snippets are all messages that I have sent.

![56007](https://user-images.githubusercontent.com/32269875/52716830-a2c0dd00-2f6d-11e9-9ca1-4b4a9a94f925.jpg)

# Proposed Solution
Unread message counts should be removed once a message has been sent by the user.

**Comment by mandrigin** [comment]
Yeah, I agree. Maybe we should either
(1) when you open a chatroom, scroll to the first unread message
(2) plainly clear unread status when you enter the chatroom.

@hesterbruikman @yenda what do you think?

**Comment by hesterbruikman** [comment]
(2) Yes, pleae. Open chat room implies there are no unseen messages left. Although obviously we will never know for sure that you have read them. We can build upon message actions with a 'Mark as unread' later.
(1) Is the reason the counter is there that a message hasn't been scrolled in view?

Q: How well would this sync between devices? Feels like we're talking about behavior that is client side only.

**Comment by oskarth** [comment]
See https://github.com/status-im/status-react/issues/6375 as well

**Comment by rachelhamlin** [comment]
To clarify, the badge should be cleared any time you open a chat, regardless of whether you send a message. This bug only occurs when there are 9+ unread messages, to my knowledge.

**Expected behavior**
Opening a chat with an unread messages clears the purple badge when you move back to the home screen. When I open a chat with 9+ unread messages, I am at the bottom of the chat. 

**Ideal future behavior**
To be implemented via issue #6375: opening a chat with unread messages will jump the user to the _first_ unread message, with option to jump to bottom. In this scenario, would we prefer that the badge remains as long as the user has not read all messages? @hesterbruikman @annadanchenko

**Comment by mandrigin** [comment]
Also, it happens when you have multiple devices. If your message is the last one in the chatroom, we shouldn't show the unread count for this chat, period.

**Comment by mandrigin** [comment]
It is a simple heuristic, and will make our app way less annoying when switching between mobile/desktop.

**Comment by yenda** [comment]
@mandrigin it should be much easier to bounty with my PR https://github.com/status-im/status-react/pull/8336

current situation with`use-statuses` is ridiculously complex for something that simple.

**Comment by rachelhamlin** [comment]
This problem is a lot better in v1, but I'm still experiencing sticky unread message counts in public chats. In this instance, I've not only sent the last message in chat, I've scrolled back and collected the past 3 days of history as well:

<img src="https://user-images.githubusercontent.com/15470435/73344913-b9169480-42b5-11ea-85ea-1dcd160a4e9c.PNG" width=250/><img src="https://user-images.githubusercontent.com/15470435/73344843-9d12f300-42b5-11ea-8e6b-4f066ad07aa6.png" width=250/>

**Comment by yenda** [comment]
@rachelhamlin if you reopen the chat does it go away? If you reopen and Scroll all your history?

**Comment by rachelhamlin** [comment]
@yenda okay, so it finally cleared after I scrolled up for the **3rd** time and fetched more messages, to the point where it can no longer return any more. 

But I had previously fetched history as well. I scrolled from the oldest history back to the bottom. It didn't clear the first time I did this, or thereafter upon scrolling up and down again.

**Comment by rachelhamlin** [comment]
Update - unread badge only goes away if I scroll up through several additional 'pages' of content. 

So for example, in #status-dogfooding, I have 10 unread messages. I scroll back up to my own last message—there are actually 14 messages between my last message and the bottom, so I've scrolled more than 10. When I exit, I still have 10 unread.

**Comment by churik** [comment]
Unread message counter is redesigned, don't think this issue is relevant anymore in 1.4
