### ISSUE TITLE
Lokalise translations aren't updating in Status

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#7634]
### User Story

As a user in a country with translation support, I would like to use Status in my own language.

### Description

*Type*: Bug

*Summary*: Translations from Lokalise aren't sticking. When @jinhojang93 makes a translation update, the language .js files are not updated + the app rolls out without new translations.

#### Expected behavior
Language files are updating with new content from Lokalise and the app displays new translations.

#### Actual behavior
Translations have not been updated in Status since December.

**Comment by rasom** [comment]
in order to apply changes from okapis we need to create and merge a new pull request with changes, like this one https://github.com/status-im/status-react/pull/7635/files

<blockquote><img src="https://avatars0.githubusercontent.com/u/40699771?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react/pull/7635">Lokalise: Translations update by status-im-auto · Pull Request #7635 · status-im/status-react</a></strong></div><div>This pull request was initiated by Lokalise (user Roman) at 2019-03-01 10:20:03</div></blockquote>

**Comment by rasom** [comment]
This can be done in Lokalise ui by pressing `Upload` button and then `Build only`. Don't forget to select languages.

**Comment by jinhojang6** [comment]
Thank you for the reply 👍 However, I cannot find the `upload` button in my lokalise project.

<img width="613" alt="screen shot 2019-03-02 at 10 30 50 pm" src="https://user-images.githubusercontent.com/41753422/53682617-e6bc2c00-3d3a-11e9-8de8-e1ec919d80a0.png">

 The lokalise documentation says the upload button is listed at the top as above but 

<img width="1170" alt="screen shot 2019-03-02 at 10 07 51 pm" src="https://user-images.githubusercontent.com/41753422/53682317-fdad4f00-3d37-11e9-8542-918b8fd72558.png">

This is what I can see(only the glossary button). I cannot access the `status-react` repository settings as well so cannot follow the [github pull request guide](https://docs.lokalise.co/integrations/github) to pull the `ko.json` file.

For your reference, the last translations update was on [Dec 13 2018](https://github.com/status-im/status-react/commits/develop/translations/ko.json) made by @cammellos.

**Comment by rachelhamlin** [comment]
Thanks for the directions @rasom. I've got access to the `Upload` flow but I'll see if we can upgrade you to an admin @jinhojang93. If not, we can schedule a regular time to push the update together.
