### ISSUE TITLE
Search bar does not appear next time after pull-down gesture on Home screen performed with search bar shown [iPhone]

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#7676]
***Type***: Bug

***Summary***: Search bar does not appear second (or more) times after pull Home screen down gesture been done while Search bar is present on screen. Please see video and steps of issue below 

No issue with Android.

#### Expected behavior
Search bar appears on Home screen after pull-down gesture on iPhone

#### Actual behavior
Search bar does not appear on Home screen second time if pull-down gesture was done before while search bar is shown (on iPhone)
Please see video of issue here: https://drive.google.com/file/d/1TetB9tHGTfEeQx4679oVM6yMekZb8Lgr/view

### Reproduction

- Open Status and create new account
- Join any public chat
- Navigate back to Home screen
- Pull down Home screen so that "Search" bar appear
- Pull down Home screen again several times more
- Put cursor in the Search bar (There is a 'Cancel' button should appear next to search bar) 
- Tap 'Cancel' button
- Pull down Home screen
 

### Additional Information
* Status version: Develop 0.11, Release 0.10.1
* Operating System: |iOS 12.1.2

**Comment by churik** [comment]
Another scenario:

- Open Status and create new account
- Join any several chats
- Navigate back to Home screen
- Pull down Home screen so that "Search" bar appear
- Put the cursor in the Search bar (There is a 'Cancel' button should appear next to search bar)
- Tap 'Cancel' button
- Scroll to the end of chat list (pull up several times)
- Try to pull down again to see search bar.

Actual: can't see Search bar, but you try again after ~10 sec
Expected: Search bar is shown
Video: https://monosnap.com/file/Vq9eJ2f8n0O4HqJEFHPyVQwJsdSEIq

**Comment by rachelhamlin** [comment]
Not ideal and we need to fix it, but I'd rather ensure that any TtT work in progress is wrapped before diverting for this. aka not urgent. @yenda @churik

**Comment by hesterbruikman** [comment]
@Serhy referenced this issue in https://github.com/status-im/status-react/issues/7697

As @rachelhamlin mentioned, best if TtT can be wrapped up first. With @yenda we discussed to put a bounty and see if we can find someone who can focus on the animation behavior. With that said, are you ok if I close this issue and follow up in #7697 ?

**Comment by Serhy** [comment]
@hesterbruikman sure, it's not super urgent priority or blocker and it was noticed only on iOS.
Let's close it and follow up in #7697
