### ISSUE TITLE
Fairdex Dapp doesn't work

### ISSUE THREAD

**Issue by tbenr** [status-im/status-react#7851]
# Problem Fairdex Dapp

https://fairdex.net

After:
- approving all terms&cond
- giving permission to access wallet
- Fairdex Dapp stucks while loading (wallet)?

![image](https://user-images.githubusercontent.com/15999009/55151227-10a41b00-514e-11e9-8b36-c2f6fb14b280.png)

it somewhat interacts with the wallet by the way:

![image](https://user-images.githubusercontent.com/15999009/55151391-72648500-514e-11e9-85dd-21d1291bcc96.png)

**Comment by michaelsbradleyjr** [comment]
Hello @tbenr,

I'm not sure if this issue is still relevant to you / Fairdex, but for Dapps to integrate with Status wallet currently they need to implement EIP-1102.

See:  https://status.im/developer_tools/run_on_status/dapp_store_requirements.html

If this issue is no longer relevant, can you close it?

**Comment by tbenr** [comment]
Hi @michaelsbradleyjr 
It is no more relevant to me.
Closing.
