### ISSUE TITLE
Clock value is from the past

### ISSUE THREAD

**Issue by adambabik** [status-im/status-react#7884]
# Problem

For `#status` chat, I observed a very strange `clock` values for some envelopes from a particular account.

Take a look:
```
Account   | Envelope Hash   | Clock value     | Timestamp            | Message
------------------------------------------------------------------------------
0x03f8fa8 | Hash = 0xf75bb3 | 155426119985601 | 03 Apr 19 05:13 CEST | Ping
0x03f8fa8 | Hash = 0x55358a | 155426119985601 | 03 Apr 19 05:13 CEST | Ping
0x03f8fa8 | Hash = 0xf75bb3 | 155426119985601 | 03 Apr 19 05:13 CEST | Ping
...
0x03f8fa8 | Hash = 0xdbef95 | 155614702284313 | 02 Apr 19 13:04 CEST | Me too
0x03f8fa8 | Hash = 0x98bcfd | 155614702284319 | 02 Apr 19 13:08 CEST | The messages are apprearing in past
...
0x03f8fa8 | Hash = 0x174870 | 155614702284321 | 02 Apr 19 13:09 CEST | Some messages
0x03f8fa8 | Hash = 0x7ff065 | 155614702284322 | 02 Apr 19 13:20 CEST | See https://notes.status.im/uploads/upload_67d7f92b11acd559b9eae8bbe259cf43.jpg
```

# Notes

It looks like some old clock value was initially calculated and only later updated to the correct one.

cc @annadanchenko

**Comment by cammellos** [comment]
@adambabik not sure I read this correctly, but roughly looks correct, your concern is that:

`155426119985601`

is much smaller than

`155614702284313` 

?

**Comment by adambabik** [comment]
Yeah and the fact that there are other messages sent around the same time
with higher clock value by others.

It might be correct behavior but if so I wonder how the mobile client
handles it.

That person also complained that the order of messages is incorrect for
his/her.

**Comment by cammellos** [comment]
Ok, so in terms of clock values:

We use lamport timestamps for ordering as it's one way to achieve causal ordering.

Basically clock value of a new message is equal to `last-clock-value-in-a-chat + 1`.

If there's no clock value (i.e you never fetched any message from the chat, see those `ping` messages), we initialize that with a `timestamp` (instead of 0), but since it's a logic clock, the actual `clock-value` of the chat might be higher (that's the case in #status), so it will be ordered in the past (that's unfortunately is unavoidable).
So that explains the ordering.

The fact that they are displayed in the notification bar I believe is a bug, although they should be marked as new messages, I can see if I can replicate.

There's also an open bug on ordering as some code sorts messages by timestamp, which it should not, but that's a different issue.

**Comment by adambabik** [comment]
> but since it's a logic clock, the actual clock-value of the chat might be higher (that's the case in #status), so it will be ordered in the past (that's unfortunately is unavoidable).

That makes sense, I wanted to confirm that there is no "heuristic" that would try to rearrange messages if any new appear in the chat or something like that. And we don't have any UI that would suggest waiting until the request for message before sending new messages? 

This is pretty common case I would say. When working on the console client, it's pretty common to see a few messages out of order every day.

**Comment by cammellos** [comment]
Currently we don't have that, but there's an outstanding PR moving in that direction https://github.com/status-im/status-react/pull/7663 although is only for empty chats.
Also currently we have too much room for messages with high clock value (1 month), and we should shrink that to something more sensible (a day or even less), but we need to wait for #status to normalize first, and possibly use NTP time for the timestamp component of the clock value.
