### ISSUE TITLE
Can't see group admin profile from group info view

### ISSUE THREAD

**Issue by churik** [status-im/status-react#7935]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to navigate to group admin profile before joining group chat from group info screen.

### Description

*Type*: Bug or Feature?

*Summary*: don't see any reason to block the user from navigating to admin profile from Group view. Now it can be done via system messages or via messages from admin.

#### Expected behavior
can navigate to admin's profile

#### Actual behavior
can't navigate to admin's profile
However, there is no option in design as well:
<img width="188" alt="sdfsdfdsf" src="https://user-images.githubusercontent.com/4557972/55730225-028caf00-5a18-11e9-986d-c50ccbd931b1.png">
or it is supposed to redirect on profile on tapping user picture, can you elaborate @errorists?

### Reproduction

- Open Status
- Create a group chat with user B
- As user B navigate to Group info (open chat -> ... -> View group ingo)
- Try to navigate to group info view

### Additional Information
* Status version:  nightly 08/04/2019
* Operating System: all

cc @hesterbruikman

**Comment by errorists** [comment]
Tapping on any of the group participants (note: not only the picture but the entire width of the list cell) should take you to their respective profile. For admins, there's the additional ••• next to each member for admin-y type controls

**Comment by hesterbruikman** [comment]
Thanks for raising  @churik. For completeness, I want to add that this means we're deciding that info of group members is shared through an invite.

2 questions:
- Is there specific group information, you both would look for? For example, would showing the number of group members in the invite be sufficient? Sounds like we might be missing something in the invite flow if there is an incentive to go into group profile view.

- What should tapping on the header/group name do @terrorist? Not sure if it already has a function, similarly to member names, ideally tapping on the content should show group info, rather than hidden under overflow.

**Comment by errorists** [comment]
> What should tapping on the header/group name do @terrorist? Not sure if it already has a function, similarly to member names, ideally tapping on the content should show group info, rather than hidden under overflow.

Hell yes, it should. I'm still overdue for filing an issue for that, maybe we can make a small bounty? 

> Is there specific group information, you both would look for? For example, would showing the number of group members in the invite be sufficient? Sounds like we might be missing something in the invite flow if there is an incentive to go into group profile view.

Hard to say, I'm making an educated guess a current number of members would go appreciated. More evolutionary, we can add optional descriptions for groups that would also be visible in invites.

**Comment by churik** [comment]
fixed in #10099
