### ISSUE TITLE
[Wallet] Sign transaction module

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8026]
Implement a new module, it should 

- [x] get tx data map on input
- [x] show title (1)
- [x] show tx details on the bottom sheet (details should be different for sending eth or calling contract (2))
- [x] it's only possible to change one field -  network fee in this module
- [x] sign with password
- [x] show sent popup

this issue doesn't include:
- USD values (3)  https://github.com/status-im/status-react/issues/8027
- sent popup design [GHI]
- tx fee slider [GHI]
- to field details [GHI]
- approveAndCall detection (showing token amount) [GHI]
- prompts for signing phrase, gas and gas price [GHI]

![image](https://user-images.githubusercontent.com/11790366/58483807-34410d00-8161-11e9-9b5c-57dd7b558e36.png)

**Comment by rachelhamlin** [comment]
Notes from [8/5/2018 call](https://notes.status.im/035Hrq-DS7uj7VRbwzxkKA?edit): 

- Keeping signing phrase, not using emoji guard.
- Overview screen can not be edited by the user in first iteration.
- `Cancel` brings user back to the screen where Tx was initiated: from wallet, to the input fields. From DApp, to the screen that launched Tx. From chat, back to chat.
- Confirmation pop-up appears over Tx launch screen (e.g. DApp).
- Token amount can display as `N/A` if the Tx is only for gas.
- New `Data` field will contain other information from the Tx, such as a TtT setting amount. For non-Status contracts, this data will not be human readable. Requires more effort. Power users appreciate seeing it. For Status contracts, we could make the data readable.
- Not using `Wallet` field until we have multi-account.
- Not using the `DApp` field in first iteration. In future, could pull the URL from the browser if Tx was launched there.
- Not including conversion rates in first iteration. In future, must decide how many decimal points to show.
- Passcode / pincode / Keycard sign are all required. First iteration can probably get away with passcode only, as pincode/Keycard are not in production yet.
- QA is concerned about overflow on certain lines, e.g. if translated to different language or long network fee.

Design changes needed
- A way to see full recipient address, either in a dedicated field or on a long press.
- Error state in place of confirmation screen, to be used if Tx fails because user does not have enough ETH/token
- Info button/tool tip with copy explaining what signing phrase does
- Slight variation of overview screen required for signing messages that don't have on-chain Tx (e.g. logging in): "Signing message" vs. "Signing transaction" and only the recipient and signing phrase fields are necessary.

**Comment by flexsurfer** [comment]
take this into account:
eth_signTypedData_v3 password is refused. #8241
web3.personal.sign() not displaying message to sign and refusing password #8209
Gas estimation on contract transfers for Eth transfers incorrect #8269
