### ISSUE TITLE
Update Android app icon as PlayStore demands

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8098]
# Problem
New app icon specification for Google Play
App icons on Google Play are changing. From June 24, transparent backgrounds will no longer be allowed, and Google Play will dynamically add rounded corners and drop shadows to icons.

Let us know when your icon meets the new specification. If you're not quite ready, you can keep using the old specification for now. We'll automatically scale down your icon on June 24. 

https://developer.android.com/google-play/resources/icon-design-specifications

![](https://user-images.githubusercontent.com/6584810/57029878-48b5e680-6c43-11e9-9a4d-6175f60c55e8.png)

@hesterbruikman can you have a look if the new icon proposed in PlayStore is ok

**Comment by hesterbruikman** [comment]
@errorists @andmironov 

My guess is that we want update this to the circular logo. Right?

**Comment by errorists** [comment]
It's a bit outdated, this is what Google now calls a 'Legacy Icon', since some time now they've switched to a concept called Adaptive Icons that take different mask shape depending on the manufacturer, it's really cool https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

I'll create assets for one and we can see if it works with RN.

edit: actually I think that's what they mean in the requirements attached above

**Comment by hesterbruikman** [comment]
That's pretty cool, especially those visual effects!

**Comment by errorists** [comment]
Ok, I've created all of the necessary assets, available here [Dropbox](https://www.dropbox.com/sh/powx7dtzbu62goo/AAC2jeyqVyB846kUs57W-LvAa?dl=0)

It has two layers, foreground and background, together they combine the icon. Best instructions on how to include them in the app, I found over here https://proandroiddev.com/android-adaptive-icons-are-easier-than-you-think-3c66be2dd4dd

**Comment by errorists** [comment]
hey @mandrigin who can we ask about including those assets in android resources?
