### ISSUE TITLE
Resolved ENS address is not checksummed

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8121]
### Description
_Type_: Bug
_Summary_: when pasting valid ENS name as a recipient, get `Error in address: <address>` when tapping on `Done`

#### Expected behavior
address is resolved

#### Actual behavior
![photo!UNITO-UNDERSCORE!2019-05-03 12 34 15](https://user-images.githubusercontent.com/4557972/57132403-cabb2200-6d9f-11e9-8870-6da9e64002be.jpeg)

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

* Open Status
* Restore account with ETH
* Go to wallet > Send transaction
* In "Choose recipient" select "Enter recipient address"
* Enter valid ENS name (tried with several, i.e. `nastya.stateofus.eth`

### Additional Information
[comment]: # (Please do your best to fill this out.)

* Status version: nightly 03/05/2019 (issue is not presented in nightly 02/05/2019
* Operating System: Android, iOS

**Comment by asemiankevich** [comment]
i believe it is not wallet problem, since wallet received address resolved from ens usernames contract. We need to update ENS contract here to send checksummed addresses when resolved.
@richard-ramos  please take a look
or @3esmit :)

**Comment by richard-ramos** [comment]
Hi @asemiankevich  .  
The resolver is working as it should. You can check this on etherscan for the resolver used by status ens domain:
https://etherscan.io/address/0x5ffc014343cd971b7eb70732021e26c35b744cc4#readContract
If you go to the form "4. addr" and paste the value: `0x371decdaf7c88ef7881bcc3ecb2f08e4e9b2436c29b9ace2770ff5f6d90e06a8`  which is the hash representation of `nastya.stateofus.eth`,  it will resolve to the wallet address: `0x58d8c3d70ce4fa4b9fb10a665c8712238746f2ff`.

If the issue is related to the checksum, in the wallet you can use: `web3.utils.toChecksumAddress(WALLET_ADDRESS_HERE)` to format it correctly, since the contract does not and needs not to handle this.

**Comment by asemiankevich** [comment]
ah okay then it is still wallet , thank you for clarifying !

**Comment by 3esmit** [comment]
seems like there is an empty space at the beginning? 
If all chars are lowercase, or all chars are uppercase, than checksum should not be tested, it should only test the checksum if some are uppercase, and other lowercase.
