### ISSUE TITLE
Use multihash for sticker image in message instead of uri

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#8262]
# Problem

Currently, it's possible to send any url in stickers

## Implementation

multihash should be sent and image should be loaded from ipfs or swarm

**Comment by rachelhamlin** [comment]
@flexsurfer sounds like this is a must-have for stickers v1? Can we bounty it?

**Comment by flexsurfer** [comment]
@rachelhamlin not sure it can be done as bounty, it's a small change but requires some knowledge to be done

**Comment by jeluard** [comment]
It turns out packs stored on IPFS already references to URI (using INFURA gateway). See https://cloudflare-ipfs.com/ipfs/QmQRmKoVi5a1CCWDNUFPRdEixMQfsZ2ECC5e2nQF1Gwi86/

BTW those hashes do not resolve using the official IPFS gateway.

Necessary steps to fix this issue:

- update all packs so that they use an abstract representation of files (multi hash?)
- update contract to point to thoses
- update the code to deal with those hashes

Ideally we would also build a simple tool to publish new packs.
