### ISSUE TITLE
Issues in Desktop two-pane UI

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status-react#8661]
Collection of issues found on WIP desktop-mobile #8630.

```
Windows 10
15.6”
1920x1080 (16:9)
```

* [ ] 1. When opening a new public channel via [+]-button, it's not added to left pane.
* [ ] 2. Left pane content might need some scaling down, most channel names become unreadible and all start with Status
* [ ] 3. Bottom nav icons might need some scaling up. They are tiny on desktop
* [x] 4. [Select a chat to start messaging] should be grey (#939BA1) as it is a hint text, blue is reserved for buttons/links
* [x] 5. Repositioning the cursor on the text entry box in chat is not responsive
* [ ] 6. I thought on desktop UI the bttom nav was intended to be positioned at the bottom of the left pane. Spreading accross the whole bottom only on tablet sizes. @errorists can you confirm?
* [ ] 7. [+]-button menu should come up as an overlay or have some shadow at the top
* [ ] 8. Notifications probably needs to trigger an OS settings menu
* [ ] 9. The icons on the Settings list items (i.e. [>] and [switch] are too far on the right. Especially in [Devices] the switch gets cut off.

**Comment by errorists** [comment]
🙏 Thanks @hesterbruikman 
I'll continue with my batch

```
macOS 10.14.5
5120x2880
8-core Xeon 3,2ghz, 32gigs RAM, 1TB SSD, Redeon Vega 64 16gb
```

- [ ] Chat list items, either we can correct it manually here so titles use 15px font-size or wait for this issue to get fixed https://github.com/status-im/status-react/issues/7785
- [ ] bottom tab bar is missing its shadow
- [ ] Chat text input field is misaligned, it's hugging too close to the top of the toolbar.
- [ ] On both tablet and desktop we should remove the minimised state of the tab bar along with the animation and instead just show the modified 'on' state with text labels to the right of icons, always.
- [ ] We're missing a highlight on the left pane indicating which of the list items is currently selected.
- [ ] we should remove the back arrow from root level views, since there's nothing to go back to
- [ ] All of the '>' chevrons in list items have black fills, it should be 40% dark grey
- [ ] The transition when I click on share profile is weird, there's some garbage animation in the place where QR code will be rendered happening.
- [ ] QR code is misaligned
- [ ] Notifications should point to OS' system preference pane
- [ ] Mobile Data Setting, I'd hide it on desktop
- [ ] There's no browser available so browser specific settings should likewise be hidden.
- [ ] Going to Contacts from Profile and tapping on any contact takes me to Chats two column layout with the contact shown there. This is super weird.
- [ ] When I choose to edit my profile pic / username, there's no visible indication on what's possible to edit.
- [ ] '+' button's bottom sheet, there's an unnecessary large margin at the bottom
- [ ] Bottom sheets, the translucent overlay placed below the sheet covering the screen is not visible. Ideally we should use popups like in the design, but if we decide to reuse the same bottom sheet component we should at least make it behave correctly.
- [ ] Start new chat view, input field is missing its horizontal padding
- [ ] the Knight Rider loading indicator we use, the one in the left pane navigation bar, it stutters and drops frames like crazy on an iMac Pro, I think it's safe to say it shouldn't be the case :(
- [ ] an extension of the above, the overall UI performance feels super laggy.
