### ISSUE TITLE
Change  "Connect & get paid" to "Chat & transact" in "ens-welcome-point-3-title"

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8717]
# Problem

There is string "Connect & get paid" in ens welcome screen that can mislead user that he/she can be paid if connect with other users. Please, change it to  "Chat & transact" as it's more fair. Agreed with @rachelhamlin 

String to change:
"ens-welcome-point-3-title" in https://github.com/status-im/status-react/blob/develop/translations/en.json

**Comment by hesterbruikman** [comment]
There is actually a full copy update for this screen that was out of scope of PR earlier: https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=2317%3A50

![ENS copy](https://user-images.githubusercontent.com/35233054/62927677-51c46100-bdb7-11e9-8eaf-72e2e414149f.png)

**Comment by yenda** [comment]
Point 2 is even less clear on the right it says ETH address in the title and talks about chat key. It is actually doing both you wallet address and chat key

**Comment by hesterbruikman** [comment]
@yenda Agree, that copy doesn't make sense:S 

What about:
**Simplify your addresses**
Chat with people using an easy to read and share name: myname.stateofus.eth

To make sure I understand correctly, if I'm using another wallet like Gnosis safe (random, but they were integrating ENS). And I send funds to yenda.stateofus.eth, where do those funds end up?

- The account of the key we use for Whisper, and don't offer you access to in Status wallet yet
- The account of the key you used to purchase your ENS name

cc @errorists

**Comment by hesterbruikman** [comment]
Just realized the above doesn't make sense for point 2 either as it basically repeats point 1. How about the following @yenda @rachelhamlin @errorists 

1. Readable chat key 
Your chat key becomes an easy to read and shareable name: myname.stateofus.eth. 

2. Show your name in Status
Control your privacy by using your ENS name in chat instead of your random 3-word name (e.g. @vitalik94 instead of Breezy Tall Elephant).

3. 10 SNT to register
Register once to keep the name forever. After 1 year you can release the name and get your SNT back.

@ already own a username?

Still struggling with 1. I realize it is also an address, but we explicitly decided not to treat it as such, for example also not surfacing it in your wallet unless you manually add it when we allow to do so at some point.

**Comment by rachelhamlin** [comment]
Hmm, in your most recent suggestion, 1 and 2 are still speaking to the same benefit @hesterbruikman. Why not call out the fact that it can also be used as a wallet address? 

1. Customize your display name
An ENS name can replace your random 3-word name in chat. Be @yourname instead of Breezy Tall Elephant.

2. Simplify your ETH address
You can receive funds to your easy-to-share ENS name rather than your hexadecimal hash (0x...).

3. 10 SNT to register 
Register once to keep the name forever. After 1 year you can release the name and get your SNT back.

**Comment by hesterbruikman** [comment]
Sorry I dropped off here! This looks better! Few notes:

- I think we'd better go for `1. Customize your name in chat` so we get rid of the display name terminology
- Major benefit is `Receiving transactions in chat`. Based on earlier convs this week and talking to @errorists. 

1.  Customize your display name
An ENS name can replace your random 3-word name in chat. Be @yourname instead of Breezy Tall Elephant.

2.  Simplify your ETH address
You can receive funds to your easy-to-share ENS name rather than your hexadecimal hash (0x...).

3. Instant transactions in chat
Others can send you funds in chat without having to ask for your wallet address.

4. 10 SNT to register
Register once to keep the name forever. After 1 year you can release the name and get your SNT back.

wdyt? Believe I can update this myself if we all agree.

**Comment by rachelhamlin** [comment]
I think you mean...

`1. Customize your name in chat` no? :) Or even `1. Customize your chat name`

And as for #3, that's a good point. 

I think because it only applies to scenarios in which you are requesting/receiving, I might title it, `3. Receive transactions in chat` or even `3. Receive transactions freely` (although we do not have plans to add an address list back to wallet yet, so this might be too vague)

```
3. Receive transactions in chat
Others can send funds to your ENS wallet in one simple step.
```

```
3. Receive transactions in chat
Others can send funds to your ENS wallet without any action on your part.
```

```
3. Receive transactions in chat
Others can send funds to your ENS wallet without asking for your address.
```

Perhaps? I think I'm being too picky. They all work! Go for whatever change you feel is best @hesterbruikman :)

**Comment by hesterbruikman** [comment]
Thanks @rachelhamlin Great points! I'll take this last set and will make a final call based on what they look like on screen.

**Comment by hesterbruikman** [comment]
@yenda Looking to update the copy, but they are now 5 points instead of 4.
`1 2 3 4 @`

where it was
`1 2 3 @`

Can you take a look to make sure:
`ens-welcome-point-4-title` shows `4` instead of `@` 
`ens-welcome-point-x` and `ens-welcome-point-x-title` shows a `@` 
_(this would be a new 5th point but I'd rather not number it as the prefix shouldn't be a number but an `@`)_

1. Customize your chat name
An ENS name can replace your random 3-word name in chat. Be @yourname instead of Breezy Tall Elephant.

2. Simplify your ETH address
You can receive funds to your easy-to-share ENS name rather than your hexadecimal hash (0x...).

3. Receive transactions in chat
Others can send you funds via chat in one simple step.

4. 10 SNT to register
Register once to keep the name forever. After 1 year you can release the name and get your SNT back.

@. Already own a username?
You can verify and add any usernames you own in the next steps.

@rachelhamlin I'd opt to leave out `ENS wallet` although I ideally also want to include some way of saying you would receive transactions in chat on the address you use to register your ENS name. I cannot find a way to describe it without creating confusion around wallets, addresses, etc... Better solution would be to add a label to `Account info` (to be implemented post-V1) to indicate that the account address is the ENS controller. cc @errorists 

Also, @yenda I think it'd might be cool if a chat transaction can include the fact that it was a chat transaction as well as for a regular transaction to include a typed message. Transactions are too impersonal... #futuremusic #kudosintegration

**Comment by errorists** [comment]
I updated the copy in [designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4227%3A17267) to what @hesterbruikman suggested above.
@rachelhamlin how about we try and squeeze this one in before the release, it's all text updates and an additional bullet point.

**Comment by Lumeo6** [comment]
Massive respect to the creators of this community! I love how FemaleSideHustle has become a supportive hub for women ready to take charge of their income streams. It is refreshing to see real advice, authentic stories, and tips that help us turn our passions into profit. Seeing other women succeed through [FemaleSideHustle](https://femalesidehustle.com/) motivates me to hustle smarter and believe that financial freedom is totally within reach.
