### ISSUE TITLE
Welcome screen is shown instead of accounts list if tapping Back from Get yourself a key first screen

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8736]
# Problem

Back button breaks Accounts screen on Androids. There are several cases here, which will be logged as separate issues:

2. Case two: Welcome screen is shown when user taps Back device button when being on Get yourself a key first screen. Looks like all accounts are gone (which is not true)

Steps:
1. open status and create account
2. logout
3. tap Generate new key
4. tap build-in `<` button or device Back button

Actual result: welcome screen is shown
Expected result: user should be redirected to previous screen (list of accounts)

![image](https://user-images.githubusercontent.com/28752642/62869464-9650ed80-bd20-11e9-9221-ec57ed47e15b.png)

Video: https://drive.google.com/open?id=1pIrRiA2Vygp8-1LDJy-af9aTn5vaLqGF

**Comment by hesterbruikman** [comment]
@asemiankevich In this particular case we could also use a Cancel button instead of Back. That still doesn't resolve the issue of the native back button, right? 

Sounds like this has something to do with handling native Android behavior: https://reactnavigation.org/docs/en/custom-android-back-button-handling.html

**Comment by rachelhamlin** [comment]
Would you mind including screenshot of expected state when available? Cheers!
