### ISSUE TITLE
No [Confirm the code] screen shown if keycard initialized, has secred, paired and user recovers account

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status-react#8749]
# Problem

No PIN confirmation shown.

Figma https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=927%3A14702

Flow: 

![image](https://user-images.githubusercontent.com/28752642/63005577-7f77db80-be85-11e9-930e-e581d591ece1.png)

## Steps:

1. create keycard account 
2. logout
3. open status ->  access key -> recover with keycard -> begin recovery
4. tap the card which is init + has secret + paired (same card u just used for account creation)
5. enter PIN code on [Enter your 6-digit code] screen

Expected: code confirmation screen appears after i entered code 1st time

Actual: Recovering key screen is shown, so no code confirmation 

@guylouis @hesterbruikman

**Comment by guylouis** [comment]
It should be impossible to recover a multiaccount with the same seed than one that is already on the phone. It's the same principle as for "normal" recovery from a mnemonic

So what should be done, in this case,  is to show him an error message "You can't recover this multiaccount because it's already on your phone". 

When it's recovery from a keycard, then @bitgamma  (michele) can you remind us what is the parameter that we can get from the keycard tapped that we can compare to the existing account on the phone in order to establish if they have the same seed ?

**Comment by bitgamma** [comment]
that would be the Key UID (returned in the SELECT command response)
