### ISSUE TITLE
Unknown in Profile and "null is not an object" at attempt to log out after log out from offline

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8806]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: when log out without network, after login instead of username "Unknown" is shown without user picture and also at attempt to log out "null is not an object(evaluating 'n.toLowerCase''"
Network settings are empty for such users.

#### Expected behavior
Can log out;
usename \ userpicture is valid;
network settings are shown

#### Actual behavior
![photo_2019-08-21 16 00 18](https://user-images.githubusercontent.com/4557972/63438559-c8530580-c42c-11e9-9b06-2793a644eee2.jpeg)

### Reproduction

- Open Status
- Create new account
- Turn on Airplane mode
- Log out
- Login
- Turn off Airplane mode

### Additional Information

- Status version: nightly 21/08/2019
- Operating System: Android, iOS

#### Logs

[status_logs.zip](https://github.com/status-im/status-react/files/3525698/status_logs.zip)

**Comment by churik** [comment]
cc @yenda @rachelhamlin

**Comment by churik** [comment]
The same behavior is reproducible when you create account -> switch to Ropsten -> create new account.

**Comment by yenda** [comment]
@churik do you mean create account or create multiaccount?

**Comment by bitsikka** [comment]
I came across "Unknown in Profile" part of the issue doing simply this

- create account and log in (profile behaves as it should)
- log out and log back in
- scroll down in profile to reveal profile header in toolbar position (profile shows blank pic shifted down with "Unknown" for name

I found it while testing/iterating/developing PR #8825 , bothered me very much since I am partly responsible :), investigated and found the cause, fixed it in latest push.

It happened because subscription `:multiaccount` is `null` briefly when logging in. When it got populated millseconds later, the header-in-toolbar component that subscribes it was not setup to re-render.

Please note, while this is related, and "part" of the original issue seems to be fixed in that PR, other parts of the original issue have not been attended in the PR.

**Comment by rachelhamlin** [comment]
Legend @bitsikka!!

@churik can you confirm that this is fixed by PR [8825](https://github.com/status-im/status-react/pull/8825) and close if so?

**Comment by churik** [comment]
@bitsikka thanks a lot!
Tested both scenarios and can't reproduce anymore.
