### ISSUE TITLE
Text in the input field is lost if navigate from Chat to Chats and back

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#8865]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Input field contains no text if type some text and then navigate back to Chats and return back to Chat. In 0.13.0 version input field contains typed text if navigate back to chat.

Note: it also happens if you navigate in any other way away from Chat (to Wallet, Profile, etc) and then return to the chat

#### Expected behavior

text remains in the input field

#### Actual behavior

input field is empty

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
Video: https://drive.google.com/file/d/1iW2yYG_PbPuPeGBuQke1UN_FWWw9pW0N/view?usp=sharing
- Open Status
- Open public chat (or 1:1 or group chat)
- Type some text in the input field (e.g "hello world") and do not send it
- use < button to navigate back to Chats
- Open same chat again
- Check content of the input field

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly August 29
- Operating System: real Android 9, Pixel XL and real iphone 6s, iOS 12.4

**Comment by bitsikka** [comment]
It is possible it got broken after this PR that I made https://github.com/status-im/status-react/pull/8589 a while back. I had to touch on search bar on that PR as it was interacting with network status display. As it was secondary to the issue I was fixing, I did not pay so much attention to search bar.

This issue is probably also related https://github.com/status-im/status-react/issues/8662

Then there also this unassigned bountied issue that is related https://github.com/status-im/status-react/issues/7697

If given the opportunity I believe I can fix all of these.

**Comment by cammellos** [comment]
Can't replicate in latest develop, might have been fixed in the meantime, @status-im/status-core  could anyone try to replicate as well? If another can't replicate we can close the issue.

**Comment by yenda** [comment]
@churik is it reproducible?

**Comment by churik** [comment]
It's fixed, yes
