### ISSUE TITLE
Network indicator in transaction overview

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#8884]
Let's show an additional list item in the transaction overview modal when the network is not "Mainnet" with a tappable question mark icon and a popup on top.

<img width="834" alt="Screen Shot 2019-09-02 at 16 59 32" src="https://user-images.githubusercontent.com/3115606/64119803-57540c00-cda3-11e9-948a-cbf81bcf8082.png">

FIGMA https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Mobile-wallet?node-id=1543%3A11264

┆Attachments: <a href="https://storage.www.wrike.com/attachments/107999177?accountId=2688416">Details.png</a>

**Comment by flexsurfer** [comment]
cc @rachelhamlin

**Comment by rachelhamlin** [comment]
I like the idea @andmironov - what inspired it? Does it come out of a problem observed somewhere? Not sure how to prioritize.

**Comment by flexsurfer** [comment]
we had network prompt before in the wallet, and we lost it in the new sign transaction flow, but it looks dangerous for the user, because he doesn't know in which network he is signing transaction. so better to show this information

**Comment by StatusWrike** [comment]
➤ Andrei Mironov commented:

thanks! not really, i was just revisiting the transaction overview modal while working on
https://www.wrike.com/open.htm?id=389379190 and realized this is missing. I can recall a lot of requests fro the QA team to explicitly mention the network when it comes to sending transactions, I guess someone from the QA team can provide use cases/problems that this can solve.

**Comment by flexsurfer** [comment]
but it's getting noisy , maybe we could show only for testnets this item,  and nothing for mainnet, wdyt @andmironov ?

**Comment by StatusWrike** [comment]
➤ Andrei Mironov commented:

absolutely! forgot to mention that it was the idea: show it only on test networks.

Also, re: noisiness, i'll prep up a transaction overview screen with hidden fields as an experiment.

**Comment by StatusWrike** [comment]
➤ Andrei Mironov commented:
<img width="375" alt="Details" src="https://user-images.githubusercontent.com/3115606/64177508-4faa6b00-ce68-11e9-8f33-107e43779b0b.png">

just fyi, not sure if we should do this

**Comment by hesterbruikman** [comment]
@Serhy @churik would love to hear your thoughts on this. I always understood the risk of mistaking testnet for mainnet, to be in sending funds _to_ a testnet address, not _from_ a testnet address. 

It seems more useful to me to have this warning appear when you tap on `Receive` or `Share`.

**Comment by Serhy** [comment]
We had on the Send transaction view (when sending from Wallet) ‘You are on [network]. [Real/Test] ETH will be sent’. But then we introduced new tx flow and lost it (we have those actually now too but just when sending from Wallet)
The same in my opinion would make sense to reflect in the ‘Sending transaction’ bottom sheet, i.e. displaying network in all cases.

Risks here are about what is going on to be sent: mainnet or testnet assets. 

The worst case that may happen is that user sends real ETH thinking (s)he send test ETH.
So to mitigate this risk when on TestNet we should display `TestNet` label. 
But when on Mainnet, we alarm user with `Mainnet` label: "Beware, you are on Mainnet, you operate with real ETH!" 
 

> risk of mistaking testnet for mainnet, to be in sending funds to a testnet address, not from a testnet address.

Testnet address is the same as Mainnet address for one account. And when scanning QR code of address there is even network_id inside which will notify sender about different network.  

So if we decide to have network value indication in `Sending...` bottom sheet, my call if to display network value disregard its testnet or mainnet.

**Comment by hesterbruikman** [comment]
> The worst case that may happen is that user sends real ETH thinking (s)he send test ETH.
Got it, so you might send a high amount on Mainnet, mistaking it for Testnet.

If that's the risk I suspect the currency indicator (ETHri ETHro STT) plays an important role in communicating what you're sending. This hasn't always been that visual, if we even use a distinction at all. We can also play with absence presence of USD value. E.g. show USD on Mainnet, and replace it with something like Test token on Testnet. @andmironov this could be an alternative to hidden fields you mentioned above. It can be hard to notice the difference in something that's not there witout a side-by-side comparison.


> So if we decide to have network value indication in Sending... bottom sheet, my call if to display network value disregard its testnet or mainnet.
@Serhy can you elaborate what you mean with `network value`?

**Comment by Serhy** [comment]
With the 'network value' I mean this indication:

<img width="834" alt="64119803-57540c00-cda3-11e9-948a-cbf81bcf8082" src="https://user-images.githubusercontent.com/8749671/67403863-38137700-f5bb-11e9-9f4d-2672abb1d289.png">

Yes, we have ETHri/ETHro indicating that it's something non-mainnet and USD values on TestNet are 0 everywhere disregard ETH/token amounts. 
<img width="361" alt="Screenshot 2019-10-23 at 18 28 55" src="https://user-images.githubusercontent.com/8749671/67409773-b07e3600-f5c3-11e9-8f86-66dc97731b8d.png">

But, in my opinion, it doesn't solve the part of "Send ETH on mainnet thinking it's testnet" (because we'll have all "indications" on TestNet only - 0/no_USD value or ETHro/ETHri or `TestNet` network) which user may not even know and get used to it by using Status. 
From another point, having many indications on TestNet only (ETHro + No/Zero USD value + TestNet label) increase the strength of awareness when user is on Mainnet... And considering we default for all new/recovered accounts to Mainnet we at the same time consider users are using actively Mainnet so they should notice the difference between Mainnet or Testnet...

Ok, both cases works for me :) 
1) Having only 'testnet' indications (0 USD everywhere and ETHro/ERTHri as asset - we have already) + in scope of that issue we'll get a Network: Ropsten/Rinkeby/Goerli (by the way, would it make sense then to have 'Testnet' suffix here, so `Network:`................ `(?) Ropsten (Testnet)` ?
2) We display network in `Sending...` bottom sheet view whether it's Mainnet or Testnet.

I think the first item above has most votes then.
