### ISSUE TITLE
Show app version 

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#889]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to find app version in the app's interface so that I know which version is used.

Instabug: 
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/264
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/387

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature 

*Summary*: There is no app version in the app. User needs to go to settings and check the version there. It would be better to show the app version, e.g. in profile

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App version can be found in the app
#### Actual behavior
[comment]: # (Describe what actually happened.)
there is no app version now in the app interface

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

- [ ] Design app version place and look
- [ ] Implement "show app version"

**Comment by yugensoft** [comment]
How do I get access to these on instabug? When I click them it just takes me to my dashboard

**Comment by jarradh** [comment]
instabug is for core contributors, partly because of how instabug SaaS is setup and partly because they contain some private information

**Comment by etherstudio** [comment]
@yugensoft James?

**Comment by yugensoft** [comment]
Who is James?
Well can I take this issue on? I'd like to get started contributing and this looks like a good start

**Comment by etherstudio** [comment]
@yugensoft Someone I know who uses the word Yugen. How are you planning to contribute?

**Comment by yugensoft** [comment]
Just asking maintainers if I can take on this issue

**Comment by Smokyish** [comment]
@yugensoft Feel free to work and submit a PR on any open issue. The core contributors are usually listed as Assigned if they are working on an issue, which should help you choose those which aren't being worked on right now by them

Though this particular issue shows in the summary that a design is needed, so this first needs a design by @andmironov before it should be worked further.

**Comment by denis-sharypin** [comment]
Overview
<img width="688" alt="screenshot 2018-02-09 17 42 00" src="https://user-images.githubusercontent.com/6559881/36038654-95e140e0-0dc0-11e8-9015-d0e6db3e4d2f.png">

Specs:
The label is aligned on the right side, it means when it grows it will expand to the left

Tap area: because of the tricky position of this label tap zone of a logout button should be reduced in a half
<img width="815" alt="screenshot 2018-02-09 17 48 10" src="https://user-images.githubusercontent.com/6559881/36038981-7507d766-0dc1-11e8-853f-70cb9250baa3.png">


iOS:
<img width="685" alt="screenshot 2018-02-09 17 43 39" src="https://user-images.githubusercontent.com/6559881/36038856-21980c2c-0dc1-11e8-876a-d404378b4833.png">

Android:
<img width="710" alt="screenshot 2018-02-09 17 43 50" src="https://user-images.githubusercontent.com/6559881/36038874-2d670990-0dc1-11e8-88b3-efcb7360947f.png">

**Comment by chadyj** [comment]
Would love to see this.
Will it, or can it display dev build numbers too?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 700.00
Contract address: [0x920cf6126cac7417c14781436f730c176ecd684c](https://etherscan.io/address/0x920cf6126cac7417c14781436f730c176ecd684c)
Network: Mainnet
Paid to: jeluard
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by audriu** [comment]
Could I use a React Native module for this or is it better just to add code?
