### ISSUE TITLE
Give user a hint on how to re-send phone number

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-react#891]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to provide my phone number again in case there is any trouble with initial input, so that contacts from my phone contact list are added to the app.

Instabug:
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/282
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/246
* https://dashboard.instabug.com/applications/status/beta/bugs/168
* https://dashboard.instabug.com/applications/status-10bb8cbc-15f6-44f0-8c7a-db478dc34d7d/beta/bugs/343

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: It's possible to send a new phone number in Console with command /phone. However, for fist-time users it's hard to find this command. They are using blinking Console message "Tap here to enter your phone number" and it's perceived as the only place to provide a number. If user provided valid but wrong phone number then message is no longer blinking and user does not know how to provide another phone number.

Same issue is for confirmation code message: when code expires then user does not know what to do to initiate code re-send.  

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
User needs to get "a hint". For example, we can extend a console message "Thanks! We've sent you a text message with a confirmation code..." with extra sentence that explains how to re-send a phone number in case of any issues.

#### Actual behavior
[comment]: # (Describe what actually happened.)
There is no hints for user who typed wrong phone number on how to re-send a phone number again.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status as a new user who didn't provide phone number yet
- in Console tap on message "Tap here to enter your phone number..."
- type valid phone number  

### Additional Information
[comment]: # (Please do your best to fill this out.)
* Status version: 0.9.3
* Operating System: Android and iOS

**Comment by sooheon** [comment]
One note is that the original green phone button in the message continues to work, so the user can simply press that again.

Anyways, I may try to start on this, once I understand how the handlers work. I suggest a two part solution:

1. After the user has successfully entered the confirmation code, rather than printing only "Success", say something like "Great, you're all set! If you wish to add a new phone number, simply message me `/p` (short for `/phone`) and the number. 
2. If after some time the user inputs nothing, send a new message with helpful prompt ("Didn't get the confirmation code? Check your number, and you can tap the phone button again to tell me."), but not necessarily the factoid about typing in commands yet. If the user is having trouble moving forward, hitting them with new info to digest might not be the best idea, plus we have the message upon success.

**Comment by annadanchenko** [comment]
same as #674

**Comment by annadanchenko** [comment]
Phone command is removed
