### ISSUE TITLE
In profile address is shown instead of name and "Mailserver" label is overlapped when connected to custom mailserver

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8955]
###  Description

*Type*: Bug

*Summary*: when connected to custom mailserver, address is shown  instead of name and no "Mailserver" label in Profile > Sync settings

#### Expected behavior
![photo_2019-09-09 14 18 00](https://user-images.githubusercontent.com/4557972/64530272-fd0bfb80-d30c-11e9-8e0d-f63e7f625094.jpeg)

#### Actual behavior
<img width="220" alt="dfs" src="https://user-images.githubusercontent.com/4557972/64530309-1745d980-d30d-11e9-86d5-c0619044b3d7.png">

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to profile > Sync settings
- Add custom mailserver 
- Connect to it
- Go back

### Solution

[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:
I'm actually not sure how we can handle mailservers with long names.
For now "Mailserver" label is overlapped, which is not right IMO:

![photo_2019-09-09 14 26 34](https://user-images.githubusercontent.com/4557972/64530641-f2059b00-d30d-11e9-9f45-11b9ea59bea5.jpeg)

@andmironov or @errorists please take a look, what is better from your POV.

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly09/09/2019
- Operating System: Android, iOS

**Comment by errorists** [comment]
The `Mailserver` text label should not get truncated or overlapped, no question there 👍 

This is the desired behaviour, `16px` of blank space between and truncate the text accessory (mail server address) in the middle
![Small Cell](https://user-images.githubusercontent.com/4932774/64534050-026d4400-d315-11e9-96b1-397a5aff9018.png)

so the following would work only on iOS but React Native does support text prop like `adjustsFontSizeToFit` where it will try and shrink the text down to make it fit up to a minimum scale factor `minimumFontScale` where `0.7` sounds like a reasonable value. No such luck on Android :(

This is how it would look like. It's optional, if it's only two lines of code to add we might as well do it.
![Small Cell](https://user-images.githubusercontent.com/4932774/64534157-334d7900-d315-11e9-964c-ce95ea767853.png)

**Comment by andmironov** [comment]
>so the following would work only on iOS but React Native does support text prop like adjustsFontSizeToFit 

I like it, but is it going to truncate the value if it's extremely long anyway?

Here's how this edge case is specified in our design system at the moment

<img width="612" alt="Screen Shot 2019-09-09 at 16 58 19" src="https://user-images.githubusercontent.com/3115606/64537229-1c158800-d323-11e9-93f4-d5cd17d1dd7e.png">

**Comment by bitsikka** [comment]
interesting! :)

I handeled it differently in #8912 so far
- I made it so that `text` accessory is no longer than 62% of device width. To be precise, I did this
```clojure
(defn accessory-text [width last]
  {:color       colors/gray
   :max-width   (if last (* @width 0.62) (* @width 0.55))
   :line-height 22})
```

In that way, I kept it simple, for now.

Rationale is that in the nesting structure in the implementation, it is made such that column containing `title` (includes `title-prefix`, `title-accessory`, `subtitle`, `subtitle accessory`) is supposed to be the `primary` content - the king/queen if you will. Two columns on its side(icon/accessories) are supposed to be `secondary/accessorial/peripheral` if you will. So, `title` has `flex 1` and is supposed to eat up majority of space, which it does on most cases.

A long accessory taking over the king/queen :) is in that perspective, a misbehavior :)

What I propose is, if there is a long content which wants to be aligned towards accssories, we put it in title. The `black title` goes in `title-prefix`. This facility exists already. We even have `title-color-override` to make it gray instead of default black. What would be needed is conditional 16px left margin on title, and `title alignment` prop. That would achieve the intent of the spec.

Also, `title-elipsize-mode`, because `title` has `tail` by default.

Note: `list-item` as it is implemented does NOT use any `absolute positioning`, `negative margin`, only one case of `transform translateY`(for chat-list unread count badge), `flex-grow`, `flex-shrink` and `flex-basis`. In my opinion, it is best to stay away from those as much as possible.

**Comment by errorists** [comment]
thanks for commenting @bitsikka I appreciate your in-depth thoughts on this! I like what you're suggesting even if it doesn't match the semantic use of defined props to achieve this goal :) I don't want us to split hair over such a detail, the important bit is to truncate the accessory in the middle (since this way there's less chance the truncation will make recognising the selected choice among multiple others difficult) and block the text accessory from pushing pass this 62% threshold you suggest, so it doesn't force overflow on titles like on the attached screenshots.

**Comment by bitsikka** [comment]
Another possibility is, without any change:

- make black title (eg `Mailserver`) a `title-prefix`
- put the long text (eg `looooong.looong.mail.server.name`) in `title` as a `component`(yes, `title` can be component in this implementatino)
- in the `title` component use `text` view with `:margin-left 16`, `text-align right`, `ellipsize-mode middle`

That ought to do it.. no change necessory in the implementation of `list-item`

**Comment by bitsikka** [comment]
I did (as in the last idea) this(in #8912 ) for
- `node-version` and `app-version` in `Profile > About >`
- `Mailserver` in `Profile > Sync Settings >`

```clojure
[list-item/list-item
     {:type                :small
      :accessibility-label :node-version
      :title-prefix        :t/node-version
      :title
      [react/text
       {:number-of-lines 1
        :ellipsize-mode  :middle
        :style
        {:color        colors/gray
         :padding-left 16
         :text-align   :right
         :line-height  22}}
       node-version]}]
```

Not: About this issue's Original Post.. the part about

> address is shown instead of name

is not handled in #8912. I figure `mailserver-subscription` need to be fixed, and that is not a part of the PR focused on polishing/putting-finishing-touches of `list-item`

**Comment by churik** [comment]
Still relevant in nightly 07/01/2020

**Comment by shivekkhurana** [comment]
This problem also occurs in the about section with status version.

![IMG_BF83F39D27F2-1](https://user-images.githubusercontent.com/1925158/98104601-ab351600-1ebc-11eb-85a4-04b88745dda0.jpeg)
