### ISSUE TITLE
No text formatting (bold, italic) applied in chat for messages in asterisks (*) or underscores (_)

### ISSUE THREAD

**Issue by churik** [status-im/status-react#8995]
### Description

*Type*: Bug
*Summary*: Text of message is not formatted accordingly on home screen when message in chat (1-1  / public) sent wrapped up with asterisks (`*`) or tildes (`_`)

#### Expected behavior
**bold text** and *italic text*

#### Actual behavior
Text of message is not formatted on home screen in **bold**/_italic_ font when message in chat sent wrapped up with asterisks (`*`) or tildes (`_`)
![dfsdfsdfds](https://user-images.githubusercontent.com/4557972/64867625-0dd6ad00-d63e-11e9-917e-807125bea33e.png)

### Reproduction

- Open Status
- Join any public chat
- Send message wrapped up with asterisks and tildes (e.g. `*Bold*, _Italic_ fonts`)

### Additional Information

* Status version: status nightly 13/09/19
* Operating System: Android, IOS

**Comment by churik** [comment]
@rachelhamlin not sure if it is required for V1 - it is just broken in `develop` now (seems that it was introduced in https://github.com/status-im/status-react/pull/8943) - but not critical IMO

**Comment by rachelhamlin** [comment]
Lovely. Agreed, not critical.

**Comment by yenda** [comment]
@churik you are correct, the upgrade to react-native with #8943 uses vanilla react-native, and does not include the custom changes that were made to support markdown
But if we could reintroduce that as a react-native library instead of having to use a cumbersome fork of react-native that would be great.
For that reason @rachelhamlin I would propose a L bounty and to split the work between iOS and Android

**Comment by rachelhamlin** [comment]
Introduce custom changes required to support markdown, _as_ a react-native library? @yenda 

Adding to bounty backlog. 👍

**Comment by rachelhamlin** [comment]
@acolytec3 here's a great candidate for you to look into! Are you interested?

**Comment by acolytec3** [comment]
@rachelhamlin Funny coincidence, I was actually looking at this last night.  Question though, are you looking for full markdown support or just support for bold/italics?  My question stems from the fact that I saw a number of libraries on npm that support markdown so there is already a lot of that sort of thing that exists today.  That said, does it make more sense to try writing it directly in Clojurescript and just make it part of the chat module?  I haven't had much chance to look at how interop with javascript works but it seems like it might be pretty straight forward to just have the message-content functions parse the text of incoming messages, look for the markdown indicators, and then format appropriately but it could get unwieldy pretty quickly if you're looking for full markdown support.

**Comment by cammellos** [comment]
@acolytec3 I am looking into something related to this, we would like to move parsing of text on the sender side and just render according to the recipe on the receiving end, for performance reason.

I wasn't aware that we used a fork of react-native for rendering bold/italic/code, so that changes a bit things, I will have to understand why it was done (likely performance), and if that's still the right approach, as opposed to render through a recipe sent by the sender.

If that's ok, could we put this on hold this week so I can look further into whether we should be using or own fork of RN for this (ideally no, as it's more code to maintain), or we can get away without?

cc @rachelhamlin @andremedeiros

**Comment by acolytec3** [comment]
@cammellos Sure, that's fine. 

@rachelhamlin, any other specific issues you want me to take a look at?

**Comment by rachelhamlin** [comment]
Yes - definitely, let's @cammellos.

@acolytec3 want to take a look into [this one](https://github.com/status-im/status-react/issues/6946) instead?
