### ISSUE TITLE
No conversion for some tokens and currencies 

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9140]
# Bug Report

## Problem

It is the same as https://github.com/status-im/status-react/issues/4508.
Should be automated with fix.

#### Expected behavior
as we are using https://min-api.cryptocompare.com for fetching tokens price, there are several tokens presented in Status app, but not provided by https://min-api.cryptocompare.com/.

List of tokens:
- XPA (no info)
- ٨ (DentaCoin, should be DCA for getting info)
- BRLN (no info in cryptocompare)
- ST (should be OST for getting info)
- ROL (should be DICE for getting info)

List of currencies:
- AFN
- BBD
- MZN

**Comment by rachelhamlin** [comment]
BRLN is the ETHBerlin token so that one doesn't have a price :)

**Comment by yenda** [comment]
well if they are not in cryptocompare what are we suppose to do? we can't make up a price for it if there is no market.

So I suppose this task is about using the right symbol for the 3 that are named differently in cryptocompare?

**Comment by churik** [comment]
Ofc we can't.
I think it is better to delete all currencies, which we can't support and replace symbols with the right ones. In the future it should be automated (e2e), because seems that lists are hardcoded and didn't take into account that list of currencies/tokens can be changed in cryptocompare.

**Comment by tmlee** [comment]
May I suggest considering our API at https://www.coingecko.com/en/api

One of the pain points we hear from developers is to support unknown ERC-20 tokens. To solve that problem we provide an endpoint to query token price using contract addresses. Since we support over 5500 coins/tokens there is a chance that you may find the token market data from CoinGecko.

Here is example for CDAI
https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0xf5dce57282a584d2746faf1593d3121fcac444dc&vs_currencies=usd,eur,gbp,eth,btc

**Comment by churik** [comment]
still relevant

**Comment by cammellos** [comment]
@churik is this still relevant?

**Comment by churik** [comment]
yes, still an issue in 1.9

**Comment by churik** [comment]
Still relevant on nightly

**Comment by cammellos** [comment]
Closing as this might not be relevant in the new wallet
