### ISSUE TITLE
Keycard onboarding UI touchups / use components

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9177]
## Problem
After https://github.com/status-im/status-react/pull/8903 it is required to use same components across all onboarding process, including Keycard part.
It should resolve differences in design and issues with long text (i.e. impossibility to create account  with Keycard when the application  in Russian - screenshot is attached)
![photo_2019-10-11 13 20 56](https://user-images.githubusercontent.com/4557972/66647744-03ea9e80-ec2a-11e9-9c88-cce74a7aa410.jpeg)

More details will be added by @siphiuel

**Comment by churik** [comment]
More issues #9200 and #9201

**Comment by vitvly** [comment]
@dmitryn not sure if this is the best approach, but that's what I did when fixing #8911 (Basic recovery flow):

1. Move views from `status-im.ui.screens.multiaccounts.recover.views` to `status-im.ui.screens.intro.views` so that `top-bar`, `bottom-bar`, etc. can be re-used.
2. Re-use logic from `status-im.multiaccounts.create.core` for recovery flow as much as possible, but preserve `status-im.multiaccounts.recover.core` for wizard forward-action handling and recovery-specific calls. All wizard state data is now in `(:intro-wizard db)`.
3. Initialize custom back-button/iOS swipe action processing in `core` namespaces via `::navigation/add-wizard-back-event` fx. This means that now wizard's back action (clicking on back arrow, Android's hardware back button and iOS's swipe left gesture) are invoked via `navigate-back`, which then invokes proper back handling as setup by `wizard-back-event`. Forward action is different between intro flow and basic recovery flow, and is setup in `core` namespaces via `(get-in db [:intro-wizard :forward-action])`.

**Comment by churik** [comment]
related issue: https://github.com/status-im/status-react/issues/8851

**Comment by rachelhamlin** [comment]
@guylouis I think we bumped this one from v1 must-haves, right? Want to double check w/ you, I forgot to drop release label last week.

**Comment by guylouis** [comment]
@rachelhamlin yes, it's out of v1 
@andrei I guess this one should be closed and be part of your newly edited issues right ?

**Comment by andmironov** [comment]
Addressed in https://github.com/status-im/status-react/issues/9356
