### ISSUE TITLE
Recover a key from seed on keycard: a password is asked to the user (it should not)

### ISSUE THREAD

**Issue by guylouis** [status-im/status-react#9231]
Tested with today's nightly StatusIm-191017-025900-7b6dfa-nightly-universal.apk

From a fresh download of status, user actions
- access key 
- from seed
- enter seed
- to keycard 

then Status asks for a password (before even asking to tap a keycard or anything)

Correct behaviour should be : ask to the user to tap a card, and then depending on its state proceed 
- if card is not initialzed: initialize it (define pin, puk, pairing) and load secrets 
- if card is initialized with a secret on it, ask the user to reset card
- if card is initialized with no secret on it, ask for pin, and load secret

In no case a user password should be asked

**Comment by churik** [comment]
> if card is not initialzed: initialize it (define pin, puk, pairing) and load secrets
if card is initialized with a secret on it, ask the user to reset card
if card is initialized with no secret on it, ask for pin, and load secret

@guylouis I didn't catch the idea of it.

Now if I try to restore account from seed phrase (account was created with Keycard) with following steps:
1) create account with KeyCard
2) reinstall app
3) Access Key > Enter seed phrase
4) enter seed phrase > select keycard 
5) after proceeding I see "You already have multiaccount on card"
![photo_2019-11-06 11 41 45](https://user-images.githubusercontent.com/4557972/68291569-6cdb0000-008a-11ea-89b5-5484dc218dc8.jpeg)
Why I can't use instructions from message:
- I can't login because I delete the app 
- I can't reset the card because we removed this option.

If I instead of access key on 3 step chose "Recover with Keycard" > I will be asked for pairing code and can recover account.

IMO it should be the same for both cases OR we can prevent user somehow that if he is trying to recover account with keycard, he should choose option  "Recover with Keycard" instead of access key > seed phrase.

WDYT?

**Comment by guylouis** [comment]
Great feedback ! 

Just to be clear: 
- this case is about the user that wants to type his mnemonic and 'put it' on a keycard. So it's "access key">"enter seed"
-  it's not about: the user that has already a keycard with a mnemonic imported on it, and want to add this keycard account on its phone. This use case is tackled with "access key">"access with keycard"

First off the copy of the error message must be reviewed. I think the text should be "This keycard has already a key on it. If you wish to change it, login first, and reset your card. If you want to access the key from this card, use "Access key" and "Access key from keycard" option."  @andrei do you agree ? if yes, may you create an issue, and add it in onboarding epic ? 

Also, in your case @churik the card you tap has already an account on it. If it had not then the user would proceed. So in your case, the user has entered a seed to put it on a keycard, but the keycard he is tapping is not empty, it already has a seed in it. 

**I can't login because I delete the app** -> in this case the user needs to go to "access key">"access with keycard"

**I can't reset the card because we removed this option.**->I agree this needs to be part of v1. This is #9229 and @rachel has put it in the v1 backlog

**Comment by churik** [comment]
@guylouis 
OK, much clear now, thanks!
So if I understood correctly, now I should be able to port mnemonic to keycard through this flow 
"access key">"enter seed"?

If so, we need to test it and create separate test case for it.

**Comment by guylouis** [comment]
"So if I understood correctly, now I should be able to port mnemonic to keycard through this flow
"access key">"enter seed"?"
yes, exactly
