### ISSUE TITLE
Userpic in reply snippet not updated after re-reply different user message

### ISSUE THREAD

**Issue by Serhy** [status-im/status-react#9490]
# Bug Report

## Problem

When user quotes message from different user (including your own account) while reply snippet already present in message input - then the userpic of different user is not updated in message input.

#### Expected behavior
Userpic corresponds to contact who message is quoted 

#### Actual behavior
Userpic in reply snippet not updated after re-replying different user message

<img width="698" alt="Screenshot 2019-11-19 at 15 58 29" src="https://user-images.githubusercontent.com/8749671/69152634-73836180-0ae5-11ea-9ceb-6162af9b9734.png">

### Reproduction

- Open Status and create new account
- Join public chat with messages from two or more different users
- Long tap on message from UserA -> Reply
- Long tap on message from UserB -> Reply
- Verify in the message snippet there is UserB's userpic

### Additional Information

- Status version: `0.14.0 develop (2019181102)
- Operating System: Android and iOS

**Comment by churik** [comment]
Continuation of #6214 - closed it

**Comment by cammellos** [comment]
Looks like this is a caching issue with re-frame (or the way we use re-frame). Subscription `chats/photo-path` is not re-run (likely because is cached), but the value passed to the view is the old one. I have verified the correct `from` parameter is passed.
You can also verify that by resetting the re-frame subscription cache (reload code), and the right picture will appear.

**Comment by churik** [comment]
Still relevant on nightly 26/02/2020

**Comment by churik** [comment]
still relevant on release 1.4

**Comment by churik** [comment]
not relevant, no more picture in reply snippet (Status 1.13)
