### ISSUE TITLE
Speed up pending sent transactions

### ISSUE THREAD

**Issue by leafcutterant** [status-im/status-react#9685]
# Feature Issue

### User Story

As a developer, I want to be able to submit  pending senttransactions with a different gas price or gas limit and same nonce **so that** I can speed up transactions, unclog a clogged transaction queue, prevent the failed execution of a transaction with too low gas limit, etc.

### Description

*Summary*:
* extra option appearing in Transaction history for pending sent transactions, in-line (no need to go to Transaction details to find it)
* extra option: a small button with "Speed up"
* the name is simplified for UX, it actually lets you tweak both gas price and gas limit, and in both directions
* nice-to-have, but not critical: give gas price estimates (a la Metamask)

### Acceptance Criteria

See above

**Comment by flexsurfer** [comment]
@errorists wdyt ?

**Comment by errorists** [comment]
@flexsurfer actually I'm not sure, with the current gas prices it's been months since I made a transaction on mainnet. This was written in December 2019, happy times 😅  What do you think, should we include this? In general with wallet, I don't like the UX of our wallet and I'm still keeping my fingers crossed for a redesign and if it were to happen we'd gather requirements first like this one here.

**Comment by leafcutterant** [comment]
@errorists how big of an effort would it take to implement this? I'm certain that the mainnet situation won't end soon (it requires a major adoption of L2), and I guess a wallet redesign wouldn't happen soon either.

**Comment by hesterbruikman** [comment]
Closing as this will be addressed by #11214
