### ISSUE TITLE
Handle released ENS names

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9719]
# Problem

After owning an ENS name for one year, you are allowed to release it. We don't currently support this in our UI, but it can be done through Etherscan.

However, the UI does not respond when a person does so.

I released my name rachel.stateofus.eth. I can still see the name on my profile afterward, and set it to display in chat. 

When I attempt to re-register the name, the UI says that it is connected to my chat key, and thus I am blocked doing so.

Though it doesn't actually work. Clicking into details about my name showed `Transaction processing` (the release Tx was already complete at this point), and in chat my 3 word name was displayed.

When I attempted to register it from another wallet, I found I had the option to do so.

Per @3esmit:

> Releasing does not remove the data defined in the resolver, because users can change the resolver - but we can add that if needed

![IMG_6404](https://user-images.githubusercontent.com/15470435/71280775-31d71800-232a-11ea-9b5e-666b66145a21.PNG)
_Profile with released ENS name_

![IMG_6405](https://user-images.githubusercontent.com/15470435/71280797-3c91ad00-232a-11ea-881a-242605d7adee.PNG)
_Options for released ENS name_

![IMG_6401](https://user-images.githubusercontent.com/15470435/71280809-45827e80-232a-11ea-8f71-02f3377ecb28.PNG)
_Clicking into detail on released ENS name_

![IMG_6406](https://user-images.githubusercontent.com/15470435/71280820-4ca98c80-232a-11ea-8f9b-068a3c6092e3.PNG)
_Attempting to re-register released ENS name_

## Implementation

When a user releases their ENS name, the UI should acknowledge it:

- Listen for the release event. Again per @3esmit - `can subscribe to the indexed topic about the namehash (not the label)`
- Make the name inactive or remove from profile entirely
- Ensure that user can not set it as their display
- Do not display name in profile any more
- Clear cache that is preventing me from re-registering the name 

## Acceptance Criteria

When a 1+ year old name is released, it no longer shows up in the user's profile but can be re-registered if available.

**Comment by 3esmit** [comment]
The reason that data in resolver was not cleared up is because there is many unknown fields, and user might set the resolver to a different address that would fail to clean up

Allowing the UsernameRegistrar Contract to call an "unknown address" (user set resolver) to do "unknown things" (clean up user set fields) is not recommended because it opens the contract to unknown unknowns. 

Therefore, the only thing UsernameRegistrar calls at release is the ENSRegistry contract and the SNT token contract. 

When I mean "we can add that if needed" would be a feature of cleaning up a fixed public resolver address, the fields that are automatically filled in at registration (address, pubkey).  

This can be added in the upcoming update of UsernameRegistrar, which is needed because of ENS migrations.

**Comment by acolytec3** [comment]
Is this one I could pick up? Assuming it involves using the json-rpc to set up a new `eth_newfilter` subscription monitoring the namehash on the UsernameRegistrar and then take the appropriate action on the user profile as specified in the issue description.

**Comment by 3esmit** [comment]
Sure, @acolytec3 
I am not entirely sure how good it would work with the `eth_newfilter`, so we would also need a manual check at login, that could create a "synthetic" event (or simply call directly) for the "released action", which would remove the ENS name from the profile database. 

_Note to future issues: Events should be subscribed also for the namehash of the contact list, and for any change that matters (such as resolver, addr or pubkey). 
A notification could appear to notify a contact released their username. The ownership/resolving should also be checked when user manually navigate to a specific user (in case an event is missed)._

**Comment by acolytec3** [comment]
@3esmit so maybe 2 parts:
1) When the release action takes place in the app, set up a subscription with `eth_newfilter` to monitor for the event on the UsernameRegistrar and update the profile in the app database accordingly.
2) When the user first logs into the app, if there is an ENS name on the profile, call the UsernameRegistrar contract to see if the name is still registered to that address.

Does that sound about right?

**Comment by 3esmit** [comment]
Yes.

`ENSRegistry.owner(ensNode) == address(0)` is important to check if available to register, and also to know if the owner is one of the user wallets and could release, or change the resolver.

Your code would have to check first `ENSRegistry.resolver(ensNode) != address(0)`, and then try to resolve the pubkey and check against user chat key `PublicResolver(ENSRegistry.resolver(ensNode)).pubkey(ensNode) == user_chat_key`.

**Comment by acolytec3** [comment]
@rachelhamlin @3esmit Starting to dig into this a bit more and I'm still trying to make sure I understand current state of how ENS names are released before thinking about the best way to move forward.  Is current state just a hard-coded message on the details page saying that the name can't be released until 5/20/20 and then a "pending" message if the ENS name doesn't resolve when the user tries to navigate to the ENS view with the app?

**Comment by 3esmit** [comment]
I think the issue here is handling cases where the Status App thinks a name is correctly registred and associated, but the user from outside Status App changed something, such as released the ENS Name, changed the resolver, changed the chat pub key... 

This also open two cases, the change is done in other devices and: 
a. the status is closed
b. the status is open

For a. this detection would be done by reading the state after login, and comparing if the pubkey changed. if not, just subscribe the events for b. case.
 
Here is an example in a pseudo programming language:
```python
checkName:
  if user.ensName != null: 
    resolver = ensregistry.methods.resolver(namehash(user.ensName)).call()
    pubkey = resolver.methods.pubkey(namehash(user.ensName)).call()
    if pubkey != user.chatKey:
      delete user.ensName
      this.warnUserAboutNameRemoved()
    else:
      ensregistry.events.NewResolver(namehash(user.ensName)).subscribe(this.checkName)
      resolver.events.PubkeyChanged(namehash(user.ensName)).subscribe(this.checkName)
```

You dont need to make the function in this format, for example, this could be far improved for using less calls from state (as they cost resources as internet or cpu), in case of new resolver everything needs to be checked, but in case pubkey changed, it just needs to delete. 
Also you should consider that resovler can return address 0, and this means that no pubkey can be resolved.
You also need to consider that method .pubkey might not be available, as the resolver can be set by user to any address they want. 

@rachelhamlin needs to tell us what should be done in UI side for warning user, if need any warning to start (perhaps can be silent). 

You can see the ENS contracts here https://github.com/status-im/ens-usernames/tree/master/contracts/ens 


When the release feature becomes implemented in Status, it would also benefit from this already subscribed events.

**Comment by acolytec3** [comment]
That all makes sense then.  Here's my thought on how to approach.

1) At every login, check to see if there is a ENS name cached in the app db. If so, try to resolve it and the pubkey per your approach above. If it doesn't resolve, prompt the user with an error scenario regarding their ENS Name and remove it from local storage.

2) Add a new feature in the UI that allows a user to release their ENS name if the statutory year has passed.  When this happens, disassociate the ENS name in the app once the release transaction is processed on the blockchain.

Thoughts?

**Comment by 3esmit** [comment]
Yeah, you can solve both if you want in this issue, as they are very close related.

**Comment by acolytec3** [comment]
@3esmit Sorry I've left this one hanging but I'm going to step back from this one. Been focusing on some other projects and this one might be bigger than I can take on in the near term.

**Comment by hesterbruikman** [comment]
Captured in https://github.com/status-im/status-react/issues/10794
