### ISSUE TITLE
QR code reader inserts a space before the read address, throws error

### ISSUE THREAD

**Issue by leafcutterant** [status-im/status-react#9748]
# Bug Report

## Problem

When you scan a QR code with a "0x01234..." Ethereum address, Status gives the error "Invalid address" and displays the address with a white space before it, which makes me think that space is interpreted as part of the address.

#### Expected behavior

There's no space in the QR code data, so Status has some glitch. Also, if it *did* have an white spaces before or after, Status should notice it and trim it, and interpret the data afterwards.

#### Actual behavior

Error thrown, see above. Can't proceed with the transaction.

#### Acceptance Criteria

1. No space inserted
2. Spaces at the beginning and the end of the QR code data automatically removed

### Reproduction
- Open Status
- Read a QR code from Etherscan from a random address

### Additional Information

- Status version: 0.14
- Operating System: Android

#### Logs

**Comment by ghmulti** [comment]
Seems that the problem is the format of your address (no "ethereum:" prefix)
Can be reproduced with
`(re-frame.core/dispatch [:qr-scanner.callback/scan-qr-code-success {:handler :wallet.send/qr-scanner-result} "0x01234..."]) `
while the following event will work fine
`(re-frame.core/dispatch [:qr-scanner.callback/scan-qr-code-success {:handler :wallet.send/qr-scanner-result} "ethereum:0x01234...""])`

Interesting thing though - adding arbitrary amount of whitespaces in front of "   ethereum:" will work fine but adding whitespaces to the end will lead to "Invalid address" popup. Not sure what is the desired behaviour here

![Screenshot from 2020-01-09 22-19-14](https://user-images.githubusercontent.com/4256893/72105576-15793a80-332e-11ea-9409-eb3f7a02e754.png)
