### ISSUE TITLE
"Log out" instead of "Sign out"

### ISSUE THREAD

**Issue by andmironov** [status-im/status-react#9790]
Let's keep it consistent and replace "Log out" with "Sign out" here in this prompt window (3 times)

![photo_2020-01-10 12 46 32](https://user-images.githubusercontent.com/3115606/72143149-3fbb0e80-33a7-11ea-9014-2049c64c3653.jpeg)

**Comment by errorists** [comment]
Is it necessary to repeat `Log Out` three times? 🙃 
maybe it's better to rephrase the alert title like 'You are about to sign out' and remove the message, one log out less

**Comment by andmironov** [comment]
sure that's even better :-)

**Comment by ghmulti** [comment]
Assuming that changing text from question to statement will require(?) changes in all language-files, who is usually doing the translation? :smile: 
Does that looks fine?
![Screenshot from 2020-01-13 21-29-58](https://user-images.githubusercontent.com/4256893/72289752-0d7e0b00-364c-11ea-9afa-f0c3394fac61.png)

**Comment by errorists** [comment]
@rachelhamlin any thoughts you'd like to share on the wording here? imo it still doesn't feel 'right' somehow

**Comment by rachelhamlin** [comment]
Actually wait - why do we even have a log out confirmation? This isn't a pattern I'm familiar with.

**Comment by errorists** [comment]
@rachelhamlin It's not that uncommon, I tried 3 first apps I came across, Twitter, Dropbox and Soundcloud. of those 3, only soundcloud didn't ask me before signing out. 

![IMG_1267](https://user-images.githubusercontent.com/4932774/72360158-d8c38f80-36ef-11ea-9625-8db35db43d22.jpeg)
![IMG_1268](https://user-images.githubusercontent.com/4932774/72360171-dc571680-36ef-11ea-9e73-b4ad979da10a.jpeg)

I'd probably leave it, just rephrase into something that doesn't give a headache. twitter's not bad, maybe 
title: Username
message: Are you sure you want to sign out of Status?
buttons: Cancel | Sign out

cc @hesterbruikman to join the sign out confirmation brainstorm

**Comment by rachelhamlin** [comment]
Haha, hmm! And I tried my bank, FB and Trust and didn't find this anywhere.

But +1 "Are you sure you want to sign out of Status?" works for me, and it's a nice place to re-surface the username, since that's the person's identifier for signing back in. Speaking of—I wonder if lack of ENS name on the unlock/sign-in screen will confuse people who have them.

**Comment by andmironov** [comment]
re: showing the confirmation dialog
I think it should stay, especially keeping in mind that the account might require a keycard to sign back in and the user might not have it with them 

re: copy
i like what @errorists is suggesting
> title: Username
message: Are you sure you want to sign out of Status?
buttons: Cancel | Sign out

**Comment by hesterbruikman** [comment]
Ugh.... this 'sign out' has been bothering me! Thanks for creating the issue @andmironov And indeed the inconsistency makes it worse.

I don't have an answer the perfect terminology in mind, but here are some perspectives on the behavior before jumping to naming:
- We need the dialog atm because Sign out in effect resets your unlock settings (and possibly others, haven't checked). Ideally we remove the distinction between `Sign out` and `Closing` the app, as concluded eventually here: https://github.com/status-im/status-react/issues/9763#issuecomment-573063838. If we remove the distinction we don't need the dialog and the only question remains is what to call this thing in Settings.
- If we make changes I would suggest to bundle these with replacing `Unlock` with `Your keys` to ensure consistency https://github.com/status-im/status-react/issues/9782

**On the naming:**
- Result of lengthy onboarding discussions was the term Unlock. Rationale being that `Sign in` or `Log in` are terms from a server era and not an accurate description of what happens. Which is `unlocking or decrypting your local keys`. If this is true for opening a Status multiaccount, I reckon it's true for closing one.
- As far as I know, the keys are encrypted when you close the app or maybe even right after decrypting. So this is not really a sign out, a.k.a., lock, log out use case, but more of a `Close` or `Switch` case.
