### ISSUE TITLE
Connectivity banner cuts off text when message is too long

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9803]
# Bug Report

## Problem

When the connectivity banner contains more than one line of copy, the text overflows. 

![image](https://user-images.githubusercontent.com/15470435/72243899-a4809e00-361f-11ea-8146-ef2a35090983.png)

#### Expected behavior

Room for two lines of copy on the top banner.

#### Actual behavior

Bottom line of text is cut off.

**Comment by errorists** [comment]
I think it's the fault of the message contained within, we shouldn't show users such crap like 'an error occurred while fetching history, check the logs…'. also this might be resolved with https://github.com/status-im/status-react/issues/9288 since we opted to cut out all unnecessary messages from the connectivity snackbar.
