### ISSUE TITLE
No gas estimate for ENS registration

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-react#9876]
# Bug Report

## Problem

ENS registration transactions have an empty gas fee calculation:

![image](https://user-images.githubusercontent.com/15470435/72881289-126d4980-3d33-11ea-9cec-1476c063fb81.png)

#### Expected behavior

Wallet estimates a network fee, e.g.

![image](https://user-images.githubusercontent.com/15470435/72881517-78f26780-3d33-11ea-8fb4-71477f40b145.png)

Transaction is easier to make.

#### Actual behavior

Empty estimate & error message requires user to manual input.

**Comment by rachelhamlin** [comment]
Sounds like another Infura issue. I have loads of SNT.

**Comment by yenda** [comment]
Was caused by call to `approve` instead of `approveAndCall` more than a year ago when the dapp for ens registration was being developed and tested.

Solution was to first call `approve` with a value of 0 SNT

Not related to infura
Probably only concerns that specific accounts so doesn't require a fix in status

Still here would be the solution proposed by @3esmit in case we have more users complaining about it:
```
you could treat this case if u want, by:
- if SNT.allowance(userAddress, UsernameRegistrar.address).call() == 0: 
- ~ SNT.approveAndCall(UsernameRegistrar.address,10^18, UsernameRegistrar.register(...).encodeABI()).send(). //encode register call in approveAndCall with 10 SNT
- else:
- ~ if SNT.allowance(userAddress, UsernameRegistrar.address).call() < 10^18: SNT.approve(UsernameRegistrar.address, 0).send() and  SNT.approveAndCall(UsernameRegistrar.address,10^18, UsernameRegistrar.register(...).encodeABI()).send() // clear approval and approveAndCall
- ~ else: UsernameRegistrar.register(...).send()//direct call to username registrar
It might worth the effort if users start having problems, but I dont think anyone will run into this, because, only old users who already have an username would be affected, which are who?
old users is like, before Sep 7, 2018
```

Careful though:
- the error described is very generic, basically it just means that gas estimate failed, and it can be for various reasons, for instance it could be because the user doesn't have enough tokens for a particular transaction to succeed
- when the error looks like this there is 0 chances infura is involved, because infura wouldn't fail consistently on the same account for the same transaction data and not others

**Comment by rachelhamlin** [comment]
@yenda is a legend for fixing this for me.
