### ISSUE TITLE
Stickerpage overlaps with "Send transaction" screen

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9884]
# Bug Report

## Problem

At attempt to buy 'TOZEMOON' stickers 'Send transaction' screen doesn't cover stickers layer, so screens are overlapping and it is possible to tap 20 SNT several times

#### Expected behavior
no overlapping

#### Actual behavior
![photo_2020-01-22 14 27 18](https://user-images.githubusercontent.com/4557972/72897916-4f314480-3d23-11ea-9ebc-efcd10431237.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join to #status
-  Tap on `TOZEMOON' stickerpack to but it

### Additional Information

- Status version: RC [build 10 ](https://ci.status.im/job/status-react/job/release/job/release%252F1.0.x/10/)

- Operating System: Android (checked on Android 10 and Android 8)

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by churik** [comment]
сс @flexsurfer

**Comment by flexsurfer** [comment]
@Ferossgp do you know if we changed modal z position?

**Comment by Ferossgp** [comment]
@flexsurfer  When you press on a sticker it is opened in modal. While the bottom-sheet and popover are rendered with the position absolute in the main app view. Because the modal is handled by react separately as a view above the app, and we didn't had background color for modals at the time of this app build, the current state came. In the current develop, all modals have white bg, and the transaction sheet is not visible at all. To fix it more globally I've removed the modal and left it to be handled by react-navigation.
