### ISSUE TITLE
Can't add valid mailserver

### ISSUE THREAD

**Issue by churik** [status-im/status-react#9896]
# Bug Report

## Problem

Can't add valid mailserver due to validation error
![photo_2020-01-23 17 21 46](https://user-images.githubusercontent.com/4557972/73002792-d9050e80-3e04-11ea-994b-f25a528677f6.jpeg)

#### Expected behavior
Can add mailserver

#### Actual behavior
Validation error is show

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Go to Profile > Sync Settings > Mailserver
- Tap on +
- Copy valid mailserver from https://fleets.status.im/
- Try to paste into address field and proceed

### Additional Information

- Status version: RC 2020012313
- Operating System: Android, iOS

**Comment by churik** [comment]
cc @rachelhamlin

**Comment by cammellos** [comment]
mailserver copied from fleet are not valid, the format must include a password:
this is copied from fleet and is not valid:

`enode://da61e9eff86a56633b635f887d8b91e0ff5236bbc05b8169834292e92afb92929dcf6efdbf373a37903da8fe0384d5a0a8247e83f1ce211aa429200b6d28c548@47.91.156.93:443`

This is valid, as it has a password:

`enode://da61e9eff86a56633b635f887d8b91e0ff5236bbc05b8169834292e92afb92929dcf6efdbf373a37903da8fe0384d5a0a8247e83f1ce211aa429200b6d28c548:password_is_needed@47.91.156.93:443`

the second one should be valid, otherwise there's indeed a bug
