### ISSUE TITLE
Transaction history is delayed in status

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9927]
# Bug Report

## Problem

When sending transaction in status there is no confirmed transaction in history , but on etherescan it has  a few confirmations already

#### Expected behavior

Confirmed transaction appears in transactions history

**Comment by yenda** [comment]
[Status-debug-logs (1).zip](https://github.com/status-im/status-react/files/4121755/Status-debug-logs.1.zip)

Could reproduce by just sending a transaction from chat command to @andrey
Then I moved around in the app, checked etherscan from the pending transaction in transaction, was confirmed already there, back in the app it wasn't, after some time I sent the log, later on it was validated without having to relogin.

**Comment by rachelhamlin** [comment]
I have the same thing but would be hard pressed to say if it worked any better on previous RC. @rasom does this issue surprise you? 

The Tx shows as pending in my Status history, to be clear. Not that it doesn't show up.

**Comment by rasom** [comment]
@rachelhamlin 
As I mentioned in discord, I know what causes this problem, thus it is a not a surprise anymore.
It has never worked better, because this bug was there from the very moment we implemented listening to the new blocks on go side. :) 

I already have a naïve fix locally, but it wouldn't work with a big delay (for instance, if app was put to background on iOS for 2h or so). A proper fix should be ready soon, the latest tomorrow morning.

**Comment by rachelhamlin** [comment]
Wow 🔥 yes please to a proper fix. I could probably live without this being a blocker, but that's really good.
