### ISSUE TITLE
Endless spinner  for messages status in case of reopening app after sending message from "Connecting" state

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-react#9928]
# Bug Report

VIDEO: https://drive.google.com/file/d/1OCCBrg9nExZ_A01RoTtKFOfg4qAUHTtl/view?usp=sharing

## Problem

Endless spinner  for messages status

#### Expected behavior

Message status instead spinner

#### Actual behavior

Endless spinner  for messages status

### Reproduction

- Open Status
- While "connecting.." is showed open any chat
- Send messages
- YOu should see a spinner in message status
- close the app
- open again
- endless spinner

**Comment by rachelhamlin** [comment]
What's the latest insight into this suite of issues (#9929, #9930 also)? Are all three related to Andrey's installation? I haven't been able to reproduce on either platform.

**Comment by cammellos** [comment]
I think they are kind of related, but in this case, it is triggered by Andrey installation (but it's not the root cause).

I believe what happens is that in Andrey's case, the phone was doing a lot of work, and this was slowing down sending of messages.

This uncovered a few issues, for example this one, which is due to the fact that when a message has not been sent yet, and the user logs out, it will  be forever pending, showing an endless spinner. The bug is already present in develop, but it's difficult to trigger in normal circumstances, as messages are sent relatively quick. So there's definitely a bug, but maybe not v1 material.

**Comment by cammellos** [comment]
#9929 is again due to the fact that Andrey's phone is doing a lot of work ( that has been fixed in develop), while #9930 is not clear yet whether is due to Andrey's phone, or whether is an existing bug just triggered by the fact that the phone is being slowed down, worth investigating.

**Comment by rachelhamlin** [comment]
Hmm, okay, thanks for the insight @cammellos. Can we do anything further to help troubleshoot? Sounds like Maciej is also experiencing some of this, and I'm checking in public chats to see if other users are struggling.

**Comment by rachelhamlin** [comment]
We'll watch this closely in v1 and see how many more user reports come in. Flagged for v1.1 so I remember to review.

**Comment by rachelhamlin** [comment]
Are messages actually being delivered when this happens?

**Comment by cammellos** [comment]
yes, delivered and stored on the mailserver, so they should be marked as `Sent`

**Comment by flexsurfer** [comment]
haven't seen this for a while

**Comment by flexsurfer** [comment]
Powerful Specific Bluefish@statuBOTToday at 7:14 AM
I found a bug.
1. after I sent some messages. few of them are show icon 'sending'. circle round move below messages. 
2. it happen yesterday. and still happen after exit the dapp.

**Comment by rachelhamlin** [comment]
Thanks Andrey. I think we should keep monitoring for reports of this before prioritizing.

**Comment by churik** [comment]
Still reproducible on RC v1.3

**Comment by flexsurfer** [comment]
no spinner no issue :)
